### ISSUE TITLE
Export Options

### ISSUE THREAD

**Issue by AdamWorth** [Zettlr/Zettlr#228] opened 2019-06-06 23:15 UTC
### Additional Export Options
Would it be possible to add the following as export options?
1. Epub
2. Mobi

This is a very **very** nice Markdown editor! Thank you very much for the obvious hard work you've put into it!

**Comment by nathanlesage** [comment] 2019-06-07 08:42
Mobi, if I saw it correctly, is not included in the Pandoc Writers, but Epub is. Have a look here: https://pandoc.org/

So of course I can add Epub. But it's not high priority; until then you can use epub by simply overriding the Pandoc command temporarily to force Pandoc to spit out an epub! (replace the Target-Format with epub and append .epub to the outfile variable).

**Comment by nathanlesage** [comment] 2019-06-14 23:59
Closing for now; as soon as we have 3 together, I'll add it.

**Closed by nathanlesage** 2019-06-14 23:59 UTC

**Comment by perrotuerto** [comment] 2022-09-06 05:33
> (replace the Target-Format with epub and append .epub to the outfile variable)

Hi, I think I did what you recommended and I overwrote RST exporter as:

```
reader: markdown
writer: epub
output-file: ebook.epub
verbosity: INFO
log-file: epub.log
epub-fonts:
- fonts/alegreya-bolditalic.ttf
- fonts/alegreya-bold.ttf
- fonts/alegreya-italic.ttf
- fonts/alegreya-regular.ttf
number-sections: false
filters:
- type: citeproc
```

It is working, but the problem is that the output file is `TILE.rst` instead of `ebook.epub`. So, what do you mean by “target format” and “outfile variable”, where should they go?

**Comment by nathanlesage** [comment] 2022-09-22 09:19
The thing is, the `output-file`-variable is being overridden internally by Zettlr. But that's not something I could change (since it would make Zettlr completely static, and you could only use one profile for one single file)
