### ISSUE TITLE
Can’t launch the update from the .deb

### ISSUE THREAD

**Issue by Monolecte** [Zettlr/Zettlr#1316] opened 2020-09-28 14:52 UTC
The software manager refuse the .deb to the 1.8 alpha.
![Sélection_00045](https://user-images.githubusercontent.com/28186535/94448174-e603aa00-01aa-11eb-8067-a843aab8df8d.png)

Perhaps it’s about the new software manager (I’m just upgrading to 20.04 LTS from Ubuntu), but I don’t know how install manual .deb without this.

**Comment by nathanlesage** [comment] 2020-09-28 15:27
Duplicate of #1304

**Closed by nathanlesage** 2020-09-28 15:27 UTC
