### ISSUE TITLE
[Bug] Pictures with relative path not included in export

### ISSUE THREAD

**Issue by yh21equn** [Zettlr/Zettlr#2534] opened 2021-09-30 13:23 UTC
### Description

Pictures are only correctly exported to html/pdf (I did not test anything else) if they are given as an absolute path. If a relative path is used they are not shown in the exported document or print view, despite being shown in Quicklook and rendered in Zettlr directly. This happens both with a custom template and without one.

### Reproducing

1. Create a file Markdown file containing a relative path to a picture.
2. Export the file (or the project) 

### Zettlr Version

Beta (if applicable)

### Specify version

Zettlr 2.0.0-beta-4

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 21.04

### Additional Information

I don't know if it is relevant, but I am using the internal Pandoc for the export and saving the exported files into a temporary directory.

**Comment by nathanlesage** [comment] 2021-09-30 14:16
Duplicate of #1343

**Comment by nathanlesage** [comment] 2021-12-14 13:15
Does this still happen in 2.0.3 and/or the latest nightlies?

**Comment by nathanlesage** [comment] 2022-06-04 09:08
Closing due to lack of reproducibility and activity.

**Closed** 2022-06-04 09:08 UTC
Labels: bug
