### ISSUE TITLE
[DEVELOP] Image preview rendering broken in the Electron forge branch

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#1228] opened 2020-09-02 11:01 UTC
Pinging @tobiasdiez 

Image rendering is broken, neither the `safe-file`-protocol nor the regular way works out, there's something afoul, need to check this.

**Comment by Kangie** [comment] 2020-09-07 07:56
As an interesting aside, it seems like it's only file:// & safe-file:// URIs that cause this issue. Image rendering is fine for http:// URIs (tested on a few from wikipedia and they render perfectly fine!).

Based on the output from the console:
`net::ERR_FILE_NOT_FOUND` for safe-file://
`Not allowed to load local resource:` for file://

And the fact that http sources render images fine, I imagine that something has changed on the Chromium side of things - these errors would indicate to me that something in the web-engine security is preventing local file access.

Some experimentation has shown that modifying `zettlr-window.js` to the following (beginning line 83):

```javascript
      webPreferences: {
        // Zettlr needs all the node features, so in preparation for Electron
        // 5.0 we'll need to explicitly request it.
        nodeIntegration: true,
        webSecurity: false
      },
```

Gets us a little further. - We run into a bug in electron where with webSecurity disabled there's no handler for file:// URIs (see electron/electron#23757). This isn't super helpful, as 1.7.5 was also on Electron >9.0.0, but may be a starting point.

There's a fix for that listed in the thread listed above, but I don't have time to dig further into it right now / don't want to guess at where the code should go as I'm not super familiar with the Zettlr codebase.

I also note that Zettlr is appending a querystring to all image requests (even those that are local, e.g. `C:\test\my.jpg?c=1599464036537`). This will possibly cause some issues as (near as I can tell) querystrings are [not part of the file:// URI specification](https://tools.ietf.org/html/rfc8089). This is discussed in the issue linked above, where after adding a file:// URI handler, querystrings still break image rendering.

I hope that this information is useful when trying to track this down. Good luck! 

The electron-forge / 1.8.x branch looks great so far!

**Comment by Kangie** [comment] 2020-09-07 09:56
@nathanlesage 

OK, I think I've worked it out. Pushed a quick and dirty fix to [Kangie/Zettlr/img-rendering](https://github.com/Kangie/Zettlr/tree/img-rendering).

I don't understand the impact of removing the querystring from the `makeAbsoluteCachefreeURL` overall, so I won't submit a PR, but it works for absolute and relative paths. I assume that it'll break Zettlr#981 again until there's a proper fix in.

It looks like redefining safe-file:// a little while ago fixed most of this, however the querystring in `makeAbsoluteCachefreeURL` is treated as if it's part of the path, so the file will never be found as `example.jpg?123344546753245` will never exist.

By changing `makeAbsoluteCachefreeURL` to safe-file and commenting the line that appends the querystring, images render from local sources perfectly. I didn't have to adjust the webSecurity settings at all to get this to work, so it looks like it was all down to the querystring and redefinition of the URI.

If you want `file://` URIs to work, you'll probably need to redefine them in the same way as safe-file has been - I've tested and it doesn't work currently.

Hm. Further investigation suggests that it doesn't break Zettlr#981, and everything seems to be working... Let me know if you'd like me to submit a PR!

**Comment by tobiasdiez** [comment] 2020-09-07 10:18
Thanks @Kangie for your investigation. I agree the cleanest solution would be to leave `webSecurity` to true, remove the querystring in `makeAbsoluteCachefreeURL` and use the `safe-file` protocol. However, the problem with removing the querystring is that the image is cached, so if you change it on your disk, then edit the image description and leave edit mode again, it will still show the old cached image. You need to close the editor and reopen the file for the new picture to show correctly.

Do you have an idea of how to fix this?

**Comment by Kangie** [comment] 2020-09-07 11:21
@tobiasdiez 

I can't think of, or find a good fix for this. 

However, some testing of my branch seems to indicate that file:// URIs aren't being cached. I'm able to replace the image on-disk, and the next time I click on an image (to reveal the URI) and then away from it, it's replaced by the appropriate image from the disk. 
Would you be able to confirm that behaviour for me? If it's working as it appears to be working as expected for me. I have to question if cache busting is necessary at all for `file://` URIs.

**Comment by Kangie** [comment] 2020-09-08 05:38
After spending a solid 6 hours working on Windows using the electron-forge branch with the fix from the PR I'm pretty happy with the way that images are working. I've been able to modify the source image on-disk to blur identifying information and have it reload without any caching issues using the same workflow as I would in 1.7.5.

If we're happy to go with option 1 based on that, I'll amend my PR to remove the `makeAbsoluteCachefreeURL` function as it's superfluous at this point, and replace any usage of it with `makeAbsoluteURL` so that it's a bit tidier.

Please let me know if you think that I've missed anything, but as far as I can tell it all works!

**Comment by Kangie** [comment] 2020-09-08 10:47
Pretty happy to call this fixed, pending some testing of Windows behaviour. The VirtualBox package for my distro is broken, so I'll report back tomorrow. 

PR has been tidied up and squashed.

**Comment by Kangie** [comment] 2020-09-09 03:03
Everything seems to work on Windows from the branch in my Repo. 

I'll test on another machine when I get home because I encountered some odd behaviour that I want to be 100% sure was me, and not caused by the patch.

**Comment by Kangie** [comment] 2020-09-09 12:05
I'm happy to call this fixed and thoroughly tested on Windows / Linux

The issue on Windows was that the javascript URL interface considers `C:\example.jpg` to be a valid path to generate a `file:` URI, while relative paths and unix paths are apparently not. It took me longer than I want to admit to work out that behaviour...

I've removed my change to disable the HTTP cache, as the `safe-file://` handler does this for us when rendering images anyway.

This probably means that http/https URIs will have their images cached, I'm not sure that's undesirable behaviour anyway.

Should be good to merge now!

**Comment by nathanlesage** [comment] 2020-09-09 15:23
I've already commented on your PR and I am happy with how you did this. Disabling caching even for http-links would be preferable, so if you have a fix, feel free to open a PR. apart from that, we only need the unit tests working again, and we are good to go!

**Closed** 2020-09-11 11:19 UTC
Labels: bug [critical], confirmed, develop, priority:high
