### ISSUE TITLE
[Bug] Zettlr crashes on macOS 10.15.x

### ISSUE THREAD

**Issue by KevinSource0** [Zettlr/Zettlr#3364] opened 2022-04-01 02:32 UTC
### Description

It always fails to start(Apple generates a crash report) on first attempt, force quit and restart a few times, it starts up eventually (the whole process usually takes 10min or longer).

There is a related [issue](https://github.com/Zettlr/Zettlr/issues/2732) on macOS 10.13.x, it's happening on 10.15.x as well.

### Reproducing

1. Download and install Zettlr
2. Start Zettlr

Expected:
Zettlr starts up successfully

Actual:
Zettlr crashes, then freezes, force quit, then restart a few times for the app to load.

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.4

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [x] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

10.15.7 Catalina

**Comment by nathanlesage** [comment] 2022-04-02 19:47
Are there any logs that you might be able to share? I am specifically talking about Zettlr logs (located in `~/Library/Application Support/Zettlr/logs`). Maybe the app does attempt to start and then just fails …

**Comment by KevinSource0** [comment] 2022-04-07 23:09
Attached related log around start up time, nothing alarming at first sight
```
[10:59:24] [Info] [Citeproc Provider] Loading CSL locale file at /Applications/Zettlr.app/Contents/Resources/app.asar/.webpack/main/assets/csl-locales/locales-en-US.xml ...
[10:59:24] [Info] こんにちは！ Booting Zettlr at Thu Mar 31 2022 10:59:24 GMT-0400 (Eastern Daylight Time).
[10:59:24] [Info] Registering custom protocol safe-file
[11:00:57] [Warning] [Translation Provider] Could not update translations: ENOTFOUND | Details: {"code":"ENOTFOUND","timings":{"start":1648738827564,"socket":1648738827564,"lookup":1648738857565,"error":1648738857565,"phases":{"wait":0,"dns":30001,"total":30001}},"name":"RequestError","options":{"agent":{},"decompress":true,"timeout":{},"prefixUrl":"","ignoreInvalidCookies":false,"context":{},"hooks":{"init":[],"beforeRequest":[],"beforeError":[],"beforeRedirect":[],"beforeRetry":[],"afterResponse":[]},"followRedirect":true,"maxRedirects":10,"throwHttpErrors":true,"username":"","password":"","http2":false,"allowGetBody":false,"headers":{"user-agent":"got (https://github.com/sindresorhus/got)","accept-encoding":"gzip, deflate, br"},"methodRewriting":false,"retry":{"limit":2,"methods":["GET","PUT","HEAD","DELETE","OPTIONS","TRACE"],"statusCodes":[408,413,429,500,502,503,504,521,522,524],"errorCodes":["ETIMEDOUT","ECONNRESET","EADDRINUSE","ECONNREFUSED","EPIPE","ENOTFOUND","ENETUNREACH","EAI_AGAIN"],"backoffLimit":null,"noise":100},"method":"GET","cacheOptions":{},"https":{},"resolveBodyOnly":false,"isStream":false,"responseType":"text","url":"https://translate.zettlr.com/api/languages","pagination":{"countLimit":null,"backoff":0,"requestLimit":10000,"stackAllItems":false},"setHost":true}}
[11:00:57] [Warning] [Assets Provider] Found outdated filter links.lua; copying ...
[11:00:57] [Warning] [Assets Provider] Found outdated filter tags.lua; copying ...
[11:00:57] [Info] [Stats Provider] Writing statistics to file
[11:00:57] [Info] [Window Manager] Loading state information from /Users/***/Library/Application Support/Zettlr/window_state.json
[11:00:57] [Info] [Window Manager] Window Manager started.
[11:00:58] [Warning] [FSAL Directory] Path /Users/***/*** took 353.30802500247955ms to load.
[11:00:58] [Warning] [FSAL Watchdog] The chokidar process falls back to polling. This may lead to a high CPU usage.
[11:00:58] [Info] [FSAL] Loaded all files and workspaces in 0.4147539199590683 seconds
[11:00:58] [Info] [Document Manager] Restored 1 open documents.
[11:00:58] [Info] [Application] Added /Applications/Zettlr.app/Contents/Resources to PATH.
[11:00:58] [Info] [Application] The bundled pandoc executable is now in PATH. If you do not want to use the bundled pandoc, uncheck the corresponding setting and reboot the app.
[11:01:00] [Info] [R] [Main Window] /Users/***/tutorial.md (index.js:2)
[11:01:03] [Info] [Config Provider] Writing configuration file to /Users/***/Library/Application Support/Zettlr/config.json...
[11:01:05] [Info] さようなら！ Shutting down at Thu Mar 31 2022 11:01:05 GMT-0400 (Eastern Daylight Time)
[11:01:05] [Info] Application uptime was: 1 minutes, and 41.466 seconds.
[11:01:05] [Info] [FSAL Cache] Cleaned up cache: Removed 0 remnants.
[11:01:05] [Info] [Stats Provider] Writing statistics to file
[11:01:05] [Info] [Config Provider] Writing configuration file to /Users/***/Library/Application Support/Zettlr/config.json...
[11:07:45] [Info] [Citeproc Provider] Loading CSL locale file at /Applications/Zettlr.app/Contents/Resources/app.asar/.webpack/main/assets/csl-locales/locales-en-US.xml ...
[11:07:45] [Info] こんにちは！ Booting Zettlr at Thu Mar 31 2022 11:07:45 GMT-0400 (Eastern Daylight Time).
[11:07:45] [Info] Registering custom protocol safe-file
[11:09:18] [Warning] [Translation Provider] Could not update translations: ENOTFOUND | Details: {"code":"ENOTFOUND","timings":{"start":1648739328886,"socket":1648739328886,"lookup":1648739358889,"error":1648739358889,"phases":{"wait":0,"dns":30003,"total":30003}},"name":"RequestError","options":{"agent":{},"decompress":true,"timeout":{},"prefixUrl":"","ignoreInvalidCookies":false,"context":{},"hooks":{"init":[],"beforeRequest":[],"beforeError":[],"beforeRedirect":[],"beforeRetry":[],"afterResponse":[]},"followRedirect":true,"maxRedirects":10,"throwHttpErrors":true,"username":"","password":"","http2":false,"allowGetBody":false,"headers":{"user-agent":"got (https://github.com/sindresorhus/got)","accept-encoding":"gzip, deflate, br"},"methodRewriting":false,"retry":{"limit":2,"methods":["GET","PUT","HEAD","DELETE","OPTIONS","TRACE"],"statusCodes":[408,413,429,500,502,503,504,521,522,524],"errorCodes":["ETIMEDOUT","ECONNRESET","EADDRINUSE","ECONNREFUSED","EPIPE","ENOTFOUND","ENETUNREACH","EAI_AGAIN"],"backoffLimit":null,"noise":100},"method":"GET","cacheOptions":{},"https":{},"resolveBodyOnly":false,"isStream":false,"responseType":"text","url":"https://translate.zettlr.com/api/languages","pagination":{"countLimit":null,"backoff":0,"requestLimit":10000,"stackAllItems":false},"setHost":true}}
[11:09:18] [Warning] [Assets Provider] Found outdated filter links.lua; copying ...
[11:09:18] [Warning] [Assets Provider] Found outdated filter tags.lua; copying ...
[11:09:18] [Info] [Stats Provider] Writing statistics to file
[11:09:18] [Info] [Window Manager] Loading state information from /Users/***/Library/Application Support/Zettlr/window_state.json
[11:09:18] [Info] [Window Manager] Window Manager started.
[11:09:19] [Warning] [FSAL Watchdog] The chokidar process falls back to polling. This may lead to a high CPU usage.
[11:09:19] [Info] [FSAL] Loaded all files and workspaces in 0.14107260298728944 seconds
[11:09:19] [Info] [Document Manager] Restored 1 open documents.
[11:09:19] [Info] [Application] Added /Applications/Zettlr.app/Contents/Resources to PATH.
[11:09:19] [Info] [Application] The bundled pandoc executable is now in PATH. If you do not want to use the bundled pandoc, uncheck the corresponding setting and reboot the app.
[11:09:19] [Info] [R] [Main Window] /Users/***/tutorial.md (index.js:2)
[11:09:24] [Info] [Config Provider] Writing configuration file to /Users/***/Library/Application Support/Zettlr/config.json...
[11:10:05] [Info] [R] [Main Window] /Users/***/-.md.md (index.js:2)
[11:10:10] [Info] [Config Provider] Writing configuration file to /Users/***/Library/Application Support/Zettlr/config.json...
[11:10:12] [Info] Saving file -.md.md...
[11:10:12] [Info] [Stats Provider] Writing statistics to file
```
After more testing, it seems even though it's unresponsive and generates a crash report "Zettlr quit unexpectedly". It does attempt to start in the background, if I ignore the crash popup and wait a bit longer (20s-40s), the app will load.

**Comment by nathanlesage** [comment] 2022-04-08 18:31
The logs look absolutely wonderful, nothing bad happening (it even shuts down correctly in the background, despite all the error messages)

**Comment by nathanlesage** [comment] 2022-12-19 21:05
Since this issue has no clear path of remedification, I am going to close it now. I have neither been able to reproduce this, nor do I possess the resources to try and recreate the exact environment in which it broke (see my similar comment on the earlier issue). If someone else stumbles upon this issue, please consider upgrading macOS to a recent version.

**Closed by nathanlesage** 2022-12-19 21:05 UTC
Labels: bug
