### ISSUE TITLE
1.3.0 wouldn't save files or close

### ISSUE THREAD

**Issue by Leoj03** [Zettlr/Zettlr#237] opened 2019-06-14 02:12 UTC
## Description
I upgraded from 1.2 to 1.3, and when I did so, I noticed that Zettlr would not close unless I force quit it or logged out.  It also would not save my files, and as a result I lost about 2,000 words of a story.  I am running it on Ubuntu 19.04 with the Budgie Desktop

## Reproducing
I am not sure if it can be reproduced, but you can try testing it on Ubuntu 19.04

## Expected behaviour
It should close and save properly

**Screenshots**

## Platform
 - OS: [e.g. iOS] Ubuntu Linux
 - OS Version [e.g. 11] 19.04
 - Zettlr Version [e.g. 0.15] 1.3.0
 - Screen Resolution [only necessary if the bug is relating to the GUI] 1366*768

**Comment by nathanlesage** [comment] 2019-06-14 06:32
The not-closing is clearly related to the not-saving, as Zettlr doesn‘t shut down without having saved the file first.

It sounds as if there‘s a rights-issue on your computer. Obviously Zettlr can‘t save when it doesn‘t have appropriate rights. This is for instance an issue with Nextcloud on macOS as well. Sometimes apps change CHMods of files without restoring them.

**Comment by samarulmeu** [comment] 2019-06-14 08:21
I also think is a rights related issue. I am using Zettlr on an Ubuntu based distribution (Lubuntu) for 3 or 4 hours every day and I never lost work. The only thing that troubles me is that I sometimes forget, at work, to mount the USB sticks where I keep my personal notes (issue #219 that seems to be solved in the next release). 

There is an issue I encounter from time to time, but, as I can not reproduce it, I did not mentioned it till now. Sometimes (especially if I move a file or I copy some content) it seems that Zettlr is not able to do the writing and creates a new file with this *new* content, a file named `New  File 2019-...` (if I remember correctly), but, as I mentioned, I never lost anything (it happened a lot with other markdown editors that I was testing before).

**Comment by nathanlesage** [comment] 2019-06-14 09:22
I'm currently thinking about checking file write permissions with the app first using [fs.access](https://nodejs.org/api/fs.html#fs_fs_access_path_mode_callback) and indicating missing permissions somehow so that you're not surprised that you can't actually save your content.

**Comment by nathanlesage** [comment] 2019-08-10 13:58
Did the issue resolve in the meantime with the betas?

**Comment by Leoj03** [comment] 2019-08-10 14:26
I believe (based on similar experiences with other software) that it was due to the USB drive I was keeping my story on accidentally being unplugged/knocked out, and when it was plugged in again it somehow messed up the permissions.  So, no fault of Zettlr.  Thanks for the help, everyone.

**Comment by nathanlesage** [comment] 2019-08-11 10:23
Alright, thanks for the feedback! :)

**Closed by nathanlesage** 2019-08-11 10:23 UTC
