### ISSUE TITLE
[BUG] Zettlr freezes with 100% CPU when adding a [[link]]

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#967] opened 2020-07-01 20:50 UTC
So I've got a note. Pretty regular one, with one tag (shared by ~10 other notes), id inline, no yaml front-matter. When I type `[[`, I get the list of notes — and can't do anything after that.

Electron's CPU usage up to 100%, does not respond to key presses or clicks inside the window. Both logs and console have nothing unusual. I can click on menu items, and I can start the developer tools — only it's completely empty. If I start the console before typing `[[`, open "Memory" panel, then type `[[` — I can press the button for heap snapshot, but the snapshotting never ends.

I have no idea how to debug this. But the error stands, and it's reproducible here.

_Zettlr 1.7.0 beta 13 (built from develop branch just now), Fedora Linux 32_

Update: turns out it's the same for any notes with or without tags.

**Comment by nathanlesage** [comment] 2020-07-01 21:05
Electron treats the CPU as Chrome treats the RAM :D 

Unfortunately, can't reproduce here locally :/ Did you maybe forget a `yarn install`? I have updated some dependencies in the last few days, so maybe that's the cause …?

**Comment by Zverik** [comment] 2020-07-02 11:19
No, I always do this:

    git fetch upstream && git merge --ff-only upstream/develop && yarn install && yarn start

Maybe this is a broken cache issue?

**Comment by kyaso** [comment] 2020-07-02 20:11
Could this be related (if not the same) to #956 ?

**Comment by nathanlesage** [comment] 2020-07-03 06:23
> Maybe this is a broken cache issue?

Mhh … does it go away when starting the app from the command line using the `--clear-cache`-flag? Full path should be something like `/Applications/Zettlr.app/Contents/MacOS/zettlr` if I'm not mistaken …

**Comment by Zverik** [comment] 2020-07-03 07:07
Did `yarn start --clear-cache`, nothing has changed. Sorry :)

**Comment by nathanlesage** [comment] 2020-07-03 11:14
Perfect, then we can at least rule out the caching adapter … which leaves like 99% of the rest of the source code the potential culprit 🤔

**Comment by Jos512** [comment] 2020-07-03 13:27
I have a similar issue that Zverik reports. In my case it happens when editing links, not when inserting. And I cannot open the developer tools after reaching 100% CPU.

Should I make a different issue report or type my information in this issue? :thinking: I don't want to be hijacking Zverik's issue.

**Comment by nathanlesage** [comment] 2020-07-03 13:48
Mh, the question is whether or not it's related, or not. And apparently it is! But I'm really surprised to see what seems to be an infinite loop in that logic, but without some errors or other logs to hint to where it happens, it's as good as searching for a needle in a haystack :S So please continue to look where you encounter the error, because I cannot reproduce it locally!

**Comment by Jos512** [comment] 2020-07-03 14:48
> Mh, the question is whether or not it's related, or not. And apparently it is!

Thanks. This is the issue analysis that I made with the bug report template:

-----

## [BUG] Zettlr freezes when working with file selector text ([[ & ]])

### Description
When I work with zettel links (`[[ ... ]]`), the program can become unresponsive.

More specifically, it happened in these situations:

- After selecting a file from Zettlr's drop-down menu _and then_ accidentally pressing Tab again (with the text cursor still between `[[` and `]]`).
- When editing the filename that's between `[[` and `]]`.
- When placing the text cursor behind `[[]]` and pressing Backspace.

The problem does not happen when:

- Clicking on zettel links.
- Copy/pasting pre-made zettel links into the content.
- When typing `[[` and then inserting a filename from the file list with Tab or Enter. 

So for me the problem happens when editing the _existing_ `[[` and `]]` text. Not when inserting the filename link in the first place. 

Perhaps:

- Zettlr gets stuck with validating the new text between `[[` and `]]`?
- Or, if I combine @Zverik information with mine, Zettlr gets stuck (re-)loading the list of filenames?

When I say 'stuck' or 'unresponsive', this is what I mean:

- The program does not respond to key presses.
- The program does not respond to mouse clicks.
- One of the .exe processes uses almost one full CPU core (so 100%, or ~25% since my CPU has four cores).
- That one process writes around 400kb-500kb per second to disk.

One of the times that Zettlr became unresponsive, I waited 10 minutes but described behaviour above didn't end. So even though there is writing to disk, there wasn't progress.

### Reproducing
See information above. I also recorded a video that shows me putting the text cursor behind `[[]]` and then pressing Backspace. At that point Zettlr becomes unresponsive. The video is [here](https://ttprivatenew.s3.amazonaws.com/pulse/hsdajflwesdf/attachments/13993154/TinyTake03-07-2020-02-44-30.mp4).

### Expected behaviour
Zettlr may experience a short pause when 'thinking', but I wouldn't expect the program to become unresponsive during text editing.

### Platform
- OS and version: Windows 7 64-bit.
- Zettlr Version: 1.7.0.
- Screen Resolution: 1920x1080.

**Comment by nathanlesage** [comment] 2020-07-03 21:30
> gets stuck with validating the new text between [[ and ]]

Definitely not, as Zettlr doesn't care what is between these brackets

> Or, if I combine @Zverik information with mine, Zettlr gets stuck (re-)loading the list of filenames?

More probable, albeit Zettlr only reparses on directory changes …

> That one process writes around 400kb-500kb per second to disk.

Zettlr should not write to disk ~at all~ when rendering, so either it's an unrelated process or something really weird is happening

**Comment by sesi200** [comment] 2020-07-04 15:30
I can reproduce it reliably:

**Reproducing:**

- write a link, e.g. [[20200704162928]].
- Try to delete one or both of the closing brackets while leaving the two opening brackets there.
- It hangs.

'delete one of the closing brackets' can be:
- using backspace
- Ctrl+X
- Ctrl+V-ing over the closing brackets

It doesn't hang if:
- any part of the link that is not the closing brackets gets modified
- with the same edit action at least one of the opening brackets gets deleted (and therefore it is no longer a valid link beginning)

**Platform:**
- Win 10, 64 bit.
- 1.7 Release

**Comment by nathanlesage** [comment] 2020-07-04 18:52
Ah, this really sounds as if I messed up the renderer accidentally! I'll have a look tomorrow and see to get a patch out by Monday! :)

**Comment by nathanlesage** [comment] 2020-07-04 19:04
Sometimes I feel so stupid, lol — forget one basic thing in the parser, now it works.

Please feel free to test out the current develop branch. If it works out, the patch will go live tomorrow. If not, I'll spend tomorrow hunting that thing down!

**Closed** 2020-07-04 19:03 UTC
Labels: bug [critical], confirmed

**Comment by Zverik** [comment] 2020-07-04 21:40
Yup, works for me now — thanks Hendrik!

**Comment by akstrfn** [comment] 2020-07-04 22:11
Works for me as well. Thanks!

**Comment by nathanlesage** [comment] 2020-07-04 22:17
Woohoow! Thank you for testing it out quickly so I can release the patch in peace tomorrow! :)

Just so you know: it helps so much to have people who test my stuff and say if it works, or even if something different broke! This gives me confidence, so thank you very much :)
