### ISSUE TITLE
Rendering feedback becomes slow for long lines

### ISSUE THREAD

**Issue by max-l** [Zettlr/Zettlr#435] opened 2019-12-15 20:39 UTC
I have the habit of writing paragraphs in single lines when I write in markdown, and let the rendering take care of the multiline display. 

I noticed that the typing becomes slow when the lines / paragraphs reach about 500 words, when I hit that limit, I can type a dozen of characters before I see the display.  

It took me a while to notice that the performance degradation was caused by line length and not file length. Now that I know I can work around the issue by introducing line breaks every hundred or so words. But the slowness almost caused me to switch editor, which would have been unfortunate because everything else is good about this editor !

**Comment by nathanlesage** [comment] 2019-12-16 08:44
Yeah, rendering long lines becomes difficult to render, especially on slower machines. What I'm asking myself is: Why do you write 500 words per paragraph to begin with? Normally, even long paragraphs are at max 200 words or so, if I'm not mistaken ...?

**Comment by nathanlesage** [comment] 2020-02-01 14:04
Closing.

**Closed by nathanlesage** 2020-02-01 14:04 UTC

**Comment by adrn** [comment] 2020-07-07 15:22
@nathanlesage I just ran into this issue as well. I sometimes write long paragraphs when I'm brainstorming or drafting an email, so I personally think it's reasonable to request that rendering doesn't break down for long lines. 

Do you have an idea of what causes? None of the other editors I have (VSCode, Atom, etc.) seem to have this issue.

**Comment by nathanlesage** [comment] 2020-07-07 19:30
> None of the other editors I have (VSCode, Atom, etc.) seem to have this issue.

These also have it, but they simply skip it after a certain amount of text. It depends upon the CodeMirror code, and a few other things. There's certainly room for improvement, but there are >150 issues open right now, so I can't guarantee how fast I am in optimizing things.

**Comment by adrn** [comment] 2020-07-07 19:32
Understood, and I did not mean to sound unappreciative! What you have made is game-changing for me, and I really love what you are doing 🙏.

**Comment by nathanlesage** [comment] 2020-07-07 19:39
Hey, yeah, sorry, I didn't want to sound barky, but I just looked through 30+ new issues on the repositories, and always just seeing new issue requests and no PRs is pretty exhausting 🙈

**Comment by adrn** [comment] 2020-07-07 19:41
I totally understand! I'll hopefully get to the point of helping with PRs, but only just started using Zettlr yesterday, and am new to Electron/CodeMirror, so I'm still getting up to speed :)

**Comment by 13rac1** [comment] 2020-08-25 20:01
I've noticed this before with longer paragraphs, but it became a severe problem recently with some long form stream-of-consciousness notes. I had to switch to a different editor.

I've done some tests to debug. The delay increases linearly with line length. You can see the per character delay range by using keyboard key repeat. Processing delays start becoming noticeable tends of milliseconds at ~500 characters. Delays are enough to trip up my typing at ~1000 characters. The delay becomes over a second per character at 5000 characters and, as an extreme test, 17 seconds per character on a 50k character line.

The upstream issue CodeMirror issue https://github.com/codemirror/CodeMirror/issues/2090 may never be fixed, but points to codemirror.next https://github.com/codemirror/codemirror.next/issues/29 which resolves the issue in https://github.com/codemirror/codemirror.next/commit/c036e124f7f78f67d0ff6177cc69ac624544ed5e perhaps the next step is starting (or testing) the port to [CodeMirror 6](https://codemirror.net/6/)?
> CodeMirror 6 is a rewrite of the CodeMirror code editor. The new system provides solid accessibility, touchscreen support, better content analysis, and a modern programming interface, while matching the existing code in features and performance. It is not API-compatible with the old code.
> The project is at a point where the core is in good shape, most essential extension have been implemented, and you are encouraged to try it out. It hasn't been used very widely yet and should be considered beta-quality. The interface is stabilizing but there may still be breaking changes.

**Comment by 13rac1** [comment] 2020-08-27 04:47
Decided to test further and confirm a path forward.

Test procedure: Paste 10k characters into one line, then type additional characters.

* CodeMirror 5 demo - https://codemirror.net/demo/variableheight.html - Confirmed. Not Zettlr specific.
* CodeMirror 6 demo - https://codemirror.net/6/ - Cannot reproduce. Extremely long lines can be edited without issue.
* [Ace](https://github.com/ajaxorg/ace) Demo - https://ace.c9.io/build/kitchen-sink.html - Editor used in AWS Cloud9. Cannot reproduce. Extremely long lines can be edited without issue.

CodeMirror 6 or Ace both resolve the issue. CodeMirror is probably a more direct, but still breaking, upgrade path.

**Comment by nathanlesage** [comment] 2020-08-30 15:29
We will be switching to CodeMirror Next as soon as it is released.
