### ISSUE TITLE
[Bug] paste image results in a JPG icon

### ISSUE THREAD

**Issue by Stals** [Zettlr/Zettlr#3231] opened 2022-02-17 16:17 UTC
### Description

When I copy-paste the image from the disk into a .md file it shows a dialog of where to put it, but the image size and the image itself are wrong. Instead of the actual image, it inserts the JPG icon or PNG icon.
When I copy the image from google search it does paste the actual image.

<img width="713" alt="Screenshot 2022-02-17 at 19 32 17" src="https://user-images.githubusercontent.com/472089/154526738-84056712-98c2-4656-a705-dca343ab7fe9.png">

### Reproducing

- Open any .md file (for example the tutorial one)
- Copy any .png or .jpg file from disk
- Paste it (using Command + V) into this .md file

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.2

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Montorey 12.2

**Comment by nathanlesage** [comment] 2022-02-17 18:00
I'm surprised by this twice: First, because I didn't expect macOS to copy the literal file icon into the buffer, and second because I didn't expect that dialog to show up.

We would need to analyze the actual clipboard contents in this case to see if we can get the actual image somehow.

**Comment by matthewpaulthomas** [comment] 2023-01-29 01:17
This looks to be the same as #3778, which is newer but has more discussion.

**Comment by nathanlesage** [comment] 2023-01-29 16:58
That is true, thank you for spotting this!

Closing this as duplicate of #3778.

**Closed by nathanlesage** 2023-01-29 16:58 UTC
Labels: bug
