### ISSUE TITLE
Right-clicking a reference does not anymore allow you to open its Zotero attachment

### ISSUE THREAD

**Issue by BabakFarshchian** [Zettlr/Zettlr#4499] opened 2023-07-16 11:01 UTC
### Description

One feature of Zettlr that has been essential for me is to be able to right-click a reference to Zotero and open the PDF. This feature is now gone from Zettlr 3.0 beta 6. Is it a bug or a feature? 

### Reproducing

Open any file with a reference to any Zotero item. If you right-click on the reference you are presented with a normal text editing context menu with no option to open the attachment.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0 beta 6

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

**Comment by nathanlesage** [comment] 2023-07-17 06:27
I just tried this out with the current dev branch and for me, right-clicking the item gives me the correct context menu:

<img width="335" alt="image" src="https://github.com/Zettlr/Zettlr/assets/17251683/db734115-9524-46b9-9cae-91caa3b3c078">

There's a chance I broke that accidentally and then fixed it accidentally again. Please try out the current nightly that's going to be compiled in a few hours to see if the bug persists, and, if it's gone, please close this issue!

Thanks!

**Comment by BabakFarshchian** [comment] 2023-07-18 05:48
Hm. Uninstalled everything and installed from nightly build. Same error. Closed the workspace and restarted and open workspace again. Same thing. I get the standard context menu and not the one shown above.

**Comment by nathanlesage** [comment] 2023-07-22 16:26
Then I cannot reproduce your issue and thus cannot help, unfortunately :/

We need to find someone who can reproduce this issue and also can take a look into it.

**Comment by nathanlesage** [comment] 2023-07-22 19:51
Oh yes, I Never fully understood what that function did and I find that Marijn has recently heavily changed the code. If that works for you I can try out that nothing breaks otherwise and then implement that

**Comment by nathanlesage** [comment] 2023-07-22 21:19
@UFOMelkor You know what? Thinking about it, there should be nothing speaking against this change. Feel free to look for the same line of code in other renderers, it may be that I copied over that snippet tonischere which may also cause problems, and then feel free to open a PR, then you also have some more clout for v3.0! :)

**Closed** 2023-07-23 13:08 UTC
Labels: bug
