### ISSUE TITLE
Zettlr 3.0.0-beta.1 Fails to open (macOS)

### ISSUE THREAD

**Issue by vtcarlino** [Zettlr/Zettlr#4093] opened 2023-01-26 09:38 UTC
### Description

Zettlr fails to launch and produces the following error:

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: dlopen(/Applications/Zettlr.app/Contents/Resources/app.asar.unpacked/.webpack/main/native_modules/build/Release/Nodehun.node, 1): no suitable image found.  Did find:
	/Applications/Zettlr.app/Contents/Resources/app.asar.unpacked/.webpack/main/native_modules/build/Release/Nodehun.node: mach-o, but wrong architecture
	/Applications/Zettlr.app/Contents/Resources/app.asar.unpacked/.webpack/main/native_modules/build/Release/Nodehun.node: stat() failed with errno=316
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at 19572 (/Applications/Zettlr.app/Contents/Resources/app.asar/.webpack/main/index.js:2:1153497)
    at r (/Applications/Zettlr.app/Contents/Resources/app.asar/.webpack/main/index.js:2:2156778)
```

### Reproducing

Attempt to run the program.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta.1 

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

macOS Catalina 10.15.7

**Comment by nathanlesage** [comment] 2023-01-26 19:01
Duplicate of #4068

**Closed by nathanlesage** 2023-01-26 19:01 UTC
Labels: bug
