### ISSUE TITLE
[ENHANCEMENT] Hover over hyperlink shows note in popup

### ISSUE THREAD

**Issue by ruizjme** [Zettlr/Zettlr#920] opened 2020-06-12 07:23 UTC
## Description
Wikipedia-like hover on hyperlink shows popup of linked note's contents

## Proposed Changes
When hovering over a link to another note in a note, a popup appears on the link showing the (beginning of) the note's contents. E.g.

![image](https://user-images.githubusercontent.com/14925094/84476368-5c9a9b80-acd1-11ea-829c-033f812e6950.png)

## Caveats
n/a

**Comment by PhilHem** [comment] 2020-06-12 08:27
I could imagine that this sort of feature is pretty dependant on how people take notes. Personally, I don't necessarily take notes that are structured like Wikipedia articles. In such a case, this feature would just put out garbage. 

I could imagine that this could possibly be an option if there was some sort of text environment, that is marked to be used for such a preview. 

For example `### This is a preview text section ###`.

This would however mess with the idea that the markdown files should mostly adhere to common markdown language. A philosophical break like that... Don't know if its warranted.

**Comment by nathanlesage** [comment] 2020-06-13 13:08
I like how apparently my subversive display of Marxist stuff around the net begins to influence people :D 

Nevertheless: In principle an interesting idea, the question would be what to display, because I want to keep the workload low while maintaining speed. Therefore, I neither can load the content of all notes into your RAM (well, I could, but then we would have created a Sarlacc pit for RAM modules) nor request files on hover (would take too long to display).

Compromise: I can show you something like what is displayed when hovering over the tabs in the current beta; would be a compromise between fast access and keeping the RAM out of harms way

**Comment by Derkness** [comment] 2021-03-25 08:42
We are a group of 5 students from Adelaide uni. Our names are Tom, Jason, Ben, Shrey, and Ryan, and as part of our course, “Software Process Improvement”, we are tasked with making a contribution to one real-world open-source project. We’d like to contribute to this issue. We will be working from April until the end of May 2021 during our semester 1. Our Pull requests should be coming steadily throughout April & May

If anyone has any tips on where to start with that, please feel free to contact us.

**Comment by nathanlesage** [comment] 2021-03-26 08:44
@Derkness Thank you for the help! @tobiasdiez since you're the assignee – what's the status here?

**Comment by tobiasdiez** [comment] 2021-03-26 09:25
I've not yet started working on this, so @Derkness and his team are more than welcome to start with it!

**Comment by Derkness** [comment] 2021-04-17 02:43
Sorry to bother you, but we just have a couple of questions which may be very general to do with working on these types of programs. We have forked the repository and downloaded a copy, and we wish to run this to see how the program looks/interacts. We ran yarn install and yarn package, but we cannot find any way to actually launch the program.

We think that the only way is to create an installer with yarn release, install the program, and launch from here every time we want to test a new bit of code. Is this correct?

(If it helps, we are all using the ubuntu subsystem terminal on a windows 10 setup)

**Comment by tobiasdiez** [comment] 2021-04-17 10:54
You can use `yarn start` to compile and run the application without installing it, see https://github.com/Zettlr/Zettlr/blob/6f0199f22360698c8843f9f8108ee94e07ba3704/package.json#L19

**Comment by Derkness** [comment] 2021-04-19 08:01
Sorry to bother you again, but we have had quite the trouble getting this to work. The errors we are finding seem to only have solutions for self-written projects, and we can't find a fix without changing the downloaded file, which seems incorrect. We have also done several fresh installs.

If possible, could you let us know of any guides, or just what to do to fix this?

The specific errors we cannot seem to fix, and some notes underneath them, are below:

"The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755."
^^^
This error goes away by using chown and chmod, however it seems the permissions reset after each failed 'yarn start'

"Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Permission denied"
^^^
Adding 'sudo' to the beginning removes this, however, it asks for us to use the flag --no-sandbox, which doesn't work with 'yarn start'

"UnhandledPromiseRejectionWarning: RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 1173.
DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code."

**Comment by nathanlesage** [comment] 2021-04-19 08:34
> This error goes away by using chown and chmod, however it seems the permissions reset after each failed 'yarn start'

I'm pretty sure that's related to it being the subsystem.

> "UnhandledPromiseRejectionWarning: RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 1173.

That error message normally appears when the main process crashes while the renderer is starting up (both the main process and the renderer are separate processes due to security & performance reasons).

> DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code."

That one will always appear when the renderer crashed during boot up, so whenever you see this, that happened.

***

That being said, I just re-read that you're using the subsystem on Windows. Since that's not actually a Linux system but some weird abomination by Microsoft, it can very well be that that one is not really working with Electron projects. Since I can confirm that developing Zettlr on Win10 without the subsystem works, I would suggest you roll with Windows Vanilla for this one. Some remarks about that:

- I think the current setup requires Git for Windows to be installed (since it ships with Git Bash, which is required for the Pandoc downloader, if my guess is right)
- There are some weird permission errors using VisualStudio Code's built-in terminal, but the normal command line (`cmd.exe`) should work fine (after installing Node, Yarn, etc., that is)

**Comment by Derkness** [comment] 2021-04-19 08:36
Thank you so much for your quick reply. I'll try to install it through windows git. Ill report back with the results :D

**Comment by tobiasdiez** [comment] 2021-04-19 09:19
The Linux subsystem doesn't include any GUI libraries, so this will never work for Zettlr.

**Comment by Derkness** [comment] 2021-04-19 10:15
I have an issue using cmd.exe (attached) when running yarn start, surrounding download of Pandoc.

![image](https://user-images.githubusercontent.com/67995374/115220408-ab159380-a147-11eb-8330-db30e99ca0c9.png)

From reading another issue, it seems that this requires bash to be installed, however, you suggested I could use cmd.exe. I am wondering if this information changed?

**Comment by Derkness** [comment] 2021-04-19 10:19
Nevermind, I found a guide to manually put it in zettlr's files. I now have it running! Thanks for the help guys :D

**Comment by tobiasdiez** [comment] 2021-04-19 11:07
Glad it worked for you! I think it would be good idea to instructions on how to setup a local workspace in the `CONTRIBUTING.md` (see e.g https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace for inspiration). Maybe @Derkness you can start this by recording your experence and how you manage to setup everything in the end.

**Comment by nathanlesage** [comment] 2021-04-19 11:51
Great idea, @tobiasdiez. We should re-do the CONTRIBUTING document either way since it's still the default thing I added way back, so I'm sure we can make a better document at this point.

**Comment by Derkness** [comment] 2021-04-20 02:50
I'd be more than happy to document my experiences in the pull request for the feature. I will say though that while I did spend lots of time trying to get this work after I switched to just using windows purely, it was only about three steps, so the addition may not be as big as you could expect.

It also may include arbitrary steps that I just happened to do on the one time it worked, so feel free to edit out useless steps when I add the documentation.

**Comment by Derkness** [comment] 2021-05-04 15:34
Apologies for the gap in communication, it was Uni holidays for us.

We are having quite a bit of trouble understanding the code, and just have a couple questions. We also have some ideas on solutions underneath each question, just incase we are already correct.

- Where should the code for the popup itself?
Zettlr\source\win-main\PopupHyperlink.vue
- Where should the on-hover event be placed?
Zettlr\source\win-main\Editor.vue, however we cannot figure out how to link the $showPopover function, or where in the file this should go.

Sorry for needing so much guidance, this is unlike any project we have worked on before.

**Comment by nathanlesage** [comment] 2021-05-12 19:39
> Where should the code for the popup itself?

Careful, since there are _two_ types of popovers we have (note that I'm calling this popover, since that's the "official" term from the Human Interface Guidelines) – one is a tooltip, instantiated from tippy, and one is the Popover.

Why am I saying this? A popover is opened via a _click_ by the user. A tooltip, however, is opened simply by hovering. That being said: A popover must be manually closed (e.g. via a click outside of it) while a tooltip disappears if the mouse goes away.

I am pretty sure a note popup in this case should be a _tooltip_ because it makes sense to have a user hover an internal link, have the tooltip appear with a loading indicator (loading spinner, something appropriate) while the note's contents are being fetched in the background. Then, as soon as the contents arrive in the renderer, you can replace the loading spinner with the actual contents. As soon as the user goes away from the note (it should have the `interactive`-property set to true) the tooltip automatically disappears.

A few pointers:

* There is a function to retrieve file contents in the renderer, see the Editor.vue for this (search for ipcRenderer.invoke)
* On how to instantiate the tooltips, see the documentation of tippy.js and search for `tippy(` within the codebase
* The hover event should be pretty analogous to the tooltips of rendered links, see for this the file `link-tooltips.js` in `source/common/modules/markdown-editor/hooks`
* Something that might be of interest: There is a utility function `md2html` (filename: `md-to-html`) that can convert Markdown to HTML, which can be shown instead of the Markdown in said tooltip. That might be better in terms of user experience; but feel free to fiddle around with this.

> Sorry for needing so much guidance, this is unlike any project we have worked on before.

Don't worry, you're not alone. I myself don't have a clue how that whole project could've exploded in a way it did in the past four years …

**Comment by Derkness** [comment] 2021-05-17 07:20
Thankyou so much for those pointers.

The last thing we are struggling with is how to get the absolute path of a zelttlekasten link. The only data we seem to be able to get from the link is the name (i.e. [[contents]] would only gives us the string "contents"). We seem to be struggling to find the absolute path. The only instance of 'get-file-contents' seems to be able to use 'this.activeFile.path' straight away.

**Comment by nathanlesage** [comment] 2021-05-17 11:34
@Derkness There's a nice little utility function in the FSAL, called `findExact`: https://github.com/Zettlr/Zettlr/blob/fb7fbd5a50f9ae15ecb7313faf17e7b7213591a5/source/main/modules/fsal/index.ts#L966

This is being used as exemplified in the `force-open`-command (folder: source/main/commands). But I think you'll need to create an additional command OR just add the ability for the Zettlr main class to handle these calls (I think in `runCommand` or similar)

**Comment by nathanlesage** [comment] 2021-06-12 20:04
Fixed by #1988

**Closed by nathanlesage** 2021-06-12 20:04 UTC
Labels: pinned
