### ISSUE TITLE
Pandoc Export Error

### ISSUE THREAD

**Issue by pcstopper18** [Zettlr/Zettlr#1614] opened 2021-01-08 18:08 UTC
I just updated to 1.8.5 on Windows and received the following error when exporting:

![image](https://user-images.githubusercontent.com/33755323/104049002-14e2e080-51dc-11eb-8db4-1703d0fad13c.png)

No changes to settings were made prior to this.

Possible solution?

**Comment by nathanlesage** [comment] 2021-01-08 18:54
First solution is to untick this "Use internal pandoc" checkbox here: 

![image](https://user-images.githubusercontent.com/17251683/104053271-3a2b1b00-51eb-11eb-93d9-15bd60e1ede6.png)

I'll have a look at how to run a full path-application on Windows shells …

**Comment by nathanlesage** [comment] 2021-01-08 18:59
[Apparently we can switch from `child_process.exec()` to `child_process.execFile()`](https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback) internally, as this takes a path as an argument, making it safer. Then the question would be about Apple's M1 chips, which currently need to run using the `arch -x86_64`-processor. @Kangie aren't you on a windows and can have a look at this space-problem?

**Comment by Kangie** [comment] 2021-01-08 19:31
Mostly at work, I use Linux personally. I'll dig out one of my spare Windows boxen briefly this weekend if I have time!

**Comment by nathanlesage** [comment] 2021-01-08 20:41
Thanks so much! Maybe I should be reactivating my work laptop as well. It's been sitting here since I got it, and I never thought I despise Windows so much!

**Comment by Kangie** [comment] 2021-01-10 03:59
Going to look into this briefly tomorrow, playing with templates and markdown linting ate up a *lot* more time than I expected this weekend.

**Comment by Kangie** [comment] 2021-01-13 04:23
So I'm a few days later than I said I'd be. 

Issue 1: You can't bundle pandoc if you're operating on Windows. Makes windows testing from develop a little hard. Need to add a windows batch / powershell file to do the same as `get-pandoc.sh`, (or something similar).

Having said that, I installed 1.8.5 and it all works for me. 

Production data, have to censor some of the output. Sorry!

```
[15:17:01]	[Export] Using bundled Pandoc instead of system-wide!
[15:17:01]	Running Pandoc with command: C:\Users\matthew.jolly\AppData\Local\Programs\Zettlr\resources\pandoc.exe "C:\Users\MATTHE~1.JOL\AppData\Local\Temp\1\export.tmp" -f markdown -t latex --template="C:\Users\MATTHE~1.JOL\AppData\Local\Temp\1\template.latex" --pdf-engine=xelatex --mathjax --resource-path=.;C:\Users\matthew.jolly\doco\Templates\css;C:\Users\matthew.jolly\doco\Templates\LaTeX\template_resources\ --self-contained --top-level-division=section -V block-headings -o "C:\Users\MATTHE~1.JOL\AppData\Local\Temp\1\«NAME».pdf"
[15:17:22]	Pandoc ran successfully. However, there were warnings and/or additional output.
stdout: <br>stderr: [WARNING] Could not fetch resource 'images/«IMAGE NAME I PROMISE»': replacing image with description <br>
[15:17:22]	Successfully exported file to C:\Users\MATTHE~1.JOL\AppData\Local\Temp\1\«NAME».pdf
```

I suspect that the issue is do do with spaces, as I can validate that the internal pandoc is being used and have no spaces in any of my paths. Since I can't bundle pandoc on Windows it's a little hard to test if that code change will fix it...

However, installing pandoc locally (i.e. to "C:\Program Files\..." does result in the same error, so I'm pretty sure that you're on the money with your suggestion. I'd say implement the fix and I can validate with either a new build or 1.8.6.

```
An error occurred on export: C:\Program Files\Zettlr\resources\pandoc.exe "C:\Users\MATTHE~1.JOL\AppData\Local\Temp\1\export.tmp" -f markdown -t latex --template="C:\Users\MATTHE~1.JOL\AppData\Local\Temp\1\template.latex" --pdf-engine=xelatex --mathjax --resource-path=.;C:\Users\matthew.jolly\doco\Templates\css;C:\Users\matthew.jolly\doco\Templates\LaTeX\template_resources\ --self-contained --top-level-division=section -V block-headings -o "C:\Users\MATTHE~1.JOL\AppData\Local\Temp\1\«NAME».pdf"
title: Export failed<br>message: An error occurred on export: C:\Program Files\Zettlr\resources\pandoc.exe "C:\Users\MATTHE~1.JOL\AppData\Local\Temp\1\export.tmp" -f markdown -t latex --template="C:\Users\MATTHE~1.JOL\AppData\Local\Temp\1\template.latex" --pdf-engine=xelatex --mathjax --resource-path=.;C:\Users\matthew.jolly\doco\Templates\css;C:\Users\matthew.jolly\doco\Templates\LaTeX\template_resources\ --self-contained --top-level-division=section -V block-headings -o "C:\Users\MATTHE~1.JOL\AppData\Local\Temp\1\«NAME»<br>additionalInfo: 'C:\Program' is not recognized as an internal or external command, operable program or batch file. <br>
```

**Comment by Kangie** [comment] 2021-01-13 04:24
Man, looking at those pandoc commands makes me glad I'm halfway through writing a defaults file generator. So much less clutter!

**Comment by nathanlesage** [comment] 2021-01-13 08:59
> Man, looking at those pandoc commands makes me glad I'm halfway through writing a defaults file generator. So much less clutter!

Hahaha, yes

As for this issue: Closing, because I found the cause and [wrote it down in this comment here](https://github.com/Zettlr/Zettlr/issues/1552#issuecomment-759305334). Please refer to that one for an explanation.

**Closed by nathanlesage** 2021-01-13 08:59 UTC
Labels: bug [non-critical], confirmed, priority:high, tested:win
