### ISSUE TITLE
Windows: Path to attachments in sidebar missing directory separators ("/" or "\")

### ISSUE THREAD

**Issue by zibmcnib** [Zettlr/Zettlr#1490] opened 2020-12-04 14:07 UTC
## Description
When opening another file (for example, a PDF) that is supposed to open in an external application, I receive a "Could not open <path> externally error" Inspecting the returned path in the error, it is missing path separators i.e.
`C:\blah\blech.pdf` 
is returned as 
`C:blahblech.pdf`

## Reproducing
Attempt to open an external file in Windows with the Attachments portion of the sidebar.

## Expected behavior
The selected file should open in the appropriate external program.

![image](https://user-images.githubusercontent.com/3598194/101173098-4a097b00-35ff-11eb-9a15-2e767116271e.png)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.8.0

**Comment by nathanlesage** [comment] 2020-12-13 14:56
Duplicate of #1448

**Closed by nathanlesage** 2020-12-13 14:56 UTC
