### ISSUE TITLE
Image overlaps text

### ISSUE THREAD

**Issue by MenooMeow** [Zettlr/Zettlr#5466] opened 2024-11-07 16:39 UTC
### Description

The image should not overlap with markdown text.  The image should break text at the upper and lower margins, like is done in a traditional word processor.

The first screenshot shows overlapping text.

The second screenshot shows the markdown, accessible only by lasso selecting.

![Screenshot_20241107_103038-1](https://github.com/user-attachments/assets/ecc9b402-b962-4453-bfb4-be913fc12639)
![Screenshot_20241107_103833](https://github.com/user-attachments/assets/863f796b-414e-42db-ae5d-6b69af30f41f)

### Reproducing

- Insert image in between markdown text with headings.  
- Preferences --> Editor --> Maximum width of images = 100%
- Preferences --> Editor --> Maximum height of images = 50%

### Zettlr version

Zettlr 3.2.3.

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Linux Mint 22 Cinammon

**Comment by nathanlesage** [comment] 2024-11-07 18:48
Duplicate of #4565

**Closed by nathanlesage** 2024-11-07 18:49 UTC
Labels: bug
