### ISSUE TITLE
[FEATURE] Use bibtex database as specified in YAML header

### ISSUE THREAD

**Issue by conig** [Zettlr/Zettlr#718] opened 2020-05-05 03:50 UTC
## Description
Currently a single citation database is set for all documents. I use different databases depending on the project. Ideally zettlr would search YAML headers for bibliography fields and automatically change the database for a given document/project.

## Proposed Changes
The presence of a bibliography field in a document's YAML would override the citation database settings in preferences/export. This should also support the presence of multiple bibtex files in bibliography fields.

## Caveats
Some users may prefer to still set the citation database through preferences so this feature may need to be toggled.

## Additional Information
I'm using rmarkdown, information on the bibliography field as used by rmarkdown can be found here:
https://bookdown.org/yihui/bookdown/citations.html

**Comment by nathanlesage** [comment] 2020-05-05 08:48
I remember that there has been an issue somewhere where I already outlined the caveats.

Currently, the problem with this is that the citeproc-provider within Zettlr only supports one database. Per-se it might be possible by re-loading whenever a document is open that sports this database type. I'll keep this issue open for further reference. But a huge problem might be that multiple databases might need to be supported … the implementation might prove difficult, albeit it's of course a very reasonable feature request!

**Comment by nathanlesage** [comment] 2020-05-05 09:36
Found it!

Duplicate of #459

**Comment by nathanlesage** [comment] 2020-05-05 09:36
Duplicate of #459

**Closed by nathanlesage** 2020-05-05 09:36 UTC
Labels: Feature
