### ISSUE TITLE
Zettlr-2.0.0-beta.4-x86_64.AppImage window always maximised

### ISSUE THREAD

**Issue by zchap26** [Zettlr/Zettlr#2521] opened 2021-09-27 19:28 UTC
Zettlr-2.0.0-beta.4-x86_64.AppImage on Debian 11 bullseye does not remember window position or size between launches of the application.
Zettlr-2.0.0-beta.4-x86_64.AppImage always starts with the application window maximised and occupying the whole screen.

Regards

**Comment by torgeros** [comment] 2021-09-28 14:15
Same problem on Windows. Especially with a widescreen monitor where I dont ever maximize any windows... I really love this program, but having to resize it to a usable size every time I open it makes it annoying to work with, not even to speak of the problems with resizing described in #1516.

I think this issue should be a Feature Request for application windows to open with the size (height & width) and state (maximized/not maximized) you last closed it with.

<sub>Zettlr 1.8.9 on Windows 11 22000.194</sub>

**Comment by nathanlesage** [comment] 2021-09-28 21:48
> I think this issue should be a Feature Request for application windows to open with the size (height & width) and state (maximized/not maximized) you last closed it with.

That is actually the idea behind the window state management logic, but I think I botched something in there. I've opened an issue here (#2200), but I haven't gotten to it.

As with many issues, I appreciate any PR addressing this!

**Comment by nathanlesage** [comment] 2021-09-28 21:49
That being said, closing this as  duplicate of #2200.

**Closed by nathanlesage** 2021-09-28 21:49 UTC
