### ISSUE TITLE
Cannot open workspace

### ISSUE THREAD

**Issue by lsolesen** [Zettlr/Zettlr#3398] opened 2022-04-19 19:08 UTC
### Description

It keeps complaining about:

<img width="290" alt="Skærmbillede 2022-04-19 210502" src="https://user-images.githubusercontent.com/148026/164077424-6a57acd9-7b62-4437-9c42-ea2b0daac349.png">

when trying to open a workspace:

<img width="519" alt="Skærmbillede 2022-04-19 210528" src="https://user-images.githubusercontent.com/148026/164077469-28da82ee-9dba-408f-a442-d2502ffc9679.png">

### Reproducing

I just installed the program and tried to open a directory, but to no avail.

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment] 2022-04-23 11:44
It would be great if you could help me out with two things that may be causing this.

First, we've had this issue here: https://github.com/Zettlr/Zettlr/issues/3400 Could it be that there are some `.ztr-directory` files in the directory that is not working? If so, I already included a fix that will come with the next release.

If that is not applicable, it would be great to see some logs, because the error should be logged. To look at the logs, activate the debug mode, which will then enable a "Develop" menu from which you can open the log viewer and have a look into what might be going wrong.

Thank you!

**Comment by nathanlesage** [comment] 2022-04-23 14:04
Oh, and also closing as duplicate of #3296; please add any additional info that I requested in my previous comment there!

**Closed by nathanlesage** 2022-04-23 14:04 UTC
Labels: bug
