### ISSUE TITLE
"Zettlr cannot be closed" while updating

### ISSUE THREAD

**Issue by ailintom** [Zettlr/Zettlr#3456] opened 2022-05-08 20:07 UTC
### Description

Regardless of whether Zettler is running or not, the installer shows the message "Zettlr cannot be closed" while updating from 2.2.5 to 2.2.6
![image](https://user-images.githubusercontent.com/24455000/167313767-8c34d46d-4b24-4e51-acc5-44f0a722c53d.png)

Retrying does not help, cancel leads to the following message: 
![image](https://user-images.githubusercontent.com/24455000/167313856-8971ea63-5253-401f-a089-279a9a4afa5a.png)

### Reproducing

1) Install Zettlr 2.2.5 (for all users). 
2) Try installing Zettlr 2.2.6. If Zettlr is not running, the error message is shown. If it is running, the installer closes Zettlr and then shows the error message.

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.6

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment] 2022-05-09 12:44
Hmm, this could be an instance of a Zombie process. Would you mind having a look into Task Manager whether Zettlr is still running even if the windows are all closed?

If so, does force-quitting the app and then running the installer work?

**Comment by ailintom** [comment] 2022-05-09 12:51
The problem occurs regardless of whether the app is running or not. 
Even after rebooting the system when I run the installer as the first thing without ever starting the Zettlr.
Also if Zettlr is running successfully closes (it disappears from the Task Manager), but it still shows the error message AFTER successfully closing the app ("Zettlr cannot be closed").

**Comment by nathanlesage** [comment] 2022-05-09 14:26
That is super weird. Does fully uninstalling Zettlr first, and then running the installer work?

If not, what if you additionally remove the data directory (after backing up the important files [as outlined in the documentation](https://docs.zettlr.com/en/troubleshooting/#3-try-resetting-the-app))?

If all of that doesn't solve it, it might very well be that your system has a serious hiccup that just happens to affect Zettlr.

**Comment by ailintom** [comment] 2022-05-09 19:06
Thank you. Was trying to uninstall, but had the same problem during uninstall of version 2.2.5 after reboot with no instance of Zettlr running: it first says 
![image](https://user-images.githubusercontent.com/24455000/167478846-90494340-6a04-43b6-a97e-0f02374bfd57.png)
and then "Zettlr cannot be closed".

The problem was solved by deleting the folder C:\Program Files\Zettlr\ while preserving the folder %APPDATA%\Zettlr 
After this I installed version 2.2.6 with no problems and all my settings are intact.

**Comment by nathanlesage** [comment] 2022-05-10 08:02
Alright, it's good to hear that it was solved! Maybe some of the program files got corrupted at some point. Closing as solved – but please comment here again in case this behavior occurs more frequently!

**Closed by nathanlesage** 2022-05-10 08:02 UTC
Labels: bug

**Comment by guntern** [comment] 2022-06-03 05:34
Hi there,
I had the same issue even though Zettlr is installed in %APPDATA%\Local\Programs\Zettlr.
I was trying to update from 2.2.5 to 2.2.6 via winget and also tried to fully uninstall. Both ways yielded the same error messages as shown above.
I also was able to solve the issue by simply deleting the Zettlr directory and running `winget ugprade zettlr`

**Comment by guntern** [comment] 2022-06-14 13:31
Updating from 2.2.6 to 2.3.0 via winget had the same issue. I had to delete the directory before the upgrade was possible. This does not seem to be bad luck.

**Comment by ailintom** [comment] 2022-06-14 13:32
Same here when updating from 2.2.6 to 2.3.0 on Windows 11

**Comment by guntern** [comment] 2022-06-14 19:30
@nathanlesage could you explain a bit more, how double clicking solves the issue? This sounds counter intuitive. I would be happy to help, but I have not yet understood the problem.

**Comment by xtyuns** [comment] 2022-08-16 16:16
@nathanlesage I had the same problem, when I try to reinstall or uninstall, it tells me that Zettlr is running and I can't complete the action.
**Reinstall**
![cannot close Zettlr](https://user-images.githubusercontent.com/41326335/184923223-62c6ad8d-4162-463e-8e11-b6303f6c68c8.png)
![failed to uninstall](https://user-images.githubusercontent.com/41326335/184923246-9361f821-055f-4492-bf2a-621b3484e049.png)

**Uninstall**
![Zettlr is running](https://user-images.githubusercontent.com/41326335/184923098-b59111a2-bc31-4e1a-ad7b-4c970ddb5436.png)


So I searched the internet for related questions, and finally I found this: ["Signal couldn't update"](https://github.com/signalapp/Signal-Desktop/issues/5854).
Here you can learn the root cause of it: [Signal fails to update when git linux commands are in path.](https://github.com/signalapp/Signal-Desktop/issues/5856)



But when I tried to pull the source code of Zettlr to reproduce the problem I found that it no longer existed, because the version of dependency `electron-builder` had been updated to 23.3.3 in yarn.lock at 8632b3a71cd468c7bdad2f7c58732d768789404f, this issue has also been fixed in this version(see: https://github.com/electron-userland/electron-builder/pull/6771)

So I think now we just need to update the version in package.json as well.
https://github.com/Zettlr/Zettlr/blob/a1b78bb2b285963491e3d72977ac075babcbcc33/package.json#L115

**Comment by nathanlesage** [comment] 2022-08-16 20:55
The issue has already been fixed, and was not caused by electron-builder.
