### ISSUE TITLE
AppImage of 1.8.0 build doesn't start

### ISSUE THREAD

**Issue by AlienTux** [Zettlr/Zettlr#1303] opened 2020-09-24 01:03 UTC
## Description

AppImage doesn't start up

## Reproducing

Download, set AppImage to executable, try to run

## Expected behaviour

Execute

Here's the code reported on the terminal:

```
kurt@kurt-lin ~/bin/AppImages $ ./Zettlr-1.8.0-alpha-x86_64.AppImage 
/tmp/.mount_ZettlrXnXW5e/AppRun: line 43: /tmp/.mount_ZettlrXnXW5e/zettlr: No such file or directory
kurt@kurt-lin ~/bin/AppImages $ 
```

## Platform
 - OS and version: Solus 4.1 Gnome
 - Zettlr Version: 1.8.0
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment] 2020-09-24 06:04
Thank you for reporting! We will have a look!

**Comment by nathanlesage** [comment] 2020-09-26 17:52
Duplicate of #1304

**Closed by nathanlesage** 2020-09-26 17:52 UTC
Labels: bug [critical], develop, pinned, priority:high, scope:Linux, v1.8.x
