### ISSUE TITLE
pandoc was not found on the system

### ISSUE THREAD

**Issue by orthl** [Zettlr/Zettlr#4953] opened 2024-02-12 16:31 UTC
### Description

Hello,
I have installed Pandoc and Zettlr for all users on my computer. 

Unfortunately Pandoc is not found by Zettlr, I have also added the environment variable in Windows manually and can use pandoc normally in other programmes. 

Both using the internal Pandoc of Zettlr and changing Pandoc in the settings of Zettlr had no success. I always get the error message that pandoc is not installed on my system. 

Can anyone help me here?

Kind regards
Lucas

### Reproducing

I don't know if it is reproducible.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.5

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

**Comment by nathanlesage** [comment] 2024-02-12 17:09
Could you please kindly try to export something, and then look in the logs for potential errors? The internal Pandoc should always work. This reminds me: Please have a look into the install folder of Zettlr, there should somewhere be a file "pandoc.exe".

**Comment by orthl** [comment] 2024-02-13 14:18
Hello, thanks for your reply. 

1. The file (pandoc.exe) exist in the folder (C:\Program Files\Zettlr\resources).
2. On the following secreenshots you can see my settings and the errorlog.

![image](https://github.com/Zettlr/Zettlr/assets/70632173/43887b2c-2d90-4d00-a45a-2843ea1ba5eb)
![image](https://github.com/Zettlr/Zettlr/assets/70632173/ed1e7042-dfb3-4737-bdc9-3e240e1dc8e7)

Thanks!
Lucas

**Comment by IntrixTheName** [comment] 2024-02-15 15:02
I've encountered a similar issue, and I'd like to add some of the reproducibility and troubleshooting information from my case. For context, I am also using version 3.0.5 downloaded from the website on an Intel 64bit computer with Windows 11.

# Reproducibility

- Begin with a fresh installation of 3.0.5
- Verify "Use the internal Pandoc for exports" is checked in settings (should be by default)
- Attempt exporting any file using any preset (I attempted "HTML", "Simple PDF", "Plaintext", and "Microsoft Word", more in the troubleshooting section)
- Window appears, stating "Pandoc has not been found on this system. Please install Pandoc prior to exporting or importing files". The image below is the log of this error.

![image](https://github.com/Zettlr/Zettlr/assets/101839315/d3ba79cd-cdc8-4522-87d0-28c83d05bed6)

Alternatively, another reproducibility sequence:

- Begin with a fresh installation of 3.0.5
- Download and install Pandoc following the instructions for Windows download (downloading the installer, not the Chocolatey method): <https://pandoc.org/installing.html>
- Restart the computer
- Launch Zettlr
- Verify "Use the internal Pandoc for exports" is unchecked
- Attempt exporting any file using any preset
- Window appears with identical message to the previous sequence, with an identical error message in the logs.

# Troubleshooting

Below are some sequences I have attempted at troubleshooting.

## Attempt full reinstallation

> For context, I first encountered this error after upgrading from 2.3.0 to 3.0.5:

- Through Windows Settings > Apps > Installed Apps, uninstall Zettlr
- Manually delete the app data folder (in my case, C:\Users\brad1\AppData\Roaming\Zettlr)
- Reinstall 3.0.5 release

## Verifying internal Pandoc exists:

- Navigate to Zettlr's install directory (in my case, C:\Program Files\Zettlr)
- Verified internal Pandoc is present (located C:\Program Files\Zettlr\resources\pandoc.exe)

## Revert to previous version (2.3.0):

- Uninstall Zettlr from Windows Settings
- Manually delete app data folder
- Download and install 2.3.0 release

## Verifying Pandoc is installed:

- Install Pandoc following instructions on <https://pandoc.org/installing.html>
- In the installer, install for local user only
- Restart the computer
- Verify Pandoc is installed by running `pandoc --version` in terminal, see screenshot below for output

![image](https://github.com/Zettlr/Zettlr/assets/101839315/36d61305-42c7-4448-ab26-79b951da9c59)

Alternatively,

- In the installer, install for all users on the machine
- Restart the computer
- Verify Pandoc is installed by running `pandoc --version` in terminal

## Installing LaTeX

- Follow instructions for installing MikTeX from Zettlr documentation: <https://docs.zettlr.com/en/getting-started/installing-latex/#windows>
- Restart the computer after installation

Hope this information helps!

**Comment by nathanlesage** [comment] 2024-02-16 10:18
I did a quick search for the error code, and it is being thrown at three positions within the entire codebase, always in this constellation:

```ts
try {
  await commandExists('pandoc')
} catch (err) {
  throw new Error(trans('Pandoc has not been found on this system. Please install Pandoc prior to exporting or importing files.'))
}
```

I suspect that `commandExists` may have difficulties on Windows; I remember once looking into its source and it seemed very convoluted.

To be honest, this is a very old error message back from the times when we didn't ship Pandoc with Zettlr. Maybe it's time to retire `commandExists`.

I just did a quick trial run, and my code is more resilient than I expected. I removed the internal Pandoc, tried to export, and it worked because despite me having checked the "Use internal Pandoc" checkbox, Zettlr did find the system wide install. After quickly removing that one, Zettlr successfully did not detect a Pandoc install and threw a readable error that Pandoc has not been found.

I guess that's good enough. Please try out the next Nightly, it should fix this. If not, please comment here again.

**Closed** 2024-02-16 10:20 UTC
Labels: bug
