### ISSUE TITLE
[[ followed by a tab inserts double ]]

### ISSUE THREAD

**Issue by GertjanBrouwer** [Zettlr/Zettlr#1708] opened 2021-02-03 14:35 UTC
## Description
Zettlr inserts an extra set of ]] after a link

## Reproducing
In any file create a link by typing [[ and either clicking on a random result or use tab.
You should now see a proper link e.g. [[zettelkasten]] Working with zettelkasten
Then press backspace and stop before deleting the [[ so only [[ is leftover. 
The start the search again and once again click on a result or tab.
The link that is inserted now has double ]] at the end

## Expected behaviour
Should only insert ]] after a link

[printscreen](http://prntscr.com/y5oe5w)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: v1.8.7

**Comment by boutil** [comment] 2021-02-04 22:48
Hi,
This looks like a duplicate of #1636.

**Comment by GertjanBrouwer** [comment] 2021-02-04 23:26
> Hi,
> This looks like a duplicate of #1636.

I couldn't replicate his problem. So I created my own issue with an easier replication instruction

**Comment by nathanlesage** [comment] 2021-02-08 13:34
I'll close #1636 because this one is newer and indeed it's the same issue (same module is working wrong here)

**Comment by nathanlesage** [comment] 2021-05-13 16:02
I've done a lot of fixing and in 2.0 I cannot reproduce this anymore, so closing as fixed!

**Closed by nathanlesage** 2021-05-13 16:02 UTC
Labels: bug, confirmed, pinned
