### ISSUE TITLE
link navigation not working

### ISSUE THREAD

**Issue by cedardocster** [Zettlr/Zettlr#2183] opened 2021-07-13 03:11 UTC
version 1.8.9 July 12

Hi, trying link navigation for files [[like this]] to go to "like this.md", but its not working. (see gif attached)

it is working better than before however (used to offer to create the file because it thought it didn't exist.

![zettlrLinks](https://user-images.githubusercontent.com/10538705/125384035-90714600-e355-11eb-8396-d61d55e72183.gif)

**Comment by nathanlesage** [comment] 2021-07-13 15:56
_Please_ use the issue template I provided. Saves me several steps of cleaning up. Will have a look.

**Comment by nathanlesage** [comment] 2021-07-21 09:57
Cannot reproduce this locally. Do the developer console say something after you ctrl-click?

**Comment by cedardocster** [comment] 2021-07-23 22:03
I can't find a "developer console" anywhere in the program.  I tried "which zettlr" at the terminal to try to run it that way, but that command comes up empty.  Also tried find . -name '*zettlr*', but nothing.  I can only run from the activities (ubuntu) and type in the name.

**Comment by nathanlesage** [comment] 2021-07-24 08:26
The developer console can be found by activating the debug mode in the preferences, and then in the newly appearing develop menu. The devtools work exactly like the Google Chrome devtools.

**Comment by cedardocster** [comment] 2021-07-26 00:12
the big list at the side in the developer console doesn't seem to change at all when I hover, then click, then ctrl-click on a link

(see attached)
![ZettlrLinks2](https://user-images.githubusercontent.com/10538705/126918039-b4320206-3f37-4b57-8b07-938fabd168ce.gif)

**Comment by cedardocster** [comment] 2021-07-26 00:15
Just to be clear - when I click on a link I'm expecting that file to open in a zettlr tab.  When I ctrl-click there's a search thingie that happens and most of the time I can see the file listed over there amoung other files, and I can open it from there, but I'd assume a link should just open when clicked.  Is that what's supposed to happen?

**Comment by nathanlesage** [comment] 2021-07-26 07:42
Yeah, seemingly unrelated but I'm pretty sure they have something to do: Generally the warning messages `FSAL event had an outdated timestamp` should not be logged, just like the `patchInFileTree` error you got above that. The whole file tree updating logic seems still a little wonky but working on that with little info has made it hard for me to find the remaining bugs.

So whenever something like that is logged, the only way I found to resolve them (right now) is to restart the app, since then everything should work. I'm gonna open a new issue for people to report these I think …

**Comment by cedardocster** [comment] 2021-07-26 14:18
Is there a checkbox somewhere to allow me to give you a more detailed look at a log file or something that would help?

**Comment by nathanlesage** [comment] 2021-07-26 16:16
Hm, the only two places are the devtools, and the log viewer. All logs are retained for I think 30 days in the logs subfolder of your appdata directory. I think there's not more than that …

**Comment by zh217** [comment] 2021-08-14 04:28
I encountered this problem recently after moving to a new Mac. Zettlr would refuse to follow any links.

Then I noticed that after I changed a file, links to that particular file (and only that file) started to work again.

So I did `touch *` in the terminal, and everything seemed to be fixed.

Might be something related to timestamp/cache?

**Comment by nathanlesage** [comment] 2021-08-15 10:56
> Might be something related to timestamp/cache?

Mh, the cache might be a problem. Zettlr should clean that after every update – are you on beta.1?

(And wrt OneDrive: that one does produce a few problems, yes, we've had multiple complaints that the way OneDrive works is not really sustainable)

**Comment by zh217** [comment] 2021-08-15 11:26
> Mh, the cache might be a problem. Zettlr should clean that after every update – are you on beta.1?

No I used the stable version installed by homebrew.

And I wasn't able to reproduce the problem after it has been "solved". Anyway if the "fix" is a simple `touch *`, I don't have any complaints if developer time is spent on more worthwhile problems, even if the cause remains a mystery.

**Comment by nathanlesage** [comment] 2021-09-11 15:34
> No I used the stable version installed by homebrew.

I think this should work on the most recent 2.0 beta, and I just checked it again and the functionality seems to be working fine. If something else pops up, feel free to comment here!

**Closed by nathanlesage** 2021-09-11 15:34 UTC
Labels: waiting for feedback, bug, develop

**Comment by cedardocster** [comment] 2021-09-15 00:39
I got the app-image for Zettlr-2.0.0-beta.3-x86_64.AppImage and I still am not able to follow links on ctrl-click (however the hover-over the link still shows the correct info of the file)

**Comment by nathanlesage** [comment] 2021-09-15 08:33
Are there any log outputs that might give an indiciation for what is happening? This is strictly speaking platform-independent code so it's weird that it's working on one platform but not on another.

**Comment by cedardocster** [comment] 2021-09-15 17:47
The following is the log immediately after starting and waiting for the current workspace to open and then control-clicking on a link that for sure does exist

[11:45:06]	こんにちは！ Booting Zettlr at Wed Sep 15 2021 11:45:06 GMT-0600 (Mountain Daylight Time).
[11:45:06]	Performing environment check ...
[11:45:06]	[Application] Pandoc has been bundled with this release. Path: /tmp/.mount_Zettlr9q9o6c/resources/pandoc
[11:45:06]	Added DevTools extension: Vue.js devtools
[11:45:06]	Environment check complete.
[11:45:06]	Registering custom protocol safe-file
[11:45:06]	Log provider booting up ...
[11:45:06]	Config provider booting up ...
[11:45:07]	[Config Provider] Loading configuration file from /home/david/.config/Zettlr/config.json ...
[11:45:07]	[Config Provider] Successfully loaded configuration
[11:45:07]	Appearance provider booting up ...
[11:45:07]	Assets provider starting up ...
[11:45:07]	Citeproc provider booting up ...
[11:45:07]	[Citeproc Provider] Loading CSL locale file at /tmp/.mount_Zettlr9q9o6c/resources/app.asar/.webpack/main/assets/csl-locales/locales-en-US.xml ...
[11:45:07]	[Citeproc Provider] Loading CSL locale file at /tmp/.mount_Zettlr9q9o6c/resources/app.asar/.webpack/main/assets/csl-locales/locales-en-GB.xml ...
[11:45:07]	Dictionary provider booting up ...
[11:45:07]	Recent documents provider booting up ...
[11:45:07]	Menu provider booting up ...
[11:45:07]	Tag provider booting up ...
[11:45:07]	Target provider booting up
[11:45:07]	CSS provider booting up ...
[11:45:07]	Translation provider booting up ...
[11:45:07]	Update provider booting up ...
[11:45:07]	Notification provider booting up ...
[11:45:07]	Stats provider booting up
[11:45:07]	Tray provider booting up ...
[11:45:07]	[Application] Added /tmp/.mount_Zettlr9q9o6c/resources to PATH.
[11:45:07]	[Application] The bundled pandoc executable is now in PATH. If you do not want to use the bundled pandoc, uncheck the corresponding setting and reboot the app.
[11:45:07]	[Stats Provider] Writing statistics to file
[11:45:07]	[Dictionary Provider] Loaded dictionaries: en-US
[11:45:07]	FSAL booting up ...
[11:45:07]	[Update Provider] Checking for application updates ...
[11:45:07]	[Updater] Checking https://www.zettlr.com/api/releases/latest for updates ...
[11:45:08]	[Update Provider] No new update available. Current version is v1.8.9.
[11:45:08]	[FSAL Directory] Path /home/david/SyncthingFolders/zettlrEpsilon/done took 123ms to load.
[11:45:09]	[FSAL] Path /home/david/SyncthingFolders/zettlrEpsilon took 1465ms to load.
[11:45:09]	Loaded all roots in 1.467 seconds
[11:45:11]	[R] [Main Window] Failed to decode downloaded font: file:///tmp/.mount_Zettlr9q9o6c/resources/app.asar/.webpack/renderer/3f5da30f833016202b1e.woff (index.html:0)
[11:45:11]	[R] [Main Window] OTS parsing error: invalid sfntVersion: 1836016757 (index.html:0)
[11:45:11]	[R] [Main Window] Failed to decode downloaded font: file:///tmp/.mount_Zettlr9q9o6c/resources/app.asar/.webpack/renderer/3f5da30f833016202b1e.woff (index.html:0)
[11:45:11]	[R] [Main Window] OTS parsing error: invalid sfntVersion: 1836016757 (index.html:0)
[11:45:14]	[Config Provider] Writing configuration file to /home/david/.config/Zettlr/config.json...
[11:45:28]	[R] [Main Window] Failed to decode downloaded font: file:///tmp/.mount_Zettlr9q9o6c/resources/app.asar/.webpack/renderer/3209557d68df4a11be08.woff (index.html:0)
[11:45:28]	[R] [Main Window] OTS parsing error: invalid sfntVersion: 1836016757 (index.html:0)
[11:45:28]	[R] [Main Window] Cannot show application menu: Target item has not been found. (index.js:2)

**Comment by nathanlesage** [comment] 2021-09-17 08:57
Mh, it seems as if the click is not even registered, because if it were and failed, there would be an error. On an unrelated note: "Cannot show application menu: Target item has not been found." This should not happen as well 🙄
