### ISSUE TITLE
[BUG] Filename is not longer added when linking files

### ISSUE THREAD

**Issue by b4nn** [Zettlr/Zettlr#840] opened 2020-05-25 16:08 UTC
## Description
Filename is not longer added when linking files.

## Reproducing
1. Create a link with [[]] function
2. Chose note from the autocomplete list

## Expected behaviour
Once a note is added, the filename should be added alongside the ID number. I've tried to change relevant Zettelkasten settings back and forth and to restart the app but the issue persists. 

**Screenshots**

Editor view:

![image](https://user-images.githubusercontent.com/65569952/82828937-0ee8fb00-9eaa-11ea-8ab0-d3b2fec46770.png)

My settings:

![image](https://user-images.githubusercontent.com/65569952/82828615-620e7e00-9ea9-11ea-906e-b1f47d278dd0.png)

## Platform
- Zettlr Version: v1.7.0-beta.7
- System: win32 10.0.18362 (architecture: x64)

**Comment by nathanlesage** [comment] 2020-05-25 18:19
Duplicate of #831

**Closed by nathanlesage** 2020-05-25 18:19 UTC
