### ISSUE TITLE
[Bug] Hotkey for sidebar not working on W10 and German QWERTZ keyboard layout

### ISSUE THREAD

**Issue by ItsFullOfCode** [Zettlr/Zettlr#2638] opened 2021-10-15 17:37 UTC
### Description

The sidebar can be toggled with the "Toggle Sidebar" button and the corresponding menu entry, but not by the hotkey Ctrl+?
By comparison, the hotkey Ctrl+! to toggle the file manager works by clicking Ctrl+Shift+! (QWERTZ keyboard). Neither Ctrl+? nor Ctrl+Shift+! works for the sidebar.

### Reproducing

Press Ctrl+Shift+? (or Ctrl+?) on a QWERTZ keyboard on Windows 10. The sidebar will not be toggled.

### Zettlr Version

Stable (most recent version)

### Specify version

 2.0.0

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment] 2021-12-14 13:14
Can you still reproduce this in 2.0.3? Shortcuts are `Cmd/Ctrl+!` and `Cmd/Ctrl+?`, where you may need to press the `Shift` key if the `!` or `?` characters require that.

**Comment by Skelbti** [comment] 2021-12-16 10:50
Same issue with the french AZERTY layout. Nothing works on `2.0.3`.

**Comment by nathanlesage** [comment] 2021-12-16 13:43
Will test that out momentarily on my Windows machine and see what happens.

**Comment by nathanlesage** [comment] 2021-12-16 14:04
Just tested it out on Windows 10 with both QWERTY and QWERTZ layouts, following observations:

* Both ANSI- and ISO-keyboard: `Ctrl+Shift+1` (a.k.a.. `Ctrl+!`) works to toggle the file manager in both German and U.S. layouts
* Both ANSI- and ISO-keyboard: `Ctrl+Shift+/` (a.k.a. `Ctrl+?`) works to toggle the sidebar in U.S. layout
* With a German QWERTZ layout, however, that second shortcut does not work **on an ANSI or ISO keyboard**. For both keyboard styles, the shortcut switches to `Ctrl+'` (the key with `#` printed on it)

However, after a cursory search on Google, it appears that this is simply out of my control. So I would say we postpone fixing this (or, rather, acknowledge the fact that this is unfixable on my end) until we have custom keyboard shortcuts so that everyone can customize the shortcuts to their liking.

**Comment by Skelbti** [comment] 2021-12-16 16:10
I've tried your solution on my french AZERTY layout and it works.
- `Ctrl+Shift+1` (produce `1` symbol in AZERTY layout) toggles the file manager.
- `Ctrl+Shift+/` (produce `/` symbol in AZERTY layout) toggles the sidebar.

A feasible solution would be to modify the shortcut indications in the menus according to the location. For example, Zettlr is in French on my computer and instead of having written in the menus the shortcuts `Ctrl+?` and `Ctrl+!`, I would have `Ctrl+1` and `Ctrl+/`.

**Comment by nathanlesage** [comment] 2021-12-16 17:27
> For example, Zettlr is in French on my computer and instead of having written in the menus the shortcuts Ctrl+? and Ctrl+!, I would have Ctrl+1 and Ctrl+/.

Yeah, that idea came up earlier as well, but I refrained from doing this until now, because I worry that those mappings would change, or be inconsistent or something else. Plus, in general it would be so great if it would just … work … as advertised :/

**Comment by MildlyInterested** [comment] 2021-12-22 17:14
To save some time you could add a disclaimer somewhere in the settings that keybinds are based on the key LOCATION on a standard ANSI layout. Then people can look up the difference between their layout and the standard one and figure out what character it is on theirs.

Not an ideal solution but better than nothing.

**Comment by nathanlesage** [comment] 2021-12-23 09:54
The thing is there is no guarantee that works. I recently found two instances of keys that were mapped completely arbitrary

**Comment by nathanlesage** [comment] 2023-12-03 18:53
I just decided it is time to close this ages-old bug and move the shortcut to be `Cmd/Ctrl+Shift+0`, which is reasonably close to the (physical) location of the original intended shortcut, but it actually works (although only tested for DE-ISO, US-ISO, and US-ANSI layouts, but I guess it's safe to say it should work in general…)

**Closed as completed** 2023-12-03 18:52 UTC
Labels: bug
