### ISSUE TITLE
[Bug] 2.2.3 Newly created files aren't added to workspace until application restart

### ISSUE THREAD

**Issue by fatzombi** [Zettlr/Zettlr#3248] opened 2022-02-21 23:24 UTC
### Description

When using a combination of the CMD + N and CMD + S keyboard shortcuts to create and save a file, the file is properly saved to the file system, but does not appear in the workspace until after an application restart occurs. This happens to me no matter what the File manager mode is defined as.

My expectation is that the newly created file will appear in the file list without requiring an application restart.

I was NOT able to reproduce this bug on Windows Server or on my Kali Linux box.

### Reproducing

1. Press CMD + N, to create a new note.
2. Type "this is a test" in the editor.
3. Press CMD + S, to save the note that is currently open.
4. Click the Save button in the save dialog.
5. Observe that the saved file does not appear in the file list.
6. Restart the application.
7. Observe that the saved file now appears in the file list.

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.3

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Monterey 12.2.1

### Additional Information

Application log
```
[17:53:00]	Saving file 20220221175258.md...
[17:53:02]	Saving file to /Users/fatzombi/Documents/Zettlr Tutorial/20220221175258.md...
[17:53:02]	[Stats Provider] Writing statistics to file
[17:53:02]	File 20220221175258.md saved.
[17:53:02]	[R] [Main Window] TypeError: Cannot read properties of undefined (reading 'parent') (index.js:2)
[17:53:07]	[Config Provider] Writing configuration file to /Users/fatzombi/Library/Application Support/Zettlr/config.json...
```

Console log
```
index.js:2 TypeError: Cannot read properties of undefined (reading 'parent')
    at I.addToFiletree (index.js:2)
    at index.js:2
    at index.js:2
    at Array.forEach (<anonymous>)
    at index.js:2
    at I._withCommit (index.js:2)
    at I.commit (index.js:2)
    at Object.I.commit (index.js:2)
    at I.filetreeUpdate (index.js:2)
(anonymous) @ index.js:2
Promise.catch (async)
(anonymous) @ index.js:2
(anonymous) @ VM114 preload.js:1
emit @ VM14 node:events:394
onMessage @ VM112 renderer_init:73
```

**Comment by nathanlesage** [comment] 2022-02-25 11:35
This was a very weird race condition which I fixed in commit 59b5ba42 just now. Please feel free to keep an eye on this in case it re-occurs.

**Closed by nathanlesage** 2022-02-25 11:35 UTC
Labels: bug

**Comment by subhodeeps** [comment] 2022-03-01 21:33
Hi I am still facing this issue. I am on MacOS M1.

**Comment by nathanlesage** [comment] 2022-03-02 10:14
Yes, that is to be expected since we did not yet release the patch.

**Comment by cjpoor** [comment] 2022-05-31 01:05
I find basically the same issue. 

When a new note is added externally to the workspace directory it is not found by Zettlr unless the app is restarted.

Expected behaviour: Some way to reload the directory without restarting Zettlr.

Zettlr Version: 2.2.6 (UUID: d22d729e-276e-4ec3-b830-aff3a4e3f4b9)

System: linux 5.4.0-66-generic (architecture: x64)
Linux Mint 20.3 Cinnamon

**Comment by cjpoor** [comment] 2022-05-31 02:49
Update: The most recent note added was recognized by Zettlr.

This may be an intermittent bug.

**Comment by cjpoor** [comment] 2022-06-02 04:50
No new problems of this kind so far.
It could be this problem with inotify which would explain why it is so intermittent. See
https://unix.stackexchange.com/questions/548509/reliability-of-inotifywait-loop

**Comment by abigailswallow** [comment] 2022-09-01 00:31
Hi! Came across this as I'm presently facing the same issue. Files don't update until a restart of workspace or app. 
System: M1 Mac, macOS 12.3
Zettlr version: 2.3.0

Any ideas on a fix for this?

**Comment by nathanlesage** [comment] 2022-09-03 09:09
I'm currently getting towards finishing the Codemirror 6 migration, after that I can have a look, but I think it's already fixed. So if you're accepting some risk you could switch to the nightly builds.

**Comment by smartguy1196** [comment] 2022-12-04 03:17
Currently observing this bug on Ubuntu Desktop 22

**Comment by smartguy1196** [comment] 2022-12-04 03:22
Created new document with Ctrl+N, saved with Ctrl+S as Automation Engineer.md

![image](https://user-images.githubusercontent.com/12621101/205472669-e4562421-31b0-41e4-819d-e9ecc34589e8.png)

**Comment by nathanlesage** [comment] 2022-12-04 18:25
@smartguy1196 As I mentioned in my last comment, this is fixed in the current dev branch and hence will be fixed in the next version.

**Comment by aathanor** [comment] 2023-09-12 06:52
Same bug in version 3 on Mac M1. Any new file created in Finder does not show in the workspace if not restarting the app. (I have a workflow with Drafts writing files in a folder workspace)

**Comment by thinkhuman** [comment] 2024-01-29 18:16
> Same bug in version 3 on Mac M1. Any new file created in Finder does not show in the workspace if not restarting the app. (I have a workflow with Drafts writing files in a folder workspace)

Confirmed for me:
* Macbook Air M2, MacOS Sonoma (v14)
* Zettlr v3.0.0
* Workaround: restart app.

**Comment by nathanlesage** [comment] 2024-02-02 21:32
Please wait for next Monday's nightly, try it out, and then open a new issue with any additional info.

**Comment by jzedwards** [comment] 2025-02-14 17:21
> > Same bug in version 3 on Mac M1. Any new file created in Finder does not show in the workspace if not restarting the app. (I have a workflow with Drafts writing files in a folder workspace)
> 
> Confirmed for me:
> 
> * Macbook Air M2, MacOS Sonoma (v14)
> * Zettlr v3.0.0
> * Workaround: restart app.

+1 on Windows 11 v3.4.1, incl w  Feb 10 nightly

Workspace is on a webdav share; is there anything I can do to force a re-read?
