### ISSUE TITLE
[Bug] Cannot open Zettlr nightly installation 

### ISSUE THREAD

**Issue by joraphael** [Zettlr/Zettlr#2140] opened 2021-06-29 12:09 UTC
### Description

Hi, 

I'm unable to open Zettlr after installing the nightly version. Zettlr pops up as background process in the Windows Task Manager for a couple of seconds, then disappears. Installing and opening the stable version works fine.
Wondering if this is a bug,or if I'm missing something? 

Many thanks, I'm really looking forward to Zettlr 2.0!

### Reproducing

1) uninstall Zettlr
2) download nightly .exe
3) run .exe --> install zettlr-nightly
4) open zettlr --> leading to bug.
5) uninstall zettlr-nightly
6) install zettlr stable (i.e. choco install zettlr)
7) open Zettlr --> works fine.

### Zettlr Version

Nightly

### Specify version

Zettlr-1.8.9-x64.exe + nightly -28062021

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment] 2021-06-29 14:53
I've been notified yesterday that there was something off. I'll be on the lookout for this!

**Comment by legend053** [comment] 2021-06-29 20:44
Thank you. Same here.

**Comment by nathanlesage** [comment] 2021-07-02 09:59
Haven't been able to test this out myself, but in a few hours a new nightly will be automatically built by the CI anyway, so please make sure to test this one out. If it still doesn't work, please comment here so I can have a look.

**Comment by joraphael** [comment] 2021-07-02 15:59
Hi, I unfortunately the problem persists. I tested the Fri Jul 2nd, 2021 14:29:13 version of Zettlr-1.8.9-x64.exe. No change to what I described above.

Many thanks for your hard work!

**Comment by nathanlesage** [comment] 2021-07-02 16:08
Alright, will spin up my windows machine in a few minutes and test that out!

**Comment by nathanlesage** [comment] 2021-07-02 16:34
Calling in from my windows machine: Figured that the `yarn test-gui`-command didn't work, but that's unrelated. I just downloaded and installed the most recent nightly and it started like a charm. Would you mind renaming your configuration file from `config.json` to `config.backup.json`? This will prompt Zettlr to create a new configuration file. Maybe that's the cause.

**Comment by joraphael** [comment] 2021-07-02 16:51
Perfect. Now it's working for me. Many thanks!
For others with the same issue: The configuration file is stored under Windows: C:\Users\<your username>\AppData\Roaming\zettlr More info here: https://docs.zettlr.com/en/install/

**Comment by nathanlesage** [comment] 2021-07-02 17:27
Ah perfect! CC @tobiasdiez Apparently there's another config issue.

@joraphael Would you mind sharing the not-working config file so we can have a look at what it's causing?

Finally, closing as solved.

**Closed by nathanlesage** 2021-07-02 17:27 UTC
Labels: bug

**Comment by joraphael** [comment] 2021-07-02 19:07
I send an email to hendrik@zettlr.com.

**Comment by nathanlesage** [comment] 2021-07-02 20:45
Received an email, found the bug, and fixed it. Thank you!
