### ISSUE TITLE
Autosave moves the text insertion cursor to text file start

### ISSUE THREAD

**Issue by ME7DYCgw8M** [Zettlr/Zettlr#802] opened 2020-05-15 07:39 UTC
## Description

Autosave moves text insertion cursor to the start of the file.

## Reproducing

1. Have md-file with multiple rows
2. Write something, asterisk appears to tab (indicating that file is not saved yet)
3. Wait for some seconds for autosave to activate
4. Zettlr autosaves the file (asterisk in tab disappears)
5. Cursor moves instantly to the start of the file

## Platform
 - OS and version: Windows 7
 - Zettlr Version: Release v1.7.0-beta.4

**Comment by nathanlesage** [comment] 2020-05-15 08:18
Duplicate of #773

**Closed by nathanlesage** 2020-05-15 08:18 UTC
