### ISSUE TITLE
[Bug] v2.2.0 not opening on ubuntu

### ISSUE THREAD

**Issue by gusmmm** [Zettlr/Zettlr#3178] opened 2022-02-11 15:11 UTC
### Description

I had v2.1.3, and it worked prefectly. I installed the v2.2.0, and I get this error messages:

Performing environment check ...
[Application] Pandoc has been bundled with this release. Path: /opt/Zettlr/resources/pandoc
Environment check complete.
mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!
[4194:0211/150432.936726:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
RangeError: Maximum call stack size exceeded
    at String.includes (<anonymous>)
    at e (/opt/Zettlr/resources/app.asar/.webpack/main/index.js:2:1632193)
    at e (/opt/Zettlr/resources/app.asar/.webpack/main/index.js:2:1632458)
    at e (/opt/Zettlr/resources/app.asar/.webpack/main/index.js:2:1632458)
    at e (/opt/Zettlr/resources/app.asar/.webpack/main/index.js:2:1632458)
    at e (/opt/Zettlr/resources/app.asar/.webpack/main/index.js:2:1632458)
    at e (/opt/Zettlr/resources/app.asar/.webpack/main/index.js:2:1632458)
    at e (/opt/Zettlr/resources/app.asar/.webpack/main/index.js:2:1632458)
    at e (/opt/Zettlr/resources/app.asar/.webpack/main/index.js:2:1632458)
    at e (/opt/Zettlr/resources/app.asar/.webpack/main/index.js:2:1632458)

Zettlr does not open.
Thanks for your time!

### Reproducing

try to open zettlr

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.0

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

ubuntu 20.04

**Comment by kyaso** [comment] 2022-02-11 15:37
Possible duplicate of #3174.

Interesting to note is that here the error occurs at `String.includes`, instead of `String.split`.

**Comment by AIBN60** [comment] 2022-02-11 16:32
Confirmed, nor deb neither appimage version is working on Focal Fossa. All is fine in Bionic Beaver

**Comment by kyaso** [comment] 2022-02-11 17:07
Closing this in favor of #3174. A temporary workaround that hopefully fixes the issue can also be found over there.

**Closed by kyaso** 2022-02-11 17:07 UTC
Labels: bug
