### ISSUE TITLE
[Bug] Quote chararacters turned into strange characters when copying from Zotero 6.0.4 to Zettlr

### ISSUE THREAD

**Issue by jeroenmuller** [Zettlr/Zettlr#3352] opened 2022-03-28 15:15 UTC
### Description

When copying notes or citations from Zotero 6.0.4 to Zettlr 2.2.4, the quotations marks included in the note/citation are somehow turned into strange characters in the Zettlr editor. LEFT DOUBLE QUOTATION MARK (“) is turned into â€œ and RIGHT DOUBLE QUOTATION MARK (”) is turned into â€. These seem to be the underlying UTF-8 characters (see https://www.cogsci.ed.ac.uk/~richard/utf-8.cgi?input=2E&mode=bytes). When copying to other text editors, for example gedit or the terminal, this issue does not occur. When the text is first copied to gedit, and then from gedit to Zettlr, the problem also does not occur. This leads me to believe that the issue is due to a specific interaction between Zotero and Zettlr (perhaps due to Zotero using UTF-8 encoding and CodeMirror using UTF-16 encoding). 

This is a problem because these characters are widely used in Zotero and in the new built-in note pdf annotator in Zotero 6 (see https://www.zotero.org/blog/zotero-6/). The problem makes my workflow with Zotero built-in notes and Zettlr very cumbersome. I don't know if the problem is caused by Zettlr, or if Zotero somehow does something wrong in a way that most other appications can deal with. 

## Steps to reproduce
1. Set Zotero language to English (Preferences -> Advanced -> Language). Localization affects quote symbols in Zotero so this issue may not occur in the same way for other languages 
2. In Zotero preferences -> Export, set Note format to "Markdown + Rich Text" (the default option). 
3. Add a new item to the library by clicking File -> New item -> Document. Enter a title for the document, e.g. Test
4. Drag the item from the library pane to the Zettlr editor. 

Alternatively, create an item with a PDF attachment and add a note with the built-in PDF editor including an annotation (the highlighted text will be enclosed in quotes). Drag the note item from the library view into Zotero.

## Expected behavior
The text should show up as “Test,” n.d. (it shows up like that when dragged to gedit)

## Actual behaviour
The text shows up as â€œTest,â€ n.d.

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.4

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 21.10 with xorg session

### Additional Information

It is possible to circumvent this issue in some cases by changing the note template in Zotero to not use this type of quote: 
https://www.zotero.org/support/note_templates

**Comment by jeroenmuller** [comment] 2022-03-28 16:02
Hi, thank you for the quick response. Pasting as plain text indeed works fine. I just tried the nightly and the problem persists, and it also persists when I switch to the Ubuntu display manager (Mutter) instead of xorg. This problem also existed for me with Zettlr 2.2.2 and with earlier versions of Zotero 6, so I do not think it is related to recent changes in Zettlr.

**Comment by nathanlesage** [comment] 2022-04-02 19:54
Hm. Could be a problem with the operating system as well. It sounds to me as if something produces an encoding error when taking the string from Zotero into the clipboard and/or when taking the string from the clipboard into Zettlr.

I don't think that this one is Zettlr's fault.

**Comment by RuizSerra** [comment] 2023-01-31 05:39
FWIW, I am having the same issue `â€œSome highlighted quote.â€` with:

* Ubuntu 22.04
* Zotero 6.0.20
* Obsidian 1.1.9

**Comment by nathanlesage** [comment] 2023-02-19 09:45
@RuizSerra This sounds as if this may be a Zotero problem … I am going to close this issue because I am unable to reproduce this issue, but I am also frequently updating Zotero, and it is likely that they fixed this in the meantime.

**Closed by nathanlesage** 2023-02-19 09:45 UTC
Labels: bug

**Comment by RuizSerra** [comment] 2023-03-24 04:03
The problem is that when wrapping the annotation in quotes, Zotero uses ` “ ` and ` ” ` as opposed to ` " `. When dropping the dragged annotation into a plain text editor it shows the double quotes, but when dropping into Obsidian (and I assume Zettlr), it converts the double quotes into the `â€œ` and `â€` for left and right respectively.

**Comment by nathanlesage** [comment] 2023-03-24 11:24
This has nothing to do with fancy quotation marks. Zettlr uses these everywhere as well. This is an encoding issue. Zettlr internally works with UTF-8, and I believe Obsidian as well. My assumption is that the Zotero drag behavior may possibly encode strings in some ANSI or ISO encoding, possibly an oversight because many people don't drag and drop text, and rather use Ctrl-C/CTRL-V for that. In light of the fact that this only happens with Zotero and doesn't occur if you copy and paste text, I don't think it would be wise for Zettlr to implement an exception for that one case.
