### ISSUE TITLE
Error exporting to Reveal.js

### ISSUE THREAD

**Issue by hiperterminal** [Zettlr/Zettlr#1604] opened 2021-01-06 13:58 UTC
## Description

My zettlr (1.8.4) is not exporting to Reveal.js. I reported an issue some versions ago (1.8.1 if I am correct) and the next version that was solved, but now is not exporting again.

You can not export your documents.

## Reproducing

* I wrote something in markdown in Zettlr.
* Then I use the menu to Export > reveal.js Presentation > Choose a theme.
* A message appears: error exporting.

## Expected behaviour

With the same set up in previous versions of Zettlr, I can export without problem.

![Screenshot of the message](http://wiki.hiperterminal.com/lib/exe/fetch.php?media=capturas:captura_de_pantalla_de_2021-01-06_14-48-04.png)

## Platform
 - OS and version: Ubuntu 20.04.1 LTS
 - Zettlr Version: 1.8.4

## Additional information

In the last updates I need to write a ticket because this error is coming back. I know I have a correct set up because it worked before and my pandoc and xelatex worked well.

Thanks for your help!

**Comment by ShadowMax** [comment] 2021-01-08 13:46
I have similar error, when I try to export my project:
![image](https://user-images.githubusercontent.com/10102994/104022101-3f7f6a00-51d9-11eb-9fad-b04ab25fb50e.png)

**Comment by nathanlesage** [comment] 2021-01-08 15:16
@ShadowMax The problem is the $citeproc$-thingy. Consider "resetting" the Pandoc command (Settings -> Advanced -> the button next to the text field)

**Comment by nathanlesage** [comment] 2021-01-08 15:18
Ah, and the same goes for @hiperterminal, sorry!

Closing this issue, because this error is basically a result of the Pandoc command in the first place, BUT as we are now migrating to Pandoc, I will get rid of this error-prone thing as well, so rest assured: Beginning from 1.9.0 or so you won't have to analyse your failing commands anymore! :) 

Please see issue #1552 for further updates!

**Closed by nathanlesage** 2021-01-08 15:18 UTC

**Comment by ShadowMax** [comment] 2021-01-09 21:29
> @ShadowMax The problem is the $citeproc$-thingy. Consider "resetting" the Pandoc command (Settings -> Advanced -> the button next to the text field)

Cool! It's work for me, thx for help! :)

**Comment by hiperterminal** [comment] 2021-01-11 09:12
@ nathanlesage Thanks, it works!
