### ISSUE TITLE
[Bug] Can't open workspace

### ISSUE THREAD

**Issue by jlnbdt** [Zettlr/Zettlr#3296] opened 2022-03-06 15:37 UTC
### Description

Hi,

I'm using Zettlr 2.2.4 with Fedora.

I get this error message when I try to open a workpace (got it with 2.2.3 too):

![Capture d’écran du 2022-03-06 10-41-16](https://user-images.githubusercontent.com/6383095/156930013-671995db-3109-4756-a036-ae79118f4aab.png)

It depends on the workspace. For example, loading the workspace `/home/julien/Documents/Nextcloud/Notes personnelles` failed, but I can load `/home/julien/Documents/Clara-nxc/Notes CLARA`

### Reproducing

Just trying to load a workspace.

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.4

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Fedora

### Additional Information

Can't see anything conclusive in the logs.

**Comment by StuporMundi1337** [comment] 2022-03-17 07:23
Hey guys, I'm experiencing similar behavior with Zettlr 2.2.4 (stable) on Windows 10 (AMDx64). I always get the Windows notification, that Zettlr is trying to open the directory, but it just won't work sometimes (I waited for about 45-60 minutes twice). Tried reinstalling Zettlr twice, restarting the PC twice.
However, I tried to open the same directories on my older notebook (Windows 10, Intelx64, Zettlr 2.2.4 (stable)) and it works. Don't really know if it fits in this thread, just wanted to report it.

**Comment by nathanlesage** [comment] 2022-03-17 11:13
Is there something more informative logged? You can open the logs by activating debug mode in the preferences, then choosing Develop -> Open Logs. A screenshot of some relevant looking parts would be very helpful!

**Comment by StuporMundi1337** [comment] 2022-03-17 14:56
Are the logs supposed to show if you're opening a workspace? Logs don't show anything, if I try, neither the working nor the failing workspaces.

**Comment by nathanlesage** [comment] 2022-03-18 16:25
Then I forgot to log something …

But I mean it is something with those workspaces that prevents them from opening. I'll add appropriate logging so that we have a chance to figure out what is happening.

**Comment by nathanlesage** [comment] 2022-03-18 19:08
Logging is now in. The new nightly on Monday will have that feature. Please download it (it's otherwise the same as 2.2.4) and then we will have the error logged and we can go further in what is going wrong.

**Comment by StuporMundi1337** [comment] 2022-03-19 10:05
Thank you, I'll definitely do that! I've also found the old issue with the large loading time, I'm just confused why it's working on my older laptop with the exact same directories.

**Comment by nathanlesage** [comment] 2022-03-19 11:42
> I'm just confused why it's working on my older laptop with the exact same directories.

There are basically two obvious possibilities, notwithstanding potential more obscure issues: Either on your laptop there is a rights-issue (either that the directories themselves have wrong access rights, OR that Zettlr does not have the right to access these directories, for example on macOS you have to explicitly allow apps to access certain parts of the file system, and if you accidentally denied that, it is hard to grant it afterwards). The other possibility is that on your other computer some file has sneaked into the folder that causes Zettlr to caugh.

The former issue is not an issue with Zettlr, the latter is something we should be able to handle!

**Comment by StuporMundi1337** [comment] 2022-03-22 09:06
So I've downloaded the new nightly and here's the relevant part of the logs when I'm trying to open a new workspace in Zettlr:
![Zettlr_workspace_error](https://user-images.githubusercontent.com/100134191/159444916-eabc5ec5-59d6-470b-8299-18a219da9b2e.png)
"ZK_leisure_reading" is part of "MarkdownNotes". I can open any other directory in "MarkdownNotes" directly, just "ZK_leisure_reading" won't open.

**Comment by nathanlesage** [comment] 2022-03-25 18:29
@StuporMundi1337 Ah, I have never thought there were still errors left in parsing settings files, I haven't touched that code in ages. But I can add an additional check so that malformed settings files are just ignored and log a warning (rather than preventing the loading of that directory as a whole).

With regard to the error that prevents the error dialog from showing up (oh, the irony), I have to investigate why that is a problem on Windows. Or, rather, someone else. Because neither do they throw an error on macOS, nor do I have a Windows computer ready at hand right now.

**Comment by nathanlesage** [comment] 2022-03-25 18:30
Oh and I just saw that there's this small error next to the error message, which means there are some details! If you could just paste them here as well, maybe they give us an additional hint!

**Comment by StuporMundi1337** [comment] 2022-03-28 07:23
Okay, thanks! Here's the additional information for the first error message:
Name: Error
Message: Could not parse settings file for ZK_leisure_reading
Error: Could not parse settings file for ZK_leisure_reading

And for the second error message:
Name: Error
Message: ERR_FAILED (-2) loading 'file:///C:/Users/User/AppData/Local/Programs/Zettlr/resources/app.asar/.webpack/renderer/error/index.html?title=Could+not+open+new+root&message=There+was+an+error+accessing+%22%3Cunknown%3E%22&contents=undefined%3A+Unknown+error'
Error: ERR_FAILED (-2) loading 'file:///C:/Users/User/AppData/Local/Programs/Zettlr/resources/app.asar/.webpack/renderer/error/index.html?title=Could+not+open+new+root&message=There+was+an+error+accessing+%22%3Cunknown%3E%22&contents=undefined%3A+Unknown+error'

Is that what you mean? Let me know :)
And btw: I've worked around the error by just creating a new directory and pasting all files from the directory that can't be opened. Now everything works as usual. So no rush! And thanks a lot.

**Comment by StuporMundi1337** [comment] 2022-03-29 06:07
Fun Fact: Today I can't open the workspace that I created yesterday and renamed into ZK_leisure_reading. That's weird, it worked yesterday.

**Comment by clarkie1977** [comment] 2022-04-06 17:49
As requested via Twitter: I cannot add a directory (my iCloud directory that I have been using since I first discovered Zettlr) on my Older Mac (Intel) and my newer (M1) Mac. I can add a local directory. I am using Version 2.2.4 (2.2.4). I have ensured that the entire directory is fully downloaded from the iCloud. I receive the same "Unkown Error" message as displayed above. 

**I am not a developer but in the log, I see three warnings:** 

[18:40:20]	[Assets Provider] Found outdated filter links.lua; copying ...
[18:40:20]	[Assets Provider] Found outdated filter tags.lua; copying ...
[18:40:20]	[FSAL Watchdog] The chokidar process falls back to polling. This may lead to a high CPU usage.

**In the console I see one issue message:**

A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.
1 source
index.js:1

Not sure this info is of any use?

**Comment by nathanlesage** [comment] 2022-04-07 18:27
The info itself is not really helpful, but I'm going to try to create some iCloud folder to test this out myself … if I figure out how to do so!

**Comment by NLeVoguer** [comment] 2022-04-12 08:24
Hello, first I want to thank you for this great software you created and that I have been very happy to use for the past year. I have a similar problem to the ones noted above since I installed zettlr version 2.4 (and also in 2.5, I tried today). When I try to open a file I get a "system.error.open_root_error" message. 

Just as StuporMundi, I noticed that I cannot open a folder that I have opened before but I have no problem opening new folders. So, if I just create a copy of my folder, I am able to open the new one but I will again not be able to open the new one after restarting the computer. I am on Windows 10. 

The only error message I get in the logs is : 
"[0:11:15]	Could not open new root F:\These\Zettelkasten\rédaction - Copie!"

I hope this can help you resolve the issue.

**Comment by nathanlesage** [comment] 2022-04-23 11:59
I've just fixed issue #3400 and hopefully that was the cause for these issues as well. Please feel free to check out [the next nightly version](https://nightly.zettlr.com/) which is coming on Monday to see if that fixes the problem, and please then report back here.

**Comment by ChibiYuzu** [comment] 2022-08-23 08:13
Hello There! I have a similar problem here! I have downloaded Zettlr 2.3.0. from the FlatHub repository available on my computer and for the last few days, whenever I launch it, it gets first stuck on the following message:

`ENOENT: no such file or directory, open '/home/usr/Documents/NOTES/BIBLIOGRAPHIES/Ma bibliothèque.json'
ENOENT: no such file or directory, open '/home/usr/Documents/NOTES/BIBLIOGRAPHIES/Ma bibliothèque.json'`

Then, when I click on ok, it opens, but it won't load the workspaces I have been using for months. When I try to open a new workspace, it can't find any other folder except "Home" and "Desktop". And in "Home" it can't find the Documents folder, where I have sub-folders with my notes. If I try to save files on "Home" or "Desktop", I can't find them anywhere afterward. It's like they are saved in another mysterious "Home" ou "Desktop" folders I can't find when using Nautilius navigation tool. For the moment, I'm using the AppImage, but I'm not very good with handling these packages (for instance, I can't add it to my list of software in the start menu, despite my efforts to follow instructions on how to do that from various sources). So, I'd rather used the package downloaded from FlatHub, 

**Reproducing**
Just trying to load  workspaces.

**Zettlr Version**
Stable (most recent version)
**Specify version**
2.2.3

**Your Platform**
- [ ] Windows
- [ ]   macOS
- [x] Linux

**Architecture**
Intel 64bits

**Operating System Version**
Ubuntu 22.04

**Comment by nathanlesage** [comment] 2022-08-23 08:41
@ChibiYuzu As far as I understand the flathub release has now very restrictive access regulations. Please see here for potential help in your regard: https://github.com/flathub/com.zettlr.Zettlr

**Comment by JonnnPB** [comment] 2022-12-02 16:11
Hello, I know this has been closed, but two days ago I started experiencing this same issue. 

Here are my logs: 
![Screen Shot 2022-12-02 at 16 10 04](https://user-images.githubusercontent.com/119676721/205300368-9802cd9a-ab9c-40d0-b139-7fe63dd8b08c.png)

I was using the latest update of Zettlr, but after reading this thread decided to try the nightly version. I had the exact same issue. I'm using Version 2.3.0+nightly-20221128 on an Intel Mac.   

The Workspace Directory is in my Google Drive folder, but I have ensured that it's always downloaded onto my computer. Furthermore, I've been using Zettlr for at least a month with this setup without prior issues. 

I'd like to have it on Google Drive. Google Drive has an option to backup a folder on your computer, but if I do that, I haven't been able to access that folder from iA Writer on my phone, which is a deal breaker. My current setup, until this issue presented itself two days ago allowed me to use the same directory of notes in Zettlr on my computer and iA Writer on my Android phone. 

I'm open to changing or tweaking my workflow if what I'm trying to do is just inherently problematic, but I don't know a better way nor did I have any problems for a while with my current setup. 

Thank you so much in advance!

**Comment by nathanlesage** [comment] 2022-12-02 18:38
@JonnnPB Are you using Windows 10? I found this thread here: https://answers.microsoft.com/en-us/msoffice/forum/all/permission-denied-error-70-when-you-use/979ad63d-9c5d-4e95-9bd0-fd514651c1cb

Could this be the cause? If so, I know that Google Drive has caused numerous problems in the past; but that would be the only immediate solution for now …

**Comment by JonnnPB** [comment] 2022-12-02 19:37
Thanks @nathanlesage for the tip. Unfortunately, I'm not using Windows 10. I'm using Mac OS Monterey (Version 12.1) on 2017 Macbook Air. Have there been Google Drive issues on Mac too? If so I can try to find a workaround.

**Comment by nathanlesage** [comment] 2022-12-02 21:12
> Have there been Google Drive issues on Mac too?

I don't know, I'm using a Nextcloud setup, but I know others had issues as well … I just don't know whether they fixed the issues … does opening workspaces work if you copy a directory out of the Drive directory?

**Comment by JonnnPB** [comment] 2022-12-03 04:37
> does opening workspaces work if you copy a directory out of the Drive directory?

That must be the issue. I wasn't able to copy and paste the folder into a new local folder at all using the system file manager. It returned an error message that some of the files couldn't be read or written (which is surprising for a folder of .txt and .md files). Google Drive must be messing something up. It's nice to know it's not a Zettlr issue, but means I'm back at the drawing board for how to sync my notes across Zettlr on Mac and iA Writer on Android. 

Thank you so much @nathanlesage .

**Comment by nathanlesage** [comment] 2022-12-03 18:54
> That must be the issue. I wasn't able to copy and paste the folder into a new local folder at all using the system file manager. It returned an error message that some of the files couldn't be read or written (which is surprising for a folder of .txt and .md files).

That sounds ugly o.O I've never heard something THAT bad

**Comment by nathanlesage** [comment] 2023-02-19 09:42
I'm going to close this issue because this turned out to be more of a catch-all issue for anything related to Workspace opening. Please open specific issues with the actual error if you encounter something like that. But first make sure to always test out the most recent nightly ;)

**Closed by nathanlesage** 2023-02-19 09:42 UTC
Labels: bug
