### ISSUE TITLE
[FEATURE REQUEST]: Open files in tabs

### ISSUE THREAD

**Issue by DutchPete** [Zettlr/Zettlr#313] opened 2019-09-09 11:00 UTC
## Description
This is NOT a bug.
When one wants to work on a file, the currently opened file is closed and replaced.

## Expected behaviour
If I am working on a file, and want to open another file too because I need to jump back & forth between the 2 (or more), it would be much more efficient to jump between tabs, esp. if there are shortcuts such as <kbd>CTRL</kbd>+<kbd>PgUp</kbd> to move to the previous tab, <kbd>CTRL</kbd>+<kbd>PgDn</kbd> to move to the next tab, etc.

**Screenshots**

## Platform
 - OS: Linux Mint
 - OS Version 19
 - Zettlr Version 1.4.1
 - Screen Resolution [only necessary if the bug is relating to the GUI]

**Comment by nathanlesage** [comment] 2019-09-09 12:17
Duplicate of #243

**Closed by nathanlesage** 2019-09-09 12:17 UTC
