### ISSUE TITLE
[Bug] Newly created file does not appear in link autocomplete using first heading

### ISSUE THREAD

**Issue by zh217** [Zettlr/Zettlr#2706] opened 2021-10-22 02:50 UTC
### Description

With "If present, use the first heading level 1 instead of the filename" checked, newly created and edited files are not found when trying to link to the file using the title with autocomplete in another file.

### Reproducing

1. Ensure the option "If present, use the first heading level 1 instead of the filename" is checked
2. Create a new file
3. Give it a H1 title and save
4. Create another file
5. In the second file, type "[[" and try to link to the first file
6. Nothing is found by the autocomplete
7. If the first file is saved twice in a row, then the second file can link to the first file by autocomplete

Self-linking from the same file suffers the same problem.

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.1

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Big sur 11.6

**Comment by nathanlesage** [comment] 2021-12-14 13:20
Cannot reproduce this in current develop (> 2.0.3), but I've also improved the autocomplete code, so it might now work. Please feel free to test the next nightly next Monday and report if this bug still occurs.

**Comment by Yaco** [comment] 2022-06-06 18:19
@nathanlesage I am running Zettlr 2.2.6 in ArchLinux and I confirm this bug is still there. Any help to fix this?

**Comment by nathanlesage** [comment] 2022-06-06 19:53
Are you sure the file is actually *saved to disk* before attempting this? In-memory files won't appear yet, they have to be saved first.

**Comment by Yaco** [comment] 2022-06-06 20:21
Yes! totally sure. I am saving the files. The option "First heading level 1 if applicable" is enabled. 

I create a new file, set a title with a first level header and save the file. The title appears in the file tab name, but not in the file tree. When I try to link from other file to the the new and saved filed, it appears in the dropdown with the filename (id) but the title is not recognized. If I close Zettler and open it again, the title is recognized in the file tree and available in the linking autocomplete feature.

When I run the application from command line, I see several of errors like this one:

```
(node:105050) UnhandledPromiseRejectionWarning: Error: ENOSPC: System limit for number of file watchers reached, watch '/home/yaco/Documentos/Notas/Bibliografia/IllichIvan-2002-spa/20210727173212.md'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2247:34)
    at P (/usr/lib/zettlr/app.asar/.webpack/main/index.js:2:193042)
    at /usr/lib/zettlr/app.asar/.webpack/main/index.js:2:194306
    at e.exports._watchWithNodeFs (/usr/lib/zettlr/app.asar/.webpack/main/index.js:2:194775)
    at e.exports._handleFile (/usr/lib/zettlr/app.asar/.webpack/main/index.js:2:195450)
    at e.exports._addToNodeFs (/usr/lib/zettlr/app.asar/.webpack/main/index.js:2:198537)
(node:105050) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 132)
[17:15:35] [Application] Unhandled rejection received
Error: ENOSPC: System limit for number of file watchers reached, watch '/home/yaco/Documentos/Notas/Bibliografia/IllichIvan-2002-spa/20210727173400.md'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2247:34)
    at P (/usr/lib/zettlr/app.asar/.webpack/main/index.js:2:193042)
    at /usr/lib/zettlr/app.asar/.webpack/main/index.js:2:194306
    at e.exports._watchWithNodeFs (/usr/lib/zettlr/app.asar/.webpack/main/index.js:2:194775)
    at e.exports._handleFile (/usr/lib/zettlr/app.asar/.webpack/main/index.js:2:195450)
    at e.exports._addToNodeFs (/usr/lib/zettlr/app.asar/.webpack/main/index.js:2:198537) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/home/yaco/Documentos/Notas/Bibliografia/IllichIvan-2002-spa/20210727173400.md',
  filename: '/home/yaco/Documentos/Notas/Bibliografia/IllichIvan-2002-spa/20210727173400.md'
}
``` 

Thanks for your help!

**Comment by nathanlesage** [comment] 2022-06-06 21:28
Alright, I'll have a look again. By the way, these errors indicate that you're reaching the amount of allowed file watchers. Are you using macOS or Linux and loading a ton of files?

**Comment by Yaco** [comment] 2022-06-06 21:45
I am using Linux, but my current workspace haves only 156 files at the moment, that's a pretty low number I think. Any clue?

**Comment by nathanlesage** [comment] 2022-06-07 11:37
I know that on some systems this maximum amount of file watchers is severely limited – and they are shared across apps, so maybe you have other files that also watch files for changes. I mean, it's not really impeding the functionality of the app, only remote changes may not be detected.

**Comment by Yaco** [comment] 2022-06-07 19:44
@nathanlesage It seems that was the problem. I had other electron based app running (Atom editor) with tons of file watchers. I closed it and ran Zettlr again and didn't get the previous console errors. The autocomplete function worked perfectly! Thanks!

**Comment by nathanlesage** [comment] 2022-06-07 20:29
Ouh, okay, so that was the cause! Awesome! But this does prompt us to maybe devise a better file watching strategy. But I'd say we can keep that for a later point in time :)

**Closed by nathanlesage** 2022-06-07 20:29 UTC
Labels: bug
