### ISSUE TITLE
Image and Formula items inside a table are not rendered correctly

### ISSUE THREAD

**Issue by wwhio** [Zettlr/Zettlr#1369] opened 2020-10-20 02:10 UTC
## Description

Formula in LaTeX style is not rendered correctly when it's inside a table cell.

## Reproducing

Try this :

<pre>
| Operation | Formula       |
|-----------|----------------|
| Add       | $y=a+b$        |
| Product   | $y=a \times b$ |
</pre>

<pre>
| Name | Image |
|-----------|----------------|
| Image 1.  | ![1.png](1.png) |
| Image 2.  | ![2.png](2.png) |
</pre>

## Expected behaviour

Correctly render formula and image items inside a table.

![image](https://user-images.githubusercontent.com/4829051/96531487-58543f80-12bc-11eb-96cb-9f860657a96c.png)

## Platform
 - OS and version: Windows 10 2004
 - Zettlr Version: 1.7.5

**Comment by nathanlesage** [comment] 2020-10-20 07:57
Duplicate of #632

**Closed by nathanlesage** 2020-10-20 07:57 UTC
