### ISSUE TITLE
[Enhancement] Auto numbering and cross reference

### ISSUE THREAD

**Issue by KYang-N** [Zettlr/Zettlr#3232] opened 2022-02-18 03:57 UTC
### Description

Zettlr doesn't support auto numbering and cross reference of equations or math blocks. These two functionalities are of vital importance for academic writing in science and engineering. These two functions have been realized in the popular markdown editor Typora, and that might be one of the most significant weaknesses compared with Typora.

### Auto numbering 
This can be realized in two ways. The first way is to support `\begin{equation}`, `\begin{align}`, `\begin{gather}` environments inside the double dollar sign`$$`, e.g., 
```
$$
\begin{equation}
   a+b=c
\end{equation}
$$
```
Actually this syntax is already supported in Zettlr, but there are three problems:
1. The position of the number is rendered incorrectly.
![image](https://user-images.githubusercontent.com/37972210/154609855-24d09475-b18b-44bb-b40a-2e55fcb37137.png)
2. The file can't be directly exported in PDF(LaTeX) format when using such syntax. I think this is because pandoc replaces double dollar signs by `\begin{equation} ... \end{equation}` environment and the repetition of the `\begin{equation}` environment leads to this error
![image](https://user-images.githubusercontent.com/37972210/154610463-28f9d150-1986-4732-b109-0c1849412bf8.png)
I guess changing the way how pandoc deals with double dollar signs might fix this problem. By the way, Typora supports this syntax when generating PDF using Pandoc and LaTeX.
3. When there are too many equations, the numbers get wrong. I think this is because Zettlr only renders the equations you are looking at for efficiency. It "forgets" the preceding math blocks and starts renumbering when you scroll down the file.

The second way is to add auto numbering of math blocks without using `\begin{equation}`, `\begin{align}` etc. Typora has this functionality.

### Cross reference
The purpose of numbering equations is to refer to them. LaTeX has commands like `\label{}` `\ref{}` `\eqref{}` to serve this purpose. These commands are not supported in Zettlr (they are supported in Typora).
![image](https://user-images.githubusercontent.com/37972210/154613509-4e8580e4-7f81-4f10-8567-54dc434e6b2e.png)
![image](https://user-images.githubusercontent.com/37972210/154613529-6ee308a1-6378-40f3-b6c2-dd97e8d6b6aa.png)
![image](https://user-images.githubusercontent.com/37972210/154613553-9f6933b8-8934-4e05-a676-00593fea2199.png)
However, when exporting in PDF (LaTeX) format, these commands are rendered correctly. 

All in all, the key issue is that Zettlr uses two distinct mechanisms for editing and exporting (in PDF (LaTeX) format) mathematics, and thus what you see is not what you get...

 

### Caveats

Maybe that enhancement can slow down the rendering of math formulas.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Operating System Version

Window 10

### Additional Information

That's how Typora processes mathematics: [Math and Academic Functions](https://support.typora.io/Math/). It is really inspiring.

**Comment by nathanlesage** [comment] 2022-02-18 12:11
CC @tobiasdiez would you mind taking this over?

**Comment by nathanlesage** [comment] 2022-02-18 20:32
You got some good points.

Closing as duplicate of #248.

**Closed by nathanlesage** 2022-02-18 20:32 UTC
Labels: enhancement
