### ISSUE TITLE
Cursor jumps to the start of the file

### ISSUE THREAD

**Issue by gjldp** [Zettlr/Zettlr#4729] opened 2023-10-10 08:20 UTC
### Description

On the 3.0.2 version, I have the following issue: when editing my file, the text cursor jumps from time to time to the start of the file.

I couldn't measure the time, that varies. I couldn't identifiy a cause either. It just jumps. It's a little like when I reloaded the file on Bversion 2.XX (when I had other problems), the cursor was back to char 1 line 1. but it in this case, it doesn't seem to be a reload problem.

### Reproducing

I couldn't identify the causes of this behaviour.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.2

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

MS Windows 11.

**Comment by BabakFarshchian** [comment] 2023-10-11 04:59
I can confirm this. In my case (3.02 on Win11) this happens on each autosave, which makes it impossible to work actually.

**Comment by nathanlesage** [comment] 2023-10-11 06:21
Could you both please uncheck "automatically reload files" in the advanced settings and tell me what happens?

**Comment by BabakFarshchian** [comment] 2023-10-11 06:58
Yes it seems to be the auto save function. It is not only cursor moving, also the last enter text is undone at the same time (older content being loaded from file on disk I guess). There is an option for "Always load remote changes to the current file" in the General menu. I guess this is what you mean? I could not find anything similar in the advanced section of the settings.

I disabled this. Now quite often when editing I get a dialog box asking me what to do. I upload a screenshot here. I am not sure what the effect of ticking the option at the bottom of the dialog box is. (My watchdog polling is active and at 2000 ms, if that is relevant?)

![image](https://github.com/Zettlr/Zettlr/assets/1062643/59675240-1e7f-4bc0-a2b8-c672c373553d)

**Comment by gjldp** [comment] 2023-10-11 20:03
Ho Hendrik,

Sorry but I won't be able to do this tonight. I have a big time and
reverted to 3.0.1. But I will soon comply.

Good night.

And btw: zettlr rocks. It's an amazing piece of software!

Le mer. 11 oct. 2023 à 08:21, Hendrik Erz ***@***.***> a
écrit :

**Comment by BabakFarshchian** [comment] 2023-10-12 04:44
FYI. I disabled load remote AND autosave. Now I occasionally get a message when saving, telling me that the file on disk is changed.

I am not sure when I get the occasional message. I however discovered that if I have an open note that is modified in the editor and I quit Zettlr, I am not warned that changes will be lost. It seems Zettlr keeps the unsaved changed somewhere, which is really good if you don't want to have autosave on (it is similar to Notepad++). However, when I restart Zettlr and try to save the changes I get the message telling me the file is changed on disk. I am not sure if this is the only case when it happens but it is one of them.

**Comment by BabakFarshchian** [comment] 2023-10-12 05:03
BTW I think the title of this issue should be something like "Load remote changes overwrites local changes in autosave more".

**Comment by StuporMundi1337** [comment] 2023-10-12 08:06
Experiencing the same issues. These were also symptoms of some saving problems in the last version. You could prevent the problems with disabling autosave as well as unchecking "Always load remote changes to the current file". Then you would sometimes get the pop-up window shown above. Just hit enter and everything is fine.

The effect of ticking the box is simple: It will retick the "Always load remote changes to the current file" box in the menu (at least that's what I've experienced).

**Comment by nathanlesage** [comment] 2023-10-18 10:03
@kyaso putting you in the loop.

This issue is almost certainly either related to, or has the same root cause, as #4732.

**Comment by kyaso** [comment] 2023-10-20 19:05
@BabakFarshchian @StuporMundi1337 Do you mind testing with Watchdog polling of, say, 3000ms?

![image](https://github.com/Zettlr/Zettlr/assets/18646029/1130c302-c378-43fd-9df0-bfa4e6f5f8d8)

It looks like that Zettlr's file watcher is picking up undesirable file change events (wherever they may come from), so maybe this setting might reduce the likelihood of that happening. On my affected machine it looks like 3000ms is the optimal setting to not have the filed changed pop-up anymore (I will keep testing though, to see whether the option really helps).

**Comment by BabakFarshchian** [comment] 2023-10-27 19:47
> **Update**: I still get the pop-up sometimes, even with a 3000ms watchdog :(

Me too.

**Comment by BabakFarshchian** [comment] 2023-11-02 07:30
I wonder if a quick and dirty fix for this issue could be to have the option of always overwriting the file on disk with current editor content. Currently we have only the option to always do the opposite (load changes from disk into the editor, as it is shown above in the dialog box "File changed on disk" ).  In my scenario (working on local files which I am the only one changing them) this option would allow me to have autosave on without the fear of loosing editor content.

**Comment by nathanlesage** [comment] 2023-11-02 10:36
>  In my scenario (working on local files which I am the only one changing them) this option would allow me to have autosave on without the fear of loosing editor content.

I have a similar situation, but this would make it impossible to open a file in another editor and change something. Also, given that it did work well previously, I don't think this would be a proper fix :/

**Closed** 2023-11-09 09:00 UTC
Labels: bug

**Comment by nathanlesage** [comment] 2023-11-09 10:51
Hello everyone – the fixing PR has now been merged. All of you who experience this issue, I invite you to try out the most recent nightly release (see https://nightly.zettlr.com/) and use it for a day or so to see if it fixes your issue.

If it does, I will be releasing the official v3.0.3 beginning of next week. Please comment if this fixes your issues.

**Comment by BabakFarshchian** [comment] 2023-11-09 21:34
I have done some tests and it seems to be working normally, i.e. no pop-ups. My settings are not load remotely, and save automatically after some delay.

**Comment by nathanlesage** [comment] 2023-11-10 07:56
Thank you very much for doublechecking! I will then proceed to release v3.0.3 probably beginning of next week, but of course feel free to use the nightly until then so that you can work productively.
