### ISSUE TITLE
"Add to Dictionary" not available?

### ISSUE THREAD

**Issue by curbia** [Zettlr/Zettlr#4750] opened 2023-10-25 13:44 UTC
### Description

I've recently started using Zettlr again and enabled spell-checking. I want to add false positive words to the dictionary to prevent them from being underlined in red, however there is no such option available in the right-click menu. I remember this being a feature in v1.8.9, perhaps it was broken in an update?

### Reproducing

Enable LanguageTool. Right-click a word underlined in red.

![image](https://github.com/Zettlr/Zettlr/assets/87792521/a8ff0740-de71-4246-bd14-ddd41e9154c9)

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.2

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 23.04

**Comment by nathanlesage** [comment] 2023-10-26 10:47
Duplicate of #4733

**Closed by nathanlesage** 2023-10-26 10:47 UTC
Labels: bug
