### ISSUE TITLE
Menu to select a note to link disappears after hit space

### ISSUE THREAD

**Issue by Raphapere** [Zettlr/Zettlr#953] opened 2020-06-25 13:57 UTC
## Description
The drop-down menu to find and select a note to link using "[[" disappears after hit space.
If I have too many notes with similar titles, it's difficult to find using only one word.

## Reproducing
1. Type "[[" and a word to search the note I want to link.
2. Type space to search with a second word.
3. The Drop-down menu to select a note disappears.

## Expected behavior
When hit space on keyboard after type the first word, Zettlr should keep showing the menu to select and let the user search with a second word.

**Screenshots**
![Bug Zettlr](https://user-images.githubusercontent.com/20495934/85731936-77660a80-b6ea-11ea-86c3-ae303ef85250.gif)

## Platform
 - OS and version: Linux Mint 19.3
 - Zettlr Version: 1.7.0-beta13

**Comment by nathanlesage** [comment] 2020-06-25 19:40
Duplicate of #694

**Closed by nathanlesage** 2020-06-25 19:40 UTC
