### ISSUE TITLE
[ENHANCEMENT] Open the notes in the same tab by default, press 'ctrl/cmd' to open in a new tab

### ISSUE THREAD

**Issue by b4nn** [Zettlr/Zettlr#835] opened 2020-05-23 17:51 UTC
## Description
When browsing the notes one can quickly end up with dozen of notes opened which gets confusing and cluttered. Instead notes should open in the same view/tab by default, unless user decides otherwise. This would most likely be expected functionality for most of the users as it matches pattern established in popular programs like internet browsers or other note-taking apps.

## Proposed Changes
Open the note in the same window unless user specifies otherwise by right-clicking on the note while pressing 'ctrl/cmd'.

**Comment by nathanlesage** [comment] 2020-05-23 23:05
This idea conflicts with one that has been issued someplace else to keep transient tabs (or, pending, if you so will) — that is: A tab is considered "pending" for as long as it is not modified or manually "confirmed". If it's pending, it can be replaced with another tab easily. This is basically the behaviour of VSCode and other editors, and has received some support (unfortunately I don't exactly know the issue…)

**Comment by b4nn** [comment] 2020-05-25 09:43
I don't know VSCode so I can't speak about how usable transient tabs idea really is, maybe it's far superior than what I'm describing here so I will leave it to others to judge.

The only thing I will add is that as a rule of thumb unless something is vastly superior I would steer away from it if a popular suitable alternative exists. Popular design patterns are seamlessly adopted by the users: they already know what to do and what to expect and it comes naturally to them. The amount of users that use internet browsers is vastly larger than those that use code editors. Plus, the users of code editors are also internet browser users so a behavior based on a browser will be just as natural for them as for everybody else.

**Comment by nathanlesage** [comment] 2020-05-25 10:06
> Popular design patterns are seamlessly adopted by the users: they already know what to do and what to expect and it comes naturally to them.

Absolutely! I'm heavily biased by code editors, and so I don't know which is the better version; because the idea of VSCode stuff is actually not that bad, so that's why I hope others can chime in here.

**Comment by nathanlesage** [comment] 2020-05-25 10:12
Just started a poll over on Twitter; let's see what the users decide: https://twitter.com/zettlr/status/1264861826543738880

**Comment by ME7DYCgw8M** [comment] 2020-05-25 11:44
I would guess more people are accustomed to browser tab behavior (Chrome, Firefox) than VS code behavior.

**Comment by halcyonquest** [comment] 2020-05-26 00:37
I would vote for browser tabs as well. That way the only files that are open are the ones I want to have open. In the 1.7 betas I find myself constantly closing tabs to keep it clean.

**Comment by nathanlesage** [comment] 2020-06-04 07:48
Closing in favor of #879

**Closed by nathanlesage** 2020-06-04 07:48 UTC
Labels: Enhancement, help wanted, pinned, question, waiting for feedback
