### ISSUE TITLE
Mac OS 10.13.6

### ISSUE THREAD

**Issue by bremferd** [Zettlr/Zettlr#4139] opened 2023-02-10 08:07 UTC
### Description

Hi there, I've tried uninstalling and reinstalling the app a few times, but I am unable to open it.  I get a crash report each time that I try to open: "Zettlr Quit Unexpectedly".

### Reproducing

- Install MacOS version of Zettlr from website, compatible with my Macbook 2011 running OS 10.13.6
- Mount by double clicking.
- Drag into applications folder.
- Open app.

### Zettlr Version

Stable (most recent version)

### Specify version

Intel (X86_64)

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Mac OS 10.13.6

**Comment by nathanlesage** [comment] 2023-02-10 13:41
Duplicate of #2732

**Closed by nathanlesage** 2023-02-10 13:41 UTC
Labels: bug

**Comment by exanrauzer** [comment] 2023-02-10 14:05
@nathanlesage Please explain me, why it is better to close the issues which are repeatable instead of tagging them as known issue? I thought that users search issues only in open ones and if they do not find any that matches, they start an issue. If issues are closed as completed if they are not solved, it do not stop the same issues to come over again. Like the ARM case recently.

**Comment by nathanlesage** [comment] 2023-02-10 18:31
I see what you mean, but it stresses me out having too many open issues, and my mental sanity is just more important than catering to people who refuse to search the closed issues as well. Also, there's nothing gained by tagging an issue with "known" and then leaving it open.
