### ISSUE TITLE
[ENHANCEMENT]: Select project output formats

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1172] opened 2020-08-07 07:04 UTC
## Description
For projects that I'm working on, it would be nice to be able to select 'Export Project' and have it compile the several formats I need, rather than having to amend project settings three times to do so.

## Proposed Changes
Replace the 'Export Format' dropdown on the _Project Settings_ screen with checkmarks for supported formats, e.g: 

- [ ] PDF
- [ ] HTML
- [ ] DOCX
- [ ] ODT

Amend the logic for project exports so that it exports to each format that is checked.

**Comment by nathanlesage** [comment] 2020-08-09 10:37
Sounds simple enough to implement!

**Comment by zhangfanfansz** [comment] 2021-03-24 14:19
Hi, I am Fan Zhang from the University of Adelaide, my team and I are very interested in this issue and happy to contribute to this issue. Are there any suggestions that you can give us to tackle this issue? We may do our first pull in a few weeks.

**Comment by nathanlesage** [comment] 2021-03-24 18:08
Yes, this should be possible. We'd need some way to let the user choose which output formats they need. Quite a few files would be touched by this, but the place to start should be the directory PopOver (which you can open by right-clicking a directory in the develop branch), and add that there under "Project".

**Comment by zhangfanfansz** [comment] 2021-03-30 14:31
![image](https://user-images.githubusercontent.com/58411513/113005513-15c45680-91bc-11eb-842c-c46026f32f37.png)
Hi, I am wondering if there is any change of the latest version of the source code. This is what I got after running yarn start after I clone this project today, and the version of days ago works fine.

**Comment by zhangfanfansz** [comment] 2021-03-30 14:33
And in the previous version, I tried to export a tutorial file to see how it works, but it shows me that can't find the path of the file, I am so confused about this, pls help.

**Comment by nathanlesage** [comment] 2021-03-30 15:05
A few commits ago I changed the way the Pandoc retrieval worked. There is a bash script in `./scripts/get-pandoc.sh` which is being used by the forge workflow to download the appropriate Pandoc version for the target platform and architecture. If you just run `yarn start` this would be whatever is in `process.platform` and `process.arch` (on the CI, where we actually bundle the app, these parameters would be taken from the command line arguments instead). The script then simply attempts to download the corresponding Pandoc version (if it is not yet in the `./resources`-directory) so that you can both use Pandoc during development AND that Pandoc can be bundled when we package the app.

That being said, this added an additional constraint to the build process which I haven't yet added to the documentation: It runs a Shell-Script as well.

That being said, there are two ways for remedying this situation:

1. The complicated way: Make sure to use Bash, since neither the Windows command line nor PowerShell understand Bash script.
2. The easy way: Simply download Pandoc manually and put the binary into your resources directory, renaming it appropriately (e.g. `pandoc.exe` --> `pandoc-win32-x64.exe`, if you're running on Linux ARM, it would be `pandoc-linux-arm64` I believe).

Since the check of whether or not the corresponding Pandoc binary is already present or not is being done in Node code and the Shell script is not executed if Pandoc is found, it should run platform-independently.

Since it appears you are running Windows, it should be `pandoc-win32-x64.exe`, as is being checked in this line:

https://github.com/Zettlr/Zettlr/blob/2e327679e5390f4dfa7f5c71f7f22e27236ac064/forge.config.js#L75

***

With regard to your second question: Would you mind actually sending the error message, and any potential log output here as a comment? (The logs from since you started Zettlr can be found in the develop menu; older logs from previous runs are saved to your user data directory, which is located at `C:\Users\<your username>\AppData\Roaming\Zettlr`).

**Comment by zhangfanfansz** [comment] 2021-03-31 06:09
Thanks for the information, it works, and the output functionality works also fine

**Comment by nathanlesage** [comment] 2021-03-31 07:10
Record what?

**Comment by zhangfanfansz** [comment] 2021-03-31 08:29
Oh sorry, I thought I should record how to fix the error above, NVM now. Thanks again

**Comment by c321474** [comment] 2021-05-09 09:30
Hi, our group has created multiple choice selection checkbox, just like that ![image](https://user-images.githubusercontent.com/69238809/117566580-96993b00-b0f6-11eb-95ae-06b5be9d08ef.png)

Unfortunately,  it only can output the last selected format and we have try different ways but it still not work, could you please give us some hits what is the next step and do we need to focus on _PopoverExport.vue_

Thanks

**Comment by nathanlesage** [comment] 2021-05-09 14:06
@c321474 The exporter in there is not the right place. The exporter Popover is only meant for single page exports which also implies a single target format. This issue was specifically created to allow more than a single _project_ output format, so the right way to start would be my stub-implementation in the Directory Properties popover, which includes a switch to enable project functionalities, but nothing more yet, since I haven't had time to get back to it just now.

**Comment by nathanlesage** [comment] 2021-05-09 14:07
Additionally, you may want to take a look at the various project `commands` in the main module.

**Comment by zhangfanfansz** [comment] 2021-05-26 10:06
Sorry for the delay, our group will not work on this issue anymore.

**Comment by nathanlesage** [comment] 2021-06-12 20:05
Duplicate of #1005 

Sorry, just realised that, and Ploum was first :D However, I already implemented most of it GUI-wise, just need to drop that stuff into the exporter, so it shouldn't take too long …

**Closed by nathanlesage** 2021-06-12 20:05 UTC
Labels: UX, enhancement, pinned, priority:low, v1.7.x
