### ISSUE TITLE
Drag and drop or "copy" image file should copy to the default images folder if configured

### ISSUE THREAD

**Issue by DennisL68** [Zettlr/Zettlr#4119] opened 2023-02-01 10:20 UTC
### Description

When pasting an image file from explorer to Zettler, I expect it to be stored with the markdown document if a relative path is configured for images.

This will be more inline with how other document editors such as Word works.

### Proposed Changes

If a relative image path is configured. Drag and drop or pasting a file to Zettlr should copy the file to the configured image folder in the same way as pasting from the clipboard works.

This will be a more consistent behavior in how the UX is working and in-line with the workings of rich text editors.

### Caveats

None that I can see.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [X] macOS
- [X] Linux

### Operating System Version

Windows 10 Enterprise LTSC

**Comment by nathanlesage** [comment] 2023-02-03 20:09
Duplicate of #1281

**Closed by nathanlesage** 2023-02-03 20:09 UTC
Labels: enhancement
