### ISSUE TITLE
Syntax colors not working when using pandoc style code blocks 

### ISSUE THREAD

**Issue by cjbarroso** [Zettlr/Zettlr#4383] opened 2023-05-29 02:59 UTC
### Description

In the main editor, the syntax colors work as expected when using the traditional code header, for instance:
`  (three backticks) python  `

But if I use the pandoc style syntax using class selectors, like:

` (three backticks) {.python} `

then the syntax is not colorized. I've experimented with adding and removing spaces, adding #identifiers, adding more classes and reordering to no avail.

### Reproducing

Open a new markdown file, enter a code block for any language using the pandoc-style code block.
The syntax is not colorized.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta.4

### Installation Method

Other (please specify below)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

arch linux

### Additional Information

Im using the AppImage

**Comment by cjbarroso** [comment] 2023-05-29 03:15
also tested the nightly build and the behaviour is different but still not as expected.

**Comment by nathanlesage** [comment] 2023-06-26 07:32
Just found this issue: I wouldn't classify this as a bug, since previous Zettlr versions also didn't do this and it's not unwanted behavior. The linked issue currently attempts to improve syntax highlighting.

Closing as not a bug.

**Closed by nathanlesage** 2023-06-26 07:32 UTC
Labels: bug

**Comment by cjbarroso** [comment] 2023-07-02 18:02
Let me add a comment, maybe supporting what you wrote. After installing different versions and deleting the configuration I now have a state where I DO get the syntax hightlighting as expected. I *think* it is because I used a latter version to create the config directory but I'm using an earlier version of the app, or the other way around. In the end I now have all that I wanted, however I can't fiddle a lot with my config, at least until the related tickets are completed. Computers are weird animals for sure.
