### ISSUE TITLE
Menubar Dropdown Persists

### ISSUE THREAD

**Issue by shanvrolijk** [Zettlr/Zettlr#1458] opened 2020-11-27 12:46 UTC
## Description

The menubar dropdown doesn't disappear even though the preference menu has already appear, making it impossible to click the "save" option button.

## Reproducing

1. click menubar and choose some settings from the menubar dropdown.

## Expected behaviour

The dropdown should disappear once we choose a setting button. 

![image](https://user-images.githubusercontent.com/30141705/100450915-14d5c800-30e9-11eb-9efb-2ad9271966bc.png)

## Platform
 - OS and version: Windows 10 64x
 - Zettlr Version: 1.8.0

## Additional information

Thank you for zettlr 1.8.0. It's amazing 💯

**Comment by derwok** [comment] 2020-11-27 12:48
This is a duplicate of #1450 
Suggestion to close this one.

**Comment by nathanlesage** [comment] 2020-11-27 15:36
@derwok Yes, you're right. I already have the solution in mind, will come sometime next week or so!

**Closed by nathanlesage** 2020-11-27 15:36 UTC
