### ISSUE TITLE
[BUG] Note suggestions are gone when typing [[

### ISSUE THREAD

**Issue by Bubblbu** [Zettlr/Zettlr#737] opened 2020-05-07 22:55 UTC
## Description

With 1.7-beta the assisted selection and suggestions for notes seems to be gone.

## Reproducing

Type [[ + any filename or title of an existing note

## Expected behaviour

List is shown with suggestions

**Screenshots**

## Platform
 - OS and version: Lubuntu 16.04
 - Zettlr Version: 1.7-beta
 - Screen Resolution: 1600x900

**Comment by nathanlesage** [comment] 2020-05-08 08:56
Unfortunately I cannot reproduce this …

![image](https://user-images.githubusercontent.com/17251683/81389721-8ed93c00-911a-11ea-876f-80bae4a1d35d.png)

Any additional output somewhere? Error messages? What does the console & the logs say …?

**Comment by danieltomasz** [comment] 2020-05-08 10:47
On Ubuntu 20.04 note suggestion works in 1.7.1

**Comment by Zverik** [comment] 2020-05-08 12:47
On macOS 10.14.5 suggestions work. Maybe there's some internal file name database that wasn't updated for some reason?

**Comment by Bubblbu** [comment] 2020-05-08 17:13
It's working now! Changed nothing, did nothing differently. Sometimes I guess it's the magic of a new day (new boot) :shrug: 

Closing this!

**Comment by nathanlesage** [comment] 2020-05-08 17:25
> It's working now! Changed nothing, did nothing differently. Sometimes I guess it's the magic of a new day (new boot) 🤷

… welcome to the magical world of Electron and JavaScript 🦄 🌈 … Good to know that it works now! :)

**Comment by Zverik** [comment] 2020-05-11 16:53
Okay, now the suggestions don't work for me in beta2 :) It's not logged, so I'm not sure why the suggestions don't appear. This is application-wide: opening and closing tabs does nothing. Restarting the app helped fix this.

Also, it seems like a few seconds after starting the app, ID resolving does not work, and links are inserted to file names, not to Zk ids.

**Comment by nathanlesage** [comment] 2020-05-11 19:10
> Okay, now the suggestions don't work for me in beta2 :)

My mood after having worked on this piece of sh\*\* for two months and now random things are breaking: (╯°□°）╯︵ ┻━┻ (Just kidding, simply wanted to make use of this auto-complete Emoji I've used way too seldomly in the past months)

> Also, it seems like a few seconds after starting the app, ID resolving does not work, and links are inserted to file names, not to Zk ids.

This might help solve this riddle. I think that I actually seem to have messed up the IPC, as I tend to send more events than necessary out of fear that something might not get through … which is also the explanation for why the theme switching at application boot for a short amount of time breaks the theme with larger installations: As the main process is shoveling multiple megabytes of data through the pipes, the renderer freezes :D

**Comment by nathanlesage** [comment] 2020-05-16 08:55
For me it's working in the number 5, what about you guys?

**Comment by Bubblbu** [comment] 2020-05-17 00:35
I just installed beta.5 and will keep testing. The problem for me was that I couldn't consistently reproduce this bug (at least it seemed to me quite random at times). So I'll keep an eye out in the next few days and report back!

For now, beta.5 seems to be working for me too.

**Comment by vtcarlino** [comment] 2020-05-17 14:49
Hi, I'm using 1.7 beta 5 and links are inserted to file names instead of IDs.

**Comment by nathanlesage** [comment] 2020-05-31 15:08
Whoops, forgot to close this thingy!

**Closed by nathanlesage** 2020-05-31 15:08 UTC
Labels: bug [non-critical], confirmed
