### ISSUE TITLE
Adding a tab to second pane creates additional, flickering scroll bar

### ISSUE THREAD

**Issue by noah-arroyo** [Zettlr/Zettlr#4339] opened 2023-05-15 17:43 UTC
### Description

**Expected behavior:** Any pane in a window has a single scroll bar to the far right.

**Buggy behavior:** When a second pane is already open, adding another tab to that pane creates a second scroll bar in the first pane. The new scroll bar disappears and reappears over and over.

### Reproducing

I'm not yet able to reproduce this bug with 100% reliability, but it occurs often. 

When it does happen, these are the steps that precede it:

1. Open at least three notes, so that your window shows the notes as adjacent tabs in a single pane.
2. Open a second pane by drag/dropping one of the notes/tabs into the zone that will have that effect, at the bottom of the current note.
3. Attempt to drag an additional tab toward the second pane, as you would if you intended to add that tab to that pane.
4. If, in the process of navigating the mouse, the cursor traverses a pane-creation zone (in the first pane) _other than_ the zone you intend, the unintended zone will highlight and reveal itself.
5. After the cursor reaches the intended zone, and you "drop" the tab there by releasing the mouse button, the unintended zone will remain highlighted. In some cases when this happens, the zone will flicker in and out of visibility, and while it's visible a second scroll bar will appear alongside the first pane's pre-existing scroll bar.
6. Sometimes it's possible to make the unintended zone and second scroll bar disappear by dragging another tab across that zone (recreating step 3).

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.0-beta.4

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by sarahtelford** [comment] 2023-06-05 23:32
I have been able to replicate this issue using macOS. Will generate a macOS bug ticket for this issue.

**Comment by nathanlesage** [comment] 2023-06-18 16:55
The main issue here is that I have to listen to a wide variety of mouse events to show and hide those zones, and sometimes there's an unfortunate series of events that leaves one pane visible even though it should not be. Since this can be mitigated easily by kind of "erasing" this with the dragged tab, this issue has low priority, but if someone has the energy to dig in, feel welcome.

**Comment by nathanlesage** [comment] 2023-07-04 11:01
Duplicate of #4399

**Closed by nathanlesage** 2023-07-04 11:01 UTC
Labels: bug
