### ISSUE TITLE
export to PDF error: "Document contains trailing content not separated by a ... or --- line"

### ISSUE THREAD

**Issue by leowill01** [Zettlr/Zettlr#3740] opened 2022-08-30 18:02 UTC
### Description

im trying to export to PDF (non-latex option), but can't because i get the following error: `Document contains trailing content not separated by a ... or --- line`

### Reproducing

i reproduced this with a new .md document with any text at all, e.g. a .md file that contains only:

```
This is a sentence.
```

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

Homebrew

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

macOS Monterey v12.5.1

**Comment by nathanlesage** [comment] 2022-08-31 10:57
This sounds very much like a YAML frontmatter that is not terminated. Could it be that you're accidentally pulling in a YAML file to Pandoc…?

Could you please share the contents of your HTML export assets file?

**Comment by nathanlesage** [comment] 2022-11-04 11:20
Closing as unattended and unable to reproduce.

**Closed by nathanlesage** 2022-11-04 11:20 UTC
Labels: bug
