### ISSUE TITLE
Zettlr won't open workspaces

### ISSUE THREAD

**Issue by cf2747** [Zettlr/Zettlr#5528] opened 2024-12-23 21:05 UTC
### Description

Today I updated Zettlr to 3.4.0 and my workspaces cleared out of the directory bar. When I try to reload them, they will not. I can only load a workspace folder from my computer if it has no other subfolders within it; any folder containing subfolders won't load. 

I keep my zettlr directory in a GoogleDrive-linked folder, and have often found loading workspaces a bit clunky in the past because I couldn't just load my Zettlr folder containing all of my subfolders. However, before the update today, I could load the next level subfolders, e.g. Zettlr>Notes or Zettlr>Archived folder. Now I can only add a folder without any other folders in it.

I have since deleted 3.4.0 and reinstalled 3.3.1 and am able to load my workspaces.

Thanks for your help.

### Reproducing

I closed Zettlr and reopened it and still couldn't load workspaces. I deleted and resinstalled version 3.4.0 and still couldn't load workspaces.

### Zettlr version

3.4.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment] 2024-12-23 21:21
Duplicate of #5526

**Closed by nathanlesage** 2024-12-23 21:21 UTC
Labels: bug
