### ISSUE TITLE
[Bug] Problem with some characters (ü,ł,ś,ą etc.) in regular expressions

### ISSUE THREAD

**Issue by LegonEtp** [Zettlr/Zettlr#3052] opened 2022-01-17 00:07 UTC
### Description

In the search field, Polish characters (but also German umlauts, etc.) are treated **as spaces** by the regular expression when it searches for a string `space+letter+space`. 

### Reproducing

Search for `/\b\w\b/` find not only `[space][letter][space]`, but also `[some unicode letter][letter][space]`, for ex.:
not only **\_i\_** but also **że_**. In Regex101.com (javscript flavor) this works as expected, ie. find **\_i\_**, and not find **że_**.
In string *Zapisuję w notesie, że jest błąd* Zettler search: *Zapisuję **w** notesie, **ż**e jest błą**d***, while regex101 searches correctly: *Zapisuję **w** notesie, że jest błąd*.

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by Wietor-bb** [comment] 2022-06-06 17:21
Nathan, 
this is not the letter "z" (ASCII 0122), but the Polish letter "ż" (unicode: Latin Small Letter Z with Dot Above, U+017C) - a small difference, but important in Poland :). This is not only a Polish problem. Replace "ż" by Czech "ů" or "ž" and you will see the same effect (example: sentence "My God" in Czech).
![obraz](https://user-images.githubusercontent.com/70803464/172211998-3fda862b-8733-4cbf-b45c-4f4ef3c95fdb.png)

I know that in this case \s replaces \b, but this error bothers me - characters outside the basic ASCII table (Latin1) are recognized as spaces...

**Comment by nathanlesage** [comment] 2022-06-06 19:59
Of course I meant the z with the diacritics, I just hadn't the correct character available and was too lazy to copy and paste.

This is apparently in the RegEx specification of JavaScript itself and not considered a bug. See this SO answer: https://stackoverflow.com/a/5311760

Closing as not a bug.

**Closed by nathanlesage** 2022-06-06 19:59 UTC
Labels: bug
