### ISSUE TITLE
Switching between documents is slow in 1.8.0 AppImage x64

### ISSUE THREAD

**Issue by tordeu** [Zettlr/Zettlr#1479] opened 2020-11-30 13:42 UTC
## Description

After clicking on a file in the file manager it takes ~0.5-1s before anything happens. The lag is noticeably higher than in 1.7.5.   

## Proposed Changes

I propose to reduce the lag to at least 1.7.5 levels or more, if possible.

## Caveats

No

## Additional Information

I am using the x64 AppImage of Zettlr 1.8.0 on current OpenSUSE Tumbleweed.

**Comment by cloudhan** [comment] 2020-12-01 09:12
On Windows, it is also noticeable slower than previous version. Maybe 200ms to 500ms, I can not measure at the moment.

**Comment by yhoiseth** [comment] 2020-12-01 14:43
Have reproduced this on macOS 10.15.7 with Zettlr 1.8.0. I can’t remember it being an issue in 1.7.5.

With a couple of files with 3,221 and 443 words, respectively, clicking control + tab is noticeably slow. 

Repeatedly switching tabs can easily get the CPU usage up to more than 80 percent:

<img width="912" alt="Screen Shot 2020-12-01 at 15 38 48" src="https://user-images.githubusercontent.com/8469540/100754770-bdd33a00-33eb-11eb-8d1a-08ccef2b4e8b.png">

**Comment by nathanlesage** [comment] 2020-12-06 13:57
Does this still happen in 1.8.1? I radically cut computation time, so it should be faster now.

**Comment by yhoiseth** [comment] 2020-12-06 16:43
> Does this still happen in 1.8.1? I radically cut computation time, so it should be faster now.

Thanks! It’s a bit better with 1.81 :) 

I still get CPU usage at 70-80 %, and switching files is noticeably slow, but not as bad as with 1.8.0.

**Comment by nathanlesage** [comment] 2020-12-06 21:12
Alright, it's still not as good as it could be, but I'm still searching for the cause. Right now, I don't have a clue, so any help is appreciated here!

**Comment by nathanlesage** [comment] 2020-12-14 11:49
So, I've further improved the speed of document switching, and I'll keep monitoring this. But now it's almost back to "normal" so to speak, so I'm going to close the issue ;)

**Closed by nathanlesage** 2020-12-14 11:49 UTC

**Comment by yhoiseth** [comment] 2020-12-14 12:24
@nathanlesage Great! Thanks a lot :)
