### ISSUE TITLE
Alternative Tex template not used by PDF export in Project

### ISSUE THREAD

**Issue by webopold** [Zettlr/Zettlr#1126] opened 2020-07-28 12:40 UTC
## Description
Zettlr doesn't use the given template in the Project Settings - is just  taking the default template.

## Reproducing
Make a new directory ~/letters
Make a new directory ~/template
place mytemplate.tex to ~/template
start zettlr and make ~/letters a project; set the template to mytemplate.tex
(i have a letter template with address etc.) 
PDF-Export 

## Expected behaviour
The above works well on the commandline with pandoc ...  --template="mytemplate.tex"  . So should zettlr do.
Furthermore there might be some additional settings for using templates without the full project behaviour

## Platform
Debian testing
 - Zettlr 1.7.2

**Comment by jsstanley** [comment] 2020-07-28 21:10
There are currently some issues with exporting to pdf files in Zettlr 1.7.2 (see #1113).

I would recommend downgrading to Zettlr 1.7.1 to see if this issue still persists.

**Comment by nathanlesage** [comment] 2020-07-28 21:40
Yes, I think it's related

I fiddled with the exporter and forgot to check the project exporting. I'm feeling a little bit sick this week, but I know where the bug is and I'll be fixing this soon!

**Comment by jsstanley** [comment] 2020-07-28 22:01
Get well soon @nathanlesage!

**Comment by nathanlesage** [comment] 2020-07-29 14:21
Soo, someone found a fix for the other problem, but concerning this thingy, I'll need to verify this before closing this!

**Comment by nathanlesage** [comment] 2020-07-31 10:28
Has been fixed indeed! 🥳

**Comment by webopold** [comment] 2020-08-03 08:58
1.7.4 Bug still exists --> Tex Template specified for the Project is not used, instead of it Zettr uses the one defined in global settings. If i set the global Template to my specific, everything works as expected, but not so usefull

**Comment by nathanlesage** [comment] 2020-08-09 10:06
I cannot reproduce this locally, as for me, when I set a specific LaTeX template on the project settings, it is indeed using that one, and not the global one. Do you use the absolute path to the template? Otherwise it won't work because Zettlr will fallback to the global template if the file cannot be found, and no path-normalization is being done.

**Comment by webopold** [comment] 2020-08-10 10:11
I set the template via the project settings page - the chosen path ist absolute by default and was not altered by any means. 
besides that i would like to have relative paths in such settings.

Additionally i found that zettlr does not respect the project setting itself. If i delete the project from the directory, it shows up again after the next start. I have to delete .ztr-directory manually. 

This is the content of the file:

{"sorting":"name-up","project":{"title":"Briefe","format":"pdf","cslStyle":"","pdf":{"author":"Generated by Zettlr","keywords":"","papertype":"a4paper","pagenumbering":"arabic","tmargin":3,"rmargin":3,"bmargin":3,"lmargin":3,"margin_unit":"cm","lineheight":1.2,"mainfont":"Times New Roman","sansfont":"Arial","fontsize":12,"toc":true,"tocDepth":2,"titlepage":true,"textpl":"/home/user/privat/Vorlagen/cfbrief.tex"}},"icon":null}

Deleting does not affect the Bug.

**Comment by nathanlesage** [comment] 2020-08-13 21:19
This sounds more like an issue with file synchronisation than with the template itself – are you sure Zettlr doesn't use the template?

**Comment by webopold** [comment] 2020-08-17 15:41
The template in the project setting is for writing a DIN letter.
The Zettlr-Template makes nearly plain pages.

pandoc "/tmp/export.tmp" -f markdown -F pandoc-mermaid -t latex --template="/tmp/template.latex" --pdf-engine=xelatex --mathjax -o "/tmp/muster.pdf"

**Closed** 2020-10-09 12:27 UTC
Labels: bug [non-critical], priority:mid, v1.7.x
