### ISSUE TITLE
[Bug] 0 words, 0 characters when previewing tabs

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#793] opened 2020-05-14 00:08 UTC
## Description

When previewing tabs they display
```
0 words, 0 characters 
```

even when they have content. I noticed this since 1.7.beta4

After writing on them and saving they display words and characters properly.

After restart the wordcount again disappear.

## Reproducing

Open notes in tabs [they show 0 count]
Edit & save them [they show count properly]
Restart Zettlr [they show 0 count again]

## Expected behaviour

**Screenshots**

## Platform
 - OS and version: MacOS 
 - Zettlr Version:1.7.beta4
 - Screen Resolution:

**Comment by nathanlesage** [comment] 2020-05-14 06:27
It's there since the first tabs implementation was in and I have not been able to pinpoint this issue. Because as soon as you edit the file it somehow works and I have literally no idea what is happening. I've been poking around the source code for hours already …

**Comment by danieltomasz** [comment] 2020-05-14 14:28
> It's there since the first tabs implementation was in and I have not been able to pinpoint this issue. Because as soon as you edit the file it somehow works and I have literally no idea what is happening. I've been poking around the source code for hours already …

@nathanlesage I dont know if this  matter but you have two different Case sensitive variables  in file `zettlr-renderer.js`

```
  file.wordcount = this._editor.getWrittenWords() 
```
in line 563

and then in function `refreshCurrentFile`  in 359

```
f.wordCount = file.wordCount

```

and you use the `file.wordcount`only in one place
```
./source/main/commands/file-save.js:38:    this._app.stats.updateWordCount(file.wordcount || 0)
```

**Comment by nathanlesage** [comment] 2020-05-14 15:39
Good eye! I should definitely rename that. Nevertheless, it was not the cause :/

**Comment by nathanlesage** [comment] 2020-05-14 16:08
I have literally NO IDEA when it happened, but I just realized that suddenly it works o.O

I currently assume it has something to do with the newly added `localizeNumber`, but I can't really explain it …

Feel free to comment if I break it again :D

**Comment by danieltomasz** [comment] 2020-05-14 17:25
On my machine, when I build your latest commit I am still getting this  0 words error, let's wait for others what they get ...

**Comment by nathanlesage** [comment] 2020-05-14 20:04
Ah dammit :(

**Comment by danieltomasz** [comment] 2020-05-14 22:14
> Ah dammit :(

When debugging in the VSC I could see the proper word count, but not when using the yarn build

**Comment by nathanlesage** [comment] 2020-05-15 06:39
> When debugging in the VSC I could see the proper word count

Yeah, I assumed that it's fixed on develop (albeit not on builds, because, well, I'm not too fond of the frequency of beta builds atm :D)

**Comment by nathanlesage** [comment] 2020-05-16 08:57
So for me it's working now, what about you?

**Comment by nathanlesage** [comment] 2020-05-16 10:12
Found out what it was: At some point I apparently accidentally introduced an error in the cache so that the cache saved `0` as wordCount, but not the real one. I've just committed another patch that *should* fix that. What will surely help is to clear the cache (simply navigate to the application data folder, e.g. `/Users/name/Application support/zettlr/fsal/cache` on macOS and remove all the files with names from `-1` to `99`)

**Closed by nathanlesage** 2020-05-16 10:12 UTC
Labels: bug [non-critical], confirmed, v1.7.x
