### ISSUE TITLE
Moving a document in the filemanger breaks all links to images

### ISSUE THREAD

**Issue by thekswenson** [Zettlr/Zettlr#5409] opened 2024-10-01 12:02 UTC
### Description

I use drag and drop in zettlr to move a document from one folder to another. After the move, all of the image links are broken, and I must move each one manually to the new location using the command line or the system file manager.

I would expect zettlr to move or copy the image (in the case that another document in that folder uses the image) to the new location.

### Reproducing

1. create a document with an image in it.
2. in the zettlr file manager, drag and drop the document to a new location.
3. see that the new document has a broken link.
4. then move the image file to the new location and see that it works again.

### Zettlr version

3.2.2

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Ubuntu 23.10

**Comment by nathanlesage** [comment] 2024-10-01 16:59
Instead of moving an image, it would be wiser to update all links to the image from the file. This has been on the agenda, there may even be already a bug report open for that.

**Comment by thekswenson** [comment] 2024-10-02 09:39
> Instead of moving an image, it would be wiser to update all links to the image from the file. This has been on the agenda, there may even be already a bug report open for that.

This is confusing to me. When I import an image it is copied into the folder corresponding to the document. If I move the document, I would expect the image to move too.

**Comment by nathanlesage** [comment] 2024-10-02 12:26
The folder does not just correspond to some single document, but to all documents. Remember that, unlike some note taking app, Zettlr is folder based, so images and anything outside of the actual document is not intrinsically linked to it. One image, for example, may be linked in several places. Moving the image would break all but the links to the current document. Changing the links in the document itself wouldn't break the image altogether.

Then, what we could also do is detect if the user moves some file around and update the links accordingly in the documents. But implementing that in a data-safe way will take some time.

**Comment by thekswenson** [comment] 2024-10-02 15:09
I see what you're saying, but that makes the current way of copying the image to the document directory upon import is a bit strange. It seems like, under the "image belongs to all documents" semantics, there should be a single directory for all imported images.

On the other hand, I understand that documents maybe aren't moved to new directories often, so in that sense it makes sense to keep the image near it's original document. Either way, like you said, the link needs to be updated properly when the document is moved.

**Comment by nathanlesage** [comment] 2024-10-06 18:52
I'll see to that. But I also discovered that this is a duplicate of #5400, so closing in favor of that.

**Closed by nathanlesage** 2024-10-06 18:52 UTC
Labels: bug
