### ISSUE TITLE
[win32] Zettlr not quitting when all windows are closed and the taskbar setting is off

### ISSUE THREAD

**Issue by yonojoy** [Zettlr/Zettlr#4898] opened 2024-01-15 15:38 UTC
### Description

When closing Zettlr with unsaved edits, loss of data is possible.

### First
* In Windows Associate MD files with Zettlr
* In Windows explorer generate file test.md
* Doubleclick
	* --> Zettlr opens
* Enter one character: 1
* Close Zettlr (via mouse)
	* --> No save question, Zettlr seems to be closed
* Right click on test.md in Windows explorer and open with other editor (eg PNotepad)
	* --> empty file
* Doubleclick test.md
	* --> Zettlr opens, the entered character is displayed (1) and the tab is marked with a star (*)
* Close Zettlr (via mouse)
	* --> No save question, Zettlr seems to be closed
	* However: In Taskman I see several processes running (under Details)
* Restart Windows
    * --> After restart no Zettlr processes running anymore
* check file test.md 
    * --> the file is empty, entered text is lost
	
### Second	
* Doubleclick on test.md
* enter one character again: 2
* Close Zettlr (via mouse)
	* --> Save question appears: There are unsaved changes. Do you want to save them first?
* Choose yes
* Right click on test.md in Windows explorer and open with other editor (eg PNotepad)
	* --> character is saved (2) 
	* no Zettlr instances in TaskMan anymore
	
### Third	
* Doubleclick on test.md
	* --> 2 is displayed
* enter one character again: 3
	* --> 32 is displayed
* Close Zettlr (via mouse)
	* --> No save question, Zettlr seems to be closed (but processes in TaskMan)

* repeat the steps (doubleclick, enter character, close) until the save question is displayed again
    * --> 765432 is displayed for me
	* --> it seems, the save question is working sometimes and sometimes not
	* if the question appears and Yes is answered, everything seems to be okay

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.3

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

### Config
* Autosave disabled 
* Always load remote changes to current file disabled

### Other Info
I can reproduce the state with Zettlr seemingly closed while still having processes in background by choosing "Cancel" on the Save question. Closing the file tab (instead of closing Zettlr) always seems to work.

I started to look deeper into this, because I got other problems (in 3.0.3 !), but I cannot reproduce these:

  * I lost some editing while autosave _enabled_ 
  * I experienced at least one time when Strg + S did not save (but do not remember the settings)
  * an old version of my md file mysteriously reappeared.
  	
If I should bet, I would bet that this broken Zettlr state, when MainUI is gone, but processes still sitting around, is responsible for some of the "save bugs" that were reported under issues.

**Comment by nathanlesage** [comment] 2024-01-19 18:43
A potentially very stupid question ... but ... do you have set Zettlr to remain in the taskbar? Is there a Zettlr icon when you close this window? Or does "with the mouse" mean to click on the corresponding menu item to quit (!) Zettlr?

**Comment by ejm554** [comment] 2024-01-22 23:11
I just downloaded and tried your app for the first time today, and I ran into an issue similar to this bug. Briefly, I edited a Markdown file, closed it without seeing a Save option. Upon reopening, my changes weren't saved. 

[nathanlesage](https://github.com/nathanlesage) wrote:
> ... do you have set Zettlr to remain in the taskbar?

As a matter of fact, I _did_ pin the Zettlr icon to the taskbar. Why do you ask? Could it be related to the bug?

**Comment by yonojoy** [comment] 2024-01-24 15:46
@nathanlesage 
>     * Leave app running in the notification area: Off

Do you mean this setting? It was off.

**Comment by nathanlesage** [comment] 2024-02-01 11:28
Thanks for confirming. I'm back to the office and have access to a Windows PC now. I'll have a look if I can reproduce the issue!

**Comment by nathanlesage** [comment] 2024-02-01 17:16
I have now reproduced the bug. It is that Zettlr is, interestingly enough, not quitting when all windows have been closed. I'll adapt the title to reflect that.

**Comment by yonojoy** [comment] 2024-02-02 08:27
Given this:

> I have now reproduced the bug. It is that Zettlr is, interestingly enough, not quitting when all windows have been closed. I'll adapt the title to reflect that.

and this

> If I should bet, I would bet that this broken Zettlr state, when MainUI is gone, but processes still sitting around, is responsible for some of the "save bugs" that were reported under issues.

Turning the setting 

    Leave app running in the notification area

to `On` might be a workaround for several bugs "save bugs" that were reported under issues until a fix is available (?)

**Comment by nathanlesage** [comment] 2024-02-02 13:22
> to On might be a workaround for several bugs "save bugs" that were reported under issues until a fix is available (?)

I wouldn't bet on this. But I can tell you that by explicitly quitting the app by using the menu item or pressing `Ctrl+Q`, Zettlr will ask for confirmation so you don't have any lost changes. So I recommend for the time being to always explicitly quit, not just closing the window.

**Closed** 2024-02-02 14:48 UTC
Labels: bug

**Comment by yonojoy** [comment] 2024-03-05 08:33
@nathanlesage 
> > to On might be a workaround for several bugs "save bugs" that were reported under issues until a fix is available (?)
> 
> I wouldn't bet on this. But I can tell you that by explicitly quitting the app by using the menu item or pressing `Ctrl+Q`, Zettlr will ask for confirmation so you don't have any lost changes. So I recommend for the time being to always explicitly quit, not just closing the window.

I can confirm this;
I turned on the following setting:

    Leave app running in the notification area

but nevertheless lost my data, because I forgot to close via the system menu.

**Comment by nathanlesage** [comment] 2024-03-05 08:37
> @nathanlesage 
> 
> > > to On might be a workaround for several bugs "save bugs" that were reported under issues until a fix is available (?)
> 
> > 
> 
> > I wouldn't bet on this. But I can tell you that by explicitly quitting the app by using the menu item or pressing `Ctrl+Q`, Zettlr will ask for confirmation so you don't have any lost changes. So I recommend for the time being to always explicitly quit, not just closing the window.
> 
> 
> 
> I can confirm this;
> 
> I turned on the following setting:
> 
> 
> 
>     Leave app running in the notification area
> 
> 
> 
> but nevertheless lost my data, because I forgot to close via the system menu.

That's a good observation, since the corresponding events won't be emitted by windows in that case ... I'll have to think about it, but you're right.
