### ISSUE TITLE
Automatically closing * pairs

### ISSUE THREAD

**Issue by samarulmeu** [Zettlr/Zettlr#246] opened 2019-06-21 09:21 UTC
Can you please also add `*` on the list of the automatically closing pairs? For me (maybe for others too?) the `*` is the formatting character for bold and also italic formatting? Closing it automatically will be a nice feature. 

Thank you again and again for all the great work. 

side note: the new ”bearish” screenshots are from a new theme?

**Comment by nathanlesage** [comment] 2019-06-23 07:35
I've purposedly deactivated this auto-pair due to the fact that asterisks are also used for lists. And for lists, having the auto-close feature is more than annoying :/

Concerning the bearish screenshots: Yes, and it's modeled after the Bear default theme!

**Comment by Monolecte** [comment] 2019-06-23 07:41
Not a good idea, so.
But, what about «»?

**Comment by samarulmeu** [comment] 2019-06-23 08:42
In lists' situation wouldn't this be a problem only in the case of the first element of the list? As for the others the * is automatically generated?

**Comment by nathanlesage** [comment] 2019-06-23 09:54
> Not a good idea, so.
> But, what about «»?

Isn't that automatically closed? If not I'm going to add it to the list, b/c French-style quotes should be supported!

> In lists' situation wouldn't this be a problem only in the case of the first element of the list? As for the others the * is automatically generated?

The problem is: How do you differentiate between a person who wants to create an Italic passage first on a line vs begin a list? It's impossible due to the semantic contingency :/

**Comment by samarulmeu** [comment] 2019-06-23 10:10
> The problem is: How do you differentiate between a person who wants to create an Italic passage first on a line vs begin a list? It's impossible due to the semantic contingency :/

I think that you start a list by * and a space `* ` on a new line/paragraph, but not a paragraph with the first element as an italic as you don't have a space before a character. I hope I'm not too foggy in my explanation.

**Comment by Monolecte** [comment] 2019-06-23 12:30
> Isn't that automatically closed? If not I'm going to add it to the list, b/c French-style quotes should be supported!

This is, but in the bad way → »item« and not the good way «item»

**Comment by nathanlesage** [comment] 2019-06-23 13:14
It's not bad, it's the German style of using the Guillemets :-P I'll add the pair!

**Comment by nathanlesage** [comment] 2019-06-23 13:15
> I think that you start a list by * and a space * on a new line/paragraph, but not a paragraph with the first element as an italic as you don't have a space before a character. I hope I'm not too foggy in my explanation.

I know what you mean, but I'm using a CodeMirror plugin for the auto-closing, and it doesn't support such things, as far as I know :(

**Comment by samarulmeu** [comment] 2019-06-24 09:37
Although, I'm not good with javascript, I'll try to look into the add-on you've mention and maybe come up with a solution. In the mean time maybe the new possibility of choosing formatting characters (expected in 1.4 from what I've noticed in the CHANGELOG) will make life easier for us, the ones that use `*`.

**Comment by samarulmeu** [comment] 2019-06-27 10:35
I think that if you want to be safe with the lists generated in a markdown file using `*` you can close this issue. 
I thought a bit and I don't think there is an obvious solution to this, because adding a space after the `*` to generate an entry list, and so tell the code that it should not close the `*` pair, takes place **after** the codes would generate the auto-pairing.

**Comment by nathanlesage** [comment] 2019-06-27 15:40
Yes, I see what you mean. One solution might be to let the plugin render two asterisks, which would be reported in the `change` event as the string `**`, which could then be temporarily saved. If the next character then would be a space, one might be able to remove the second asterisk programmatically, or leave it if the next character is not a space. However, one would need to make sure to disable the internal switch once anything else happens (e.g. the user decided after typing one asterisk to move the cursor someplace else and there s/he typed a space) …

**Comment by samarulmeu** [comment] 2019-06-28 05:56
It's getting complicated. In a way is strange to have `*` for emphasis and also lists in Markdown, but these are the specifications. I understand that you want to have the editor clean and as compatible as possible so I think that this issue can be closed. At least the French Guillemets  were added to the list. I also used them but I never noticed that they are not automatically closing.

**Closed** 2019-06-28 05:56 UTC

**Comment by nathanlesage** [comment] 2019-06-28 07:37
Alright! I'll nevertheless keep in mind the asterisk list/emphasis-issue and if I come up with a great solution, I'll implement it! :)
