### ISSUE TITLE
[Bug] save-image-from-clipboard not woring

### ISSUE THREAD

**Issue by i21aelbe** [Zettlr/Zettlr#1393] opened 2020-11-01 09:37 UTC
## Description
Pasting an image from the clipboard to the active documents does not work any more.

## Reproducing
- Ensure that there is an image in the clipboard
- Use Strg/Cmd-V to insert it
- Accept the dialog box
--> nothing happens (in the current document)

## Expected behaviour
- Image-Link is inserted in the document
- Image is dispayed...

## Shown behaviour
The following exception is thrown:

TypeError: this._app.getFileSystem(...).getActiveFile is not a function
    at SaveImage.run (/Users/michael/Projects/zettlr/.webpack/main/index.js:117582:83)
    at Zettlr.runCommand (/Users/michael/Projects/zettlr/.webpack/main/index.js:123219:28)
    at ZettlrIPC.handleEvent (/Users/michael/Projects/zettlr/.webpack/main/index.js:121754:33)
    at ZettlrIPC.dispatch (/Users/michael/Projects/zettlr/.webpack/main/index.js:121715:10)
    at IpcMainImpl.<anonymous> (/Users/michael/Projects/zettlr/.webpack/main/index.js:121676:12)
    at IpcMainImpl.emit (events.js:310:20)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:157:8362)
    at WebContents.emit (events.js:310:20)
[10:21:43] Unbekannten Befehl erhalten: save-image-from-clipboard

## Platform
 - OS and version: OSX 10.15.7 (Catalina)
 - Zettlr Version: HEAD of repo (Commit 988ab72), i.e. some days after fst 1.8.0 beta

## Additional information
Bug can be fixed by the following diff:

--- a/source/main/commands/save-image-from-clipboard.js
+++ b/source/main/commands/save-image-from-clipboard.js
@@ -35,7 +35,8 @@ class SaveImage extends ZettlrCommand {
   async run (evt, target) {
     // First check the name for sanity
     let targetFile = sanitize(target.name, '-')
-    let activeFile = this._app.getFileSystem().findFile(this._app.getFileSystem().getActiveFile())
+    let activeFile = this._app.getFileSystem().findFile(this._app.getFileSystem().activeFile)
 
     // A file must be opened and active, and the name valid
     if (targetFile === '') return global.ipc.notify(trans('system.error.no_allowed_chars'))

**Comment by klieret** [comment] 2020-11-02 08:44
Duplicate of https://github.com/Zettlr/Zettlr/issues/1370 (but on OSX and with debug info)

**Closed** 2020-11-02 19:15 UTC
