### ISSUE TITLE
[Bug] Strange program behavior: constant .md file update

### ISSUE THREAD

**Issue by JetV** [Zettlr/Zettlr#2783] opened 2021-11-08 21:47 UTC
### Description

I am writing my .md document from a single computer. The document is stored on a local drive. For some reason, the Zettlr suddenly starts **_constantly_** (about once a minute) to accept document changes from outside (because he is "changed from outside"). This was not the case before. 

### Reproducing

1. start Zetlr, open .md document
2. start typing
3. after about a two minutes suddenly a window appears asking you to accept the changes
![err1](https://user-images.githubusercontent.com/6479885/140823322-3f05d3ef-4da3-4ea3-9479-07299d42c2fe.JPG)
4. restarting the application does not help, the Internet is connected

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.2

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 7

**Comment by JetV** [comment] 2021-11-09 19:25
I thought it was due to the fact that specified the current directory to save the export output, but no.

**Comment by nathanlesage** [comment] 2021-12-04 20:08
Does this still occur in 2.0.3? If so, do you use a cloud service to sync your files?

**Comment by shaunirwin** [comment] 2021-12-29 20:31
I have also encountered this issue a few times, although I am using Ubuntu with Zettlr version 2.0.3. My markdown files are written to my Dropbox folder on a local SSD drive.

I cannot reproduce the issue reliably. On some days it happens several times and other days not at all.

I will try reproducing this on a non-Dropbox-synced folder and see if I ever encounter it, although I would imagine it is cloud sync-related.

**Comment by nathanlesage** [comment] 2023-02-19 09:14
This should be fixed after the changes to the FSAL watching logic.

**Closed by nathanlesage** 2023-02-19 09:14 UTC
Labels: bug
