### ISSUE TITLE
[BUG] Find dialog box undoes selection via ctrl+a

### ISSUE THREAD

**Issue by aidanhs** [Zettlr/Zettlr#1377] opened 2020-10-25 21:08 UTC
## Description
The global search/find field sometimes deselects text if navigating to it too quickly after typing

## Reproducing
A common pattern when I'm quickly moving around is to:
1. navigate to a note by its exact name (e.g. a file called `todo.md`, I'll type `todo` and hit enter and it'll open)
2. type something
3. *immediately after typing* navigate to the global search box and select all (all in one via ctrl+shift+f, or by clicking the box and pressing ctrl+a)

## Expected behaviour
The whole text should remain selected, but doesn't - it deselects and positions the cursor at the beginning of the box.

## Platform
 - OS and version: reproduced on Ubuntu 18.04 and Windows 10
 - Zettlr Version: 1.7.5

## Additional information

My experiments suggest this may only happen when using the direct name for a note, as opposed to searching for a word and clicking on an item from the results.

**Comment by nathanlesage** [comment] 2020-10-25 23:36
Cannot reproduce this on the current 1.8.x develop branch, so it seems fixed. Please comment, if it isn't fixed in the latest beta release!

**Closed by nathanlesage** 2020-10-25 23:36 UTC

**Comment by aidanhs** [comment] 2020-12-05 21:56
@nathanlesage I can still reproduce this on 1.8.1, released 2 days ago

**Comment by aidanhs** [comment] 2020-12-05 22:12
Because I figured this may be hard to understand, I've done a screen capture to explain. My problem is the part where I click in the top "search" box when it has the word "backups" in it and then press ctrl+a - as you can see, it selects and then unselects.

![zettlr](https://user-images.githubusercontent.com/1050652/101266439-d4a8c200-3746-11eb-8ff5-08f6b907cfe9.gif)

**Comment by nathanlesage** [comment] 2020-12-06 13:49
I think I found the bug finally and fixed it.
