### ISSUE TITLE
Not empty new file

### ISSUE THREAD

**Issue by FilexD** [Zettlr/Zettlr#1495] opened 2020-12-06 08:15 UTC
What about to be able to start with a non empty file?
*) Creating templates? to my knowledge, no such thing as a "template file format" for markdown. 
*) Creating "pre-structured content" to be paste after creating new file? Something that would work a little as the "signature feature" in Outlook. For example, creating a "pre-structured" sub-menu in the "preferences menu" that allows to file with whatever we want then saving it. Then, after creating a new empty file, going to a "fill with structure" item in the "file menu" so to choose the content.
*) Just adding "yaml content? In the "preference menu", create a "Yaml" sub-menu  with a window allowing to put the yaml content we want then and an optional "automaticcaly add to nex file" then when creating a new file, a little test "If /then" should add that content.

**Comment by nathanlesage** [comment] 2020-12-06 13:50
Duplicate of #1009

**Closed by nathanlesage** 2020-12-06 13:50 UTC
