### ISSUE TITLE
[Bug] [Linux] Closing tab using middle-mouse button also performs unintentional paste action

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#2663] opened 2021-10-18 19:35 UTC
### Description

When closing a tab using middle-mouse button, that tab is closed, but in the next tab, that gets focus after, whatever text you had highlighted (and thus is present in the respective system paste buffer) will get pasted at the current cursor location.

Also, when pressing the middle-mouse button within the text (to paste something), the clipboard content will be pasted _twice_.

Looks like the middle-mouse click is somehow triggering the event handler (or similar) twice?

---

(_for those that didn't know: In most Linux distributions it is possible to highlight some text, and then paste it somewhere else by pressing down the middle-mouse button (scroll wheel)_).

### Reproducing

Suppose there are two open tabs, `bar.md` and `foo.md`:

![img1](https://user-images.githubusercontent.com/18646029/137794079-becf3ab7-bed0-4c02-9bad-be626aee2980.png)

Somewhere (doesn't have to be Zettlr), I have highlighted the text snippet "peanuts".

Now, when I close tab `foo.md` using the middle-mouse button, this is how `bar.md` will look afterwards:

![img2](https://user-images.githubusercontent.com/18646029/137794655-f7adbda0-3d92-4cd6-b354-f675ed96ec5c.png)

**Note**: When tab `foo.md` was the active one, and we close that using middle-mouse, the pasting in tab `bar.md` will also happen.

---

Regarding the double pasting: This is what happens, when we go to the next line and press the middle-mouse button _once_:

![img3](https://user-images.githubusercontent.com/18646029/137795151-e7ee3239-d711-4f04-a9e7-4035863b9d44.png)

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.0

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro

**Comment by nathanlesage** [comment] 2021-12-14 13:16
Does this still happen in 2.0.3, in which I removed the custom code for that?

**Comment by kyaso** [comment] 2021-12-14 19:29
I just tested it, and yes, the pasting when closing a tab using middle-mouse still happens.

The double pasting issue is gone after your fix.

**Comment by nathanlesage** [comment] 2021-12-14 20:13
Should work now. If not, then it's likely a platform issue in that a middle mouse click gets captured by the OS, the text is pasted, and only then the middle click is being propagated to the tab. Let's hope not so!

**Comment by kyaso** [comment] 2021-12-14 21:03
Build the most recent dev version ( 4083154 ), and unfortunately, the issue is still present :/

> [...] it's likely a platform issue in that a middle mouse click gets captured by the OS, the text is pasted, and only then the middle click is being propagated to the tab.

What's weird is that when I middle-click the _current_ tab, the text is _not_ pasted into the closing tab, but instead into the tab that becomes active next.

**Comment by kyaso** [comment] 2021-12-14 21:12
> What's weird is that when I middle-click the current tab, the text is not pasted into the closing tab, but instead into the tab that becomes active next.

I just noticed that this is not always the case. When the current tab/file has not been saved yet, and I attempt to close it via middle-mouse, the saving prompt appears, and I can see in the background the text being pasted in the _current_ file.

**Comment by nathanlesage** [comment] 2021-12-14 21:20
I really can't imagine that, since the middle-mouse event cannot bubble into the editor o.O I double-checked that

**Comment by bilderbuchi** [comment] 2022-01-08 17:07
> I just noticed a special case where this doesn't apply: When the current tab/file has not been saved yet, and I attempt to close it via middle-mouse, the saving prompt appears, and I can see in the background the text being pasted in the current file.

I observe the same thing, on Kubuntu 20.04 and Zettlr 2.1.1

**Comment by nathanlesage** [comment] 2022-01-08 22:44
@bilderbuchi I fear that is something where the OS is overriding some internal behavior, I'm not sure this is something I can fix :/

**Comment by bilderbuchi** [comment] 2022-01-08 23:32
This seems a relevant related (solved) issue and linked PR https://github.com/atom/tabs/issues/461 in Atom. (although not sure of the correspondence between Atom, Electron, Chromium, Zettlr)

**Comment by Joelius300** [comment] 2022-01-14 14:22
Can confirm that this issue is still present in the latest version 2.1.2 (only the pasting when closing tab issue, not the double pasting one).
Reproduced on Manjaro KDE.

I'm not very familiar with keyboard event handling especially with electron but this line struck me as weird:
https://github.com/Zettlr/Zettlr/blob/master/source/win-main/DocumentTabs.vue#L225

It's using `event.stopPropagation()` instead of the `event.preventDefault()` I'm used to seeing. Mozilla [specifically states](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation) (emphasis mine):
> The `stopPropagation()` method of the Event interface prevents further propagation of the current event in the capturing and bubbling phases. **It does not, however, prevent any default behaviors from occurring; for instance, clicks on links are still processed. If you want to stop those behaviors, see the `preventDefault()` method.** [...]

Could that be the cause?

**Comment by nathanlesage** [comment] 2022-01-14 15:59
> The linked atom issue disables the paste event for chromium globally when on linux if I understand correctly but I don't know what that would mean (for Zettlr).

Well, if "paste event" refers to this middle-click pasting behavior, then it would simply mean that you had to copy&paste text like everyone else on macOS and Windows :D Which would arguably be better than an unintentional paste everytime you close the tab …?

**Comment by Joelius300** [comment] 2022-01-14 18:08
Not sure.. I'm referring to [this snippet](https://github.com/atom/atom/pull/15183/files#diff-27be6dac880ddf8b9a743f938730305bc87d0894dc15f3e8ca1520cbfccc2bfdR1555-R1563) from their fix (which has been there for the last 5 years it seems). I'm not using atom so I'm not sure what that exactly does but I assume this could be relevant here as well since it seems to be tied to chromium / electron and not their own code, in which case maybe a fix like this could be done here as well.

**Comment by nathanlesage** [comment] 2022-01-14 19:17
Aaaah, alright. So apparently we must interrupt a *paste*-event, not the mousedown event. That explains why the mousedown didn't do anything.

The question now is: Is the paste event triggered on the corresponding tab, or is it triggered in the editor component? If the former, then all we need to do is add an `v-on:paste="handler"` at the same element where we listen for mouseclicks, and in the handler call `event.preventDefault()`. If the latter is true, then … it's difficult, since these two components don't share a state.

@Joelius300 Feel free to try that out, whether it works!

**Comment by Joelius300** [comment] 2022-01-15 12:44
Just did and I am astonished 😅 

Using `v-on:paste` doesn't work, the handler isn't ever called. I thought maybe that's because `preventDefault` and `stopPropagation` are called on the mousedown event. So I removed those and hoped the paste handler would be called. Of course that didn't happen.. Instead, it just started working. No more pasting on middle mouse button when I closed a tab.
So after a few seconds of disbelief I hard reset to tag `v2.1.2` and commented out the line `event.preventDefault`. It actually works. This fix for windows was the issue for Linux all along it seems.

I will provide a pull request with a platform check just like they implemented in the linked atom issue so you can test if everything works on Windows. I'll try to do all the tests on the Linux side but it would be greatly appeciated if other Linux users with different distros and or DEs could help to make sure it works now (or that it still works, I don't know if there are distros/DEs that never had any issues).

**Comment by Joelius300** [comment] 2022-01-15 13:38
I opened #3044. It would be nice if some people with different OS' and DEs could make sure it works for them as well.

Also, not in the scope of this issue, but I found that middle mouse click for pasting only works for me when I click below all the test so click _on_ text doesn't paste (just puts the cursor there). Maybe that could be a new issue.

**Comment by nathanlesage** [comment] 2022-01-15 13:54
@Joelius300 Nice job! I'll test this out for macOS over the weekend!

But it's interesting since it seems that if you middle click on the text `span`, it works fine, but double pasting happens if you click outside the text, i.e. on the `div` container?

Puhhh, platform issues, let me tell ya… 😫

**Comment by Joelius300** [comment] 2022-01-15 14:06
> Puhhh, platform issues, let me tell ya… :tired_face:

I can imagine 😅

> But it's interesting since it seems that if you middle click on the text span, it works fine, but double pasting happens if you click outside the text, i.e. on the div container?

Are you talking about this issue or the one I mentioned on the side about "normal" pasting using middle mouse click?  
I just tested and for closing the tabs it doesn't make a difference if I click on the text or the empty space but for the normal pasting I have to click on the _div_, not the span, otherwise it doesn't paste anything.

**Comment by kyaso** [comment] 2022-01-15 15:02
@nathanlesage

> The question now is: Is the paste event triggered on the corresponding tab, or is it triggered in the editor component? If the former, then all we need to do is add an v-on:paste="handler" at the same element where we listen for mouseclicks, and in the handler call event.preventDefault(). If the latter is true, then … it's difficult, since these two components don't share a state.

The answer to that question is that the paste event gets triggered in the editor (at least according to what I described in https://github.com/Zettlr/Zettlr/pull/3044#issuecomment-1013694298).

**Comment by Joelius300** [comment] 2022-01-15 16:07
> The answer to that question is that the paste event gets triggered in the editor (at least according to what I described in #3044 (comment)).

No for me unfortunately 😞 https://github.com/Zettlr/Zettlr/pull/3044#issuecomment-1013707193

**Comment by kyaso** [comment] 2022-01-15 18:14
I found something interesting! Maybe the problem might be the `mousedown` event? My assumption: When closing a tab by clicking the middle-mouse button, the closing and switching to the next tab happens so fast that the new tab also registers a middle-mouse `mousedown` which causes the unintentional pasting.

So I changed the `mousedown` event in `DocumentTabs.vue` to a `mouseup` event instead (in the main develop branch),

https://github.com/Zettlr/Zettlr/blob/a179e11e9bb99f8620549788e9140578acb3758a/source/win-main/DocumentTabs.vue#L18

and no more pasting! If somebody running a Linux machine (e.g. @Joelius300) could verify this?


However, it also slows down regular clicking (e.g. when switching tabs), as you now have to "wait" until you release the mouse for the event to fire.

**Comment by kyaso** [comment] 2022-01-15 18:40
> However, it also slows down regular clicking (e.g., when switching tabs), as you now have to "wait" until you release the mouse for the event to fire.

A solution for this could be creating a separate `mouseup` event that handles middle-mouse clicks. And then move all the code regarding a middle-mouse click from `handleClickFilename()` into a new handler for the `mouseup` event.

I tried that locally, and the pasting issue is gone, and left-clicking tabs works as fast as usual.

**Closed** 2022-01-29 09:59 UTC
Labels: bug
