### ISSUE TITLE
[ENHANCEMENT] Close Editor Tab Keyboard Shortcut

### ISSUE THREAD

**Issue by ditServices** [Zettlr/Zettlr#901] opened 2020-06-08 23:25 UTC
## Description

A keyboard shortcut to close the active editor tab

## Proposed Changes

Add a keyboard short cut similar to Firefox CTRL-W

**Comment by nathanlesage** [comment] 2020-06-09 08:31
Duplicate of #841

**Closed by nathanlesage** 2020-06-09 08:31 UTC
