### ISSUE TITLE
Left click opens Link in app without return or exit path

### ISSUE THREAD

**Issue by Chuhtra** [Zettlr/Zettlr#1540] opened 2020-12-20 00:38 UTC
## Description

Consistently when I simply left click with mouse on a web link with link itself as name, the site opens on top of the Zettlr window. It hides every single of the window and there is no way to close the site and return to the app. I could only return in app by restarting Zettlr.

## Reproducing

Create a link with a link in its name like `[www.google.com](www.google.com)` -it will take you to google- or `[www.github.com](www.google.com)` -it will take you to github.

## Expected behaviour

It should open the link to a browser instead of the Zettlr window. Or at least it should somehow allow the user to return back to the app.

## Platform
 - OS and version: Manjaro Linux
 - Zettlr Version: 1.8.2

## Additional information

 --

**Comment by Kangie** [comment] 2020-12-20 09:24
I can't replicate this behaviour on develop  (linux)

**Comment by Chuhtra** [comment] 2020-12-20 13:07
Hmm, alright. I attach some screenshots in case they help:

![image](https://user-images.githubusercontent.com/40795688/102714007-b5786b80-42d4-11eb-8e40-ccbb6bcf0b52.png)

![image](https://user-images.githubusercontent.com/40795688/102714014-bf9a6a00-42d4-11eb-9621-2816596e803c.png)

![image](https://user-images.githubusercontent.com/40795688/102714021-caed9580-42d4-11eb-8a8f-3f214961b2e9.png)

Just to be sure, you tried it on 1.8.2? It might be a version thing?

**Comment by boutil** [comment] 2020-12-21 13:42
I think this is a duplicate of #1513, which has been closed with a fix about a week ago. This would mean that it is also fixed by upgrading to 1.8.3.
Please upgrade to 1.8.3 and check whether you can reproduce the issue.

**Comment by nathanlesage** [comment] 2020-12-23 21:57
Yes, this was a bug I accidentally threw into 1.8.2, it's now fixed. Please remember you can close your issues as well if they've been resolved!

**Closed by nathanlesage** 2020-12-23 21:57 UTC
