### ISSUE TITLE
No such file or directory while starting

### ISSUE THREAD

**Issue by tobiasdiez** [Zettlr/Zettlr#2033] opened 2021-05-30 08:31 UTC
## Description

Starting the develop branch yields
```
[10:23:27] Config provider booting up ...
Error: ENOENT: no such file or directory, scandir 'undefinedlang'
    at Object.readdirSync (fs.js:1021:3)
    at Object.e.readdirSync (electron/js2c/asar_bundle.js:5:10249)
    at enumLangFiles (D:\Programming\Zettlr\.webpack\main\index.js:124891:58)
    at Module.getLanguageFile (D:\Programming\Zettlr\.webpack\main\index.js:124765:51)
    at Object.getConfigTemplate [as default] (D:\Programming\Zettlr\.webpack\main\index.js:127469:25)
    at new ConfigProvider (D:\Programming\Zettlr\.webpack\main\index.js:129490:52)
    at Object.bootApplication (D:\Programming\Zettlr\.webpack\main\index.js:126895:22) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'undefinedlang'
}
```

## Expected behaviour
Not sure. Somewhere in the code one should check if the folder exists. Does it make sense to let `readdirSync` return an empty list if the directory doesn't exist?
 

## Platform
 - OS and version:
 - Zettlr Version:

**Comment by nathanlesage** [comment] 2021-05-30 09:54
Ahh, yeah I have refactored the i18n module since we needed separate `trans´-functions for main and renderer processes, and I took the opportunity to break up that file. Let me have a look!

**Comment by nathanlesage** [comment] 2021-05-30 10:03
I could not reproduce this locally; it could be that you got some commit "in between" where the bug happened; since these changes are pretty fresh. Would you mind checking again?

Besides: readdirsync should always work. The path `path.join(app.getPath('userData'), '/lang')` will be created during environmental check and the `path.join(__dirname, '/lang')` should also exist, because the CopyWebpackPlugin should successfully copy over the language files to said directory (note that `__dirname` in our context never corresponds to the actual directory name, but the one provided in `.webpack`)

**Comment by nathanlesage** [comment] 2021-05-30 10:06
Furthermore, it does look weird: The resolved path `undefinedlang` suggests that either `__dirname` or `app.getPath('userData')` returns undefined, which sounds really weird, since those two things should _never_ be undefined. Could it be that you didn't run `yarn install --frozen-lockfile` after pulling the changes? I merged many of the dependabot-PRs yesterday, including a major Electron bump (12.x --> 13.x).

**Comment by tobiasdiez** [comment] 2021-05-30 10:37
Strange...now it it working. 

I leave this issue for you to close, since maybe it is still worthwhile to explore if readdirSync  / enumLangFiles  should handle non-existing paths more gracefully.

**Comment by nathanlesage** [comment] 2021-05-30 10:39
Yes, definitely. Right now I'm adding the document headers (the BEGIN HEADING/END HEADING blocks) to all files that were missing them, but afterwards I wanted to get to these functions either way, because we don't really need the function argument. I'll make sure to add checks where appropriate!

**Closed by nathanlesage** 2021-05-30 10:39 UTC
