### ISSUE TITLE
[Image paste] Selected path to save image is the parent directory of the one chosen

### ISSUE THREAD

**Issue by narekkay** [Zettlr/Zettlr#3989] opened 2022-12-17 13:10 UTC
### Description

When I paste a picture from the clipboard to Zettlr, it lets me choose the path where to save my file,

![image](https://user-images.githubusercontent.com/24856100/208238223-c3ef17bc-30ba-4833-aa3a-ae6846ad8a1a.png)

you select the folder you want, and it works.

However, when you add another image to your markdown, now it saves your picture **in the parent directory** : so I need to correct the path everytime.

Following the logic, the temporally fix would be : 
- **create** a random folder "abc" **in the target folder**
- **save** an image in this random folder "abc"

It will no longer upload to the random "abc" one, but go one step higher, in the parent folder, which the one you initially wanted to upload to.

I think the issue resides in the function called when pressing "Save" when you selected the path after pasting a picture : 
![image](https://user-images.githubusercontent.com/24856100/208239987-ab10cf47-7dc7-42d0-a8e3-a581465db626.png)

From a quick research : 
- the value "askFileDialog" of the "dialogPaths" object in the config.json is not being updated when I save a new path after pasting an image
Effect : 
![image](https://user-images.githubusercontent.com/24856100/208243908-52d256cc-b672-4866-8ef2-cd1e29310f7e.png)
this file path indicate one folder

but when I click on the right file icon, it shows the value of the previously selected folder : 
![image](https://user-images.githubusercontent.com/24856100/208244013-27d87693-bebe-4be5-9a9d-f25b4a469f66.png)

---

Facts to consider : 
- chosen path is relative
- when pasting an image and choosing another folder, the path in "askDirDialog" does not end with a slash (or double backslash for windows)

Links of my research : 
- "askDir" parameter in the project
https://sourcegraph.com/search?q=context:global+askDirDialog+repo:%5Egithub%5C.com/Zettlr/Zettlr%24+&patternType=standard&sm=1

- the component loaded in the window when pasting an image : 
https://github.com/Zettlr/Zettlr/blob/develop/source/win-paste-image/App.vue

- the window component : 
https://github.com/Zettlr/Zettlr/blob/develop/source/common/vue/window/Chrome.vue

it might also be a cache issue, will look deeper later

Have you ever encountered this issue as well ?

### Reproducing

1. Open Zettlr
2. Create a new blank file
3. Copy an image from any source to clipboard
4. Paste (Ctrl+V) in Zettlr
5. Change save path : 
![image](https://user-images.githubusercontent.com/24856100/208243444-ecd26521-403a-44b2-9a8f-5357bbe8a7eb.png)

6. Save
![image](https://user-images.githubusercontent.com/24856100/208243465-c1ab25dc-b2a0-47a8-b358-368257dcf8dd.png)

7. Step 3 again : copy an image
8. Paste again

The path loaded will differ from the one selected at step 5

### Zettlr Version

Stable (most recent version)

### Installation Method

None

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10 21h1

**Comment by nathanlesage** [comment] 2022-12-19 19:41
I can't reproduce this in the current dev branch, so there is a high chance I've fixed this issue in the meantime. I remember I had some issues when it comes to selecting the correct start paths. Right now it works as expected: It always chooses the Markdown file's directory as a base and, optionally, append any relative path if you had set one in your preferences.

Feel free to test out the [nightly](https://nightly.zettlr.com/) and see if that fixes the bug. If so, we can close the issue!

**Closed** 2024-02-10 15:06 UTC
Labels: bug
