### ISSUE TITLE
Search stops working after closing the Global search/File manager sidebar

### ISSUE THREAD

**Issue by Barabas5532** [Zettlr/Zettlr#4958] opened 2024-02-12 22:13 UTC
### Description

After closing the left sidebar, tag search by CTRL+mouse click and autocomplete after typing `[[` stops working.

### Reproducing

- Open Zettlr.
- CTRL+click on a tag, global search opens as expected.
- Click on the search icon in the top left to close the search side bar on the left of the window.
- CTRL+click on a tag again, search opens, but is empty. Can't see tag results any more.
- Type `[[` and notice no autocomplete window pops up

https://github.com/Zettlr/Zettlr/assets/28671465/b21d861f-e2e4-4d77-8e85-67498c091c28

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.5-2 from Arch Linux

### Installation Method

Other (please specify below)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Arch Linux

### Additional Information

Installed from official Arch Linux `extra` repository

**Comment by dustdfg** [comment] 2024-02-22 09:25
Have the same issue that auto-completion after `[[` sometimes doesn't work but I can't find sequence of actions after which it happens. Your instruction doesn't work for me. Maybe I have another bug but it just has the same functional effect `¯\_(ツ)_/¯`

I tried versions from 3.0.2 to 3.0.5 in Debian all installed via deb file from github

**Comment by nathanlesage** [comment] 2024-02-25 14:55
I couldn't reproduce this issue with the current development build. Would you mind trying out the new nightly that will be released tomorrow and see if this issue occurs also there? Thanks! You can find the nightly here: https://nightly.zettlr.com

**Comment by gieselbusch** [comment] 2024-02-26 09:32
I experienced this issue before too, but it's gone with the new nightly build.

**Comment by nathanlesage** [comment] 2024-02-26 14:36
Perfect, thank you for confirming. Let's close this in the hopes it's really gone. If not, please comment!

**Closed by nathanlesage** 2024-02-26 14:36 UTC
Labels: bug
