### ISSUE TITLE
I can not use my mouse to press the OK or Cancel button in the delete file confirmation dialog

### ISSUE THREAD

**Issue by BenjaminHerbert** [Zettlr/Zettlr#2074] opened 2021-06-10 07:28 UTC
## Description
I want to delete a file. I can not use my mouse to press the OK or Cancel button in the confirmation dialog. The mouseclick is not registered. (Escape or Tab,Enter works)

## Reproducing
* Create a file
* Rightclick - Delete file
* Click on okay ... 
* Nothing happens
* Click on cancel ...
* Nothing happens

## Expected behaviour
* Confirmation dialog is closed, file is deleted
* Cancel should close the dialog

## Platform

* Zettlr Version: 1.8.9
* System: linux 5.12.7-200.fc33.x86_64 (architecture: x64)

**Comment by nathanlesage** [comment] 2021-06-11 14:03
Duplicate of #1645

**Closed by nathanlesage** 2021-06-11 14:03 UTC
