### ISSUE TITLE
Windows detects Zettlr as a virus

### ISSUE THREAD

**Issue by doms2a** [Zettlr/Zettlr#652] opened 2020-04-09 15:32 UTC
## Description
When trying to download Zettlr through the website chrome blocks the download saying that it detected a virus. Similar thing happens when trying to install via Chocolatey.

## Reproducing

Open the [download page](https://www.zettlr.com/download/win32) and download Zettlr.

## Expected behaviour
No blockage of the download such that I can install and use Zettlr.

**Screenshots**
![Virus](https://user-images.githubusercontent.com/10485106/78912457-e9359d00-7a87-11ea-9a4c-d0c415fc7b9d.png)
![Virus 2](https://user-images.githubusercontent.com/10485106/78912486-f2bf0500-7a87-11ea-8c3f-6edf883462df.png)

## Platform
 - OS and version: Windows 10 Pro N 10.0.18362 Build 18362
 - Zettlr Version: 1.6.0
 - Screen Resolution: 2x 2560x1440

## Additional information
Thanks for the help!

**Comment by nathanlesage** [comment] 2020-04-09 19:02
Duplicate of https://github.com/Zettlr/Zettlr/issues/649

**Closed by nathanlesage** 2020-04-09 19:02 UTC
