### ISSUE TITLE
[Bug] [vim mode] Normal mode cursor invisible when inside inline code

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#3126] opened 2022-01-31 20:24 UTC
### Description

When you move the block cursor (in Vim's normal mode) through an inline code snippet, the cursor becomes invisible.

Does not happen for the regular ("beam") cursor (e.g. in Vim insert mode).

### Reproducing

1. Write some inline code (single backticks)
2. Enable Vim mode in preferences
3. Make sure you are in Normal mode, i.e. the block cursor is visible
4. Move the cursor into the inline code -> cursor becomes invisible

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux manjaro 5.14.21-2

**Comment by nathanlesage** [comment] 2022-04-02 19:35
Just tested it, the problem is that the inline code receives this background color. It can be fixed by simply removing the background color from the text. (I'm not sure why people demanded that in the first place, tho).

Fixed with transparency in the color.

**Closed** 2022-04-02 19:35 UTC
Labels: bug
