### ISSUE TITLE
The editor jumps to the top randomly

### ISSUE THREAD

**Issue by manueldeljesus** [Zettlr/Zettlr#2027] opened 2021-05-27 10:29 UTC
## Description
While writing, the editor moves, most of the time to the top of the file.

## Reproducing
It sometimes happens when the mouse is moved, others it happens without anything being done. I have checked some closed issues in which a similar behavior was triggered by saving. It is not the case here -not even when autosaving-. Moving the mouse may be the most recognizable trigger for the behavior, but it does not even happen every time that I move it. It is quite random and arbitrary.

## Expected behaviour
I would hope that Zettlr stays put in the line I am writing, without moving the file up and down.

If necessary, I could try to capture my screen and make a video, but I do not think that it would add any more information to what I have -tried- to describe.

## Platform
 - OS and version: Windows 10 Education. 21H1. 19043.1023.
 - Zettlr Version: 1.8.9

**Comment by manueldeljesus** [comment] 2021-05-27 17:17
## Update on the situation

The behavior is not just jumping to the top. I am not missing my insertion point, the cursor stays put where it was, but the editor goes to the end of the file and then back as I continue typing. This morning I had a shorter document so I did not fully understand the behavior.

## Question

May it be due to the directory being monitores by Microsoft OneDrive? I have been trying to reproduce the behavior in a directory outside of it and it does not seem to occur.

**Comment by manueldeljesus** [comment] 2021-05-27 19:04
After having revised other issues more in detail, I think this is a duplicate of #1928.

**Comment by nathanlesage** [comment] 2021-05-28 19:21
Duplicate of #1928, closing.

**Closed by nathanlesage** 2021-05-28 19:21 UTC
