### ISSUE TITLE
File list scrolls down infinitely and starts flickering

### ISSUE THREAD

**Issue by mobamus** [Zettlr/Zettlr#177] opened 2019-05-05 10:38 UTC
## Description

I’m experiencing the problem, that the file list starts 'flickering' when scrolling down too far. I have ~400 files. It appears as if the program wants to scroll down, although it already reached the bottom. I can reproduce this by hitting the 'End'-Button to go down the end of the file list, or by scrolling down to ~R/S/T in alphabetical list order. 

I  am aware, that [someone already reported this](https://github.com/Zettlr/Zettlr/issues/76), but the bug was closed due to some strange spam message of the thread starter... Or was it closed, because the bug is in fact a Clusterize.js-problem and therefore out of your hands?

(I took a screen capture video of the behavior, but then I found the other bug report and figured that it is not necessary to explain the problem with a video, since you are already aware of it.)

## Platform
 - OS: KDE Neon 5.15 (Ubuntu 18.04 LTS)
 - Zettlr Version 1.2.3
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment] 2019-05-07 17:38
I just again tried to enforce this bug using my Zettelkasten (~ 4.500 files), but I couldn't reproduce it AGAIN. It stopped appearing after some reconsiderations in the CSS for me, but apparently some others still have weird issues. But as they are randomly distributed across computers with no clear pattern, it's hard to really pinpoint the issue. Maybe it's even an issue with Blink, the rendering engine itself — could be anything :/

I still always keep this in my mind, but haven't stumbled across a solution, so if anybody here has an idea, please comment!

**Comment by jlnbdt** [comment] 2019-05-09 07:54
Hi,

Same problem here. Can't say if it's related to the following point, but I've noticed that the problem occurs when the active folder is a parent folder, not when the active folder is a child folder.

Also, I get this strange behavior only with a maximized window. When I "un-maximize" the window, the issue disappears ; when I maximize it again, this issue doesn't come back (it does come back when I shut off Zettlr and launch it again in a maximized window).

**Comment by nathanlesage** [comment] 2019-05-09 08:54
Alright, that might actually be a first hint towards what is happening. I assume with "parent folder" you mean a root directory, i.e. the topmost hierarchical level?

Listen, I think I got an idea. I'll drop some `console.log` into the relevant functions that handle regenerating and displaying of the file list. Then, when the next beta comes out, I would like all of you who experience this problem to enable debug mode in the preferences and keep out an eye for those messages in the development console. I will post a comment here indicating when the console messages should appear, and how often they should appear. If they then appear according to a different pattern, we might have a fix on the problem!

**Comment by nathanlesage** [comment] 2019-05-09 09:11
So, here we go:

- `Refreshing File List ...` should appear when you select a new directory or something in the current directory changes. (Refresh = Rebuild the full list)
- `Generating File List Tags...` should be called by the refresh method. When this message appears, Zettlr will rebuild the full list as HTML tags.
- `Updating draggables ...` should be displayed more frequently: It will always be called when `Clusterize.js` renders a new block of files. This is necessary, so that jQueryUI can make these files draggable.
- `Selecting a file ...` should appear when the current file changes (it means: add the "selected" class to a file in the list). Sometimes it may also be called when the file list is rebuilt.
- `Scrolling a file into view at index ??? ...` should be called whenever the file list is rebuilt, or you change back into the directory where your current file resides. ??? should be replaced with the index (zero-based) of the file (including the directory tiles that appear in between the files!)

So I'll begin beta either tomorrow or next Friday, so then please make sure to check out the console messages in relation to this bug!

**Comment by mobamus** [comment] 2019-05-09 10:26
Yes, I’m happy to help and test that in next beta release!

For the time being, I can confirm the behavior @jlnbdt mentioned: problem is only in maximized window and disappears after unmaximizing.

**Comment by jlnbdt** [comment] 2019-05-09 11:55
> I assume with "parent folder" you mean a root directory,

Absolutely.

I'm happy to help too.

**Comment by nathanlesage** [comment] 2019-05-30 15:16
Anything new on this?

**Comment by mobamus** [comment] 2019-05-31 11:45
Hey! Sorry – i should set up an alert when there’s a new release. I didn’t notice.

I just tested with the different beta versions. A few observations I made are:
- Opening the developer’s console eliminates the flickering; so I guess, opening the console works in a similar way as un-maximising the program
- Reproducing this bug is a bit tricky and I can not quite recognize a pattern. When I first replaced `1.2.3` with `1.3.0-beta`, the bug was still there. Then I obviously did something, which I can’t remember, but after installing `1.3.0-beta.1`, the bug was gone. But when I replaced it again with `1.2.3` and then installed `1.3.0-beta.1` directly, without doing much else as opening and scrolling down, the bug was still there. So I guess, there are also some other methods to eliminate the behavior.

The Console output leads to the following: When I open one of the beta versions and the bug appears, the output hints to the `Updating draggables` function. Because it generates a very high number in a few seconds. Without the bug, I have a number of `4` or `7` at max. when scrolling down the list. But with the bug, i get something like `100` just in a few seconds.

I don’t know if this helps in any way. Is there something you want us to test more specifically?

**Comment by nathanlesage** [comment] 2019-06-01 13:28
> Without the bug, I have a number of 4 or 7 at max. when scrolling down the list. But with the bug, i get something like 100 just in a few seconds.

This sounds as if we‘re on to something! I‘ll have a look at the draggable updater, because maybe the problem is the interplay between jQueryUI and Clusterize! This is indeed a good start, as it‘s finally something concrete to work with :)

But of course please continue observing, but if this behaviour is consistent with the appearance of the bug, it could be the cause!

**Comment by mobamus** [comment] 2019-06-07 15:21
I've made a new observation: the bug only appears, if the file list shows "Additional information". If I toggle these info off and only have the single lined list, there is no flickering.

**Comment by nathanlesage** [comment] 2019-06-08 07:47
Ah hah! Okay, so this would indicate that it's indeed the sizing of the file items. As long as they are the same height, I was promised, everything is good, so either you've found a bug with Clusterize itself or a bug with the building of the items itself 🤔

**Comment by nathanlesage** [comment] 2019-06-18 21:24
Has the issue been resolved in 1.3?

**Comment by mobamus** [comment] 2019-06-19 10:46
No, it’s still present.

**Comment by nathanlesage** [comment] 2019-06-19 12:18
Damn. I'll continue!

**Comment by nathanlesage** [comment] 2019-06-19 15:33
I just got an idea of how to definitely pinpoint the issue!

@mobamus, @jlnbdt, maybe the following approach helps us decide whether or not jQueryUI is the culprit here:

1. Activate the debug mode
2. Open the developer tools
3. Run the following line of code in the console: `renderer._preview._updateDraggable = () => { }`. This will disable the drag-and-drop functionality of the files, which I am rather certain is causing the bug.
4. Test out, whether or not the bug persists.

If the bug is gone, we know that jQueryUI is the problem (or, hopefully, the method only).

(To restore the drag&drop-behaviour, simply reload the User Interface by pressing `F5` or clicking Develop -> Reload)

**Comment by nathanlesage** [comment] 2019-06-19 23:08
Okay that is bad, I mean seriously, but at least this proves jquerUI to be innocent. The question is still: what is the cause?

**Comment by nathanlesage** [comment] 2019-08-04 19:16
As the sidebar is now replaced with the new Vue-component, the bug should be gone. If it persists after 1.4, please notify me! :)

**Closed by nathanlesage** 2019-08-04 19:16 UTC
