### ISSUE TITLE
GRATITUDE: Thanks for Zettlr!

### ISSUE THREAD

**Issue by jcuenod** [Zettlr/Zettlr#113] opened 2019-03-02 17:28 UTC
I know that OSS dev work produces a lot of fatigue.
This project is awesome.
Thanks for all you're doing on it!

**Comment by nathanlesage** [comment] 2019-03-02 18:10
I'm glad to hear this! :)

(to be honest, I already experience some stress-related issues due to the past months of heavy development; but with most features implemented by now it's getting better and better, as there's not so much to be worked on, fortunately!)

**Comment by Jaifroid** [comment] 2019-03-08 07:49
It's a great project! But take it easy @nathanlesage . It's already really good. Slow and steady is better than fast and burnout!

**Comment by ploum** [comment] 2019-05-21 20:53
It seems you are everywhere (forum, bug request, twitter, development). How can we help you to make sure you enjoy it and continue developing it in the long term? I know by experience the open-source burnout syndrom ;-)

**Comment by nathanlesage** [comment] 2019-05-22 07:31
@ploum Ouh, I could tell you stories... But as mentioned in my comment from March 2nd, I'm already in the process of thinking about how to scale Zettlr to actually make a collective out of it. The problem until now was that there was not so much leverage of people who may be willing to participate. But with more and more people getting engaged I finally feel confident to do so. This is basically also why I've created a forum, to gather people who engage with the app and would be willing to lend a hand!

Therefore as soon as 1.3 is released, I'll make some announcements of how this whole project will get to the next level. But of course there's already need for help during the beta!

The main things one could help me by now as outlined in some of the forum posts are the following (for the 1.3 release):

- Do the colours and fonts match up in the three themes? What should be changed? (If someone would be willing to dedicate him/herself to this I'd gladly give some help for what to look out). Also please feel free to have a look at this forum thread: https://forum.zettlr.com/discussion/comment/16
- Someone with some experience could look into whether or not these two issues have already been fixed (or in the latter case finally localise the bug that's causing it): #134 and #107. Having these issues still open drives me crazy, because I can't reproduce them no matter what I do.
- Check all functionality and try to have fun with the app by deliberately trying to crash it =D
- And, most importantly, I would really appreciate it if **some people would have a thorough look on the [documentation](https://docs.zettlr.com/)**, because when I edited it last week to switch to MkDocs, I found so many so horrible mistakes I was ashamed that this was public for months! Besides, as I know exactly how the app works internally, many of the things I've written there were self-explanatory and therefore I think the educative factor of the documentation could certainly be improved for non-technical users!

So if you would like to lend a hand, every bit of help is greatly appreciated!

**Comment by Monolecte** [comment] 2019-05-22 07:49
What about translate the documentation?

**Comment by nathanlesage** [comment] 2019-05-22 09:00
Yes, this is a good idea. However, MkDocs still needs some time until they're implementing i18n support, so it has time. Besides, I would like to see the English documentation overhauled before we translate stuff that may then be outdated soon. This way we prevent everybody from doing superfluous work :)

So I'd say, first let's get to work on the English translation until we're happy with it, and then begin translating!

**Comment by nathanlesage** [comment] 2019-05-29 07:52
I'll finally close this issue to slim the issue list, but I'm still grateful for all your gratitude! <3

**Closed by nathanlesage** 2019-05-29 07:52 UTC
