### ISSUE TITLE
[Enhancement] Change keys for forward/backward action

### ISSUE THREAD

**Issue by nabusch** [Zettlr/Zettlr#2943] opened 2021-12-19 14:41 UTC
### Description

The most recent v2.1.0-beta version introduces a new feature: 

> "forward" and "back" actions, which are especially useful for people managing a Zettelkasten and frequently follow links: Now you can go back and forth between opened files (shortcuts: Cmd/Ctrl+[ and Cmd/Ctrl+]) so you can more quickly navigate your files.

This is a feature I have been waiting for a long time, so I am very happy to see that is is implemented now. However, the specific keys associated with these actions (left and right brackets) by default are not accessible with a single keystroke on some non-US/UK keyboard layouts. For instance, on my German keyboard, I have to press AltGr + 8 to get the "[" character. Apparently, Zettlr does not recognize CTRL+ AltGr + 8 as a keyboard shortcut for the "Back" action, and even then it would be kinda tedious.

Would it be possible to include an option in the settings allowing users to redefine the keyboard shortcuts for back/forward actions to something more suitable, e.g. CTRL + left/right?

### Proposed Changes

Include an option in the settings allowing users to redefine the keyboard shortcuts for back/forward actions to something more suitable, e.g. CTRL + left/right.

### Caveats

Can't think of a caveat right now.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Beta (if applicable)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment] 2021-12-19 15:35
Duplicate of #818

**Comment by nathanlesage** [comment] 2021-12-19 15:36
(Moved that up in priority)

**Closed by nathanlesage** 2021-12-19 15:35 UTC
Labels: enhancement
