### ISSUE TITLE
Version 3 Beta 4 (Linux inside ChromeOS) doesn't start

### ISSUE THREAD

**Issue by perekoo** [Zettlr/Zettlr#4377] opened 2023-05-27 07:56 UTC
### Description

I was able to install, launch and use version 2.30 on Linux (ChromeOS) without any problems. Beta 4 of version 3 (Zettlr-3.0.0-beta.4-arm64.deb) can also be installed, but not started. 

### Reproducing

Activate Linux system on ChromeOS. Download the above file and install it. On startup, an icon appears in the taskbar, but the application does not launch. The icon is grayed out und a circular progress indicator turns.

### Zettlr Version

Beta (if applicable)

### Specify version

Version 3 Beta 4 

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

ChromeOS 113

**Comment by lcsolano** [comment] 2023-06-09 17:58
This happened to me as well, as a workaound, chmod Zettlr executable to 755.

**Comment by nathanlesage** [comment] 2023-06-17 15:39
Duplicate of #4348

**Closed by nathanlesage** 2023-06-17 15:39 UTC
Labels: bug
