### ISSUE TITLE
The strike-through syntax doesn't work

### ISSUE THREAD

**Issue by 87113** [Zettlr/Zettlr#4263] opened 2023-04-12 20:05 UTC
### Description

Hi there, 
I found a bug since the first beta of Zettlr3 with the strike-through text ( like there : https://www.markdownguide.org/extended-syntax/#strikethrough ) 

### Reproducing

Example:

```
~~some text, should be striked~~  
Some ~~striked text~~ but not striked.   
```

In two world:

- when I put the ~~ around the text I want to strike
- it's not striked
- and the ~~ are still visible

Only if I put the cursor somewhere between the ~~ the text become striked. 

What I expect: 

- when I put a text between two ~~ 
- the text should be striked
- the ~~ should disapear when the focus is out like for bold or italic

### Zettlr Version

Beta (if applicable)

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.10

**Comment by lcsolano** [comment] 2023-06-16 14:57
I confirm this. It renders the text stricked-throuhg when clicking on it, instead of rendering it when is not clicked.

https://github.com/Zettlr/Zettlr/assets/19916268/3e54c9b3-09b8-4355-b21c-317e2716ca1b

**Comment by lcsolano** [comment] 2023-06-16 15:02
I confirm this in Zettlr-3.0.0-beta.4.nightly-amd64.deb. It renders the text when clicking on it and stops rendering when clicking anywhre else.

https://github.com/Zettlr/Zettlr/assets/19916268/73aad570-595b-4e73-8cef-fe0b6a2dcbc7

**Comment by nathanlesage** [comment] 2023-06-17 15:02
Can't reproduce in the current dev branch, therefore I'm closing this as fixed – it has been quite some time since the last beta, so it has likely been solved and will come with the next beta!

![image](https://github.com/Zettlr/Zettlr/assets/17251683/63f46a4e-019f-4147-8383-9db43b3e0e58)

**Closed by nathanlesage** 2023-06-17 15:02 UTC
Labels: bug

**Comment by 87113** [comment] 2023-06-19 08:17
Hi, 
I just install the beta5 (the .deb package) and I still get the bug :/ 

Here a little video capture : 

[Capture vidéo du 2023-06-19 10-16-35.webm](https://github.com/Zettlr/Zettlr/assets/102969362/bf623281-eb7f-4dd3-ad98-80543439faf8)

**Comment by lcsolano** [comment] 2023-06-19 15:58
I confirm it still doesn't work when installing from Zettlr-3.0.0-beta.5-amd64.deb


https://github.com/Zettlr/Zettlr/assets/19916268/365359c4-93d4-4a82-8e14-3df1a3b0fa2e

**Comment by nathanlesage** [comment] 2023-06-20 08:23
Ah wait, you have the emphasis renderer on, that explains it: The emphasis renderer is still broken, but dealt with in another issue, so the issue is in fact, correctly closed. Disable the emphasis renderer if you want to see the strikethrough.

**Comment by 87113** [comment] 2023-06-20 08:32
Ok, thank's for the tips. 

Do we need to open a new bug for the emphasis renderer?

**Comment by nathanlesage** [comment] 2023-06-20 08:41
> Do we need to open a new bug for the emphasis renderer?

No. As I said, there are various issues about that open already.
