### ISSUE TITLE
[FEATURE] Zettels net-like graphic

### ISSUE THREAD

**Issue by Porrumentzio** [Zettlr/Zettlr#2047] opened 2021-05-31 10:24 UTC
## Description
Add option to display a graphic with the net-like relations into each note/zettel, linking each note with lines to those which are linked into document (as Zettelkasten) and also displaying non existing but linked notes #2048 .
This is a feature [Obsidian](obsidian.md) privative program has, you can see there how it works for users.

## Example Workflow
As UI, there should be a button which clicking would display this graphic. There, each note would be displayed as a point (or so on) and clicking it would open the note to edit or view it. Keeping clicked some point/note on the graphic should highlight itself and its direct relations.

I don't know how to manage it about code.

**Comment by nathanlesage** [comment] 2021-05-31 18:06
Duplicate of #921

**Closed by nathanlesage** 2021-05-31 18:06 UTC
