### ISSUE TITLE
Zettlr 100% CPU render and interface freezed 

### ISSUE THREAD

**Issue by mbruyere** [Zettlr/Zettlr#1220] opened 2020-08-31 04:29 UTC
## Description

On opening Zettlr the interface freezed and the render thread goes to 100% CPU 

![image](https://user-images.githubusercontent.com/940315/91682610-1268de00-eb8d-11ea-9519-d406ef6ab1d9.png)

![image](https://user-images.githubusercontent.com/940315/91682704-5fe54b00-eb8d-11ea-94cd-7af94adb17e3.png)

## Reproducing

I supposed it could be a particular markdown file causing it, but I can not see which one Zetllr try to open/render.

## Expected behaviour

We can explect zettlr to just no freeze

**Screenshots**

Screenshot are above

## Platform
 - OS and version: macos 10.14.6
 - Zettlr Version: 1.7.5
 - Screen Resolution: dual screen : macbook display 2880x 1800 and 1280x 1024 (the one were Zettlr is opened)

## Additional information

Zettlr worked before without any issue.

**Comment by mbruyere** [comment] 2020-09-01 06:57
I will be please to provide a crash dump if necessary or conduct any debug. 
Please let me know  rapidly as I need to fix it on a way or another.

I need my Zettlr to work :-)

**Comment by nathanlesage** [comment] 2020-09-01 11:59
Please try to remove the `config.json` file (you can also rename it in case you want to restore it) from your user data directory and try to start the app. If that doesn't work, please try to completely uninstall and reinstall it. If that doesn't work, please try to reproduce the freezing behaviour.

**Comment by mbruyere** [comment] 2020-09-03 05:01
Remove the config.json and Zettlr worked as freshly installed. 

Will try now to reproduce the render freeze.

**Comment by moedn** [comment] 2020-10-21 10:12
Jepp, removing the `config.json` from a not-so-freshly installed instance solved the exact same issue for me.

**Comment by nathanlesage** [comment] 2020-10-21 11:55
@moedn Yes, sure. I suspect there might be an issue with non existing files and directories, which are still not removed on start up.

Just for scientific reasons: would you mind backing up that old config, then install the current alpha, and THEN booting it with this old, buggy config in the application data directory? Maybe it's either solved or we may get better output!

**Comment by moedn** [comment] 2020-10-30 10:30
Jo, this took a little longer, sorry. You have been faster releasing the 1.8.0-beta already :)

Anyway, I tested the old 'buggy' `config.json` with 

- `zettlr-1.8.0_alpha.3-1.x86_64` (Fedora 32)
  - no freeze!
- `zettlr-1.8.0_beta-1.x86_64`
  - no freeze!

Should I send you the `config.json` via email or so? Or can we see this issue as solved (at least for me) by the suggested workaround or the next update? :)

**Comment by nathanlesage** [comment] 2020-11-04 09:48
> no freeze!

Nice!

With regard to the config: You can just drop it in here using a block syntax highlighting (json I think, or js), and if you prefer, mask any private parts of the open paths.

**Comment by nathanlesage** [comment] 2020-11-04 09:48
(Closing so that it's off the list, but I'll receive comments! ;)

**Closed by nathanlesage** 2020-11-04 09:48 UTC
Labels: waiting for feedback

**Comment by moedn** [comment] 2020-11-04 09:56
:D alright

In the file it's all one line:

```
{"version":"1.7.5","openPaths":["/home/ruediger/Documents/Reformation/OSE Germany/[ OSEGeV Verein ]/Präsentationen Sammlung/DIN Innovationskonferenz - Messestand/00_READ ME FIRST.md","/home/ruediger/Documents/Reformation/OSE Germany/[ OSEGeV Verein ]/Präsentationen Sammlung/DIN Innovationskonferenz - Messestand/01_Fragensammlung Debatte.md","/home/ruediger/Documents/Reformation/OSE Germany/[ OSEGeV Verein ]/Präsentationen Sammlung/DIN Innovationskonferenz - Messestand/02_Visuelle Ressourcen & Ideen.md","/home/ruediger/Documents/git/admin/design_peer-review_document/design_peer-review.md","/run/media/ruediger/USB DISK","/home/ruediger/Documents/Reformation/IPS-Cloud/Klassenfahrt","/home/ruediger/Documents/Reformation/IPS-Cloud/OPEN!NEXT","/home/ruediger/Documents/Reformation/OSE Germany/Sammler","/home/ruediger/Documents/git/OSHI/illustrations","/home/ruediger/Documents/git/dr-moe"],"openFiles":[-92741401,-581168311,1768794233],"lastFile":-1575230255,"lastDir":420855805,"dialogPaths":{"askFileDialog":"","askDirDialog":"/home/ruediger/Documents/Reformation/IPS-Cloud/Klassenfahrt","askLangFileDialog":""},"window":{"x":0,"y":64,"width":1920,"height":1016,"max":true},"attachmentExtensions":[".pdf",".odt",".odp",".ods",".doc",".docx",".xls",".xlsx",".ppt",".pptx",".do",".r",".py",".sav",".zsav",".csv",".png",".jpg",".jpeg",".gif",".tiff"],"darkTheme":false,"alwaysReloadFiles":false,"autoDarkMode":"off","autoDarkModeStart":"22:00","autoDarkModeEnd":"06:00","fileMeta":true,"fileMetaTime":"modtime","hideDirs":true,"sorting":"natural","sortingTime":"modtime","muteLines":true,"sidebarMode":"thin","enableRMarkdown":false,"newFileNamePattern":"%id.md","newFileDontPrompt":false,"pandoc":"pandoc","xelatex":"xelatex","pandocCommand":"pandoc \"$infile$\" -f markdown $outflag$ $tpl$ $toc$ $tocdepth$ $citeproc$ $standalone$ --pdf-engine=xelatex --mathjax -o \"$outfile$\"","export":{"dir":"temp","stripIDs":false,"stripTags":false,"stripLinks":"full","cslLibrary":"","cslStyle":""},"pdf":{"author":"Generated by Zettlr","keywords":"","papertype":"a4paper","pagenumbering":"gobble","tmargin":3,"rmargin":3,"bmargin":3,"lmargin":3,"margin_unit":"cm","lineheight":1.5,"mainfont":"CMU Serif","sansfont":"CMU Sans Serif","fontsize":11,"textpl":""},"zkn":{"idRE":"(\\d{14})","idGen":"%Y%M%D%h%m%s","linkStart":"[[","linkEnd":"]]","linkWithFilename":"always","autoCreateLinkedFiles":false},"editor":{"autoCloseBrackets":true,"defaultSaveImagePath":"","homeEndBehaviour":true,"enableTableHelper":true,"indentUnit":4,"countChars":false,"inputMode":"default","boldFormatting":"**","italicFormatting":"_","readabilityAlgorithm":"dale-chall","direction":"ltr","rtlMoveVisually":true,"autoCorrect":{"active":false,"style":"LibreOffice","quotes":false,"replacements":[{"key":"-->","val":"→"},{"key":"–>","val":"→"},{"key":"<--","val":"←"},{"key":"<->","val":"↔"},{"key":"<-->","val":"↔"},{"key":"==>","val":"⇒"},{"key":"<==","val":"⇐"},{"key":"<=>","val":"⇔"},{"key":"<==>","val":"⇔"},{"key":"!=","val":"≠"},{"key":"<>","val":"≠"},{"key":"+-","val":"±"},{"key":":times:","val":"×"},{"key":":division:","val":"÷"},{"key":"<=","val":"≤"},{"key":">=","val":"≥"},{"key":"1/2","val":"½"},{"key":"1/3","val":"⅓"},{"key":"1/4","val":"¼"},{"key":"1/8","val":"⅛"},{"key":"2/3","val":"⅔"},{"key":"3/4","val":"¾"},{"key":"3/8","val":"⅜"},{"key":"5/8","val":"⅝"},{"key":"7/8","val":"⅞"},{"key":"mm2","val":"mm²"},{"key":"cm2","val":"cm²"},{"key":"m2","val":"m²"},{"key":"km2","val":"km²"},{"key":"mm3","val":"mm³"},{"key":"cm3","val":"cm³"},{"key":"ccm","val":"cm³"},{"key":"m3","val":"m³"},{"key":"km3","val":"km³"},{"key":":sup2:","val":"²"},{"key":":sup3:","val":"³"},{"key":":deg:","val":"°"},{"key":":eur:","val":"€"},{"key":":gbp:","val":"£"},{"key":":yen:","val":"¥"},{"key":":cent:","val":"¢"},{"key":":inr:","val":"₹"},{"key":"(c)","val":"©"},{"key":"(tm)","val":"™"},{"key":"(r)","val":"®"},{"key":"...","val":"…"},{"key":"--","val":"–"},{"key":"---","val":"—"}]}},"display":{"theme":"berlin","imageWidth":100,"imageHeight":50,"renderCitations":false,"renderIframes":true,"renderImages":true,"renderLinks":true,"renderMath":true,"renderTasks":true,"renderHTags":false,"useFirstHeadings":false},"selectedDicts":[],"appLang":"en-GB","debug":false,"watchdog":{"activatePolling":false,"stabilityThreshold":1000},"checkForBeta":false,"uuid":"9d45aaf1-9b5c-4598-b20a-8a904c0179c3"}
```

**Comment by nathanlesage** [comment] 2020-11-04 10:36
Found the error:

![image](https://user-images.githubusercontent.com/17251683/98100914-d35b4f80-1e91-11eb-9218-11ffac95794d.png)

Did you happen to modify the Pandoc command within the file itself? Because the quotation marks are not escaped, which causes the config file to fail to load.

**Comment by moedn** [comment] 2020-11-04 14:30
sharp eye!

Nope, I didn't touch the config file before and also did not modify the pandoc command in Zettlr.

**Comment by nathanlesage** [comment] 2020-11-04 15:30
> sharp eye!
> 
> 
> 
> Nope, I didn't touch the config file before and also did not modify the pandoc command in Zettlr.

Heh, rather a linter which immediately yelled at me that there was an error ;D

But it's good to know, possibly there was an error in one of the 1.7-patches where I accidentally made a bug …
