### ISSUE TITLE
Table creation unrecoverably deletes text

### ISSUE THREAD

**Issue by iron-beagle** [Zettlr/Zettlr#1208] opened 2020-08-22 03:16 UTC
## Description
When a table is created zettlr deletes the text and leaves no way to recover it.

## Expected behavior
Undo on table creation replaces the text previously in place.

**Screenshots**
![1](https://user-images.githubusercontent.com/33130592/90947181-e79abf00-e401-11ea-836a-2771bbe65426.png)
![2](https://user-images.githubusercontent.com/33130592/90947189-f1bcbd80-e401-11ea-96cb-1fc8ec5a2768.png)

## Platform
 - OS and version: Debian 10
 - Zettlr Version: 1.7.5
 - Screen Resolution:  3200x1800 pixels

## Additional information
I am using vim key bindings and have not tried undo in any other capacity.

**Comment by nathanlesage** [comment] 2020-08-24 08:51
Thanks for spotting this! This does not look good! Albeit I do not have an idea of how we can mitigate this problem, because I cannot think of any algorithm able to tell that this is not a table :S

**Comment by the-solipsist** [comment] 2020-08-24 11:37
I haven't noticed a problem during table *creation* per se, but multiple times I have lost text (Ctrl-Z doesn't recover the text) when editing tables.  I've noticed that this is more likely to happen if I am switching between windows (Alt-Tab-ing).  Not all the text disappears: only the text that I last added.  This has happened at least four or five times so far.  I'm sorry, but I'm not sure how to consistently reproduce it.

**Comment by Kangie** [comment] 2020-08-26 01:41
I actually encountered this recently with some HTML converted to MarkDown that went for Setext style headings, but couldn't manage to replicate the issue consistently enough to file a bug report! Thanks @the-solipsist.

**Comment by the-solipsist** [comment] 2020-08-26 09:55
I've also found that this happens when YAML uses `---` as the closing sequence rather than `...`.
Brief screen recording: https://imgur.com/a/qRP6jcA
(After the table gets created in the recording, I press `ctrl-z` twice. Funny thing is that each time I try to recreate this, `ctrl-z` has a different effect.)

**Comment by Kangie** [comment] 2020-09-08 05:47
+1 to getting this fixed promptly. 

I just lost a ton of content in a file I've been working on for a few hours to a table, and then while attempting to delete the table accidentally deleted the whole file by pressing the `delete` key (it triggered the 'do you want to delete this file' dialog and pressed enter because I expected the table to be gone and the need to insert some whitespace to fix my content).

To say that it's a little frustrating would be understating it.

**Comment by nathanlesage** [comment] 2020-09-09 14:26
If you have worked for hours on a table I'd say you're expecting more of Markdown tables than it can deliver. As stated in the docs, Markdown tables are only meant for a few pieces of information.

**Comment by Kangie** [comment] 2020-09-10 00:51
> If you have worked for hours on a table I'd say you're expecting more of Markdown tables than it can deliver.

I should have been more clear - the table insertion replaced a bunch of content that I was working on, and then I lost the rest of the file while attempting to delete the table using the `delete` and `enter` keys - I think I had a different part of the Zettlr UI selected than I thought.

Being able to hit `ctrl+z` to undo the table replacing body content would have been nice at the time!

**Comment by nathanlesage** [comment] 2020-09-10 13:39
I see the problem. A lot of stuff needs fixing, but this takes time (but thankfully the number of contributors rises steadily)

**Comment by nathanlesage** [comment] 2020-12-20 19:34
Should be fixed by now

**Closed by nathanlesage** 2020-12-20 19:34 UTC
Labels: bug [critical], confirmed, pinned, priority:high
