### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by bcdavasconcelos** [Zettlr/Zettlr#58] opened 2018-11-15 13:03 UTC
It would be lovely being able to access the side-bar with the keyboard (e.g. 'opt' + '←' and 'opt' + '→') and navigating articles with arrow up and down. Would it be possible?

Thanks :)

**Comment by nathanlesage** [comment] 2018-11-15 15:43
Very good idea, one I actually try to implement since months. The problem is: Zettlr actually once **had** keyboard navigation. But since I moved to clusterize.js for rendering the preview list, that feature broke. I hadn't had any luck restoring the support since. But it's still on my agenda, because it angers me as well!

Furthermore: Which sidebare do you mean? The attachment sidebar or the file list/tree view-sidebar?

So far, it sounds like a reasonable thing!

Cheers

**Comment by bcdavasconcelos** [comment] 2018-11-15 19:06
Hi Nathan!

I meant the file list side bar. But it would be great to be able to go either way. Left to ‘file view’ from the editor and right to ‘attachment bar’. Should it be possible to have another note on split view as well, that could also be in between and it would be awesome ;)

I am sorry to hear that this feature was lost and that you probably already had to go though a lot to get it back running again. Maybe there is workaround we could try as an alternative in the meanwhile? I was thinking perhaps a shortcut for next & previous article (going up and down in the list). It there was this item in the menu, we could simply set a shortcut for it.

Another cool idea that I've seen in other apps is triggering the table of contents pop-up via keyboard shortcut (e.g. cmd + 9) and navigating up and down using arrow keys and selecting the desired section pressing return. Although nice, maybe it is not worth it going through too much trouble to implement it.

**Comment by nathanlesage** [comment] 2018-11-22 10:41
Did some digging around in the source code and I managed to re-activate the arrow-key navigation.

Using the current dev build (and, probably tomorrow, the 1.0.0-beta.1 build) it should be possible to use the following keys to navigate:

- `Arrow Up`: Select the previous file in the list
- `Arrow Down`: Select the next file in the list
- `Cmd/Ctrl+Arrow Up`: Select the first file in the list
- `Cmd/Ctrl+Arrow Down`: Select the last file in the list

Unfortunately, initially you can't use the arrow keys due to some strange focusing that is happening, so you'll have to focus the preview list first by clicking on the upmost directory entry. Maybe I'll find out why this happens as well until 1.0!

**Comment by bcdavasconcelos** [comment] 2018-11-23 16:19
That is great new, Nathan. Thank you for looking into it.

**Comment by nathanlesage** [comment] 2018-11-24 12:33
You're welcome!

**Comment by bcdavasconcelos** [comment] 2018-11-24 23:47
I created a macro with shift + cmd + f and tab (x9) so now I can go directly to the articles list! :)
Also, I love the new text folding feature. It is a great one! (If there is there a keyboard shortcut for it, please let us know). Thanks again, Nathan!

**Comment by nathanlesage** [comment] 2018-11-25 09:03
Thanks! :)

There's no shortcut to trigger the text folding — would you like one? There's an option to define something like this, if I remember correctly …

(But this is a different issue, so I'm going to close this one here!)

**Closed by nathanlesage** 2018-11-25 09:03 UTC
