### ISSUE TITLE
Search Result Highlighting after a full-text search doesn't work properly.

### ISSUE THREAD

**Issue by passionate2023** [Zettlr/Zettlr#4053] opened 2023-01-15 09:55 UTC
### Description

The text highlight doesn't work properly. The text highlighted in the left and right is not appropriate. 

### Reproducing

Import the text files from zip
search for எழுப்புதல்

![image](https://user-images.githubusercontent.com/117767352/212534162-a2296d32-91b0-40f0-8ce8-6787784bf5f7.png)
[tamil message sermons txt files.zip](https://github.com/Zettlr/Zettlr/files/10419888/tamil.message.sermons.txt.files.zip)

### Zettlr Version

Stable (most recent version)

### Installation Method

None

### Your Platform

- [ ] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by exanrauzer** [comment] 2023-01-15 14:04
Confirmed on Windows 10 3.0.0 Beta. It is Tamil language, right?

**Comment by passionate2023** [comment] 2023-01-15 18:32
Yes, it is tamil language.

**Comment by passionate2023** [comment] 2023-01-15 18:33
Yes, it is tamil language.

**Comment by passionate2023** [comment] 2023-01-15 18:33
Yes, it is tamil language.

**Comment by nathanlesage** [comment] 2023-01-17 15:56
I cannot reproduce this behavior locally. Can you please do the following:

1. Close Zettlr
2. Relaunch it
3. Take notes of the EXACT steps, everything you are doing to perform a full text search that then fails to highlight in the document?

There is likely a certain set of steps necessary to make this bug appear.

**Comment by passionate2023** [comment] 2023-01-17 16:57
Case1: Failed
a. look for word எழுப்புதல் 
b. stop the search before completion
Issues on Case1
a. on clicking result, the highlight doesn't happen
b. search is very slow

Case2: Failed
a. look for word எழுப்புதல் 
b. let's wait until the search completes
Issues on Case2
a. on clicking result, the highlight doesn't happen
b. search is very slow

**Comment by nathanlesage** [comment] 2023-01-17 20:49
Thank you! Does it work if you switch both cases, i.e., if you first let a search finish and then try to see if the highlighting works?

Regarding the slowness: I'm aware of that, but I hadn't had any time to fix the search engine yet. Cannot give any ETA as well …

**Comment by passionate2023** [comment] 2023-01-18 15:50
In both the cases the highlighting doesn't work neither the cursor comes to the right position on the right hand side

**Comment by passionate2023** [comment] 2023-01-18 15:50
which database you are using to store the content? is the slowness is due to DB or code?

**Comment by nathanlesage** [comment] 2023-06-28 09:33
Still can't give an ETA, but I just saw that I needed to adapt the title of the issue to properly reflect what this is about.

**Comment by nathanlesage** [comment] 2024-10-29 08:25
I just tried it out and apparently it got fixed in the past 18 months.

**Closed by nathanlesage** 2024-10-29 08:25 UTC
Labels: bug
