### ISSUE TITLE
[Bug] Dark bars when using unordered lists

### ISSUE THREAD

**Issue by sith-on-mars** [Zettlr/Zettlr#2645] opened 2021-10-16 12:59 UTC
### Description

When inserting unordered lists, if the length of intent is six spaces or larger, the black bar will appear under the text. 
![image](https://user-images.githubusercontent.com/37974764/137588279-f28e84d3-5a2f-4785-af8d-a26c8b87c9e5.png)

### Reproducing

1. Insert `*` as an unordered list.
2. Type something after the `*` symbol.
3. Press the space key six times or more than six times to create intent.
4. The black bar appears.

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

OpenSUSE Tumbleweed

**Comment by Redsandro** [comment] 2021-10-16 22:18
Duplicate of #2637, fixed in #2641

**Closed** 2021-10-18 06:00 UTC
Labels: bug
