### ISSUE TITLE
Typewriter : keep the cursor at the middle of the page - hiding the top bar fullscreen

### ISSUE THREAD

**Issue by Ellipsine** [Zettlr/Zettlr#1197] opened 2020-08-16 19:15 UTC
Hi ! 
I use Zettlr for preparing my novels... And I would like to use it to write my novel because it has every features I need (export, tags, outlining tool...). 

However, the cursor stays at the bottom of my page, which is disturbing. I need to keep it at my eyes level to be comfortable to write. It is hard to keep my computer open for hours to work without comfort. 

**Is it possible to implement an option to keep the crsor at the middle of the page ?**

Typora, IA Writer, WriteMonkey or FocusWriter make it too  but they don't have the same features than Zettlr which is really a unique piece of software that I would love to use more and more. 

**I would like to have an option to hide the top bar while I am in distraction free mode (Cntr + J)**. In addition with the middle page cursor, the software would become perfect. 

Thank you and have a nice day !

**Comment by canpolat** [comment] 2020-08-16 20:17
This looks like a duplicate of #284

**Comment by Ellipsine** [comment] 2020-08-16 20:32
> 
> 
> This looks like a duplicate of #284

I am sorry, I am totaly new here, I was looking for "scrolling" and "type writing mode" but did not find this subject, thank you. Should I post my previous message in this issue ?

**Comment by canpolat** [comment] 2020-08-16 20:53
Not a problem at all :)

If you agree that what you suggest/request is already covered in that issue, I would suggest adding your contribution under that one. It looks like your request is twofold. One is related to the previously mentioned issue (#284). The other one is probably related to #939 and #191. It looks like these two are closed (I don't know why) .

I would suggest closing this issue, splitting the content into two and moving your comments under these other (older) issues (#284 and #939, respectively). Commenting under an already-closed issue sounds counter-intuitive, but does not mean that the comment will not be seen by the developer(s).

**Comment by Ellipsine** [comment] 2020-08-16 22:36
Thank you very much for your help ! :)

**Comment by canpolat** [comment] 2020-08-17 08:43
No problem :) Feel free to close this issue if you think it is no longer needed.

**Comment by nathanlesage** [comment] 2020-08-17 12:50
> Commenting under an already-closed issue sounds counter-intuitive, but does not mean that the comment will not be seen by the developer(s).

I do watch all notifications, and I generally approve people commenting under old closed issues, as re-opening them is much cleaner than opening blank new ones instead (because we retain the discussion history, etc.).

As to why the two issues mentioned are closed I do not know, but I aim to always give a reasoning for why I close issues, for instance this one, which I'll close for being a duplicate! ;)

**Closed by nathanlesage** 2020-08-17 12:50 UTC
