### ISSUE TITLE
[ENHANCEMENT]: Project Font Labels

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1345] opened 2020-10-12 05:18 UTC
## Description

The project font labels (for EN) in the Project Settings dialog are unclear. Update them to reflect what they actually impact.
## Proposed Changes

- Change "Main font" to "Body font"
- Change "Secondary font" to "Heading font"
## Caveats

Nil.

**Comment by nathanlesage** [comment] 2020-10-12 08:04
I just took the LaTeX variable names, so I'm unsure if we shall really change this or just provide the users with the "bleak reality" of LaTeX?

**Comment by Kangie** [comment] 2020-10-12 23:12
That's a good point; it's worth being consistent with LaTeX values.

It's not like it was particularly hard to work out what was changing based on the preview you've put next to the fields, I just thought it might catch people out as the labels aren't intuitive!

**Comment by nathanlesage** [comment] 2020-10-13 10:43
> I just thought it might catch people out as the labels aren't intuitive!

LaTeX in and for itself catches people 👀  I mean it's a valid point, but I'm unsure on how to proceed — just ignore it for now and see when we maybe even switch the PDF engine from LaTeX …? (There are some discussions simmering on the net that PDF creation might be better with smaller tools)

**Comment by Kangie** [comment] 2020-10-13 21:17
> LaTeX in and for itself catches people

Agreed, I'd be happy to leave it as-is with the preview TBH. 

> maybe even switch the PDF engine from LaTeX …? 

Interesting. I am working with a system that does continuous integration (builds documents on commit to repo), so it's useful for me to have something consistent across the board. If it's as customisable as LaTeX and easier to use, it might be another option! 

I'm interested in the discussion around this - right now LaTeX suits my needs and I'm doing a ton of templating using pandoc+latex for MarkDown content...

**Comment by nathanlesage** [comment] 2021-04-25 15:39
Short update: Since we've switched to defaults files which allow setting the fonts that way, the issue is no longer relevant, so I'm gonna close this one :)

**Closed by nathanlesage** 2021-04-25 15:39 UTC
Labels: pinned
