### ISSUE TITLE
Zettlr misinterprets some CSL-style files

### ISSUE THREAD

**Issue by arlawrence1545** [Zettlr/Zettlr#710] opened 2020-05-02 12:26 UTC
## Description
After choosing the CSL file, Zettlr appears to ignore it. I used MS Word to cross-check so I know it's not an issue with the file.

## Reproducing
I followed Zettlr Docs to the letter so I'm pretty sure I haven't done anything stupid... but how can one ever truly be sure?!

https://youtu.be/MSJGjzbDHhE

## Platform
 - OS and version: macOS Mojave v10.14.6
 - Zettlr Version: 1.6.0
 - Screen Resolution: 2560x1600

I have uploaded a [1 minute video](https://youtu.be/MSJGjzbDHhE) demonstrating the issue.

**Comment by nathanlesage** [comment] 2020-05-02 12:59
Hey,

thanks for notifying! And also thanks for the video, this makes understanding the problem much, much easier!

Unfortunately, I could not reproduce it here, as the development version does use the correct CSL-style file that I provide … hm. That leaves us with two possibilities I could think of: Either it's a bug in the 1.6, or it may be due to `pandoc-citeproc` …? If you're on the terminal, what does `pandoc-citeproc --version` spit out? For me it's version `0.17`. Furthermore, did you in any way modify the `pandoc`-command in the advanced settings?

Cheerio!

**Comment by arlawrence1545** [comment] 2020-05-02 13:20
Dude,


Thank you so much for writing! Pandoc version came out as:


pandoc-citeproc 0.17

Didn’t modify pandoc command in advanced settings, either.

Is there anything else I can do? It’s not a matter of urgency on my part
but it’d be nice to fix it for the sake of the application. Which is
awesome, by the way!

Adam

**Comment by nathanlesage** [comment] 2020-05-02 14:29
Alright, thanks for your very quick checking! Now, another thing we might want to check is: Do all the CSL-files come out the same? So, if you just try out a number of these — do all of them result in the same citations?

If yes, we have to go look deeper, but if no, it might very well be resolved by simply downloading the CSL file again. FYI: Word uses the CSL-files shipped with Zotero, and these are different ones than the ones Zettlr uses, so this would at least explain the difference in looks and feel!

**Comment by arlawrence1545** [comment] 2020-05-02 15:27
I'm afraid the answer is 'yes'. They all came out the same way.

**Comment by nathanlesage** [comment] 2020-05-02 15:55
That is not good, but I don't have a good explanation for that … mhhhh … would you just out of curiosity mind to "reset" the pandoc command in the advanced settings and try that …?

**Comment by arlawrence1545** [comment] 2020-05-03 03:33
First off, I made a mistake. Apparently, they do **not** all come out the same way. I was tired last night so I tried a few at random. Though many _do_ come out as APA, many of them work just fine. Genuine apology for having messed up on this one. Nobody wants to be that guy. As penance, I recorded [a second video](https://youtu.be/P0t6hFF5QQc) trying every single CSL file. It's a riveting watch. Hope it goes viral.

So... Zettlr is **not** ignoring CSL files. It's just picky. I'm currently trying to figure out why.

**Comment by nathanlesage** [comment] 2020-05-03 09:04
> Genuine apology for having messed up on this one. Nobody wants to be that guy.

Easy, I wasn't in the best mood yesterday either, it's the weekend either way! ;D

![image](https://user-images.githubusercontent.com/17251683/80909910-54dbf480-8d2c-11ea-82ab-0f1c2b9ed74a.png)

"… the SEQUEL"!

So but it does look interesting — I mean after all, while many styles do look similar, it does in fact look a little bit too similar. I still can't reproduce this issue, BUT I have now done what I wanted to do either way: A full log output that logs the fully resolved pandoc command that will actually be run:

![image](https://user-images.githubusercontent.com/17251683/80910138-cb2d2680-8d2d-11ea-9295-9cc2eea6653a.png)

So let's see how it goes in the beta!

**Comment by nathanlesage** [comment] 2020-06-18 19:46
I'll quickly assume this as resolved, right?

**Closed by nathanlesage** 2020-06-18 19:46 UTC
