### ISSUE TITLE
[Feature] Remember the state of file manager

### ISSUE THREAD

**Issue by donmor** [Zettlr/Zettlr#2901] opened 2021-12-08 14:21 UTC
### Description

The file manager (left sidebar)
Every time I start the program, it opens file manager automatically, discarding the state when closed last time.

### Proposed Changes

So it'll be great to see that show/hide state of the file manager is remembered and applied to the program next time it is started. If it was remained opened on quit, then it should be opened the next time, otherwise it should be hidden.

### Caveats

It might depress some people that wish to see the file manager every time. Also there could be some people who hate that. Thus it is necessary to make a new item in preferences with some kinds of options like [On], [Off] and [Last time].

### Do you Wish to Attempt Implementing this Yourself?

Yes

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Ubuntu 20.04 LTS

**Comment by nathanlesage** [comment] 2021-12-08 22:03
Duplicate of #1039

**Closed by nathanlesage** 2021-12-08 22:03 UTC
Labels: enhancement
