### ISSUE TITLE
[Bug][2.x Beta] Dialog for "..modified remotely" pops up all the time despite no remote modification

### ISSUE THREAD

**Issue by BabakFarshchian** [Zettlr/Zettlr#2357] opened 2021-08-26 05:01 UTC
### Description

I have all my files locally on my computer, and they are not changed remotely by any other application. However, every time my changes are saved a pop-up window tells me the file has changed remotely and whether I want to reload it. When I reload the file, the file has the latest edit I had, so I don't loose edits. But it is quite annoying.

This seems to happen for long files only, files longer than 1900-2000 word. I have not managed to reproduce it with shorter files up to 1700 words. But it happens continuously when files start getting big. It might be a time-related issue. Do you check file timestamp during saving?

### Reproducing

It reproduces more often (not always) the larger the files get. It happens both when autosave is on and when it is off. 

### Zettlr Version

Beta (if applicable)

### Specify version

Lates, 2.0.0 Beta 3

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

### Additional Information

I did not have large files while I was using earlier versions, so I am not sure whether this is related to the 2.0 beta or it also existed in the earlier versions.

**Comment by nathanlesage** [comment] 2021-08-28 10:16
We have had this issue pop up multiple times. There is a setting I implemented in the (advanced) settings to crank up the watchdog polling interval, because sometimes the internal file watcher might get triggered by Zettlr's _own_ file writing, if it takes too long (older HDDs, for example). You can push this up to 5 seconds and it should still work perfectly.

I should note that the file watcher only has 5 seconds of delay on macOS, so maybe that's why it's not a problem for me …?

Do you have any background processes (I'm looking especially at OneDrive since that causes a lot of problems) that might touch the files? In other words: Can you reproduce this behavior if you just create some random test folder in your Documents and edit files in there using Zettlr?

**Comment by BabakFarshchian** [comment] 2021-08-29 05:38
I started to crank up the interval. The issue seems to resolve, for now in a file of approx, 3700 words. Thanks for the tip Hendrik! Now I am back at my writing and enjoying Zettler.

For the sake of documenting: I am using a quite modern (2 years old) Lenovo X1, one of Lenovo's top models from 2-3 years ago. It has an SSD drive. All the files are on my local drive, with no connection to any cloud service. I have a background app that takes backups twice a day.

**Comment by nathanlesage** [comment] 2021-08-29 16:44
Hm, if it's only resolved with a 6s delay (I hope you restarted the app whenever you changed that, since a restart is required…?) this speaks for something writing to the file after 5seconds. And 5s is the autosave-delay of Zettlr. But that's not the cause as we have seen …

**Comment by BabakFarshchian** [comment] 2021-08-30 06:06
Yepp, you nailed it. The restart thing...:-)

I did not do the restart.

Now I am down to 2 secs. Did not go below. Things seem to work now. Thanks!

**Comment by nathanlesage** [comment] 2021-09-25 16:09
Closing as it seems fixed. I also fixed the jumpy text issue, so probably this won't be a problem anymore!

**Closed by nathanlesage** 2021-09-25 16:09 UTC
Labels: bug
