### ISSUE TITLE
Links render wierdly when in lists.

### ISSUE THREAD

**Issue by Chuhtra** [Zettlr/Zettlr#1541] opened 2020-12-20 00:50 UTC
## Description

When adding a list to the markdown file, and a bullet has a link, the link is rendered under the bullet instead of next to it.

## Reproducing

Start a list like:

- one
- two
- etc.

Add a link to the list, like:

- one
- two
- etc.
- [three](www.google.com)

See the rendering.

## Expected behaviour

Link should be aligned in the same line as the bullet, as every other list item.

### Screenshot 1
![image](https://user-images.githubusercontent.com/40795688/102702622-88dd3900-426d-11eb-92ee-fdfff6ae7b35.png)

### Screenshot 2
![image](https://user-images.githubusercontent.com/40795688/102702631-9692be80-426d-11eb-97d2-24a6e89b4975.png)

### Screenshot 3
![image](https://user-images.githubusercontent.com/40795688/102702636-a4e0da80-426d-11eb-9b37-1e3dcee74754.png)

### Screenshot 4
![image](https://user-images.githubusercontent.com/40795688/102702645-b32ef680-426d-11eb-8786-8277e64688ef.png)

### Screenshot 5 (with typewriter mode enabled)
![image](https://user-images.githubusercontent.com/40795688/102702676-f4270b00-426d-11eb-95ae-6a748866476f.png)

## Platform
 - OS and version: Manjaro Linux
 - Zettlr Version: 1.8.2

## Additional information

--

**Comment by Kangie** [comment] 2020-12-20 09:22
It appears that you're inserting an emoji (🔗) inline with content. You haven't provided this in your example here and it took me a while to work it out.

If I attempt to insert that emoji, my Zettlr replaces it with a tofu glyph instead (which is properly aligned). I don't feel like messing with my Zettlr fonts right now, so I'm going to leave it at that, but I'd like you to try a few things:

- Insert the emoji outside 🔗[your link](http://google.com)
- Don't use an emoji.

**Comment by Chuhtra** [comment] 2020-12-20 13:01
>  but I'd like you to try a few things:
> 
>     * Insert the emoji outside link[your link](http://google.com)> 
>     * Don't use an emoji.

I didn't think of that distinction since the result is the same in my Zettlr regardless of the emoji. Be it there or not, in or out of the link, emoji or simple text, the link is always rendered under the bullet when it shouldn't.

![image](https://user-images.githubusercontent.com/40795688/102713930-3c791400-42d4-11eb-8c6d-c7fe072d4bc4.png)

**Comment by boutil** [comment] 2020-12-21 13:33
I think the bug you experience is a duplicate of #1514 #1517,  #1519.
It has been fixed in v1.8.3. Please upgrade to version 1.8.3 and check whether the problem has disappeared or not.

**Comment by nathanlesage** [comment] 2020-12-22 19:32
@boutil is right here!

**Closed by nathanlesage** 2020-12-22 19:32 UTC
