### ISSUE TITLE
[Bug] All BETA Versions File manager not working: new files are not shown until I quit and start again the program

### ISSUE THREAD

**Issue by vsanchez** [Zettlr/Zettlr#2365] opened 2021-08-29 01:26 UTC
### Description

I have hesitated to create this Bug Report because a problem this serious, happening since the first beta, I found it hard to believe it was not posted before. But I cannot find it. The problem is the following: 

1. Create a new file under a workspace or directory. I normally use the default ID. 
2. The file opens and I can work it, etc. But I cannot see it in the file manager. I need to reboot the program in order for it to show. Same thing if renaming, the old name will still show, as if the file manager is never refreshing.
3. It happens with all Beta versions (1 to 3) in both Windows and Linux. 
4. It happens regardless of the configuration of the file manager. In general, the file manager is hard to navigate, sometimes not allowing changes in directories, etc.
5. I do use 3 workspaces, for what it's worth, and the files are in a dropbox synced directory. Both the windows machine and the Linux machine work on the same directory. 

### Reproducing

1. Try to create a file. The file will be created and can be modified and saved, but it will not show in the file manager until a reboot is done.
2. Other weirdness navigating the file manager, but not that clear.

### Zettlr Version

Beta (if applicable)

### Specify version

1, 2, 3

### Your Platform

- [X] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Kubuntu 21.04 latest KDE, Windows 10

**Comment by nathanlesage** [comment] 2021-08-29 16:48
It could be that the file cache is acting up. Would you mind quitting the app and then removing the complete `fsal`-directory from the application data directory? Then the app will recreate that cache and that might help. If not, it would be awesome if you could try to create a file and then share the logs (to see the logs, activate debug mode in the preferences and then use the "Open logs" item in the Develop-menu).

**Comment by vsanchez** [comment] 2021-08-29 20:00
Hi Nathan,

Interesting: clearing the fsal directory did not help neither in windows or Linux. The interesting part of the log (this is the Linux side):

[14:50:51] [Warning] [R] [Main Window] Was about to add descriptor /home/victor/escritos/ZKM_Cocina/Datos generales/20210829144953.md to the filetree, but the parent /home/victor/escritos/ZKM_Cocina/Datos generales was null! (index.js:2)
[14:50:51] [Error] [R] [Main Window] TypeError: Cannot set property 'dir' of null (index.js:2)

This has happened in two of the workspaces but in the first, the system works well. 

Trying to rename folder "Datos generales" thinking that something was wrong then gave me a similar error higher up:
[14:55:58] [Warning] [R] [Main Window] Was about to add descriptor /home/victor/escritos/ZKM_Cocina/DatosG to the filetree, but the parent /home/victor/escritos/ZKM_Cocina was null! (index.js:2)
[14:55:58] [Info] [WATCHDOG] Ignore event: unlink:/home/victor/escritos/ZKM_Cocina/Datos generales/20210217225208.md

(I tried changing "Datos Generales" to "DatosG")

Closing all other workspaces and leaving ZKM_Cocina by itself then everything seems to work. So there is nothing wrong with the directory. When I had 3 workspaces open, things will work fine in the first one only.

**Comment by noah-arroyo** [comment] 2021-08-29 20:10
I'm experiencing this bug as well, on 2.0.0-beta.3 / Windows 10.

I tried deleting `fsal` directory but it didn't fix.

**Comment by noah-arroyo** [comment] 2021-08-29 20:30
I've discovered another potential aspect of this bug:

If I have Zettlr running, and I delete a note/.md file in Windows Explorer, then that note file will not immediately disappear from Zettlr's file manager. (If I `left-click` the deleted file's name, it will not open.)

If I close and then restart Zettlr, then the file will be gone from the file manager.

**Comment by vsanchez** [comment] 2021-08-29 20:55
Hi Noah, I am curious, do you have more than Workspace open? Is the problem only in the workspaces after the first one?

**Comment by noah-arroyo** [comment] 2021-08-29 21:23
!

Very interesting. I've just closed all three of my workspaces and re-opened them. The bug is gone. In each workspace, newly created files appear immediately in the file manager and when I delete them in Windows Explorer (while Zettlr is running) they immediately disappear from Zettlr's file manager.

**Comment by vsanchez** [comment] 2021-08-30 00:44
Hmm, closing all the workspaces did not work for me. Closing the 3 workspaces and then opening them again, presented the same problem. One thing, however, the workspace that "worked" again, was the top one, *which is not the one I opened first*! It is the top because of the sorting order.

**Comment by nathanlesage** [comment] 2021-08-30 11:36
Hm, might be eventually symlinks or other weird files that cause Zettlr to experience a hiccup. And, regarding the "close everything and reopen"-fix, maybe I'm still missing a few migrations from the 1.8.9 to the 2.0.0 line …

**Comment by vsanchez** [comment] 2021-08-30 12:37
Hi Nathan,

I suspected at first problems with symlinks, but It does happen regardless if I go directly to the workspace or use a Symlink.  I also checked permissions, etc. And the fact that if loaded alone make them work seems to rule out that.  In any case, I understand my setup is complex. I gather you have not been able to replicate this problem? 

In any case, I did a clean install, erased the .config/Zettlr directory and loaded a workspace (ZKM) and created a new file without problems. Then added a second workspace (ZKM_Cocina) and created a new file and the bug showed up. I closed everything, and are putting the log file if it helps.... in this case, having 2 workspaces showed the bug.

At least I know I can work in the meantime with a single workspace, until you figure it out. I am totally at lost running electron apps, i have tried to clone the repository and try to do a local install without luck, so far :-( so I cannot help in that regard.

[2021-08-30.log](https://github.com/Zettlr/Zettlr/files/7076697/2021-08-30.log)

**Comment by nathanlesage** [comment] 2021-08-30 13:25
> I gather you have not been able to replicate this problem?

Unfortunately not. Since I use Zettlr myself every day, I tend to fix all bugs I encounter immediately, so as a default you can be certain that any new bugs that get reported are unreproducible for me :(

**Comment by vsanchez** [comment] 2021-08-30 13:36
Just closing the window (by minimizing it) would not fix the problem, but I do not know if that will force a refresh of the window. You must quit and start again. This in Linux, KDE, X11.

**Comment by nathanlesage** [comment] 2021-09-02 16:24
> Just closing the window (by minimizing it)

Closing ≠ minimizing. What you can do is activate the setting to keep Zettlr running in the tray, THEN close the main window, and use the tray icon to re-open it. Alternatively, you can activate the debug mode and then reload the main window.

**Comment by vsanchez** [comment] 2021-09-05 19:06
Sorry, did not know you could keep it running in the background. Anyways, it did not work... just closing the window and make it show again did not update the file manager view. I had to quit the program and start again.

**Comment by nathanlesage** [comment] 2021-09-09 15:25
Then I'll have a look at this issue again. As always, any more hints are always welcome!

**Comment by vsanchez** [comment] 2021-09-18 19:26
Hi Nathan, I am sorry but I have been somewhat disconnected. I can confirm it happens also in Beta 4 again in both Linux and Windows. I am looking at debugging tools to see if I can find out anything else... is always worrying when the main developer cannot replicate the bug, an apparently only a minority seem to have the problem. I will keep you posted.

**Comment by vsanchez** [comment] 2021-09-18 23:22
Well, I am starting to learn how to use the Chrome Devtools. I know this is not the cause of the bug (it always happens, regardless of the bug is triggered or not) and it comes from Electron packages and not from you, but I keep finding these error messages in the area where the bug happens, so it may be file corruption in some platforms. I am just letting you know, in case this can cause other types of problems.


Failed to decode downloaded font: file:///opt/Zettlr/resources/app.asar/.webpack/renderer/3f5da30f833016202b1e.woff
6
OTS parsing error: invalid sfntVersion: 1836016757
3
Failed to decode downloaded font: file:///opt/Zettlr/resources/app.asar/.webpack/renderer/3209557d68df4a11be08.woff

**Comment by vsanchez** [comment] 2021-09-18 23:22
### Regarding the problem at hand:  

I have a Workspace "ZKM" that works well and another "ZKM_Cocina" that does not. The problem gets flagged at `addTooFileTree`. The call looks fine, the arguments sent are ok (the hashes for the workspaces are right).

Looking at the `e.fileTree` structure, at least in the top part I do not see anything strange:

For the one that works:

> attachments: Array(0)
> children: Array(14)
> creationtime: 1609542634906.4336
> dir: "/home/victor/escritos"
> dirNotFoundFlag: undefined
> hash: -2108376608
> icon: null
> modtime: 1631135207616.452
> name: "ZKM"
> parent: null
> path: "/home/victor/escritos/ZKM"
> project: null
> size: 0
> sorting: "name-up"
> type: "directory"

For the one that does not work (except that the children array is missing all the new files, which will get added only by restarting the program):

> attachments: Array(1)
> children: Array(5)
> creationtime: 1609688140520.6145
> dir: "/home/victor/escritos"
> dirNotFoundFlag: undefined
> hash: -1347427740
> icon: null
> modtime: 1631992609251.46
> name: "ZKM_Cocina"
> parent: null
> path: "/home/victor/escritos/ZKM_Cocina"
> project: null
> size: 0
> sorting: "name-up"
> type: "directory"

When adding to the last workspace, with a correct hash, the function `n = h(r, e.fileTree);` returns "null" while in the other case, it returns the appropriate fileTree branch. I see you seem to do a full sanity check, etc which I have not been able to follow (JavaScript is new to me and this web architecture also).

**There is something different in the way the `addTooFileTree` is called: when inserting in the "good" workspace the function is called as soon I create the file, when doing it in the "bad" workspace, creating the file does not call it until I add something and save the file** So maybe there is a problem with an event trigger...

If you have any suggestions on what to do, let me know.

**Comment by nathanlesage** [comment] 2021-09-18 23:46
> There is something different in the way the addTooFileTree is called: when inserting in the "good" workspace the function is called as soon I create the file, when doing it in the "bad" workspace, creating the file does not call it until I add something and save the file So maybe there is a problem with an event trigger...

That sounds like a good pointer. Until I can replicate the bug, I'm a little bit lost still, but if you're willing to:

The `n = h(r, e.fileTree)` is actually compiled code; that is: code that is essentially hard to decipher. But if you run Zettlr from the develop branch (after setting everything up), you will instead of this n, h, r, and e letters, see the actual function names. If you could give me these then I'll have a closer look at these specifically and try to find out what could be happening.

**Comment by vsanchez** [comment] 2021-09-19 01:59
:-) Well that shows my ignorance! I was seriously worried about your choice of function names :-) 

I managed to run it in uncompiled form. Much clearer.... Let me look around and I will let you know.

**Comment by vsanchez** [comment] 2021-09-19 02:53
Ok, this may be the problem, the first Workspace is ZKM, which works fine,  the 3 one, the one that gives mi problems, is ZKM_Cocina. They are in the same directory. Look at the `findPathDescriptor`:

> function findPathDescriptor (targetPath: string, tree: any, treatAsAttachment: boolean = false): any|null {
>   const prop = (treatAsAttachment) ? 'attachments' : 'children'
>   // We need to find a target
>   if (Array.isArray(tree)) {
>     for (const descriptor of tree) {
>       if (targetPath === descriptor.path) {
>         // We have the correct element
>         return descriptor
>       } else if (targetPath.startsWith(descriptor.path) && descriptor.type === 'directory') {
>         // We have the correct tree
>         return findPathDescriptor(targetPath, descriptor[prop], treatAsAttachment)
>       }
>     }
>  

When it iterates to look for "ZKM_Cocina" it appears to search sequentially, so the first one it checks is "ZKM", of course, if fails in `if (targetPath === descriptor.path)` but then it asks ` } else if (targetPath.startsWith(descriptor.path) && descriptor.type === 'directory') {`
and since it starts with "ZKM", `targetPath.startsWith(descriptor.path)` is true and it returns that right away providing the "ZKM" entry, which is the wrong entry.  So the problem may be related to the names of the workspaces and then you may be able to replicate the problem. Why do check if it startsWith?

**Comment by nathanlesage** [comment] 2021-09-19 20:22
Huh… so the reason why I've implemented the `startsWith` is because whenever Zettlr is searching the file tree for some descriptor there is a clear hierarchy (any children's path will start with its parent full path). We could make that more explicit. But the logic is pretty fragile, I need a day of peace to actually think about what changing `startsWith` to `dir === ` would entail.

But it's good that we now know that there is this bug. If someone has the time and mental peace to check the code against this (wrong) behavior, please feel free to open up a PR!

**Comment by vsanchez** [comment] 2021-09-19 20:48
I was looking at the delete problem and I see why you need it there. But it seems you must check if the "startsWith" includes a proper "path" and not just  the starting substring:

/home/ZMK/ should not match /home/ZMK_Cocina/ because it is not really a propper sub path.  When deleting a file, you are looking for the holding directory (it looks like) but again it should look for a full path not any initial substring... 

I am trying to find startsWith and take a look, but I guess OS definitions of paths may become a problem... but again all this is new to me.

**Comment by vsanchez** [comment] 2021-09-20 03:05
I could not create a proper development environment in windows, but I could create a package from Linux so I could try it. It seems to work, so I added a Pull Request for you to try.

**Comment by nathanlesage** [comment] 2021-09-20 11:43
Yeah I think it might make more sense to use Node's PATH library to do so. Instead of simply querying `startsWith` we could see if the `dirname` of the descriptor.path (that is: descriptor.dir) works. I'll have a look at the PR.

**Comment by nathanlesage** [comment] 2021-09-25 15:59
Hah, just realized that we just fixed that bug thanks to your PR! :)

**Comment by ranoano** [comment] 2022-02-23 13:21
Hi,

I have the same issue, newly created files not displayed until restart with a similar error message ( see attached image).

Version 2.2.3 installed via homebrew on macos monterey / arm64.

I'm not familiar with Electron / Java Script to debug it.

Any hints what I can do to solve it ?

Regards.

<img width="859" alt="image" src="https://user-images.githubusercontent.com/6292830/155326683-dbe5966c-ba9d-402b-a76b-661aa9c67d2d.png">

**Comment by nathanlesage** [comment] 2022-02-25 11:05
Just found out something super weird: When we create a file either utilizing the file manager (right click --> new file) *or* by creating the file from within a different program altogether, the changes are recognized, but *not* when we are creating the file from the file-new command, and I have no explanation for that. The watcher simply never emits an event for that newly created file.

**Closed** 2022-02-25 11:34 UTC
Labels: bug
