### ISSUE TITLE
[Bug] Unable paste formated text from Word

### ISSUE THREAD

**Issue by LegonEtp** [Zettlr/Zettlr#3053] opened 2022-01-17 00:17 UTC
### Description

In previous versions I could paste formatted text from Word into Zettlr with the formatting preserved. Now CTRL+V pastes plain text!

### Reproducing

Copy text from Word and paste it in Zettlr.

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by leo-hstone** [comment] 2022-01-18 12:19
I can't reproduce this. I tested it with these lines in word:

![image](https://user-images.githubusercontent.com/62036826/149935913-86127fe7-51d0-454d-a1ea-7f2ef24c9e33.png)

Selecting, CTRL+C => CTRL+V pastes into zettlr:

```
# I am a Heading

Hi! I am **fat** and I am _italic_
```

Using 2.1.2 on Windows 10

**Comment by nathanlesage** [comment] 2022-01-29 18:38
Closing as unconfirmed. I will get a notification if someone comments here with more info and then will immediately reopen it.

**Closed by nathanlesage** 2022-01-29 18:38 UTC
Labels: bug
