### ISSUE TITLE
[ANNOYING BUG] Link insert doubles link ending

### ISSUE THREAD

**Issue by Lzgief** [Zettlr/Zettlr#1636] opened 2021-01-16 12:37 UTC
## Description

When applying link insert through link starting and choosing any link, at the end of ID link ending is doubled.
looks like "[[ID]]]] Filename"
It also causes trouble when link start/end uses the same symbol like '!'

## Expected behaviour

It should end link with one link ending after ID as it used to be.

## Platform
 - OS and version: Linux 5.10.7-arch1-1
 - Zettlr Version: zettlr-bin 1.8.5-1

**Comment by boutil** [comment] 2021-01-18 08:36
I am experiencing the same issue. It is still present in 1.8.6 (.deb package).

**Comment by nathanlesage** [comment] 2021-02-08 13:34
Duplicate of #1708

**Closed by nathanlesage** 2021-02-08 13:34 UTC
