### ISSUE TITLE
fuzzy interface

### ISSUE THREAD

**Issue by RaidOpe** [Zettlr/Zettlr#2869] opened 2021-11-28 08:38 UTC
### Description

In Windows20H2 version, 2k resolution 125% magnification, zettlr does not run normally, it has the problem of fuzzy interface, and it is installed into A “windowfx” software, but I quit this software, there are still problems

### Reproducing

Whenerver I start it.

### Zettlr Version

Stable (most recent version)

### Specify version

2.03 .1.89 V there is no such this problem

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

20H2

### Additional Information

NO IMFORMATION

**Comment by nathanlesage** [comment] 2021-11-29 09:36
Do you have a few screenshots outlining this problem?

**Comment by RaidOpe** [comment] 2021-11-29 11:25
Greetings, I tested the following from my friend's computer. His configuration is 2K resolution, 21h1 home version, 64 bit Windows. There is no fuzzy problem on his computer. It is very likely that Zettlr is incompatible with the window  beautification software developed by Stardock. If I have free time, I will try to uninstall and test Zettlr , It is suggested that you can download and test whether there are fuzzy problems. This software has a 30 day trial time.
![2021-11-29_184948](https://user-images.githubusercontent.com/95146386/143859711-a88d9a0e-6df3-44fa-8bbd-394bc2551743.png)
![2021-11-29_185057](https://user-images.githubusercontent.com/95146386/143859728-34ccc522-6ec1-47f7-b241-cf207989f8f2.png)
![2021-11-29_185036](https://user-images.githubusercontent.com/95146386/143859735-48cc5634-63a1-4872-aa94-43e044d4dc3d.png)

**Comment by nathanlesage** [comment] 2021-11-30 17:46
Just had a look at the software you were mentioning, and I'm pretty sure that indeed that might be the cause. Since there seems to be incompatibility between the base Chromium rendering engine and whatever this software does, I'm going to close it since that's out of my league. If you can consistently reproduce this on any electron app, feel free to directly open a bug report against the https://github.com/electron/electron main repo.

**Closed by nathanlesage** 2021-11-30 17:46 UTC
Labels: bug
