### ISSUE TITLE
[BUG] Pasting words with hyperlinks or italics removes the space around them

### ISSUE THREAD

**Issue by b4nn** [Zettlr/Zettlr#820] opened 2020-05-18 21:38 UTC
## Description

When copying a html text with hyperlinks and italics, pasting it to Zettlr removes the spaces before and after the word that is linked or italicized.

**Screenshots**
![image](https://user-images.githubusercontent.com/65569952/82262208-63472480-9958-11ea-8c89-e44ff347f84b.png)

## Platform
- OS and version: win32 10.0.18362 (architecture: x64)
- Zettlr Version: v1.7.0-beta.5
- Chrome 81. The issue doesn't appear when using Firefox and Edge.

**Comment by nathanlesage** [comment] 2020-05-19 06:49
Did you paste that whole paragraph or just the link itself?

**Comment by b4nn** [comment] 2020-05-19 10:14
Hi Hendrik, I'm pasting a whole paragraph with links and italics used within it as you can see on the screenshot above. I'm getting this issue on Chrome 81. It works ok when using Firefox and Edge.

**Comment by nathanlesage** [comment] 2020-05-19 10:53
The problem is actually that this is being caused by a bad interplay between an external library we use for this (Joplin-Turndown) and the way Chrome formats its HTML copies. So I am in fact not sure what we could do here to mitigate that …

**Comment by nathanlesage** [comment] 2020-05-31 15:09
I'll close the issue here and would like you all to refer to this issue on the external repository: https://github.com/laurent22/joplin-turndown/issues/11

**Closed by nathanlesage** 2020-05-31 15:09 UTC
Labels: External Issue, bug [non-critical], confirmed, help wanted

**Comment by 13rac1** [comment] 2020-07-28 18:00
Fixed in e8054877acaec21e526e5c519c128406e32197a3

**Comment by nathanlesage** [comment] 2020-07-28 21:38
Perfect, good to know

**Comment by 13rac1** [comment] 2020-07-29 19:16
I was originally just linking the related commit. Now I realize it's still failing _sometimes_. In fact, of all the tabs I have open right now, only the [Fluentd docs](https://docs.fluentd.org/) copy/paste correctly. Confirmed Chrome only, Firefox works fine.

Copy a paragraph from https://docs.fluentd.org/v/0.12/articles/docker-logging
![image](https://user-images.githubusercontent.com/195061/88842612-a01f6b00-d194-11ea-8871-344863a6f95c.png)
Pasting is fine:
![image](https://user-images.githubusercontent.com/195061/88842666-b0374a80-d194-11ea-925f-1dc057218080.png)
Copying the fluentd article from Wikipedia:
![image](https://user-images.githubusercontent.com/195061/88842726-c47b4780-d194-11ea-8401-da5b6f9a154c.png)
Pasting is still broken:
![image](https://user-images.githubusercontent.com/195061/88842754-d361fa00-d194-11ea-929d-dcbaa5009ed7.png)

Yes I've got the current checkout and run `npm i`:
```
$ cat package.json | grep jop
    "joplin-turndown/jsdom/acorn-globals/acorn": "^6.4.1"
    "joplin-turndown": "^4.0.29",
    "joplin-turndown-plugin-gfm": "^1.0.12",
```

The primary difference is the fluentd docs have extra spans in the HTML, while Wikipedia has much simpler HTML.

**Comment by nathanlesage** [comment] 2020-07-30 15:13
Yeah, then it's still related to joplin-turndown. Damn it …
