### ISSUE TITLE
[1.8.0Alpha][Linux] Case change in extecutable name breaks shurtcuts

### ISSUE THREAD

**Issue by 8hur** [Zettlr/Zettlr#1315] opened 2020-09-28 14:02 UTC
## Description
The executable file in linux has been changed from zettlr to Zettlr. Since linux is case-sensitive, the .desktop link used to start the application has to be updated.

**Comment by nathanlesage** [comment] 2020-09-28 14:26
Duplicate of #1304

**Closed by nathanlesage** 2020-09-28 14:26 UTC
