### ISSUE TITLE
Scrolling in document with images causes intermittent jumps in reverse direction (Regression) 

### ISSUE THREAD

**Issue by bryc** [Zettlr/Zettlr#4766] opened 2023-11-06 15:24 UTC
### Description

After updating from an older version (around 2.5), to the current stable (3.0.2), I noticed that scrolling (using Scroll Wheel) caused an issue where it would jump in the reverse direction. 

This seems to only affect documents that have image tags, pure text documents seem unaffected.

Clicking and dragging the scroll bar has similar issues. The scroll bar can be a bit jittery, but is at least more "usable" than scroll wheel. It also shows the size of the scroll bar changing when being dragged. For example, the scroll bar may be larger at the top of the document, and smaller at the bottom.

This could indicate a conflict with how Zettlr is calculating the document length in regards to the images contained in it.

### Reproducing

Scrolling in a document with image tags, it is quite evident that the scroll position jumps unnaturally. Here is a clip:

https://github.com/Zettlr/Zettlr/assets/1408749/a70c69c1-4af8-4967-8d85-e7babe7f6bad

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.3

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment] 2023-11-07 08:41
Duplicate of #4704

**Closed by nathanlesage** 2023-11-07 08:41 UTC
Labels: bug
