### ISSUE TITLE
Exporting to HTML returns pandoc error when working on network drive

### ISSUE THREAD

**Issue by vtcarlino** [Zettlr/Zettlr#416] opened 2019-11-28 17:07 UTC
## Description
Export dialog returns the following pandoc error when trying to export documents located on a network drive : `pandoc:  \\: openBinaryFile: does not exist (No such file or directory)` 

## Reproducing
- Store files on a network drive
- Export a document in HTML

## Expected behaviour
An HTML should be created and opened in default web browser. Note that after several attemps, the HTML file may be created.

**Screenshots**
![Zettlr_issue_2019-11-28 175303](https://user-images.githubusercontent.com/24810357/69823526-6531f580-1209-11ea-8fab-c39e392dad8b.png)

## Platform
 - OS: Windows 10
 - OS Version: 1809
 - Zettlr Version: 1.4.3

## Additional information
Exporting to `.odt` and `.docx` works fine.

**Comment by nathanlesage** [comment] 2019-11-28 18:35
Although .odt, .docx, and .html should not make any difference, it indeed seems to be the double-backslash at the beginning: https://stackoverflow.com/a/55616529

My hypothesis: Pandoc actually sees the double backslash as an escaped backslash, hence it will try to open some path that does not exist. I believe strongly in the idea that this might be pandoc-related.

I'm not completely sure, but if you'd like to try it with a mapped network device (`\\` --> `Y:\`) this might help.

**Comment by nathanlesage** [comment] 2019-12-10 14:18
Any news on this, or can I close this issue?

**Comment by vtcarlino** [comment] 2019-12-11 10:08
I need to get permission from my network admin in order to map the network device. I moved my data on C:\ and it works perfectly.

**Comment by nathanlesage** [comment] 2019-12-11 10:22
Alright, good that it does work from a mapped drive. As I suspected, it very much seems to be a problem with SMB fileshares: https://github.com/jgm/pandoc/issues/1326

At my work place, we also have three server-side directories, all of them mapped to drive letters, and for me the exports work as expected, so this really seems to be the cause!

**Closed by nathanlesage** 2019-12-11 10:22 UTC
