### ISSUE TITLE
Do not list files listed on .gitignore

### ISSUE THREAD

**Issue by endel** [Zettlr/Zettlr#711] opened 2020-05-02 18:44 UTC
## Description

I'm starting to write using the old `gitbook-cli` + Zettlr, and I'm currently seeing way too many files in the sidebar, making Zettlr a bit slow. 

## Proposed Changes

Would be nice to ignore any files listed under `.gitignore` on the file list in the sidebar

## Additional Information

![Screenshot 2020-05-02 at 21 43 40](https://user-images.githubusercontent.com/130494/80872969-098afd00-8cbe-11ea-9692-9f6764fee9dc.png)

**Comment by nathanlesage** [comment] 2020-05-03 09:37
Puh, difficult. While the idea is totally clear, this issue needs to wait until git-integration is in Zettlr. Why? Because by resolving `.gitignore`-files without showing `.git`-indications to the users this might very well confuse people …

We'll have to think this through prior, but as git-support is still some way, this has time to develop!

**Comment by nathanlesage** [comment] 2020-06-18 19:45
Closing for now, because it's a bad idea implementing gitignore, as this might lead to unexpected behaviour. We may re-discuss this on git-integration later on!

**Closed by nathanlesage** 2020-06-18 19:45 UTC
