### ISSUE TITLE
[Bug] Lists in tables are dislayed with big dot

### ISSUE THREAD

**Issue by leo-hstone** [Zettlr/Zettlr#3339] opened 2022-03-23 20:36 UTC
### Description

```
| Test       | Laden      |
|------------|------------|
| Ramen      |            |
| - Zwiebeln | Rewe       |
| - Pilze    | Asia Markt |
| Spaghetti  |            |
| - Nudeln   | Lidl       |
```
The displayed table (I know the example values are a bit weird but I think you can imagine why I want to do something like this) is rendered like this:

![image](https://user-images.githubusercontent.com/62036826/159790632-a9c33359-17d4-4e89-be2a-0e0a04232ae7.png)

As it is not possible (to my knowledge) to insert linebreaks in tables, it is not preferable to have the lists rendered as this big points. 

### Reproducing

Copy raw code above into a md file and open with Zettlr.

### Zettlr Version

Nightly

### Specify version

2.2.4

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by leo-hstone** [comment] 2022-03-23 20:39
Small workaround for everyone interested in the meantime: just insert two hyphens (`--`)

**Comment by nathanlesage** [comment] 2022-03-25 10:31
> As it is not possible (to my knowledge) to insert linebreaks in tables

That is something that is already demanded, and will come at some point once I have the sufficient time to get back to the table editor once more :D 

So closing as this is not a bug (it does do something that is intended, right? Simply because the beauty of all of it is not yet implemented doesn't make it a bug ;)

**Closed by nathanlesage** 2022-03-25 10:31 UTC
Labels: bug
