### ISSUE TITLE
[Feature] snapshot function

### ISSUE THREAD

**Issue by YetAnotherAccount5345f** [Zettlr/Zettlr#3105] opened 2022-01-30 12:02 UTC
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

A snapshot that does automatically take a shot before you edit or when you manually save a document would be a nice feature. 

Also, some comparison by word, paragraph or clause would be neat.

https://i.imgur.com/nefCoJh.png

### Example Workflow

1. Saving manually or start to edit a document
2. Snapshot gets created
3. Writing all day
4. Most of the stuff was trash, but a few sentences were nice
5. Recover the snapshot and I copy the good sentences into the recovered shot.

### Caveats

None

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

**Comment by nathanlesage** [comment] 2022-01-30 12:16
Would it suffice for you after we've incorporated git support if git automatically creates such snapshots in the form of commits which you can browse?

**Comment by YetAnotherAccount5345f** [comment] 2022-01-30 13:37
Yes, that is a great idea !

**Comment by nathanlesage** [comment] 2022-01-30 13:49
Alright, then I'm closing this issue in favor of the git implementation (which will include exactly this!)

**Comment by nathanlesage** [comment] 2022-01-30 13:49
Duplicate of #1050

**Closed by nathanlesage** 2022-01-30 13:49 UTC
Labels: feature
