### ISSUE TITLE
Crash Zettlr 3.10

### ISSUE THREAD

**Issue by dustdfg** [Zettlr/Zettlr#5135] opened 2024-05-03 19:26 UTC
### Description

I run it, it shows me a window for split second and crashes

### Reproducing

Just run it

### Zettlr Version

Stable (most recent version)

### Specify version

3.1.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Debain testing, sway (xwayland)

### Additional Information

If I run through terminal I see:

```
[Application] Performing environment check ...
[Application] Pandoc has been bundled with this release. Path: /usr/lib/zettlr/resources/pandoc
[Application] Quarto not found on system. *.qmd-files will be exported with Pandoc.
[Application] Environment check complete.
Segmentation fault
```

**Comment by dustdfg** [comment] 2024-05-03 19:40
Works after update...

**Comment by dustdfg** [comment] 2024-05-03 19:47
I just made a reboot and problem returned

**Comment by nathanlesage** [comment] 2024-05-03 20:48
That looks suspiciously like an error in Electron. Maybe [this one](https://github.com/electron/electron/issues/41839)

**Comment by nathanlesage** [comment] 2024-05-03 20:51
Please try out the last beta, it uses basically the same code but with a slightly older Electron version, that one should work while we wait for Electron to fix this 🍵

**Comment by m1ga** [comment] 2024-05-03 20:59
in Fedora it won't let me install zettlr-3.1.0.beta.3-1.x86_64 as it conflicts with Slack `slack-4.37.101-0.1.el8.x86_64` (Slack runs fine).

**Comment by dustdfg** [comment] 2024-05-04 06:25
> That looks suspiciously like an error in Electron. Maybe [this one](https://github.com/electron/electron/issues/41839)

I am not sure that it is exactly this error because I use sway and when I open zettlr through terminal it opens it in half screen because sway is tiling manager

**Comment by dustdfg** [comment] 2024-05-04 06:34
> Please try out the last beta, it uses basically the same code but with a slightly older Electron version, that one should work while we wait for Electron to fix this 🍵

It works in my case

**Comment by nathanlesage** [comment] 2024-05-04 14:12
> > That looks suspiciously like an error in Electron. Maybe [this one](https://github.com/electron/electron/issues/41839)
> 
> 
> 
> I am not sure that it is exactly this error because I use sway and when I open zettlr through terminal it opens it in half screen because sway is tiling manager

The issue talks at some point about issues with tiling managers, so there is a chance this is related.

**Comment by LaPingvino** [comment] 2024-05-05 02:21
I run Gnome on Wayland and I can confirm that both Gnome on Wayland and Hyprland have it working properly. I can reproduce the segfault with Gnome on Xorg on my Arch Linux system with an official build from the package manager.

**Comment by LaPingvino** [comment] 2024-05-05 02:59
it seems to reliably trigger if I try to run any version with the disable hardware acceleration flag

**Comment by dustdfg** [comment] 2024-05-05 04:13
> I run Gnome on Wayland and I can confirm that both Gnome on Wayland and Hyprland have it working properly. I can reproduce the segfault with Gnome on Xorg on my Arch Linux system with an official build from the package manager. The bug doesn't seem to appear with the AppImage version.
> 
> @dustdfg and @m1ga can you see if the AppImage version works as a workaround?

I even can't check because I get:
```
bash: ./Downloads/Zettlr-3.1.0-arm64.AppImage: cannot execute binary file: Exec format error
```

**Comment by dustdfg** [comment] 2024-05-05 04:15
> I run Gnome on Wayland and I can confirm that both Gnome on Wayland and Hyprland have it working properly. I can reproduce the segfault with Gnome on Xorg on my Arch Linux system with an official build from the package manager. The bug doesn't seem to appear with the AppImage version.
> 
> @dustdfg and @m1ga can you see if the AppImage version works as a workaround?

The same result with appimage

**Comment by w-wagner** [comment] 2024-05-05 05:45
I just tried --clear-cache and second, removed .config/Zettlr completely.
It did not help.

When I started without the Zettlr confir dir the output changed to
zettlr 
[Application] Performing environment check ...
[Application] Pandoc has been bundled with this release. Path: /usr/lib/zettlr/resources/pandoc
[Application] Quarto not found on system. *.qmd-files will be exported with Pandoc.
[Application] Creating required directory /home/wolfram/.config/Zettlr/dict ...
[Application] Creating required directory /home/wolfram/.config/Zettlr/lang ...
[Application] Creating required directory /home/wolfram/.config/Zettlr/logs ...
[Application] Creating required directory /home/wolfram/.config/Zettlr/defaults ...
[Application] Creating required directory /home/wolfram/.config/Zettlr/snippets ...
[Application] Creating required directory /home/wolfram/.config/Zettlr/lua-filter ...
[Application] Environment check complete.
[8699:0505/074018.026679:ERROR:nss_util.cc(357)] After loading Root Certs, loaded==false: NSS error code: -8018
Speicherzugriffsfehler

3.0.5 did work immediately before the update.
(fully updated debian 12.5, xorg, cinamon)

**Comment by w-wagner** [comment] 2024-05-05 07:25
Just reverted to 3.0.5 deb and it worked. Back to 3.1.0 and the segfault reappears.

**Comment by nathanlesage** [comment] 2024-05-05 08:05
> A lot of incomprehensible text (looks somehow like a compiled source code archive?) is printed in the console than:

I noticed that myself, but thought it might be due to some weirdness in webpack, I didn't think it reoccurred in the final builds, that may be a good observation!

***

All in all, I believe *something* in Electron 30 is really bad at handling windows. I've seen segfault bugs on the Electron repo being reported as an interaction with window opening and closing, tiling managers, and maximizing windows. Let's hope they fix this asap; I may consider releasing a 3.1.1 while reverting back to the previous Electron version if a fix won't appear soon.

**Comment by nathanlesage** [comment] 2024-05-05 09:03
I just tried it out on my work computer, and Zettlr works flawlessly.

Things to note:

- It's running Manjaro
- No tiling manager
- Hardware acceleration is on
- I forgot to run Yarn install so it runs on 30.0.1 (will report with 30.0.2), but I don't believe this to be the cause.

**Comment by nathanlesage** [comment] 2024-05-05 09:39
I have now downgraded Electron to 29.3.2 which, at least on my system, launches fine. I'll immediately schedule a manual nightly build, and request that all of you who have this issue try this one out -- just to see if it still segfaults. If it doesn't, I'll release a hotfix that downgrades Electron to 29.3.2 so that we can all use the app again.

**Comment by tannenfreund87** [comment] 2024-05-05 09:45
I run Zettlr on KDE (plasma6, x11). It segfaults when maximizing the window, manually stretching it to the screen size works fine. It also completely segfaults on start, if I choose to use the native window decorations. I tried the RPM and the AppImage, both show the same behaviour.

**Comment by m1ga** [comment] 2024-05-05 09:56
> I have now downgraded Electron to 29.3.2 which, at least on my system, launches fine. I'll immediately schedule a manual nightly build, and request that all of you who have this issue try this one out -- just to see if it still segfaults. If it doesn't, I'll release a hotfix that downgrades Electron to 29.3.2 so that we can all use the app again.

Nightly build works fine!
![Screenshot_20240505_115532](https://github.com/Zettlr/Zettlr/assets/4334997/a4dfa14e-eadf-4d37-b50d-611fc5cfb65a)

No crash on startup or resizing the window.

```
Linux fedora 6.8.8-300.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Apr 27 17:53:31 UTC 2024 x86_64 GNU/Linux
KDE, Wayland
```

**Comment by w-wagner** [comment] 2024-05-05 09:59
I confirm: When I start Zettlr using the "-m" trick, restore it to not be in fullscreen mode and exit, I can start zettlr in normal mode.
In the moment I try to maximize it, it crashes with a lot of text (propably the same as above) in the console.

RangeError: Maximum call stack size exceeded

btw: The --trace-uncaught... option did not work, changed anything.

Closing the non maximized window still issues the error message about the stack error. It happens when I close the non maximized error. This time adding the nodejs version information.
I attached the output when I close
[zettlr_out_not_maximized_closing.txt](https://github.com/Zettlr/Zettlr/files/15212441/zettlr_out_not_maximized_closing.txt)

And also the crash output, when I maximize the window:
[zettlr_out_maximizing.txt](https://github.com/Zettlr/Zettlr/files/15212443/zettlr_out_maximizing.txt)

I am going to try the nightly build now

**Comment by w-wagner** [comment] 2024-05-05 10:03
nightly:
Opening as window, maximized and via -m works now. Very good.
The error, when I close it is still there and makes the restart after clear Help - Clear FSAL Cache impossible.

**Comment by dustdfg** [comment] 2024-05-05 12:36
Nightly works fine

**Comment by nathanlesage** [comment] 2024-05-05 17:35
Perfect, I'll be releasing 3.1.1 soon that ships with this fix in a "regular" release so that others who run Linux but require a package manager will soon also be able to use the 3.1.x release line.

**Closed by nathanlesage** 2024-05-05 17:35 UTC
Labels: bug

**Comment by McTom234** [comment] 2024-05-06 10:09
Hey @nathanlesage, is there an estimate for the Arch package 3.1.1 release?

**Comment by tannenfreund87** [comment] 2024-05-06 13:18
> Hey @nathanlesage, is there an estimate for the Arch package 3.1.1 release?

Arch packages are community maintained, you need to ask the package maintainer:
https://archlinux.org/packages/extra/x86_64/zettlr/
Caleb Maclennan, @alerque 

Or you just wait, he's quite active, and the upgrade should arrive soon.

**Comment by nathanlesage** [comment] 2024-05-06 22:29
> I was reluctant to bump the Arch Linux package that involved downgrading ELectron for a bug that I couldn't reproduce

Electron 29 is still in the supporting frame, and tbh I think that it is kind of shitty of the Electron team to push this tight of a timeline onto volunteering FOSS developers anyhow. After this experience I will go back to my usual schedule of keeping one full version distance to Electron main. This is by far not the first instance where the most recent Electron version had serious bugs for people. It's similar to macOS updates: the initial ones are kind of bad, but they get better over time. What I will do, though, is publish new releases more frequently, even if that only means to bump Electron to keep up with supported versions.

**Comment by nathanlesage** [comment] 2024-05-13 16:05
There seems to be a patch incoming that should allow us to swiftly move to Electron 30/31. I'll be launching a nightly soon to confirm, please stay ready to test it so we can release a stable fix.
