### ISSUE TITLE
Cannot select "Characters" as writing target

### ISSUE THREAD

**Issue by ryota-abe** [Zettlr/Zettlr#554] opened 2020-02-19 13:29 UTC
## Description

Clicking on the "Characters" closes the "Set writing target" popup immediately.

## Reproducing
1. Right click any file and select "Set writing target..."
2. Click on "Words" in the center of the popup and try to change it to "Characters".
3. The popup will close. And it remains unset.

## Expected behaviour
Clicking the pull-down does not close the popup.

**Screenshots**

## Platform
 - OS and version: Windows 10 Home 1903
 - Zettlr Version: 1.6.0-beta.4
 - Screen Resolution: 1366x768

## Additional information

Reproducible in v1.3.0 or later.

**Comment by nathanlesage** [comment] 2020-02-19 17:25
I cannot reproduce this on macOS, the only thing I could fathom would be that somehow on Windows a click on the select is bubbled up to the popup, where the popup will decide it should close itself…?

**Comment by ryota-abe** [comment] 2020-02-20 10:11
At least in Chrome on Windows, clicking an `<option>` fires a click event and its `clientX` and `clientY` are always zero. (So reaching line 70 in zettlr-popup.js and the popup closes.)

[Here is a simple jsfiddle to check this behavior.](http://jsfiddle.net/ryota_abe/1epbf4dt/4/)
![option_click_event](https://user-images.githubusercontent.com/15438757/74922703-f54f9780-5412-11ea-918b-46fb73e772d6.gif)

**Comment by nathanlesage** [comment] 2020-02-20 11:28
>  and its clientX and clientY are always zero

Oh my, Windows keeps harassing me. Just tried this on Windows 7, same behaviour. Why the f***?!

Alright, I'll add a check to check for the `e.target` (if it's of type `option`) to prevent that behaviour … thanks for the fiddle!

**Comment by nathanlesage** [comment] 2020-02-21 08:44
Whoops, while playing I just found another bug: The event listener is never detached from the DOM o.o

**Comment by nathanlesage** [comment] 2020-02-21 08:54
Aaand here we go!

**Closed by nathanlesage** 2020-02-21 08:54 UTC
Labels: bug/non-critical, confirmed, platform/win
