### ISSUE TITLE
Cannot open existing md-files on ICloud-drive after update to Zettlr 3.4

### ISSUE THREAD

**Issue by jsingler** [Zettlr/Zettlr#5527] opened 2024-12-23 18:50 UTC
### Description

Opening of existing md-file on ICloud-drive ends up in following error message in the log:
Could not open root /Users/d039757/Library/Mobile Documents/iCloud~com~logseq~logseq/Documents/MyNotes/pages/Mathias.md: Cannot read properties of undefined (reading 'value')

### Reproducing

Try to open md-file stored on ICloud

### Zettlr version

3.4.0

### Installation Method

Homebrew

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit (includes Apple Silicon)

### Operating System Version

15.2

**Comment by jelkejelke** [comment] 2024-12-23 19:41
Similar issue here. Workspaces did not appear and I couldn't open/add them again, fol. Open md files appeared entirely empty in Zettlr (but not elsewhere). At first open I also couldn't access the right-click menu to close open files/tabs. 

I'm on MacOS 13.6.6, on a intel macbook, installed through the built-in updater. My workspace was located on Surfdrive.

Downgrading to 3.3.1 solved the issue, although I had to add my workspaces again.

**Comment by nathanlesage** [comment] 2024-12-23 21:21
Duplicate of #5526

**Closed by nathanlesage** 2024-12-23 21:21 UTC
Labels: bug
