### ISSUE TITLE
Zettlr 1.4.2 does not show any file or root in the left menu

### ISSUE THREAD

**Issue by HuebraG** [Zettlr/Zettlr#360] opened 2019-10-13 16:52 UTC
## Description
When a root is open, no folder are shown. The last file is on the editor, but if I try to open another folder, nothing appears to change.
![zettlrpb](https://user-images.githubusercontent.com/36669838/66718978-3c38db00-edea-11e9-83d3-f4d7d8a9e6bc.PNG)

## Reproducing
Install or update to version 1.4.1 or 1.4.2

## Expected behaviour
Show the menu with files and folders

**Screenshots**

## Platform
 - OS: Windows
 - OS Version 7
 - Zettlr Version 1.4.2 and 1.4.1
 - Screen Resolution [only necessary if the bug is relating to the GUI]

## Additional information
I can revert back to 1.3.0, and it works again.

**Comment by nathanlesage** [comment] 2019-10-13 20:24
Could it be that this issue is a duplicate of https://github.com/Zettlr/Zettlr/issues/343? Because Zettlr will simply show _nothing_ if there is one root with more than 7 or 8 sub-levels.

**Comment by viaregio** [comment] 2019-10-14 07:19
I don't think that this is a duplicate of #343. I have installed Zettlr 1.4.2 on two computers, one with macOS and one with Ubuntu. Opening the same directory under the two systems I get different results. Under Ubuntu I get the same behavior described in this issue. Under macOS I have no issue.

**Comment by viaregio** [comment] 2019-10-14 07:25
Sorry I have to correct myself. I wasn't aware of the fact, that Zettlr keeps a list of previously opened folders. The in #355 suggested fix worked for me.

**Comment by nathanlesage** [comment] 2019-10-14 09:37
So it's a duplicate as there was a folder with more subfolders …?

**Comment by viaregio** [comment] 2019-10-14 09:40
I can't speak for the creator of this issue, but my issue is a duplicate of #343.

**Comment by nathanlesage** [comment] 2019-10-14 09:56
Ah, just realised that, never mind :smile:

**Comment by nathanlesage** [comment] 2019-11-09 11:36
Closing as the issue might be that duplicate …?

**Closed by nathanlesage** 2019-11-09 11:36 UTC
