### ISSUE TITLE
failed upgrade to 1.8.6 on Ubuntu 20

### ISSUE THREAD

**Issue by pcarbonn** [Zettlr/Zettlr#1656] opened 2021-01-19 11:00 UTC
Previous upgrades worked well, but this one failed: the zettlr file explorer does not show my .md files, and when I want to open a file from the menu, the pop-up window is frozen (I can quit with Esc though).  If I want to open the recent files, none of my files are shown.  Luckily, my files are still on my disk, and the "Folder Open" icon works !

**Comment by nathanlesage** [comment] 2021-01-19 13:26
Duplicate of #1645

**Closed by nathanlesage** 2021-01-19 13:26 UTC
