### ISSUE TITLE
[Bug] File will not be deleted in filesystem when opened in Zettlr

### ISSUE THREAD

**Issue by AIBN60** [Zettlr/Zettlr#2712] opened 2021-10-23 10:03 UTC
### Description

A file which is opened in Zettlr and deleted by right click (and following confirmation) is invisible in Zettlr, but not deleted in filesystem. It will be shown in Zettlr again after starting Zettlr anew

### Reproducing

Open file in Zettlr
goto file manager on the left
right-click and chose delete (shortcut ctrl+backspace does not work; ctrl + delete  deletes directory)
File will diappear in file manager
File remains open
File is not deleted in file system
Close Zettlr
Start it anew
file is visible again

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux xxx 5.4.0-89-generic #100~18.04.1-Ubuntu SMP Wed Sep 29 10:59:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nathanlesage** [comment] 2021-12-09 18:39
Anything new in this regard? Since I have no Linux I can't really reproduce this issue :(

**Comment by AIBN60** [comment] 2021-12-10 08:42
Nope. Still: right click on file in the file manager on the left, delete file, click yes: file disappear in file manager but isn't deleted. It is still existent. 
Close Zettlr, open it again and voilà: file is back again.

This happens when file is open (Tab) or closed.

**Comment by nathanlesage** [comment] 2021-12-10 08:52
I just saw that I forgot to ask whether there are any bad logs after you attempt to delete? It does sound as if the file deletion process was throwing some error or so. Is there anything?

**Comment by AIBN60** [comment] 2021-12-10 13:13
No, no error visible: neither in logfiles nor on screen. But I will look for more information in files.

**Comment by nathanlesage** [comment] 2021-12-11 08:18
That would be great. It could also be because your Linux install doesn't have that trash-library? Does it work if you delete them in any case? There is a setting in the advanced preferences for these cases.

**Comment by AIBN60** [comment] 2021-12-12 13:45
A) Library is installed:
x@x:~$ dpkg -l | grep gvfs-bin
ii  gvfs-bin     1.36.1-0ubuntu1.3.3       amd64     userspace virtual filesystem - binaries

B) Right click on File in File Manager, click on Show file. Opens some kind of Dateimanager ;-). Delete File results in "do you really..... File will be permanently deleted ". This works. Deleting in the filesystem works as well

C) The option to delete without moving it to trash wasn't ticked. When this option is ticked, the file will be deleted.

I am fine with that after I got used to it. So, no need to change. Other things are more important

**Comment by nathanlesage** [comment] 2021-12-12 17:45
Okay, then I'm going to close this issue. If you notice anything new, feel free to ping me!

**Closed by nathanlesage** 2021-12-12 17:45 UTC
Labels: bug
