### ISSUE TITLE
Indentation for sub-lists is way too high

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#578] opened 2020-03-02 20:40 UTC
## Description

Consider this list:

```
1. item
2. item
    1. sub-item
3. last item
```

When a sub-item is spanning multiple lines, its indentation is very big, almost half a page. Sometimes the editor fails to see sub-item indexing, and bullets or numbers are not highlighted. See screenshot:

![zettlr-sub-indentation](https://user-images.githubusercontent.com/766031/75715661-d4265b00-5cde-11ea-90ab-77fa04c8e679.png)

(I have 4 spaces before "1." and "2.")

## Reproducing

For a simple case, copy the list above to Zettlr and try adding more words to the sub-item.

## Expected behaviour

Indentation should be smaller — if not ideal (see #511 for the general list indentation issue).

## Platform
 - OS and version: Fedora Linux 30
 - Zettlr Version: 1.6.0 beta5

## Additional information

I understand this is hard to fix, and it's nothing too important. It's okay if this waits until 1.8.

**Comment by nathanlesage** [comment] 2020-03-03 09:09
> For a simple case, copy the list above to Zettlr and try adding more words to the sub-item.

Have a look at this:

https://github.com/Zettlr/Zettlr/blob/f89e537fcd73335643dcfc5ccb3708fd871ef900/source/renderer/zettlr-editor.js#L446-L458

The "MINOR BUG"-part is what's causing this. Have to go to this again at some point.

**Comment by Zverik** [comment] 2020-05-10 07:29
Still being worked on in #628.

**Comment by tobiasdiez** [comment] 2020-06-08 20:27
This should be fixed in the latest development version, or at least not as bad as on the screenshot.

**Comment by nathanlesage** [comment] 2020-06-08 20:34
Yes, tested it out earlier, seems to work much, much better, even with indentation up to three levels:

![image](https://user-images.githubusercontent.com/17251683/84077806-2ced4a00-a9d8-11ea-82d7-312cc3542d5b.png)

(Ignore the additional indentation caused by the numbers, this is not how one should use lists, but I was too lazy :D)

**Closed by nathanlesage** 2020-06-08 20:34 UTC
Labels: All Platforms, bug [critical], confirmed
