### ISSUE TITLE
[Bug] Extraneous scrollbars around application

### ISSUE THREAD

**Issue by jchalifour** [Zettlr/Zettlr#2545] opened 2021-10-01 14:10 UTC
### Description

In the latest beta release, there are new horizontal and vertical scrollbars at the bottom and right edges of the application regardless of whether I maximize it or use it as a resized window on the desktop (though they don't make sense in either case). This also seems to be the case in the settings dialogue but in that dialogue it seems the setting are arranged in a way now that it requires scrolling. 

Here is a screenshot: 
![zettlr-screenshot_20211001](https://user-images.githubusercontent.com/5346551/135633943-df6ded58-f807-48a6-9cd9-ac516a5a3b35.png)

### Reproducing

I started the latest beta and these appeared.

### Zettlr Version

Beta (if applicable)

### Specify version

Release v2.0.0-beta.5

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Up-to-date Manjaro (rolling release) with Gnome 40 desktop

**Comment by nathanlesage** [comment] 2021-10-02 16:41
Very likely some odd sizing issue due to my latest CSS enterprises. Will have a look!

**Comment by nathanlesage** [comment] 2021-10-03 20:50
With regard to the settings dialog: The problem simply is that, on macOS, Scrollbars are of zero width, whereas on Windows and Linux they are always present, if they are necessary.

That being said: I found the culprit regarding the settings, but I could not reproduce the horizontal scrollbar in your main window here on Windows. Does reloading the main window help ...?

**Comment by jchalifour** [comment] 2021-10-04 02:15
Oh yes, reloading the main window seems to have gotten rid of the horizontal scrollbar.

**Comment by nathanlesage** [comment] 2021-10-04 07:33
Perfect, would you mind keeping an eye on those? And, if they don't happen anymore, you can safely close the issue!

**Comment by nathanlesage** [comment] 2021-10-09 11:13
I just fixed the scrollbar issue, was a slight sizing issue!

**Closed by nathanlesage** 2021-10-09 11:13 UTC
Labels: bug
