### ISSUE TITLE
[BUG] Zettlr becomes unresponsive when adding "[" before/inside a word

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#956] opened 2020-06-26 21:02 UTC
## Description
Whenever I start typing a "[" before (or inside) a word to create a link, Zettlr hangs (100% CPU) and I have to force quit it.

## Reproducing
1. Place cursor in front of (or inside) a word
2. Type "["
3. Zettlr will freeze

This only seems to happen when '"[" is typed directly _in front of_ a word or _inside_ of the word. If the cursor is _behind_ the word (with a space afterward), no freeze occurrs. Or in other words, when there is a letter immediately following the "[".

## Expected behaviour
Do not freeze.

## Platform
 - OS and version: Linux Mint 19.2
 - Zettlr Version: 1.7.0-beta.13
 - Screen Resolution: 1920x1080

## Additional information
This does not happen in Zettlr 1.6.

A workaround right now is to _pre-select_ (either by double-clicking or manually selecting), and then start typing "[" to create the link. _("Workaround" from this issue's point of view; pre-selecting and then typing "[" is better anyways imo, since you automatically get the closing brackets.)_

**Comment by nathanlesage** [comment] 2020-06-27 11:54
Can't reproduce this here — which language do you write in? At least with the latin script this works well …

**Comment by kyaso** [comment] 2020-06-27 15:11
I write in German/English.

I also found out that if a line already contains a link somewhere _after_ some word, then typing "[" before/inside that word does not cause a freeze; if there is no other link down the line (but possibly before the word), then the freezing will happen. 

E.g.:
`This is a link. This is an [[apple]].`
Then typing "[" before _"link"_ works.

`[[This]] is a link.`
Here, typing "[" before _"link"_ freezes Zettlr for me.

**Comment by kyaso** [comment] 2020-06-27 15:15
I just tested with the AppImage of 1.7.0-beta.13, and the issue is not present there!

Not sure why the development version (I did `yarn start`) has this for me.

**Comment by nathanlesage** [comment] 2020-06-27 17:56
> Not sure why the development version (I did yarn start) has this for me.

Hmm, indeed interesting. I'd say if it works in the released versions, we shall close this issue, BUT in case you start to note a pattern, please comment here so that we can have a look! Especially after the 1.7 release next Friday!

**Closed by nathanlesage** 2020-06-27 17:56 UTC
Labels: waiting for feedback

**Comment by kyaso** [comment] 2020-07-03 15:27
Now with 1.7 I'm getting the issue again.
However, in the AppImage of 1.7.0-beta.13 the issue does not appear.

**Comment by Jos512** [comment] 2020-07-03 15:31
> Now with 1.7 I'm getting the issue again.
> However, in the AppImage of 1.7.0-beta.13 the issue does not appear.

That is good news because then there's a relatively small list of changes that could cause the problem!

For the coders under us, this is a comparison of the changes between Beta-13 and 1.7-release:

- https://github.com/Zettlr/Zettlr/compare/v1.7.0-beta.13..v1.7.0

**Comment by nathanlesage** [comment] 2020-07-03 21:37
The error most likely occurs here: https://github.com/Zettlr/Zettlr/compare/v1.7.0-beta.13..v1.7.0#diff-8653658a50e663e4c51d74e07ffd5597
