### ISSUE TITLE
[Bug] Editing a table removes content in other file

### ISSUE THREAD

**Issue by philippludwig** [Zettlr/Zettlr#3338] opened 2022-03-23 15:47 UTC
### Description

When I enter a table in a document, the table will be copied to another document, deleting any content there.

See this GIF:

![table_bug](https://user-images.githubusercontent.com/3770792/159738937-49b33db0-6d11-4365-881e-f879eff5fd88.gif)

### Current behavior

1. Have two documents
2. Create a list of things in document A
3. Create a (huge) table in document B
4. Switch to A
5. Switch to B, edit a few cells in B
6. Switch to A
7. Content in A gets replaced with table from B
8. Switch to B
9. Cells in the table in B have not been updated

### Expected behaviour

Table in B gets updated, content in A does not get replaced.

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.4

### Your Platform

- [X] Linux

### Architecture

- [X] Intel 64bit

### Operating System Version

Gentoo

### Additional Information

It's not just in the UI, the files get changed on the disk, too.

**Comment by philippludwig** [comment] 2022-03-23 15:50
Here is the test table file:

[table.md](https://github.com/Zettlr/Zettlr/files/8334468/table.md)

**Comment by nathanlesage** [comment] 2022-03-25 10:34
Ouh snap. That's not good.

But I think I know the cause:

You click on the other file tab without un-focusing the table, which means that the table will notice "Hey you just unfocused me" and the corresponding code will then write the table to the corresponding range in the editor. BUT since the editor doesn't change, but the document does, it is ignorant as to what FILE it is writing this to.

So you can mitigate this by first unfocusing the table (clicking somewhere else in the file) and only THEN switching to the other file.

Marking as high-priority due to potential of data loss

**Closed** 2022-03-25 19:28 UTC
Labels: bug, priority:high

**Comment by philippludwig** [comment] 2022-03-26 06:04
Thanks for taking care of this so quickly!
