### ISSUE TITLE
v3.0.0 and v3.0.1 will not start up on Raspberry Pi

### ISSUE THREAD

**Issue by esodigoyo** [Zettlr/Zettlr#4713] opened 2023-10-02 22:32 UTC
### Description

I am using v2.3.0 on a Raspberry Pi 4. 
I updated to 3.0.0 and 3.0.1 but neither one starts up.
Rolling back to 2.3.0 and it works as expected.

### Reproducing

- Use a Raspberry Pi 4/400 running Raspberry Pi OS
- Install Zettlr-2.3.0-arm64.deb
- Run Zettlr
- Zettlr runs normally
-  Update to newer version 
- Run Zettlr again
- Zettlr fails to run

### Zettlr Version

Stable (most recent version)

### Specify version

v2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Raspberry Pi OS

**Comment by nathanlesage** [comment] 2023-10-03 08:17
Duplicate of #4595

**Closed by nathanlesage** 2023-10-03 08:17 UTC
Labels: bug
