### ISSUE TITLE
Frankfurt theme citation render

### ISSUE THREAD

**Issue by astronaute-nope** [Zettlr/Zettlr#3868] opened 2022-11-06 12:08 UTC
### Description

When I cite [@manzuchEthicalIssuesDigitization2017, 4-5] with the Frankfurt theme, it is not rendered with a - but with a box:
<img width="159" alt="zettlr" src="https://user-images.githubusercontent.com/7687660/200169727-60f3c912-0feb-4de5-a9c9-b7f5c9823e59.png">

With the other themes, it works.

### Reproducing

Select Frankfurt as theme and add a multi-pages citation.

### Zettlr Version

Stable (most recent version)

### Installation Method

Homebrew

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

MacOS 12.6

**Comment by nathanlesage** [comment] 2022-11-06 17:45
Weird. This looks as if the glyph is missing, but I cannot reproduce this on my system (macOS 12.6.1 on Apple Silicon):

<img width="496" alt="image" src="https://user-images.githubusercontent.com/17251683/200186315-9884ea53-70f9-4c97-b4ab-34bd5f8897de.png">

Could you double check in the font book whether Crimson is installed on your system, and if so, if it features the en-dash as well (–)? It could under some circumstances be that you have an older version of the font installed that didn't feature the glyph and that Zettlr is using your system font instead of the one shipped with the app.

**Comment by astronaute-nope** [comment] 2022-11-07 16:46
I don't have crimson on my Mac. (I re-installed it last month so it's a fresh install)

**Comment by nathanlesage** [comment] 2022-11-09 09:45
That is super weird … umm … so, to exclude potential issues: If you remove the Homebrew version and instead install the version directly from our website, does this change anything regarding the font display? It could be that homebrew is accidentally interfering (although I can't really imagine that). If that doesn't work, it could be that there was SOME issue that has in the meantime be fixed (the screenshot is part of the current nightly releases. If you'd like to you can also switch to these, gives you some new features, but may also have some bugs here and there left)

**Comment by nathanlesage** [comment] 2023-06-30 16:11
Closing due to impossibility to reproduce and lack of movement.

**Closed by nathanlesage** 2023-06-30 16:11 UTC
Labels: bug
