### ISSUE TITLE
Non-Table markup being turned into tables and causing data loss.

### ISSUE THREAD

**Issue by hyrcan** [Zettlr/Zettlr#1886] opened 2021-04-18 01:22 UTC
## Description
I've markdown notes created outside of Zettlr. When Zettlr opens them it incorrectly formats content as table, and replaces the original content with a messed up truncated copy. This causes data loss.

## Reproducing
The following text will be converted to a table with two rows and a single column containing only the number of characters as there are dashes. Note, no pipes are used in either examples.  All other characters/words on each line is deleted and lost.

```
any text here
---
more text here
```

In this example, a table with two rows and four columns is created containing a single character each.  All other characters/words on each line is lost.

```
any text here
- - - -
more text here
```

## Expected behaviour
The first example, should render a horizontal rule, or at the very least _not_ render a table or cause data loss.
The second example should either also render a horizontal rule, or not render anything other than what is displayed.  It should _not_ render a table or cause data loss.

![image](https://user-images.githubusercontent.com/68344486/115131050-cc00ac00-9fc2-11eb-9ea5-c40a892ec3d2.png)

## Platform
 - OS and version: Windows 10 and macOS
 - Zettlr Version: 1.8.7

## Additional information
Data loss is a showstopper for usage.

**Comment by nathanlesage** [comment] 2021-04-18 14:38
According to the CommonMark spec you are right: https://spec.commonmark.org/0.29/#thematic-breaks

However, Pandoc has a concept of simple tables, which messes up this definition: https://pandoc.org/MANUAL.html#tables

I suppose we need to stop supporting simple tables. Mh. @tarleb, @tobiasdiez does anyone of you have a suggestion on how to proceed? I mean, the table editor is perfectly fine with pipe and grid tables as well, so we could make it more restrictive so that it ignores anything that would qualify as a Pandoc simple table ...

**Comment by tarleb** [comment] 2021-04-18 16:51
The first example should neither be a table nor contain a horizontal rule, but it's a header plus a paragraph, as this is the syntax for setext headers which are part of markdown. You can try this in GitHub to confirm -- GitHub Flavored Markdown is mostly CommonMark plus a few extensions.

I agree that the second example is very confusing. Personally, I don't use these kind of tables, so my suggestion would be to disable "simple tables" by default.

In general, horizontal rules in Markdown should always be surrounded by blank lines to avoid unexpected behavior.

**Comment by tobiasdiez** [comment] 2021-04-18 17:14
I agree with @tarleb.

According to the linked spec,
> If a line of dashes that meets the above conditions for being a thematic break could also be interpreted as the underline of a setext heading, the interpretation as a setext heading takes precedence.

Thus, the first example is a heading with paragraph and the second one are two paragraphs separated by a horizontal line.

Github agrees:

Example 1: any text here
---
more text here

Example 2: any text here
- - - -
more text here

**Comment by nathanlesage** [comment] 2021-04-19 08:21
Thank you for the feedback!

So I would suggest the following:

- Simple Tables won't be supported by the TableEditor, since the table editor is too powerful and the demarcation of simple tables versus Setext headers is too thin
- I'll also be getting back to that Setext header problem, but in another issue (I think there were some oddities as well)
- And, last but not least @hyrcan: **To prevent data loss on any files, simple disable the TableEditor in the meantime, then nothing that looks like a table will be touched**. You can reactivate the TableEditor at any time, simply go to Preferences -> Editor, if I remember correctly!

**Comment by nathanlesage** [comment] 2021-08-22 14:07
Does this still happen on the 2.0 beta?

**Comment by bilderbuchi** [comment] 2022-01-08 17:01
> Does this still happen on the 2.0 beta?

On 2.1.1, loading a file with example 1 as contents yields the following on load:
![image](https://user-images.githubusercontent.com/327442/148652876-5dcb90a5-1db1-42a2-bc8b-b419a6fcc13d.png)
(I don't know if an hrule should be displayed this way)
However, clicking somewhere below the line "more text here" then creates the following:
![image](https://user-images.githubusercontent.com/327442/148652942-bb4e3a43-b1a1-4a36-85fd-3bc54ade4996.png)

**Comment by nathanlesage** [comment] 2022-01-08 22:46
@bilderbuchi that is not an hrule, that's a SeText heading. You should add an empty line between these and the next psragraph, as per the CommonMark specs: https://spec.commonmark.org/0.30/#setext-headings

**Closed** 2022-01-16 18:12 UTC
Labels: confirmed, bug, pinned, discussion, priority:mid
