### ISSUE TITLE
[Bug] system.error.open_root_error and very slow load times with large directories

### ISSUE THREAD

**Issue by JimColl** [Zettlr/Zettlr#3329] opened 2022-03-18 17:14 UTC
### Description

First off, what an amazing tool you've constructed here.  I'm hopeful it will help strengthen and speed along the background and introduction writing aspects, and the time and love you've dumped into this really shows.  Thank you for that.

My issue: Zettlr won't connect or stay connected to a workspace.  
In my idealized workflow I use zettlr as a sort of super-enhanced version of the windows folder explorer.  Unfortunately, I've been having issues getting Zettlr to behave as expected.  I can occasionally get Zettlr to open, and for the most part normal use/operations work as expected, especially when you start with a fresh folder system.  However, when I close the application zettlr loses the workspace and it can take upwards of 5 minutes to reconnect with even small (in my case 60 GB - 111,984 Files - 14,167 Folders) working directory sizes.  5 minutes to fully boot an application each time would not a deal breaker but in my case but my digital footprint exceeds 3 TB - 500,000 Files - 50,000 Folders, and letting Zettlr chew on that for a day didn't result in an open workspace.

Am I just using zettlr inappropriately or have I set up something incorrectly? (May be related to #3296, but was different enough to warrant the new issue) 

Troubleshooting steps taken so far:
* Multiple reinstalls
* My OS is installed on the C:, the hosted file folders are on the G:,  co-locating the zettlr install and the file system to the C: did not improve outcomes or performance.
* We are here

## Logs prior to a failure to connect (working > shutdown > not working)
```
[01:07:43] [Info] [WATCHDOG] Emitting event: add:G:\james.coll\Dropbox\root\areas\administriva\branding\UA\UA-StackedNameplate_Basic.jpg
[10:04:37] [Info] さようなら！ Shutting down at Fri Mar 18 2022 10:04:37 GMT-0500 (Central Daylight Time)
[10:04:37] [Info] Application uptime was: 19 hours, 39 minutes, and 30.918 seconds.
[10:04:38] [Info] [FSAL Cache] Cleaned up cache: Removed 0 remnants.
[10:04:38] [Info] [Stats Provider] Writing statistics to file
[10:14:35] [Info] [Citeproc Provider] Loading CSL locale file at G:\Zettlr\resources\app.asar\.webpack\main\assets\csl-locales\locales-en-US.xml ...
[10:14:35] [Info] こんにちは！ Booting Zettlr at Fri Mar 18 2022 10:14:35 GMT-0500 (Central Daylight Time).
[10:14:35] [Info] Registering custom protocol safe-file
[10:14:36] [Info] [Translation Provider] Updating translations for Catalan (Catalonia), Polish ...
[10:14:36] [Info] [Translation Provider] Downloading ca-CA ...
[10:14:36] [Info] [Translation Provider] Downloading pl-PL ...
[10:14:36] [Warning] [Assets Provider] Found outdated filter links.lua; copying ...
[10:14:36] [Warning] [Assets Provider] Found outdated filter tags.lua; copying ...
[10:14:36] [Info] [Stats Provider] Writing statistics to file
[10:14:36] [Info] [Window Manager] Loading state information from C:\Users\jimcoll\AppData\Roaming\Zettlr\window_state.json
[10:14:36] [Info] [Window Manager] Window Manager started.
[10:14:36] [Info] [Dictionary Provider] Loaded dictionaries: en-US
[10:14:36] [Info] [Citeproc Provider] Parsing file G:\james.coll\Dropbox\root\resources\ZoteroDBase.json as CSL JSON ...
[10:14:36] [Info] [Citeproc Provider] Database G:\james.coll\Dropbox\root\resources\ZoteroDBase.json loaded (355 items).
[10:14:36] [Info] [Update Provider] Checking for application updates ...
[10:14:36] [Info] [Updater] Checking https://zettlr.com/api/releases/latest for updates ...
[10:14:37] [Info] [Update Provider] No new update available. Current version is v2.2.4.
[10:14:38] [Info] [Translation Provider] Success: pl-PL updated.
[10:14:38] [Info] [Translation Provider] Success: ca-CA updated.
[10:14:38] [Info] Updated translations: Catalan (Catalonia), Polish
[10:14:50] [Error] Could not open new root G:\james.coll!
```

## Logs attempting to connect (not working> reconnect to system error > ... > working > quit > not working)
```
[10:53:52] [Info] こんにちは！ Booting Zettlr at Fri Mar 18 2022 10:53:52 GMT-0500 (Central Daylight Time).
[10:53:52] [Info] Registering custom protocol safe-file
[10:53:53] [Info] [Translation Provider] No updates available.
[10:53:53] [Warning] [Assets Provider] Found outdated filter links.lua; copying ...
[10:53:53] [Warning] [Assets Provider] Found outdated filter tags.lua; copying ...
[10:53:53] [Info] [Stats Provider] Writing statistics to file
[10:53:53] [Info] [Window Manager] Loading state information from C:\Users\jimcoll\AppData\Roaming\Zettlr\window_state.json
[10:53:53] [Info] [Window Manager] Window Manager started.
[10:53:53] [Info] [Dictionary Provider] Loaded dictionaries: en-US
[10:53:53] [Info] [Citeproc Provider] Parsing file G:\james.coll\Dropbox\root\resources\ZoteroDBase.json as CSL JSON ...
[10:53:53] [Info] [Citeproc Provider] Database G:\james.coll\Dropbox\root\resources\ZoteroDBase.json loaded (355 items).
[10:53:53] [Info] [Update Provider] Checking for application updates ...
[10:53:53] [Info] [Updater] Checking https://zettlr.com/api/releases/latest for updates ...
[10:53:54] [Info] [Update Provider] No new update available. Current version is v2.2.4.
[10:54:01] [Error] Could not open new root G:\james.coll!
[10:54:08] [Error] Could not open new root G:\james.coll!
[10:54:30] [Error] Could not open new root G:\james.coll!
[10:54:46] [Warning] [FSAL Directory] Path G:\james.coll took 51697.899399995804ms to load.
[10:54:50] [Warning] [FSAL] Path G:\james.coll took 56397ms to load.
[10:54:50] [Info] [FSAL] Loaded all files and workspaces in 56.397814099997284 seconds
[10:54:50] [Info] [Document Manager] Restored 5 open documents.
[10:54:50] [Info] [Application] Added G:\Zettlr\resources to PATH.
[10:54:50] [Info] [Application] The bundled pandoc executable is now in PATH. If you do not want to use the bundled pandoc, uncheck the corresponding setting and reboot the app.
[10:54:55] [Info] [Config Provider] Writing configuration file to C:\Users\jimcoll\AppData\Roaming\Zettlr\config.json...
[11:01:15] [Info] [R] [Main Window] G:\james.coll\20220227204033.md (index.js:2)
[11:05:16] [Info] [WATCHDOG] Ignore event: add:G:\james.coll\20220318110514.md
[11:05:21] [Info] [R] [Main Window] G:\james.coll\20220318110514.md (index.js:2)
[11:05:24] [Info] [Config Provider] Writing configuration file to C:\Users\jimcoll\AppData\Roaming\Zettlr\config.json...
[11:18:28] [Info] さようなら！ Shutting down at Fri Mar 18 2022 11:18:28 GMT-0500 (Central Daylight Time)
[11:18:28] [Info] Application uptime was: 24 minutes, and 37.602 seconds.
[11:18:28] [Info] [FSAL Cache] Cleaned up cache: Removed 0 remnants.
[11:18:29] [Info] [Stats Provider] Writing statistics to file
[11:18:34] [Info] [Citeproc Provider] Loading CSL locale file at G:\Zettlr\resources\app.asar\.webpack\main\assets\csl-locales\locales-en-US.xml ...
[11:18:34] [Info] こんにちは！ Booting Zettlr at Fri Mar 18 2022 11:18:34 GMT-0500 (Central Daylight Time).
[11:18:34] [Info] Registering custom protocol safe-file
[11:18:35] [Info] [Translation Provider] No updates available.
[11:18:35] [Warning] [Assets Provider] Found outdated filter links.lua; copying ...
[11:18:35] [Warning] [Assets Provider] Found outdated filter tags.lua; copying ...
[11:18:35] [Info] [Stats Provider] Writing statistics to file
[11:18:35] [Info] [Window Manager] Loading state information from C:\Users\jimcoll\AppData\Roaming\Zettlr\window_state.json
[11:18:35] [Info] [Window Manager] Window Manager started.
[11:18:35] [Info] [Dictionary Provider] Loaded dictionaries: en-US
[11:18:35] [Info] [Citeproc Provider] Parsing file G:\james.coll\Dropbox\root\resources\ZoteroDBase.json as CSL JSON ...
[11:18:35] [Info] [Citeproc Provider] Database G:\james.coll\Dropbox\root\resources\ZoteroDBase.json loaded (355 items).
[11:18:35] [Info] [Update Provider] Checking for application updates ...
[11:18:35] [Info] [Updater] Checking https://zettlr.com/api/releases/latest for updates ...
[11:18:36] [Info] [Update Provider] No new update available. Current version is v2.2.4.
[11:19:15] [Warning] [FSAL Directory] Path G:\james.coll took 38698.08869999647ms to load.
[11:19:19] [Warning] [FSAL] Path G:\james.coll took 43579ms to load.
[11:19:19] [Info] [FSAL] Loaded all files and workspaces in 43.579797200009224 seconds
[11:19:19] [Info] [Document Manager] Restored 6 open documents.
[11:19:19] [Info] [Application] Added G:\Zettlr\resources to PATH.
[11:19:19] [Info] [Application] The bundled pandoc executable is now in PATH. If you do not want to use the bundled pandoc, uncheck the corresponding setting and reboot the app.
[11:19:25] [Info] [Config Provider] Writing configuration file to C:\Users\jimcoll\AppData\Roaming\Zettlr\config.json...
[11:22:45] [Info] [R] [Main Window] G:\james.coll\20220318110514.md (index.js:2)
[11:29:53] [Info] さようなら！ Shutting down at Fri Mar 18 2022 11:29:53 GMT-0500 (Central Daylight Time)
[11:29:53] [Info] Application uptime was: 11 minutes, and 20.395 seconds.
[11:29:53] [Info] [FSAL Cache] Cleaned up cache: Removed 0 remnants.
[11:29:54] [Info] [Stats Provider] Writing statistics to file
[11:29:54] [Info] [Config Provider] Writing configuration file to C:\Users\jimcoll\AppData\Roaming\Zettlr\config.json...
[11:30:00] [Info] [Citeproc Provider] Loading CSL locale file at G:\Zettlr\resources\app.asar\.webpack\main\assets\csl-locales\locales-en-US.xml ...
```

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.4., behavior was also present in 2.2.3

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment] 2022-03-18 17:53
> In my idealized workflow I use zettlr as a sort of super-enhanced version of the windows folder explorer.

I think that might be the problem. Zettlr's file manager can do most of what the Windows explorer can do, but that is just intended so that you don't have to run to the explorer whenever you want to do something with your files. In other words, it's just there as a convenience so you don't have to leave the app just to move a file around. It really hasn't been designed to load in hundreds of thousand files. In principle it should be able to do so, but it really hasn't been optimized for that.

Rather, the intended use case is to have basically one big directory tree that (mostly) consists of only Markdown files, and another big directory tree for data and whatelse it is you do for a living. So Zettlr has been designed with a large amount of Markdown files in mind (>10k), but not necessarily for chewing through Terabytes of files. That is something that the explorer should be doing (plus, there are thousands of speed improvements in the Windows explorer that make it capable of doing so).

So first, it's not a bug but rather attempting to use Zettlr for a use-case it was not intended for, and I would argue to close this issue in favor of #3296.

I do appreciate trying it out, though, and apparently at times it is indeed succeeding :D

**Closed by nathanlesage** 2022-03-18 17:53 UTC
Labels: bug

**Comment by JimColl** [comment] 2022-03-18 23:39
Thanks for the clarification.  I'd love to see large database handling as a future use case, in my mind their is still a bit of friction separating text from non-textual content in that two folder structure, but the distinction makes using zettlr a little more consistent at least.
