### ISSUE TITLE
Zettlr is corrupting long .md files

### ISSUE THREAD

**Issue by sedol1339** [Zettlr/Zettlr#5343] opened 2024-08-25 04:59 UTC
### Description

After using Zettlr, I noticed that two of my long files ([like this one](https://github.com/sedol1339/files/blob/main/papers.md)) are cropped, so that about half of the file is removed (at the end of the file). Fortunately, I used github to store changes history, so I restored the file, otherwise this part of the file would be lost. 

Has this happened to anyone else?

### Reproducing

This happened with two files, but I cannot reproduce the problem with Zettlr 3.2.0 and 2.3.0 (the versions I used before). After loading the original file, it is not being cut anymore. So, this is not a reproducible bug report, but this indeed happened. 

### Zettlr version

3.2.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment] 2024-09-02 10:40
There is a chance that this was a bug in an earlier version that has been fixed in newer versions. There were some issues around data loss issues, and iirc the last ones known to me have been fixed in either 3.1 or 3.2. So yeah, it sounds good that the issue is non-replicable anymore. Please observe and close this issue if it hasn't happen again in, say, 6 months. Thanks!

**Closed** 2024-09-02 10:40 UTC
Labels: bug
