### ISSUE TITLE
Titles don't show up in list on `[[` to make internal link (nightly)

### ISSUE THREAD

**Issue by Etienne-TR** [Zettlr/Zettlr#3909] opened 2022-11-16 12:45 UTC
### Description

Only file ID is displayed.

### Reproducing

It does for instance : 

`[[20220620200958]] 20220620200958`

Well it's probably already known and in some todo lit but I don't know where to check that so, I do a bug report just in case.

### Zettlr Version

Nightly

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04.1 LTS

**Comment by halloichbingunnar** [comment] 2022-11-18 09:40
same here (Zettlr Nightly, Win10 - all my notes have titles, but they are not displayed:
![Screenshot 2022-11-18 103929](https://user-images.githubusercontent.com/64837252/202670761-52888ef8-1378-48a9-9b48-782eaf296644.jpg)

**Comment by nathanlesage** [comment] 2022-12-04 19:07
Please test out tomorrow's nightly and report back if it works then.

If not, please try out if it works after switching back and forth between the open file. (There are some options that do not get applied to opened files yet, I know I need to fix that, but I wanted you to know that this may be the issue here as well)

**Comment by Etienne-TR** [comment] 2022-12-10 18:31
There is still no title in the list, even if I switch between open files.

**Comment by srosenbu** [comment] 2022-12-21 08:48
I am having the same issue with the nighly build from 19.12.2022. I opened a seperate issue, because I  did not see/find this one

[Issue](https://github.com/Zettlr/Zettlr/issues/3986) (I will close it)

Currently, the drop-down menue shows a filename, if the file has no id in it, but if it has an id, the id is shown. As far as I remember, in the stable version both were shown.

**Comment by nathanlesage** [comment] 2022-12-21 20:29
I just realized what the problem is: I have moved the ID into the "info" field of the autocomplete tooltips, which only shows if the entry is actually selected. I have now restored the previous display where the ID was directly part of the entry itself. Please feel free to ping if I still didn't understand the issue!

**Closed** 2022-12-21 20:28 UTC
Labels: bug

**Comment by srosenbu** [comment] 2022-12-22 09:54
I finally managed to snap my display to show what is wrong:

In this example all my files have a meaningful name and an id. Except for two files which do not have an id.
Somehow, it seems to me that if a file has an id, it is shown by default, and only if it is not present, the filename is shown. Thats why in my 2nd picture, there is no info-Box shown because the file has no id.
As far as I understand the lines of code you changed, the label should be the string inside the drop-down menu and the info the pop-up for the selected item. So before your changes, the filename should be the only thing shown in the menu, but somehow it is overwritten by the id in my example. I am not sure if the new label with both filename and id will change this fact. I could be wrong though, since I am not familiar with the rest of the code.

![drop-down1](https://user-images.githubusercontent.com/69848361/209103937-59c4b455-9d37-42d4-8932-52e8eb9dd620.png)
![drop-down2](https://user-images.githubusercontent.com/69848361/209103954-28b8b266-a0d9-43e1-846f-fa8e029692b0.png)

**Comment by nathanlesage** [comment] 2022-12-22 10:25
Yes, I just found the bug. Now it shows as expected. The bug was related to some other part of the code that I didn't think about. See attached commit!
