### ISSUE TITLE
Main window top cannot be resized

### ISSUE THREAD

**Issue by seppedl** [Zettlr/Zettlr#1516] opened 2020-12-14 08:06 UTC
## Description
When trying to resize the Zettlr window in Windows 10, the top window border does not allow for resizing.

## Reproducing
Open the application in Windows 10 and try to resize the window from the top. On the other borders an up-down or lef-right arrow appears. On the top border not.

## Expected behavior
Allow resizing a window from the top window border

## Platform
 - OS and version: Windows 10 64-bit, 20H2
 - Zettlr Version: 1.8.2

## Additional information
--

**Comment by nathanlesage** [comment] 2020-12-14 09:34
It may be that it nevertheless works, but the arrow doesn't show up. There have been some complaints on the Electron issue tracker regarding this, and as far as I know despite the oddities, resizing should be possible. Would you mind to try this out?

**Comment by seppedl** [comment] 2020-12-14 16:07
Thank you for your fast replies. I have tried it and regretfully, it doesn't work. The issue is larger than the cursor not showing, the top window border is not resizable.

**Comment by tordeu** [comment] 2020-12-14 17:52
I noticed something that might be related. In Linux, using the AppImage, Zettlr cannot be resized and is displayed without window borders by default (using OpenSUSE Tumbleweed and KDE Plasma). After manually adding window borders or after switching to fullscreen and back, resizing is possible. 

I just downloaded the alpha/beta releases to find out, when this problem was introduced and for me it was 1.8.0-alpha.3. Seppedl, could you check, if this is the same for you? That 1.8.0-alpha.2 works, but 1.8.0-alpha.3 introduces the problem you described?

**Comment by nathanlesage** [comment] 2020-12-14 18:07
@tordeu This sounds like a very good narrowing down already, I'm watching this issue as soon as you come up with at most a few commits where somewhere the problem has been introduced, and then I can have a look!

**Comment by tordeu** [comment] 2020-12-14 23:42
I have not looked at the code, but I did find the commit: [3ffc47e](https://github.com/Zettlr/Zettlr/commit/3ffc47ec818de84686aa2dd3d8060c698fe35b8b) "Major renderer refactor and clean up". It worked in the commit before (c23978e), but in 3ffc47e, the border is gone. I can't test it on windows, yet. But I might be able to do so towards the weekend.

**Comment by nathanlesage** [comment] 2020-12-15 06:54
@tordeu this suspiciously sounds like a small bug with the Electron framework on these platforms ...? I don't know, but probably, Slack (or VSCode, anything with frameless windows) would then possibly exhibit the same problem.

**Comment by tordeu** [comment] 2020-12-19 09:44
@seppedl Could you try to enable "Use native window appearance" under Preferences > Advanced? This makes the window resizable for me.

@nathanlesage I just tested it with 1.8.3. At first, the problem was still there, but after maximizing the window once, resizing worked as expected, even with the frameless window and even after restarting the application multiple times. I could still reproduce it with 1.8.1, but 1.8.3 continued to work. Because it did no work the first time when I started 1.8.3, I thought that something in the config must have changed, so I deleted ~/.config/zettlr. I could not investigate this specific problem any further, because now the window starts maximized every time. But since it worked with 1.8.3 after the initial hiccup, the issue is resolved for me, anyway. I am curious, if @seppedl can confirm this.
I did however find a new problem of ~/.config/zettlr/windows_state.json not updating correctly(=at all) and will have a look now, if this is already reported and otherwise open a new issue.

**Comment by seppedl** [comment] 2020-12-19 13:21
I just tested it in 1.8.3 and I can confirm the behavior described. After maximizing the window once, the resizing works as expected with the frameless window and with the framed window. This is a workaround, sufficient for my needs.

**Comment by nathanlesage** [comment] 2020-12-19 19:57
> After maximizing the window once, the resizing works as expected with the frameless window and with the framed window.

It might make sense to open an issue on the main electron repository, because it seems this might be an odd behaviour introduced in Electron 11 (I switched somewhere between 1.8 and one of the three patches from Electron 10 to 11)

**Comment by torgeros** [comment] 2021-09-28 14:28
This is not a problem with Zettlr 2.0.0-beta4 one Win11 as the program bar has been replaced with Windows' default. Resizing works fine on all sides and corners.

**Comment by nathanlesage** [comment] 2021-09-28 22:04
Can confirm that this is also the case on Windows 10. Seems to be an electron bug that has been resolved in the meantime.

**Closed by nathanlesage** 2021-09-28 22:04 UTC
Labels: pinned
