### ISSUE TITLE
Broken Symlink and Desktop File

### ISSUE THREAD

**Issue by inquisitiv3** [Zettlr/Zettlr#1317] opened 2020-09-29 11:34 UTC
## Description

When installing Zettlr a symbolic link is created (`/usr/bin/zettlr -> /opt/Zettlr/zettlr`), but the path that the link is pointing to doesn't exist. The actual path to the binary is `/opt/Zettlr/Zettlr` (capital 'Z' in the binary name).

The desktop file `/usr/share/applications/zettlr.desktop` also contains the broken path to the binary (`/opt/Zettlr/zettlr`).

## Reproducing

```
# apt install ./Zettlr-1.8.0-alpha-amd64.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'zettlr' instead of './Zettlr-1.8.0-alpha-amd64.deb'
The following NEW packages will be installed:
  zettlr
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/65.7 MB of archives.
After this operation, 259 MB of additional disk space will be used.
Get:1 /home/ao/Downloads/Zettlr-1.8.0-alpha-amd64.deb zettlr amd64 1.8.0-alpha [65.7 MB]
Selecting previously unselected package zettlr.
(Reading database ... 345802 files and directories currently installed.)
Preparing to unpack .../Zettlr-1.8.0-alpha-amd64.deb ...
Unpacking zettlr (1.8.0-alpha) ...
Setting up zettlr (1.8.0-alpha) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.2+elementary2~ubuntu5.0.1) ...
Processing triggers for bamfdaemon (0.5.3+18.04.20180207.2-0ubuntu1) ...........] 
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for shared-mime-info (1.9-2) ...
Processing triggers for gnome-menus (3.13.3-11ubuntu1.1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for mime-support (3.60ubuntu1) ...

$ whereis zettlr
zettlr: /usr/bin/zettlr

$ ls -l /usr/bin/zettlr
lrwxrwxrwx 1 root root 18 Sep 29 13:07 /usr/bin/zettlr -> /opt/Zettlr/zettlr

$ ls -l /opt/Zettlr|rg ettlr
-rwxr-xr-x 1 root root 127524472 Sep 23 19:43 Zettlr

$ /opt/Zettlr/zettlr
bash: /opt/Zettlr/zettlr: No such file or directory

$ /opt/Zettlr/Zettlr
[Application starts]
```

## Expected behaviour

- The symbolic link `/usr/bin/zettlr -> /opt/Zettlr/Zettlr` is created.
- The file `/usr/share/applications/zettlr.desktop` contains the correct path to the binary (`/opt/Zettlr/Zettlr`).

## Platform
 - OS and version: elementary OS 5.1.7 Hera
 - Zettlr Version: 1.8.0-alpha (downloaded 2020-09-29)

**Comment by nathanlesage** [comment] 2020-09-29 14:49
Duplicate of #1304

**Closed by nathanlesage** 2020-09-29 14:49 UTC
