### ISSUE TITLE
Citations wrongly displaying inside tables

### ISSUE THREAD

**Issue by pstadler1990** [Zettlr/Zettlr#3412] opened 2022-04-25 09:14 UTC
### Description

When using citations inside of tables, there is a rendering bug and the citations aren't working, neither when copy-pasting the citation from outside the tables nor using the '@' - key to enable the dropdown menu.

When copy-pasting the citation (@-notation) from somewhere else, the brackets aren't resolved correctly and the date's last digit is copied into the brackets (see screenshot for clarification).

When exporting the table, the citations aren't resolved and the fields are blank.

### Reproducing

Add a table and try to add a citation using the '@' notation inside one of the cells.
<img width="790" alt="bug_zettlr" src="https://user-images.githubusercontent.com/20464813/165058741-01a58971-ad2f-48a0-aa0d-3420d5570f6e.PNG">

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by ailintom** [comment] 2022-05-12 07:17
This issue was already raised in  #620

**Comment by nathanlesage** [comment] 2022-05-14 16:04
As clarification:

1. The fact that some brackets are "left over" in rendering is indeed a bug
2. That there is no dropdown is **not a bug**, it is rather a not-yet-implemented feature. (There is a difference).
3. Regarding "When exporting the table, the citations aren't resolved and the fields are blank." --> This almost sounds like a bug within Pandoc. Feel free to get in touch with them in this regard.

**Comment by ailintom** [comment] 2022-05-15 14:21
Concerning https://github.com/Zettlr/zettlr-docs/pull/142 

one cannot say that it does not affect functionality, when parts of the text disappear. Example: 
TableEditor turned off, all renders turned off: 
![image](https://user-images.githubusercontent.com/24455000/168477520-18260c40-9023-4b0e-b2ef-e68fc05fd255.png)

TableEditor turned off, render citations turned on: 
![image](https://user-images.githubusercontent.com/24455000/168477331-be06396e-40d8-467b-9e9f-651a0d50d863.png)
TableEditor turned on, render citations turned on: 
![image](https://user-images.githubusercontent.com/24455000/168477356-f5008889-df7d-449d-b800-842b637d1688.png)
Large portion of the text disappears when I turn on the table editor

**Comment by nathanlesage** [comment] 2022-05-15 14:33
This is precisely what I stated: it's a rendering bug. Annoying but not data-critical.

**Comment by nathanlesage** [comment] 2022-06-03 16:32
This has been fixed with https://github.com/Zettlr/Zettlr/commit/00a4060a668c859c4a5d94b83f34ada50d2853ed

**Closed by nathanlesage** 2022-06-03 16:32 UTC
Labels: bug
