### ISSUE TITLE
[Bug] Recent Documents is always empty

### ISSUE THREAD

**Issue by efficacy** [Zettlr/Zettlr#2941] opened 2021-12-18 17:29 UTC
### Description

Even after using Zettlr for a long session including opening, editing and closing lots of files, the "recent documents" list is always empty.
![Zettlr-recent](https://user-images.githubusercontent.com/51254/146650154-0490ca50-0365-4309-8a1b-cfb6912797b1.png)

### Reproducing

1. Open Zettlr, open one or more files, do stuff with them.
2. Select File::Recent Documents, observer that it always says "Empty"

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.3 and 2.1b1

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

### Additional Information

My Zettlr workspace is on Google Drive using Google Drive for Desktop, so that my work is always backed up. However, I don't think this is key to the problem, as even if I create a new Markdown file and save it elsewhere (such as in my Documents folder) it still fails to appear in Recent Documents.

**Comment by nathanlesage** [comment] 2021-12-19 01:19
Thanks for opening the issue!

I just tested it and there seems to be an issue with the registration of the app with Windows. I'm not quite sure what the issue is, but it's not a logical error in my code for once.

**Comment by nathanlesage** [comment] 2021-12-19 10:33
I found something maybe of value. The electron docs state:

> To use this feature on Windows, your application has to be registered as a handler of the file type of the document, otherwise the file won't appear in JumpList even after you have added it.

That being said: Is Zettlr a default handler for Markdown-files …? On macOS registration works fine, but on Windows I'm relying on electron-builder and I may have made an error there.

**Comment by efficacy** [comment] 2021-12-19 15:17
On my PC Zettlr is not the default handler for markdown files (that happens to be Markdown Pad which I installed some time ago, before I first encountered Zettlr)
Worse, though, Zettlr does not appear at all in the list of possible applications to use to open markdown files. The short list is Chrome and VS Code, the longer list includes those plus several Adobe applications, the rest of the browsers, Calibre, Kindle, Mendeley, PyCharm, Word, Notepad, and even Paint (!), but no Zettlr.

**Comment by nathanlesage** [comment] 2021-12-19 15:32
> Worse, though, Zettlr does not appear at all in the list of possible applications to use to open markdown files.

This indicates that indeed I'm not correctly registering Zettlr as being able to open Markdown files. The culprit file should be that here: https://github.com/Zettlr/Zettlr/blob/develop/electron-builder.yml

Specifically the `fileAssociations` section:

https://github.com/Zettlr/Zettlr/blob/da6cc9fae6f49c8e60ae99b0036c821c0a114f3b/electron-builder.yml#L9-L27

Corresponding documentation: https://www.electron.build/generated/platformspecificbuildoptions

**Comment by nathanlesage** [comment] 2021-12-19 15:34
Okay, [stackoverflow to the rescue](https://stackoverflow.com/a/53538183):

> The reason [`perMachine: true`] is needed, is because on Windows, per-user installed program cannot register file associations, and that is the default setting.

However, that is not documented. Mh. I'm going to have to try it out. Feel free to test as well

**Comment by efficacy** [comment] 2021-12-19 17:57
Does this approach imply that, even when it is working, the only files which will appear in "Recent documents" are ones which are registered (i.e. .md and .markdown) ?
I sometimes store other _textual_ files in my Zettlr folder structure (text files, shell scripts, JSON files etc.) and use Zettlr to edit them, which works very well. Will these other files be "invisible" to the Recent documents mechanism? This would seem odd, as they are happily picked up by the Ctrl-[ and Ctrl-] navigation history.

**Comment by nathanlesage** [comment] 2021-12-19 19:35
> Does this approach imply that, even when it is working, the only files which will appear in "Recent documents" are ones which are registered (i.e. .md and .markdown) ?

Yes, but _registering_ a file doesn't mean setting yourself as the default handler. I would obviously need to update that section to include all other files that Zettlr can open. Otherwise it would be a tad unfunny :D 

But … how are you editing shell scripts? As far as I remember Zettlr shouldn't enable you to edit an `.sh`- or `.ps`-file o.o

**Comment by nathanlesage** [comment] 2021-12-19 22:13
Found the issue: For those recent documents to work, the app MUST be installed "per machine", and not per user. So now we know what these elevated admin rights are for during installation.

I will be adding a warning to the documentation that users should, unless there is reason to, install the app for all users instead of just for them. This way it'll work just fine!

You can just re-install the current version without uninstalling the current one; the installer will make sure to remove the user-installation before installing Zettlr again system-wide. Settings etc. will be retained!

**Comment by efficacy** [comment] 2021-12-19 22:45
> But … how are you editing shell scripts? As far as I remember Zettlr shouldn't enable you to edit an `.sh`- or `.ps`-file o.o
Good point. I hadn't noticed that Zettlr had assed an invisible .md to the end of the filename. In most cases such files are just a "swipe file" to copy stuff from, so I had never tried to run one directly.

If I change the name to xxx.sh or just xxx with no extension if mysteriously vanishes from the Zettlr file manager.
Is there any reason _why_ Zettly should not let me create and edit any textual file? Why does it hide files at all?

**Comment by nathanlesage** [comment] 2021-12-20 02:02
> so I had never tried to run one directly.

As long as you add the shebang, it should actually work, I think :D 

> Why does it hide files at all?

Because in principle Zettlr can in fact edit all files, but if I were to allow, e.g., sh scripts, then there's no reason why not also C++ files, Rust files, etc., and then people will ask if it might be possible to add linters and all kinds of stuff. I wanna keep Zettlr text-only as much as possible. Editing .tex-files is possible for templates, .yaml-files and .json-files for Pandoc configs, but I really want to keep the focus on text-only. Plus, if you do need to edit Shell scripts or the likes, VS Code is much better for those either way! So it's more an artificial constraint that keeps the focus of Zettlr on text files!

**Comment by EcoFin** [comment] 2021-12-31 16:49
Version 2.1.0 beta on Win10 Edu

I too have been wondering why "Recent Documents" is always empty.  I have just tried the "reinstall for all users" process (without touching my previous "user only" install).  It went fine (in the sense that nothing is broken afterwards) ... but **still nothing** in Recent Documents.  I have opened and closed Zettlr a couple of times  to see if it would eventually notice the  currently active tabs.  That didn't work.  I tried closing and then reopening some tabs to see if that would halp.  Still nothing.  

As a final test, I closed all open tabs, shut down Zettlr, reopened it and reopened all necessary documents. Nothing whatsoever in "Recent Documents".  So apparently there is more to the problem.  I haven't gone through the registry yet to see if there is some key remaining from the previous install.

Admittedly, I do not have Zettlr set as the default editor for .md files, but it does appear on the short list of available options for opening them.

**Comment by nathanlesage** [comment] 2021-12-31 21:16
> Admittedly, I do not have Zettlr set as the default editor for .md files

Would you mind trying if that changes anything?

**Comment by EcoFin** [comment] 2021-12-31 21:45
Hendrick,

 

I’m afraid that doesn’t help.  I upgraded from the 2.1.0beta to the 2.1.0 final; then set zettlr as default app for .md files.

Tried all the shut down/restart; delete file, add it again, shut down,. Restart.

 

Recent docs is always empty.

 

Regards

ay

**Comment by nathanlesage** [comment] 2022-01-01 20:18
Aaaah. The recent documents work down on the jump list:

![image](https://user-images.githubusercontent.com/17251683/147859375-5780d9b2-6cd0-4757-8bed-b48ae85a70c0.png)

Electron even mentions that what I have added only manages the list for the jump list but not for the menu. Grrrrr.

**Comment by EcoFin** [comment] 2022-01-01 22:41
That is true, now that I look for it – I’ve never tried to work with Electron save as a user so it would never have crossed my mind.  

The only time I would use a taskbar icon would be to try to shut an application that has become unresponsive!

 

I am one of those people who keep a lot of tabs open, so discovering the scroll-wheel trick in Zettlr was really helpful.

 

I do use the recent documents list a good deal in Notecase Pro which also has a tabbed screen layout but no scroll-wheel facility.

 

best regards

ay

**Comment by efficacy** [comment] 2022-04-29 13:08
Just bumping this, as it still does not work in 2.2.5

**Comment by nathanlesage** [comment] 2022-04-29 19:38
@efficacy Just to be clear, I just reread the thread. Is the following inference correct?

> On Windows, the `recent Documents` only affect the jump list, even if installed for all users (i.e. with elevated rights)?

If so, I can simply enable the recent documents provider to also care for Windows, and not just for Linux. Should be as simple as one line of code.

**Comment by EcoFin** [comment] 2022-04-29 23:05
That is what I have found on Win 10.  Jump list has document list; Recent Docs is empty.

I reinstalled I for all users some time ago as you suggested.

 

Regards

arthur

**Comment by nathanlesage** [comment] 2022-05-31 21:13
> Should be as simple as one line of code.

Update: It was two lines of code.

**Closed** 2022-05-31 21:12 UTC
Labels: bug
