### ISSUE TITLE
Yaml header converted to table

### ISSUE THREAD

**Issue by ecodiv** [Zettlr/Zettlr#1390] opened 2020-10-31 08:41 UTC
## Description
In the latest 1.8 beta, Yaml headers are rendered as tables as soon as you click somewhere in the document outside the Yaml.  Up to so far, it is just Zettlr rendering the Yaml header as table. As soon as you click inside the to table converted Yaml header, it is actually changed (how depends on the content of your Yaml header).

## Reproducing
1. Create a new file
2. Add a Yaml header
3. Close and open the file again
4. Click anywhere in the document, outside the Yaml header
5. Yaml header is now rendered as a table.
6. Click inside the as table rendered Yaml header
7. Close and open file
8. Yaml header has been changed
8a.  If the Yaml header consists of a title only, the upper three dashed are removed in step 8

```
tit
---
```

8b. If the Yaml header also contains keywords, the Yaml header is replaced by the below:

```
tit  
-----
key  
```
     
## Expected behaviour
Yaml header rendered as such. No changes in the Yaml header when clicking in it.

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.8.0-beta

**Comment by the-solipsist** [comment] 2020-10-31 10:03
This might have been fixed in https://github.com/Zettlr/Zettlr/commit/f79fd680a06574ad0e4809b0c485b3c06ab4406f. Please check.

**Comment by ecodiv** [comment] 2020-10-31 13:43
Hi @the-solipsist not sure how to do that, sorry. Should I wait till the next beta, or is there another way (other than compiling, which I am really not sure how to do on Windows)?

**Comment by nathanlesage** [comment] 2020-10-31 17:04
@the-solipsist Unfortunately not, this was a regression error I accidentally re-introduced as I forgot that the sanity-check which you have linked needs to check the _first_ character of the last potential-table-line, rather than the last one. It's fixed in 1e9c1ac

**Closed** 2020-10-31 17:04 UTC

**Comment by the-solipsist** [comment] 2020-11-01 20:06
Thanks, @nathanlesage for getting it fixed quickly!

@ecodiv, for now, a workaround seems to be using `...` to end the YAML metadata block.  Given the troubles I had been having with Zettlr misinterpreting `---`, I opted for that as standard practice so didn't even notice the regression :-)

**Comment by nathanlesage** [comment] 2020-11-02 19:17
> @ecodiv, for now, a workaround seems to be using ... to end the YAML metadata block. Given the troubles I had been having with Zettlr misinterpreting ---, I opted for that as standard practice so didn't even notice the regression :-)

Yes! (Albeit, caveat: For Jeckyll as a target, the frontmatter needs to end with `---`, not `...`, unfortunately …)

**Comment by the-solipsist** [comment] 2020-11-03 07:32
> Yes! (Albeit, caveat: For Jeckyll as a target, the frontmatter needs to end with `---`, not `...`, unfortunately …)

I'm not sure that is true since at least 2015:

https://github.com/jekyll/jekyll/blob/2807b8a012ead8b8fe7ed30f1a8ad1f6f9de7ba4/lib/jekyll/convertible.rb#L48
and
https://github.com/jekyll/jekyll/blob/7c4f319442b6b7a457d35cef2fc1b7a480b30850/lib/jekyll/document.rb#L9

So, given that Jekyll [at least now](https://github.com/jekyll/jekyll/issues/3674) supports the YAML specs, it may not be useful to deviate from the specs.

**Comment by nathanlesage** [comment] 2020-11-03 09:18
Ah alright; I only remember seeing the docs stating the dashes as separators ...

But anyway, dashes are also an option for Pandoc, so I think keeping it is the best way for now.
