### ISSUE TITLE
Custom CSS for reducing checked items' contrast is broken

### ISSUE THREAD

**Issue by chiphogg** [Zettlr/Zettlr#4951] opened 2024-02-12 16:01 UTC
### Description

The CSS in [this comment](https://github.com/Zettlr/Zettlr/issues/1583#issuecomment-957735805) from #1583 no longer has any effect.

### Reproducing

Set custom CSS in the preferences menu:

```css
.task-item-done {
    opacity: 0.5 !important;
    text-decoration: none !important;
}
```

Then set some checkboxes.

```
- [ ] This should be normal
- [x] This should be low-contrast and struck through
```

Observe that the second is styled identically to the first, except for the checked checkbox.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.5

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04

### Additional Information

I installed via dpkg from a .deb download.

**Comment by nathanlesage** [comment] 2024-02-12 17:17
> I believe my previous version (which I just upgraded from this morning) was 2.3.0.

That was outdated a long time ago. I did include in the Changelog an indication that the CSS rules have changed a lot and that this means that Custom CSS needs to be adapted. Please head over to the [Discord](https://go.zettlr.com/discord), there are many who are very good with applying custom CSS and may be able to help you.

Closing since this is not a bug.

**Closed by nathanlesage** 2024-02-12 17:17 UTC
Labels: bug

**Comment by chiphogg** [comment] 2024-05-06 14:02
This worked for me:

```
.cm-line input[type="checkbox"]:checked,
.cm-line input[type="checkbox"]:checked ~ .cm-content-span {
    opacity: 0.4 !important;
    text-decoration: none !important;
}
```

To be able to see the CSS in the editor, and interact with it, here are the steps.

1. Make sure that "Debug mode" is enabled in settings (I found this under "Advanced").
2. Under the "Develop" menu, click "Toggle developer tools".

This opened up a console.

Many thanks to CoopCoding on the Zettlr discord for this advice!
