### ISSUE TITLE
No Cursor on macOS Sonoma/Ventura Any Mac - caused by Errant Autocorrect entry

### ISSUE THREAD

**Issue by jd101k2000** [Zettlr/Zettlr#4961] opened 2024-02-14 16:00 UTC
### Description

When I use Zettlr 3.0.5 on my Intel Mac there is no cursor.
I can click and select text, but there is no cursor. This means that I cannot use arrow keys, as there is no cursor!

Using the same version of Zettlr on my MacBook Air (M1) does NOT have the same issue.

### Reproducing

In installed Zettlr on macOS Ventura on my Intel Mac Mini.
No cursor.

I did not have the same problem on my Macbook (M1) Sonoma, so I upgraded my Mac Mini to Sonoma 14.3.1 to see if this fixed the problem. It did not.
**Update** I have been able to replicate this on an M1 Mac, see comments below.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.5

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [x] ARM 64bit

### Operating System Version

Sonoma

### Additional Information

The app seems to work fine, but there is no cursor.
I do not have any custom CSS.
I have tried several different themes in case that was the problem.

**Comment by nathanlesage** [comment] 2024-02-14 17:51
Just to clarify: Do you mean the text cursor inside the editor, or your mouse cursor?

Also, given that it works on one computer and not on another (+ I cannot reproduce it with an M2 Pro on Sonoma 14.3.1) makes a bug in Sonoma for Intel a likely candidate for this, in which case I could not help out.

**Comment by Mela** [comment] 2024-02-15 00:01
On Intel Mac (Sonoma) & 3.0.5 and can't reproduce it either. Both mouse and editor cursor look fine. 

Installed an OS update yesterday though that addressed some display issues. Maybe @jd101k2000 could check if he'd already installed it?

**Comment by jd101k2000** [comment] 2024-02-15 11:10
It is the edit cursor that is missing.
Yes, I do have the latest 14.3.1 update.

**Comment by jd101k2000** [comment] 2024-02-15 14:38
Tried changing themes and realised it was not changing the highlighting.

deleted the config.json file and this fixed it.

So I compared old config to new config and found something interesting.

In autocorrect I had put in a blank string with '-' as the replacement.
This had created in config.json (first key/value is standard, the new value is what had been created.)

    {
     "key": "...",
     "value": "…"
    },
    {
     "value": "—"
    }

(You can see the second entry has a value but no key.)

At this point the theme still worked, but when I restarted Zettlr, the theme was ignored and the cursor could not appear. In other words, I had managed to recreate the problem.

I tried creating a similar entry in autocorrect on my M1 Mac and the same problematic behaviour happened.

Bizarrely, when I deleted the problematic autocorrect entry, the theme returned to normal **without** requiring a restart of Zettlr.

I would suggest that in a future release that it is not possible to save an autocorrect entry with a blank string value.

**Comment by jd101k2000** [comment] 2024-02-15 14:45
I tried this with earlier v3 (e.g. 3.0.0, 3.0.3) of Zettlr and the same thing happened. So this behaviour is not specific to 3.0.5

**Comment by nathanlesage** [comment] 2024-02-15 19:22
Perfect, thank you very much for searching the root cause, this helps me immensely.

**Comment by max-l** [comment] 2024-02-29 14:35
I have the same issue (disappearing cursor) on Ubuntu 22.04 Zettlr 3.0.5

1. Highlighting does not work, 
2. The cursor is not visible.

The problem happens on a specific file, restarting Zettlr doesn't help, but editing other files works without problems.

Restarting Zettlr did not fix.

I had a table in the file, the problem started while editing the table.

When I deleted the table, the problem went away. 

So unfortunately I don't have the file to submit in the issue.


Zettlr Version: 3.0.5 (UUID: bcdbf48a-c078-4f7a-bf8c-4576aa64de6b)

```
System: linux 6.5.0-18-generic (architecture: x64)

Build Dependencies
This build was compiled using
Node.js v18.18.2
Electron v28.2.1
Chrome v120.0.6099.268
v8 engine v12.0.267.18-electron.0
Zlib v1.2.13.1-motley
OpenSSL v1.1.1


```

**Comment by jpsych** [comment] 2024-04-02 08:08
> I have the same issue (disappearing cursor) on Ubuntu 22.04 Zettlr 3.0.5
> 
> 1. Highlighting does not work,
> 2. The cursor is not visible.
> 
> The problem happens on a specific file, restarting Zettlr doesn't help, but editing other files works without problems.
> 
> Restarting Zettlr did not fix.
> 
> I had a table in the file, the problem started while editing the table.
> 
> When I deleted the table, the problem went away.
> 
> So unfortunately I don't have the file to submit in the issue.
> 
> Zettlr Version: 3.0.5 (UUID: bcdbf48a-c078-4f7a-bf8c-4576aa64de6b)
> 
> ```
> System: linux 6.5.0-18-generic (architecture: x64)
> 
> Build Dependencies
> This build was compiled using
> Node.js v18.18.2
> Electron v28.2.1
> Chrome v120.0.6099.268
> v8 engine v12.0.267.18-electron.0
> Zlib v1.2.13.1-motley
> OpenSSL v1.1.1
> ```

Hi, I believe your issue is different. This bug (not yours) is fixed by clearing out null entries in autocorrect.
I think your bug is not fixed in this way, but is a problem with tables. You may wish to open a separate bug report.

All the best,

jd101k2000

**Closed** 2024-04-28 15:34 UTC
Labels: bug
