### ISSUE TITLE
[Feature] revision mode - different font colors

### ISSUE THREAD

**Issue by YetAnotherAccount5345f** [Zettlr/Zettlr#3106] opened 2022-01-30 12:10 UTC
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

A feature to have different colors for the revision process would be very helpful.

https://www.reddit.com/r/Zettlr/comments/sfr5bm/any_kind_of_revision_mode_possible/

### Example Workflow

1. Manuscript finished
2. Time to revision and polish it
3. Going back some chapters and adding more words
4. Spending hours writing new stuff
5. Wait, which words are new. And where? I wish I could see that in a different color.

### Caveats

None

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

**Comment by nathanlesage** [comment] 2022-01-30 12:14
Duplicate of #728

**Closed by nathanlesage** 2022-01-30 12:14 UTC
Labels: feature

**Comment by menelic** [comment] 2022-03-23 13:35
having read #728 I think this is not a duplicate - @YetAnotherAccount5345f is describing a "highlight recent changes" or "browse document history with color coded text by time text was added" whereas #728 is about handling of revisions via a track-changes like functionality, e.g. to cross-revise  co-authored sections to collaborate with reviewers who use  track changes in docx or odt
