### ISSUE TITLE
Zettlr ask me to save file before quit ?

### ISSUE THREAD

**Issue by mouarfff** [Zettlr/Zettlr#342] opened 2019-09-26 12:57 UTC
Hello

since this morning, each time i change file to edit antoher file, i have this prompt :
"file contain no saved modification"

but nothing looks append after i saved it.

**Comment by nathanlesage** [comment] 2019-09-26 15:24
This notification is sometimes shown if you did not have a directory selected. I have to work it out at some point, this pertains to the general user experience, which is not great if you don't follow the general design principle of Zettlr!

**Comment by mouarfff** [comment] 2019-09-30 11:06
I alway keep my markdown folders ok, i don't change it
it's happend just one day for no reasons.

what do you mean with "don't follow the general design principle of zettlr", it's a religion ? :)

**Comment by nathanlesage** [comment] 2019-10-03 09:13
Nah not that but Zettlr is currently constructed in a way that it doesn't become obvious as to _how_ you are supposed to use the app (hence: NOT open single files, but keep some directories open, etc.)

**Comment by mouarfff** [comment] 2019-10-08 12:27
ok

**Comment by jimvine** [comment] 2019-10-10 09:39
I have also started getting an error saying that a file has been altered asking whether to save or proceed without saving if I change between files.

(Zettlr 1.4.2, Windows 10.)

I think this started when I upgraded to v1.4.

I also think that I am following the Zettlr way - I have all my Zettlr files in one folder. When I open Zettlr it opens with them all listed in the left-hand bar. I only create new files using Zettlr's "+" button, which seems to correctly create the new file in the same folder as all the other files.

The error message happens intermittently for me, so I'm not too sure how to reproduce it or provide more feedback.

One characteristic of it is that clicking the "Save" option does not work. It still doesn't let me change to the other file and still thinks that the first file has unsaved changes. Also, staying in the first file and pressing Ctrl-S (which I assume saves?), and then trying to go to the other file also does not work - if it's in this state it still thinks the file has unsaved changes. The only way to get out of it is to choose the "proceed without saving" option, which does seem to work.

Looking at the files where I've had to do this, it looks like everything I had types is in them - I don't think I've lost any data. But it is a bit disconcerting to have to click a "proceed without saving" option!

**Comment by nathanlesage** [comment] 2019-10-10 11:33
> if it's in this state it still thinks the file has unsaved changes. The only way to get out of it is to choose the "proceed without saving" option, which does seem to work.

Exactly. I'm still not sure as to when and how this happens (so if anybody got a clue how to precisely reproduce the issue, please come forward!), but it's also related to the fact that modifications in the editor are sometimes not propagated correctly to the main process, etc., which leads to these false-flag messages. I have to strictly bind the state to the file itself, not the editor or so. Then it should be easy to spot the bug.

**Comment by mouarfff** [comment] 2019-10-16 17:12
I had this just on time and now all is ok ... :)

**Comment by nathanlesage** [comment] 2019-10-16 20:15
That's great to hear! I think I am also going to close this issue, because my observations over the past months resolved that this issue almost always occurs if there's an error in the main process — as long as there's none this feature works perfectly.

So to everybody stumbling upon this thread in the future: **If Zettlr asks you to save your file, but you effectively can't quit, this means that in the main process some error occurred. So please make sure to then copy the file contents out of the editor to some external program, force-quit the app and please open a new issue trying to explain as precisely as possible what you did before the error occurred so that I can get to it!**

**Closed by nathanlesage** 2019-10-16 20:15 UTC
