### ISSUE TITLE
Trouble with Reveal.js

### ISSUE THREAD

**Issue by Olisse** [Zettlr/Zettlr#1003] opened 2020-07-05 10:08 UTC
## Description

Something strange happens when I export a file with reveal.js.
1. Whatever the template that I choose, the html file is always with a black background and white font.
2. //reveal.js.plugins is added at the bottom of the page 
3. In preview mode, text can be seen on the first slide. The others are blank. 

## Reproducing
Ask to export .md file with reveal.js

## Platform
 - OS and version: macOS 10.15.5
 - Zettlr Version: 1.7

## Additional information

Here a extract from the .html export. 

```<body>
--
  | <div class="reveal">
  | <div class="slides">
  | <!DOCTYPE html>
  | <html>
  | <head>
  | <meta charset="utf-8">
  | <meta name="generator" content="pandoc">
  | <title>export</title>
  | <meta name="apple-mobile-web-app-capable" content="yes">
  | <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  | <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  | <link rel="stylesheet" href="https://unpkg.com/reveal.js@^4//dist/reset.css">
  | <link rel="stylesheet" href="https://unpkg.com/reveal.js@^4//dist/reveal.css">
  | <style>
  | code{white-space: pre-wrap;}
  | span.smallcaps{font-variant: small-caps;}
  | span.underline{text-decoration: underline;}
  | div.column{display: inline-block; vertical-align: top; width: 50%;}
  | div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  | ul.task-list{list-style: none;}
  | </style>
  | <link rel="stylesheet" href="https://unpkg.com/reveal.js@^4//dist/theme/black.css" id="theme">
  | </head>
  | <body>
  | <div class="reveal">
  | <div class="slides">
  |  
  |  
  | <section id="début-du-diapo" class="slide level1">
  | <h1>Début du diapo</h1>
  | <p>Par moi</p>
  | </section>
  | <section class="slide level1">
  |  
  | <p>(on va mettre du texte)</p>
  | </section>
  | <section class="slide level1">
  |  
  | </section>
  | </div>
  | </div>
  |  
  | <script src="https://unpkg.com/reveal.js@^4//dist/reveal.js"></script>
  |  
  | // reveal.js plugins
  | <script src="https://unpkg.com/reveal.js@^4//plugin/notes/notes.js"></script>
  | <script src="https://unpkg.com/reveal.js@^4//plugin/search/search.js"></script>
  | <script src="https://unpkg.com/reveal.js@^4//plugin/zoom/zoom.js"></script>
  | <script src="https://unpkg.com/reveal.js@^4//plugin/math/math.js"></script>
  |  
  | <script>
  |  
  | // Full list of configuration options available at:
  | // https://revealjs.com/config/
  | Reveal.initialize({
  | // Push each slide change to the browser history
  | history: true,
  | math: {
  | mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js',
  | config: 'TeX-AMS_HTML-full',
  | tex2jax: {
  | inlineMath: [['\\(','\\)']],
  | displayMath: [['\\[','\\]']],
  | balanceBraces: true,
  | processEscapes: false,
  | processRefs: true,
  | processEnvironments: true,
  | preview: 'TeX',
  | skipTags: ['script','noscript','style','textarea','pre','code'],
  | ignoreClass: 'tex2jax_ignore',
  | processClass: 'tex2jax_process'
  | },
  | },
  |  
  | // reveal.js plugins
  | plugins: [
  | RevealMath,
  | RevealNotes,
  | RevealSearch,
  | RevealZoom
  | ]
  | });
  | </script>
  | </body>
  | </html>
```

**Comment by nathanlesage** [comment] 2020-07-05 10:52
This is not a revealJS file exported by Zettlr, but a default reveal.js v4 export. I cannot reproduce this behaviour locally — did you by any chance alter the exporting command in Zettlr's advanced preferences? It almost seems as if something's off with the command

**Comment by Olisse** [comment] 2020-07-05 12:34
No. As you'll see, I didn't change anything. To be sure, I reset Pandoc command. 

pandoc "$infile$" -f markdown $outflag$ $tpl$ $toc$ $tocdepth$ $citeproc$ $standalone$ --pdf-engine=xelatex --mathjax -o "$outfile$"

I discovered Zettlr three days ago (thank you, by the way). I installed the previous version (1.6 in my memory). Reveal export worked. Yesterday, I was invited to install the 1.7, but since then, it doesn't work anymore. 

Very strange.

**Comment by nathanlesage** [comment] 2020-07-05 12:58
That is indeed strange, because in different versions of the application, it works just fine for me, and I also have the standard command … I even have the same operating system o_O This is very curious

**Comment by Olisse** [comment] 2020-07-05 14:17
> I even have the same operating system o_O This is very curious

A friend of mine too (10.15.5) and it works well for him with 1.7. 

Last trial, I overwrite the 1.6 with the 17.1 and it's broken again. :-/ 
I don't know if I can do something more.  


Anyway. Zettlr is a great stuff. I'm an academic and a Scrivener User (with Zotpick & Pandoc post-process) and really impressed by this project. 
It's easier to configure and it perfectly fit for some of my projects. 

Many thanks.

**Comment by nathanlesage** [comment] 2020-07-05 20:40
Hmmmmmmmm … what versions of pandoc have you installed? The updated homebrew version?

**Comment by Olisse** [comment] 2020-07-05 20:51
No. Pandoc installation was made with the package for Github. 

https://github.com/jgm/pandoc/releases/tag/2.10

**Comment by nathanlesage** [comment] 2020-07-05 20:57
Mh, still >2.0, so it should be fine … I am puzzled as to what is happening there

**Comment by Olisse** [comment] 2020-07-05 21:33
Maybe a clue. 
I've just installed Zettlr (1.70) on another device with macOS 10.15.5 and Pandoc 2.8.0.1 and the export works fine.

**Comment by nathanlesage** [comment] 2020-07-05 22:15
So maybe it is the pandoc version …?

**Comment by Olisse** [comment] 2020-07-05 22:22
Yes. 
On my older device, i've just upgraded Pandoc (2.8.0.1 -> 2.10) and the bug occurs.

**Comment by nathanlesage** [comment] 2020-07-05 22:34
Oh, interesting o.O

**Comment by nathanlesage** [comment] 2020-07-05 22:35
Alright, Homebrew still has `2.9.2.1` so maybe something changed in 2.10. I'll make sure to check back …

**Comment by PhilipDeussen** [comment] 2020-07-11 18:10
Same issue on Ubuntu 20.04 with Zettlr 1.7.1.
So far I've tried pandoc 2.9 and 2.10 and with both versions the issue exists (Zettlr export commands are set to default). In addition to the template issue the presentation also contains what seems to be a comment from the javascript code (image attached) that is definitively not part of my source md file and only appears to happen with the combination of Zettlr 1.7/1.71 and pandoc 2.9/2.10.
![pandoc_revealjs_export](https://user-images.githubusercontent.com/53941550/87230742-29235d80-c3b2-11ea-9193-1874fb5ee8fe.png)

**Comment by nathanlesage** [comment] 2020-07-13 08:33
Hmm … would you mind sharing a small MD-file for me to test? Just dump the Markdown-code in a code-block here in the comments and I'll check it out!

**Comment by PhilipDeussen** [comment] 2020-07-13 08:41
Sure.
```
# test export

***

slide 1

***

slide 2
```

The link below contains the generated html file with my previously mentioned configuration (just in case it you find it helpful to compare against).

[test_export.revealjs.zip](https://github.com/Zettlr/Zettlr/files/4911247/test_export.revealjs.zip)

**Comment by Olisse** [comment] 2020-07-13 08:53
```
# Start

Name

***

(Text)

*** 

Text 

***

#### End
```
[Test.zip](https://github.com/Zettlr/Zettlr/files/4911345/Test.zip)

**Comment by PhilipDeussen** [comment] 2020-07-13 09:27
Just a had a more detailed look at what is generated in my case. 
1. There are two meta tags for the generator. The first is `Zettlr with Pandoc`, the second just `pandoc`
2. it seems like there are two html pages generated and then somehow merged into one. This is based on the fact that the second `<html>` starts within the `<div class="slides">` of the first body element
3. the actual content is located in the second html page which itself is nested inside the first
4. I manually corrected the mentioned irregularities and it works fine after that (obviously not a solution, just wanted to see if the generated content is correct)

**Comment by nathanlesage** [comment] 2020-07-13 19:59
> the actual content is located in the second html page which itself is nested inside the first

WAIT A MOMENT. This would mean that pandoc in your case is exporting standalone.

Wait, does anybody of you have the "standalone" flag for pandoc hard-coded into your Pandoc command? If so, that would explain a lot

**Comment by nathanlesage** [comment] 2020-07-13 20:00
The reason for this: Currently, the revealJS has to be generated in two steps – first, Pandoc is tasked with rendering the Markdown to the revealJS DOM structure, which is then in a second step taken by Zettlr and merged into the template. This was necessary due to problems regarding the templating and styling of the reveal presentations, but it requires revealJS not to be exported as standalone (which would explain the nested HTML structure)

**Comment by PhilipDeussen** [comment] 2020-07-13 20:06
Yep, "standalone" flag is set in the pandoc command although I am very certain I did not add that to the pandoc command.
I've just tested it without the flag and it seems to work fine for now.

**Comment by nathanlesage** [comment] 2020-07-13 20:08
> Yep, "standalone" flag is set in the pandoc command although I am very certain I did not add that to the pandoc command.

Yeah, there should be a `$standalone$`-variable, which will be replaced either with the flag or not, depending on context. Do you mean this? Or the "real" standalone flag `- s`?

If the latter, it's not supposed to be there, if it's the former, you found the bug! :D

**Comment by Olisse** [comment] 2020-07-13 21:52
Here is the default Pandoc command. 

```
pandoc "$infile$" -f markdown $outflag$ $tpl$ $toc$ $tocdepth$ $citeproc$ $standalone$ --pdf-engine=xelatex --mathjax -o "$outfile$"
```

I confirm. Without this flag, it works.

**Comment by nathanlesage** [comment] 2020-07-14 08:50
@Olisse so without `$standalone$`, right? Then we have a bug!

**Comment by PhilipDeussen** [comment] 2020-07-14 09:01
@nathanlesage Sorry for the confusion earlier, I meant the `$standalone$` variable (as @Olisse mentioned as well).

**Comment by Olisse** [comment] 2020-07-14 18:35
> @Olisse so without `$standalone$`, right? Then we have a bug!

Yes it is. When I delete $standalone$ from the Pandoc command, the export works.

**Comment by Olisse** [comment] 2020-07-15 06:32
Here is (with $standalone$ in Pandoc Command)

````
[08:22:04]	Running Pandoc with command: pandoc "/Users/o**/N**/P**/N*/Zettlr/Folder/export.tmp" -f markdown -t revealjs --filter pandoc-citeproc --bibliography "/Users/o**/N**/Pandoc/Library.bib" --csl "/Users/o**/N**/Pandoc/apa.csl" -s --pdf-engine=xelatex --mathjax -o "/Users/o**/N**/P**/N*/Zettlr/Folder/Test Diapo.revealjs"

[08:22:05]	Successfully exported file to /Users/olivierjanssen/Nextcloud/Psychologie/Notes/Zettlr/Essais/Test Diapo.revealjs.htm

```

This doesn't explain why it works with the same command in Zettlr 1.6 & Pandoc 2.10 for me.

**Comment by nathanlesage** [comment] 2020-07-15 09:30
> This doesn't explain why it works with the same command in Zettlr 1.6 & Pandoc 2.10 for me.

It does. Because I know I have switched something in the exporter shortly before 1.7 was released, and in your command you can see the `- s`-flag, which shouldn't be in there! So there's obviously something wrong in the logic!

**Comment by PhilipDeussen** [comment] 2020-07-15 14:06
I would have assumed that this is due to the fact that in the export.js you check in a switch statement for the format in options but without a case for revealJS. And in the end it defaults to options.standlone = true which as far as I can see would be true for revealJS as well.

**Comment by nathanlesage** [comment] 2020-07-18 16:01
Should work now, if it doesn't in the next release, please comment again!

**Closed** 2020-07-18 16:01 UTC
Labels: bug [non-critical], confirmed, v1.7.x
