### ISSUE TITLE
Generate HTML or PDF not Working even if pandox & xelatex is working

### ISSUE THREAD

**Issue by Arvinsanity** [Zettlr/Zettlr#872] opened 2020-06-03 07:37 UTC
## Description

Check this GIF 
![OUFlP5MSwx](https://user-images.githubusercontent.com/48080735/83608631-c28b7280-a5af-11ea-9a68-633ad878bf64.gif)

Proof that pandoc and xelatex works:
![powershell_yCpjoFfoCo](https://user-images.githubusercontent.com/48080735/83608688-d505ac00-a5af-11ea-9d1d-9dba5429a906.png)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: **v1.7.0-beta.8**

**Comment by nathanlesage** [comment] 2020-06-03 09:28
Duplicate of #870 — TL;DR: already fixed and in upstream, a new release will come in approximately 2 days; export is working fine, only the automatically opening is broken.

**Closed by nathanlesage** 2020-06-03 09:28 UTC
