### ISSUE TITLE
Tag auto-completion doesn't recognise newly added tags until next restart

### ISSUE THREAD

**Issue by hungvvu** [Zettlr/Zettlr#5140] opened 2024-05-06 08:32 UTC
### Description

When adding a new tags, Zettlr tag auto-completion no longer recognises that tag immediately but instead only register it after a restart.

https://github.com/Zettlr/Zettlr/assets/63649200/298fa9f2-97ed-4a6d-9459-eddee1d8ec35

### Reproducing

1. Add a new tag to a note and save the note
2. Go to another node and type out a substring of the previous tag
3. The auto-completion should not complete the tag until the next restart

### Zettlr Version

Stable (most recent version)

### Specify version

Zettlr 3.1.1 stable

### Installation Method

Windows .exe installer

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

**Comment by hungvvu** [comment] 2024-05-06 08:55
I just realised after finishing up recording the video and closing the Zettlr Tutorial workspace that this behaviour is also replicable if you close a workspace and open up a new workspace. The tags from the new workspace don't get registered to both the tag cloud and the auto-completion until the next restart.

**Comment by nathanlesage** [comment] 2024-05-06 13:54
Likely just a missing update listener somewhere in the renderer code

**Comment by ElDuderino321** [comment] 2024-05-30 23:03
Just confirming I'm experiencing the same issue. It would be nice to have it fixed, since it's so fundamental for the functionality and using it as a Zettelkasten.

**Comment by underclockeddev** [comment] 2024-06-20 18:03
This seems like a pretty major regression, no? What's the priority/eta on this? I just found out about this project and this is _almost_ enough to get me to switch to one of the many competitors, since I have barely anything invested in Zettlr yet. Not trying to be naggy, just letting you know this is highly impactful in the new-user experience – as I'm transferring in old notes, I'm using the same few (new) tags many times in a session

**Comment by nathanlesage** [comment] 2024-06-21 13:34
There's nothing stopping you from using whichever tags you'd like. This bug exclusively relates to some quality-of-life features of Zettlr. Yes, it's a bummer, but I don't think that this is a complete showstopper. I'll get to it, and since it's a relatively benign problem, likely not too far into the future. Currently, I'm working on rewriting the TableEditor, since that is definitely a much more relevant issue.

**Comment by JDCRecomendable** [comment] 2024-10-09 11:21
Hey there, any progress on this?  As someone currently doing a literature review, having to restart the app to update the tag cloud interrupts the flow state.  I agree it is not a complete showstopper, but I also would like to have newly-created tags be auto-suggested on typing the pound key (`#`), much like how code editors can dynamically suggest variables as soon as they are created.

**Comment by kyaso** [comment] 2024-10-09 11:37
A workaround which should be faster than restarting the entire app is the following:

1. Enable "Debug mode" under "Advanced" preferences
2. Then a new option called "Develop" should appear in the menu bar on the top
3. After adding a new tag (+ saving the file), select the "Develop" menu, and click "Reload" -> This will refresh the app, and your new tag should now be available in the autocompletes

**Comment by JDCRecomendable** [comment] 2024-10-09 12:01
Wow, a great many thanks!  I can hit the "F5" key on my non-Mac keyboards and the app instantly reloads!  This is much akin to reloading the window when using VS Code.

I still do look forward to cleaner solution in the longer term.  Currently, reloading the window causes scroll position on the document I am focused on to reset to the top.

**Comment by nathanlesage** [comment] 2024-10-11 10:02
Just had a check, and it's harder than expected, because the app no longer has the ability to check for new tags. I did some quick testing, and the workaround provided in the patch seems to work reasonably fast.

**Closed** 2024-10-11 10:01 UTC
Labels: bug
