### ISSUE TITLE
[Enhancement] Behavior of Creating New Files Is Confusing (esp. w/ Autosave enabled)

### ISSUE THREAD

**Issue by ploum** [Zettlr/Zettlr#2444] opened 2021-09-10 08:55 UTC
### Description

Automatic save is not working properly with new files.

### Reproducing

1. Enable automatic save
2. Create a new file
3. Start to write in the file
4. After a while, a "save dialog" with popup regularly.

It obviously should not be the case. It also raises the question if the file would be lost in case the save is not acted (also the save is not in the good folder)

### Zettlr Version

Beta (if applicable)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 21.04

**Comment by nathanlesage** [comment] 2021-09-10 10:51
It's not a bug, but it's certainly a UX issue.

> It obviously should not be the case. It also raises the question if the file would be lost in case the save is not acted (also the save is not in the good folder)

If you create a shortcut-new file, it will be in memory only, you'd have to save it manually (that's why the dialog is popping up: it doesn't yet have a path).

I agree that it's possibly not the best UX and I'm open to suggestions.

**Comment by ploum** [comment] 2021-09-10 10:58
Before the beta, this was never an issue. The file was created in the current folder with the name heuristic defined in the preferences. In fact, the file already has that name. 

Why was the behaviour changed?

**Comment by nathanlesage** [comment] 2021-09-11 15:12
> Why was the behaviour changed?

Because I frequently like to open a file in memory without having it saved, kind of like a clipboard. If every file would automatically be created in a directory, I'd have to delete it. But I absolutely see the need to have that standardized.

**Comment by ploum** [comment] 2021-09-12 09:04
I understand your usecase. I’m more adept of the old behavior. (for me, you way breaks the "don’t need to think, everything is saved")

But, independently of our choice, I feel that this is a big change in the way Zettlr works.  . So this should be clearly communicated when the release happens.

**Comment by nathanlesage** [comment] 2021-09-12 10:54
Yes, definitely. And, given that not just you but many others as well have complained about this behavior, I'll add a setting that makes that behavior optional, so that those people (like me) who prefer to have it act much more like a real file-based editor can have that, whereas all others can be sure that everything is saved instantaneously.

**Comment by ploum** [comment] 2021-09-12 11:47
My take on it : if "automatic" save is checked, then the old behavior should be used.  Else, you will anyway be forced to save a file even if you don’t want to.  (which prompted me to open this bug in the first place).

if "automatic save" is not checked, you are anyway aware that you need to save your work.

Let’s break it down: 

- Automatic-save AND automatic-creation  : makes sense. The behavior I always expected from Zettlr.
- Automatic-save AND NOT automatic-creation : not suitable. Created this bug. Create a behavior where you cannot say if a content will be saved or not automatically. To avoid. 
- NOT automatic-save AND automatic-creation : a bit counter-intuitive but was the behavior from old Zettlr without automatic-save. It raises the question of what to put in when the file is created. Would also sometimes save, sometimes not.
- NOT automatic-save AND NOT automatic-creation : acting like a good old editor where saving should be taken care of by the writer. It looks like the behavior you want.

So, instead of adding a new setting, I will extend the behavior of the existing one.

**Closed** 2021-09-12 11:54 UTC
Labels: enhancement, pinned

**Comment by nathanlesage** [comment] 2021-09-12 11:59
Funny that you just commented, since I figured out how to do this properly :D 

***

Commit 38db46c introduces a few notable changes that should fix that behavior:

1. When you select the option not to prompt for file names in the Advanced settings, a file will **always be created**, no matter what. Whether you right-click a directory or use the keyboard shortcut. A file will always be created.
2. When that option is **not** selected (the default), you will **always be asked for a filename**, no matter what. Additionally, if you create a new file using the keyboard shortcut, that file is in memory and not saved until you manually save it (the current behavior).

This should accomodate both types of people: Those who really want to have control over the files being created as well as those who simply want to have the file being created with no further ado. Just make sure to select the corresponding setting in the advanced preferences! Please provide feedback if that is a satisfactory solution after you're able to test it out (tomorrow with the new nightly or with the beta next week).

***

NOTE: I will still have to modify the autosave behavior to not autosave if the file is in-memory only, and only do it when the file is actually present on disk. But that's peanut now that I figured out how to properly do that. Funfact: The option I chose to use for this feature was already in the settings dialog but had literally no effect. So now it's useful again, since it conveys precisely that meaning.
