### ISSUE TITLE
[Feature] Add 'Add File' to header

### ISSUE THREAD

**Issue by newhinton** [Zettlr/Zettlr#2843] opened 2021-11-20 21:12 UTC
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [ ] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

Add a 'new-file-button' to the header, next to search and filemanager to quickly create a new file.

### Example Workflow

After clicking, a new file should be created, just like if the user right-clicked in the folderview and created it there.

### Caveats

Questions to answer: Where should the file be created?

Two options that would make sense:
1. Always on the topmost folder.
2. Next to the currently open file

### Do you wish to attempt implementing this yourself?

Maybe

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

**Comment by nathanlesage** [comment] 2021-11-21 12:59
Duplicate of #2685

**Closed by nathanlesage** 2021-11-21 12:59 UTC
Labels: feature
