### ISSUE TITLE
"Cannot read property replace of undefined" when trying to export a project

### ISSUE THREAD

**Issue by ploum** [Zettlr/Zettlr#1131] opened 2020-07-29 10:41 UTC
Just upgraded Zettlr to 1.7.2 on Ubuntu.

I tried to export a project (right clic on the project folder, export) and got this error.

![Screenshot from 2020-07-29 12-34-37](https://user-images.githubusercontent.com/1233155/88790211-1c677d80-d198-11ea-981e-d7b4ca37952d.png)

Project export worked well for me under 1.7.0  (don't remember 1.7.1).

So it's probably a bug in Zettlr.

Another hypothesis is that I remove some packaging that are used by the export function. (I don't remember doing that and Pandoc is well installed). If it's the case, then the bug is more about the error being completely cryptic.

**Comment by jsstanley** [comment] 2020-07-29 13:26
This may be related to #1113 and #1126. Looks like there might be a fix in #1130.

In the meantime, I'd recommend downgrading to Zettlr 1.7.1 as that version has working pdf exports.

**Comment by nathanlesage** [comment] 2020-07-29 13:56
Duplicate of #1113

**Closed by nathanlesage** 2020-07-29 13:56 UTC
