### ISSUE TITLE
Inline equations exported as block equations in pdf, or inline equations not previewed in editor.

### ISSUE THREAD

**Issue by Wieke** [Zettlr/Zettlr#106] opened 2019-02-19 22:43 UTC
## Description

There are various related issues related to the rendering mode of equations (inline or display) and typesetting in an export pdf:

 * The non-inline equations are rendered in inline mode not display mode.
 * When exporting to pdf inline equations are typeset in display mode rather than inline mode.
 * You can get the inline equations to export correctly, by using single dollars sings instead of double dollar signs, but then they don't get rendered in the editor.
* Single dollar signs are passed to latex unescaped, so under certain circumstances latex can misinterpret two single dollar signs as an inline equation.

## Reproducing

This bit of text has all the issues covered:

> This is the current double dollar inline equation $$p(x)$$ which appears as a block in the latex. This is the workaround with single dollar signs $p(y)$ so it appears as an inline equation. And this part of a sentence where the signs $mess up$ a sentence. Granted placing two signs in a sentence like that is \$a bit weird\$ and you can always escape them. And using a $ as normal seems to go fine. 
>
> This is how a block equation looks in the editor:
>
> $$
> p(x\vert y) = \frac{p(y \vert x)p(x)}{p(y)}
> $$
>
> which isn't how a block mode equation is expected to look.

## Expected behaviour

The most important thing is the export to pdf, I expect to be able to export inline equations in some form or another. If using single dollar sign $ is the way it's supposed to work, and not a workaround, then the editor should render the equations correctly.

It would also be nice if the editor rendered non-inline equations in block mode, it looks nicer and is closer to the pdf export.

That two single dollar signs might be misinterpreted by latex as an equation isn't much of an issue in my opinion, because as far as I could tell it doesn't happen with normal use of a dollar sign.

**Screenshots**

Example of the editor:
![image](https://user-images.githubusercontent.com/6737186/53052215-6249ed80-349e-11e9-8bb0-93396fb1ef70.png)

And as a pdf export:

![image](https://user-images.githubusercontent.com/6737186/53052247-78f04480-349e-11e9-82c6-57429ee5eb4d.png)

## Platform
 - OS: Archlinux
 - OS Version n/a
 - Zettlr Version 1.1.0 (development branch)

## Additional information

There's a katex option called `displayMode` which determines if the equation is rendered in display mode. Adding `displayMode: isMulti` to the katex render call in `zettlr-plugin-render-math.js` will result in non-inline equations being rendered in display mode. However, for some reason this prevents the text cursor from travelling upwards past the equation, which is less than ideal, but it does look better:

![image](https://user-images.githubusercontent.com/6737186/53052687-b43f4300-349f-11e9-9df4-68b1f9f045cd.png)

**Comment by nathanlesage** [comment] 2019-02-20 11:30
Ah yes, the single/double-dollar issue was something I did before I fixed some other issues, I simply forgot to "re-set" the inline-quotes to single-dollar versions.

Concerning the display mode: If I am correct to assume, the `displayMode: isMulti` converts the element into a block element. CodeMirror explicitly states that those TextMarkers (which they represent internally) cannot be block elements, otherwise they break the editor, which seems to me exactly what this is doing to the editor. This is btw also the reason why images are also left-aligned and not centered within the editor — but as you stated yourself, it's not a dealbreaker, especially taking into consideration that Markdown, after all, is a source format that is supposed to be exported to, e.g., PDF.

I'll have a fix within the hour (albeit the hour starting after lunch)

**Comment by nathanlesage** [comment] 2019-02-20 13:09
There you go! Now it's possible to do one of the following:

```
$$
Multiline
Equation
$$

$$display equation$$ (something else)

Something $$display equation$$ else.

$inline equation$ (something else)

Something $inline equation$ else
```

**Comment by Wieke** [comment] 2019-02-20 19:12
Nice but here it doesn't render entirely as I expected:

![image](https://user-images.githubusercontent.com/6737186/53117535-6b44c880-354b-11e9-8eb9-d3a03543ebcd.png)

The double dollar signs version doesn't seem to work when the equation is on a single line. It seems to match the first dollar sign of both pairs of dollar signs and see that as a single equation.

Similarly the editor seems to ignore an "equation" with a single character, which isn't the end of the world of course since you can simply pad it with a space.

**Comment by nathanlesage** [comment] 2019-02-20 20:02
I see what you mean, the first fix was to simply swap the double- and single-dollar detection, yet it's still weird, because now it only renders one of the two inline equations, I'll have to look into it further.

**Comment by nathanlesage** [comment] 2019-02-22 14:30
So, some more stuff — would you mind testing whether or not it now works as expected?

**Comment by Wieke** [comment] 2019-02-22 17:06
![image](https://user-images.githubusercontent.com/6737186/53258212-5c395400-36cc-11e9-8661-b532eee4028e.png)

Looks good to me.

**Comment by nathanlesage** [comment] 2019-02-23 12:32
Nice, alright, then I'll close this issue, hopefully to leave it closed this time.

P.S.: I just found out that Zettlr pulls in KaTeX as a node-package already, so I switched to using the CSS files of KaTeX directly as it was intended to, so that it should stay automatically up to date now!

**Closed by nathanlesage** 2019-02-23 12:32 UTC
