### ISSUE TITLE
[3.1.0-beta.1] file conflict

### ISSUE THREAD

**Issue by gour** [Zettlr/Zettlr#5070] opened 2024-03-28 12:13 UTC
### Description

Hello,

I've problem installing latest beta on openSUSE Tumbleweed:

```
$ zypper  install ./Zettlr-3.1.0-beta.1-x86_64.rpm 
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following NEW package is going to be installed:
  zettlr

1 new package to install.
Overall download size: 112,1 MiB. Already cached: 0 B. After the operation, additional
447,3 MiB will be used.

Backend:  classic_rpmtrans
Continue? [y/n/v/...? shows all options] (y): y
Retrieving: zettlr-3.1.0.beta.1-1.x86_64 (Plain RPM files cache)      (1/1), 112,1 MiB    
Zettlr-3.1.0-beta.1-x86_64.rpm:
    Package header is not signed!

zettlr-3.1.0.beta.1-1.x86_64 (Plain RPM files cache): Signature verification failed [6-File is unsigned]
Abort, retry, ignore? [a/r/i] (a): i

Checking for file conflicts: ......................................................[error]
Detected 1 file conflict:

File /usr/lib/.build-id/c7/dd943c9a2f9568fcd82fa7baddb1f22f38fb22
  from install of
     zettlr-3.1.0.beta.1-1.x86_64 (Plain RPM files cache)
  conflicts with file from package
     Threema-1.2.41-1.x86_64 (@System)

File conflicts happen when two packages attempt to install files with the same name but different contents. If you continue, conflicting files will be replaced losing the previous content.
Continue? [yes/no] (no): no
```

Sincerely

### Reproducing

Attempt to install Zettlr from rpm package.

### Zettlr Version

Beta (if applicable)

### Specify version

3.1.0-beta.1

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

openSUSE Tumbleweed

**Comment by nathanlesage** [comment] 2024-03-28 17:14
Duplicate of #4905

**Closed by nathanlesage** 2024-03-28 17:14 UTC
Labels: bug
