### ISSUE TITLE
Zettlr does not display all of a Markdown document

### ISSUE THREAD

**Issue by acharseth** [Zettlr/Zettlr#4907] opened 2024-01-19 20:10 UTC
### Description

I have a Markdown document that somehow got corrupted when editing it in Zettlr. I can view it fine in Eclipse and can not find any errors in it there.

### Reproducing

I have not been able to pinpoint what is wrong with my document and have spent much time to try to tweak the document to make Zettlr to be able to read it correctly but in vain so far.  I do not want to put this document out here but can send it to a specific person doing debugging.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.3

### Installation Method

Homebrew

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

14.2.1 (23C71)

**Comment by internationils** [comment] 2024-01-25 19:31
Can you bisect the document and narrow down what is causing it? Delete the first half, try it, if the error is there, delete half of that, etc. and if the error is not there go back one step and delete the other half instead. That way you can narrow it down to where the issue is and can maybe rewrite / reword the text to make it pasteable here

**Comment by acharseth** [comment] 2024-01-25 21:52
Yes, I have tried this several times, back and forth, but I have not been
able to pinpoint where it goes wrong.

Is there a log or debug mode which can hjelp me find the problem?

Arne

tor. 25. jan. 2024 kl. 20:31 skrev Nils Boeffel ***@***.***>:

**Comment by lcsolano** [comment] 2024-01-27 04:16
Your issue reminded me about this discussion in Discord:
https://discord.com/channels/609436111860793355/874677388053717052/1148953389317759006

Take a look at **links** in the markdown file. It for example there are a new line in the middle of the link, the fil will not render.

**Comment by nathanlesage** [comment] 2024-02-05 13:42
@lcsolano If that's true, then PR #4708 may fix this issue here. And the more I think about it, the more I believe this is actually the case.

**Comment by nathanlesage** [comment] 2024-04-28 15:40
Should be fixed due to the linked PR -- if not, please open a new issue.

**Closed by nathanlesage** 2024-04-28 15:40 UTC
Labels: bug
