### ISSUE TITLE
Copy & Paste from HTML selection doesn't keep text layout under Windows 10

### ISSUE THREAD

**Issue by graphixillusion** [Zettlr/Zettlr#608] opened 2020-03-11 18:30 UTC
As already discussed in #217 i'm opening this issues about the copy & paste html selection under Windows 10.

**Comment by nathanlesage** [comment] 2020-03-11 20:48
Now it's at least in the project, so I'll have a look at it!

**Comment by nathanlesage** [comment] 2020-07-08 15:44
If this has not been fixed by 1.7.1, please comment.

**Comment by graphixillusion** [comment] 2020-07-08 17:27
@nathanlesage just tried with 1.7.1, the issue is still present.

**Comment by nathanlesage** [comment] 2020-07-08 17:48
Ah, dammit

**Comment by nathanlesage** [comment] 2020-07-08 17:49
So, just for a quick refresher: The problem was what …?

**Comment by graphixillusion** [comment] 2020-07-08 18:01
@nathanlesage The problem is that when i copy and paste some formatted text, when i paste it into zettlr, it doesn't keep the original layout. Example:

```
With Zettlr, writing professional texts is easy and motivating: Whether you are a college student, a researcher, a journalist, or an author — Zettlr has the right tools for you. Watch the video or continue reading to see what they are!

Visit our Website.

Features
Available in over a dozen languages
Tight and ever-growing integration with your favourite reference manager (such as Zotero or JabRef)
Cite with Zettlr using citeproc and your existing literature database
Four themes and dark mode support
File-agnostic writing: Enjoy full control over your own files
Keep all your notes and texts in one place — searchable and accessible
Code highlighting for many languages
Simple and beautiful exports with Pandoc, LaTeX, and Textbundle
Support for state of the art knowledge management techniques (Zettelkasten)
A revolutionary search algorithm with integrated heatmap
… and the best is: Zettlr is Open Source (FOSS)!
```

**Comment by nathanlesage** [comment] 2020-07-08 18:31
And this happens even with `Cmd/Ctrl+V`, and you are NOT holding down shift?

Could you have a look if the console says something? (Enable debug mode, then open the developer tools from the menu, then switch to the console tab)

**Comment by graphixillusion** [comment] 2020-07-08 19:37
@nathanlesage here the console log:

```
vue/sidebar.css:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
remote.js:20 Electron Deprecation Warning The 'remote' module is deprecated and will be disabled by default in a future version of Electron. To ensure a smooth upgrade and silence this warning, specify {enableRemoteModule: true} in the WebPreferences for this window.
(anonymous) @ remote.js:20
C:\Users\User\scoop\apps\zettlr\1.7.1\resources\app.asar\renderer\util\editor-tabs.js:102 [TABS] Synching 0 files
C:\Users\User\scoop\apps\zettlr\1.7.1\resources\app.asar\renderer\util\editor-tabs.js:102 [TABS] Synching 0 files
C:\Users\User\scoop\apps\zettlr\1.7.1\resources\app.asar\renderer\util\editor-tabs.js:102 [TABS] Synching 0 files
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/User/scoop/apps/zettlr/1.7.1/resources/app.asar/node_modules/@popperjs/core/dist/umd/popper.min.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/User/scoop/apps/zettlr/1.7.1/resources/app.asar/node_modules/tippy.js/dist/tippy.umd.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/User/scoop/apps/zettlr/1.7.1/resources/app.asar/renderer/assets/showdown.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/User/scoop/apps/zettlr/1.7.1/resources/app.asar/renderer/assets/mermaid.core.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/User/scoop/apps/zettlr/1.7.1/resources/app.asar/renderer/assets/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/User/scoop/apps/zettlr/1.7.1/resources/app.asar/renderer/assets/all-shapes.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/User/scoop/apps/zettlr/1.7.1/resources/app.asar/node_modules/@clr/icons/clr-icons.min.css.map: 
C:\Users\User\scoop\apps\zettlr\1.7.1\resources\app.asar\renderer\zettlr-editor.js:226 Uncaught TypeError: Cannot read property 'cmDoc' of undefined
    at C:\Users\User\scoop\apps\zettlr\1.7.1\resources\app.asar\renderer\zettlr-editor.js:226
    at C:\Users\User\scoop\apps\zettlr\1.7.1\resources\app.asar\node_modules\codemirror\lib\codemirror.js:2076
    at fireCallbacksForOps (C:\Users\User\scoop\apps\zettlr\1.7.1\resources\app.asar\node_modules\codemirror\lib\codemirror.js:2033)
    at finishOperation (C:\Users\User\scoop\apps\zettlr\1.7.1\resources\app.asar\node_modules\codemirror\lib\codemirror.js:2047)
    at endOperation (C:\Users\User\scoop\apps\zettlr\1.7.1\resources\app.asar\node_modules\codemirror\lib\codemirror.js:3787)
    at runInOp (C:\Users\User\scoop\apps\zettlr\1.7.1\resources\app.asar\node_modules\codemirror\lib\codemirror.js:3916)
    at handlePaste (C:\Users\User\scoop\apps\zettlr\1.7.1\resources\app.asar\node_modules\codemirror\lib\codemirror.js:8142)
    at HTMLTextAreaElement.<anonymous> (C:\Users\User\scoop\apps\zettlr\1.7.1\resources\app.asar\node_modules\codemirror\lib\codemirror.js:9303)
    at HTMLDivElement.<anonymous> (C:\Users\User\scoop\apps\zettlr\1.7.1\resources\app.asar\node_modules\codemirror\lib\codemirror.js:9342)
(anonymous) @ C:\Users\User\scoop\apps\zettlr\1.7.1\resources\app.asar\renderer\zettlr-editor.js:226
(anonymous) @ C:\Users\User\scoop\apps\zettlr\1.7.1\resources\app.asar\node_modules\codemirror\lib\codemirror.js:2076
fireCallbacksForOps @ C:\Users\User\scoop\apps\zettlr\1.7.1\resources\app.asar\node_modules\codemirror\lib\codemirror.js:2033
finishOperation @ C:\Users\User\scoop\apps\zettlr\1.7.1\resources\app.asar\node_modules\codemirror\lib\codemirror.js:2047
endOperation @ C:\Users\User\scoop\apps\zettlr\1.7.1\resources\app.asar\node_modules\codemirror\lib\codemirror.js:3787
runInOp @ C:\Users\User\scoop\apps\zettlr\1.7.1\resources\app.asar\node_modules\codemirror\lib\codemirror.js:3916
handlePaste @ C:\Users\User\scoop\apps\zettlr\1.7.1\resources\app.asar\node_modules\codemirror\lib\codemirror.js:8142
(anonymous) @ C:\Users\User\scoop\apps\zettlr\1.7.1\resources\app.asar\node_modules\codemirror\lib\codemirror.js:9303
(anonymous) @ C:\Users\User\scoop\apps\zettlr\1.7.1\resources\app.asar\node_modules\codemirror\lib\codemirror.js:9342

```

**Comment by nathanlesage** [comment] 2020-07-08 19:53
Okay, apparently there's an error in instantiating the document object on opening the file, which makes no sense on first sight o.O I'll have to think about this — if someone has a good idea of what might be causing this feel free to comment!

**Comment by graphixillusion** [comment] 2020-08-15 12:20
@nathanlesage Just a quick update about this. I'm testing the last 1.7.5 version and in the console window i just got this:

```
electron/js2c/renderer_init.js:82 Electron Deprecation Warning The 'remote' module is deprecated and will be disabled by default in a future version of Electron. To ensure a smooth upgrade and silence this warning, specify {enableRemoteModule: true} in the WebPreferences for this window.
(anonymous) @ electron/js2c/renderer_init.js:82
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/User/scoop/apps/zettlr/1.7.5/resources/app.asar/renderer/assets/showdown.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/User/scoop/apps/zettlr/1.7.5/resources/app.asar/renderer/assets/tippy.cjs.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/User/scoop/apps/zettlr/1.7.5/resources/app.asar/renderer/assets/popper.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/User/scoop/apps/zettlr/1.7.5/resources/app.asar/renderer/assets/mermaid.core.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/User/scoop/apps/zettlr/1.7.5/resources/app.asar/renderer/assets/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/User/scoop/apps/zettlr/1.7.5/resources/app.asar/renderer/assets/all-shapes.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/User/scoop/apps/zettlr/1.7.5/resources/app.asar/node_modules/@clr/icons/clr-icons.min.css.map: 

``` 
So no error messages when pasting like before but the pasted text is still wrong, without formatting.

**Comment by nathanlesage** [comment] 2020-08-15 13:10
What does the clipboard say? So when you copy some text, and then select Develop -> Inspect clipboard, what do you see? Is there HTML in the clipboard?

**Comment by graphixillusion** [comment] 2020-08-15 14:47
@nathanlesage yep, the "Inspect Clipboard" has two sections: 1. HTML; 2. TEXT

**Comment by nathanlesage** [comment] 2020-08-15 14:57
Both filled, and the HTML looking like HTML?

**Comment by canpolat** [comment] 2020-08-15 16:05
I feel like this and #1053  are related to each other.

**Comment by graphixillusion** [comment] 2020-08-15 16:14
@nathanlesage 
![2020-08-15 181319](https://user-images.githubusercontent.com/37411865/90316539-2670d680-df23-11ea-9a4a-e5ce782945b7.png)

**Comment by nathanlesage** [comment] 2020-08-15 19:05
Oh my god this HTML looks daunting. Zettlr makes use of Joplin-turndown for turning HTML into Markdown, soooo I will check that this weird HTML is being recognized, but if that works, it's an issue with an external library over which I do not have any control.

**Comment by graphixillusion** [comment] 2020-08-15 20:49
@nathanlesage If i try to paste the same thing in the WYSIWYG section inside Joplin, the text is pasted good, with the right format style.

**Comment by canpolat** [comment] 2020-08-16 12:01
Below is a screenshot from a simpler HTML (Windows 10, Zettlr 1.7.5). I also see the Console logs about failing to load SourceMap files but I don't think they are related to this problem. Since the HTML source in my example is simpler, I suspect Zettlr is actually using the text contents instead of HTML.

![image](https://user-images.githubusercontent.com/459891/90333655-f7607080-dfc7-11ea-9e6e-ed9f55874613.png)

**Comment by graphixillusion** [comment] 2020-08-16 14:02
@canpolat you are right: it ignores RichText Contents too.

![Annotazione 2020-08-16 160107](https://user-images.githubusercontent.com/37411865/90336100-d6a11680-dfd9-11ea-9295-96a6c77b2cc0.png)

**Comment by nathanlesage** [comment] 2020-08-19 05:46
Richtext contents are being ignored because it is easier to parse HTML to Markdown, and I have not yet come across a situation where there is RTF and not HTML … but I still can't reproduce this bug locally :(

**Comment by graphixillusion** [comment] 2020-08-19 11:26
@nathanlesage on Windows 10?

**Comment by nathanlesage** [comment] 2020-08-24 08:57
Ah, I think I spotted something: Apparently however you are copying something, Windows seems to not put it into the HTML-clipboard. This almost looks like it could be a bug with Electron's clipboard API – would someone mind to do a little bit of research into this …? The codebase of Zettlr itself simply taps into Electron's APIs, and as it is working as expected on macOS, I strongly suspect it's not an issue of the shared code part, but of Electron itself …

**Comment by graphixillusion** [comment] 2020-08-24 13:04
@nathanlesage This is another markdown application, always built upon Electron (https://github.com/marktext/marktext) which has the copy & paste working as it should, Windows too. So, at this point, i don't now if it could be something in the Electron's API itself.

**Comment by canpolat** [comment] 2020-08-24 15:38
> Apparently however you are copying something, Windows seems to not put it into the HTML-clipboard.

In some of the screenshots pasted under this issue, the `Develop > Inspect Clipboard` dialog shows HTML content and yet pasting it does not retain the formatting. Your hypothesis does not seem to explain that situation. (Or am I missing something?)

**Comment by nathanlesage** [comment] 2020-08-27 06:58
@canpolat I was looking at one screenshot where there was nothing in the HTML clipboard, hm. The thing is: The code that reads the clipboard works the same on all platforms, so I can't think of why this code would work on macOS but not on Windows, given the assumption that the Electron APIs work just fine …

**Comment by graphixillusion** [comment] 2020-08-27 11:36
@nathanlesage this is very strange indeed. Could you link the part of the code which should does this?

**Comment by canpolat** [comment] 2020-08-27 17:29
@graphixillusion I think it is this line (not sure, though): https://github.com/Zettlr/Zettlr/blob/df0cbfc5ce20442f3fbbbf39db24cf4f8fc7386e/source/renderer/zettlr-editor.js#L208

**Comment by nathanlesage** [comment] 2020-08-30 15:34
@canpolat This could indeed be the problem! (line 187 in the editor)

**Comment by graphixillusion** [comment] 2020-11-15 18:47
@nathanlesage any news about this?

**Comment by nathanlesage** [comment] 2020-11-15 22:20
No, which also has to do that there's no information on where this problem might occur. There's just nothing for me to start looking for the problem right now, unfortunately. As long as I don't have a lead, I can't do much :/ 

Looking at @canpolat's comment, however, I suspect that maybe Windows adds `\r`-characters additionally to the `\n`-characters, so what we might be needing is 

```javascript
 let explicitPaste = plain === changeObj.text.join('\r\n') // or \n\r? 
```

instead of just a simple newline. @canpolat want to give it a try? (If this is the cause I'll eat a copy of Windows 10 out of frustration)

**Comment by graphixillusion** [comment] 2020-11-15 23:01
@nathanlesage i just gave a try: i recompiled version 1.7.5 with this change in this line

https://github.com/Zettlr/Zettlr/blob/df0cbfc5ce20442f3fbbbf39db24cf4f8fc7386e/source/renderer/zettlr-editor.js#L187

```let explicitPaste = plain === changeObj.text.join('\r\n') ``` 

as you suggested and i have a good news: like this, copy and paste works as expected under Windows!

**Comment by nathanlesage** [comment] 2020-11-16 07:30
> and i have a good news: like this, copy and paste works as expected under Windows!

Ahhh perfect! Thank you so much :)

One last request @graphixillusion:

Would you mind testing it out if the following works as well?

```javascript
let explicitPaste = plain.replace(/\r/g, '') === changeObj.text.join('\n')
```

What this should do is replace all cariage return chars (`\r`) so that only normal newlines (`\n`) remain. This way it should work on both Linux/macOS and Windows as well. (We have to join the changeObj to one string, as the `===` compares identity, which won't work with an Array as Arrays are treated as unequal with `===`).

If that works, also feel free to add this in a PR which I'll merge – then you are listed as a contributor ;)

**Comment by graphixillusion** [comment] 2020-11-16 11:38
@nathanlesage yep, with that line works too as well. I opened a pr. thank you for the support.

**Comment by nathanlesage** [comment] 2020-11-16 18:41
Perfect, thanks! There's just a merge conflict which needs to be resolved before I can merge!

**Closed** 2020-11-16 22:55 UTC
Labels: bug [non-critical], confirmed, enhancement, v1.7.x
