### ISSUE TITLE
[ENHANCEMENT] Option: Note Generation when calling Link

### ISSUE THREAD

**Issue by PhilHem** [Zettlr/Zettlr#669] opened 2020-04-15 05:20 UTC
## Description
Add the option to create a new note in the link drop down menu (lowest position), dependent on the string in the square brackets. 

## Proposed Changes
So I am using Zettlr extremely frequently, and I have spent a lot of time generating links during that time.

Right now, my process is:

1. Type square brackets
3. Enter Name of potential note. If it doesn't exist:
4. CMD+L to generate label
5. Type Note name behind Label
6. Select Label and Copy
7. CMD+N to call Note Generator
8. Type Note name (second time I have to write the name)
9. Paste label in note
10. Go back to continue writing in the other note

To me ideally, it would look like this:

1. Type square brackets
2. Enter Name of potential note. If it doesn't exist:
3. Select "Create new note" from the drop-down menu

Automated Process:
1. Create new note according to string in square brackets
2. Place newly generated label in the first line of the file
3. Put string within square brackets in active file after the square brackets
4. Put newly generated label in square brackets 

(During this process, don't switch to the new note, this could maybe be optional)

## Caveats
The usefulness of this feature is probably determined by the workflow of the user and might not fit everybody. I would assume though, that these peoples workflow will not be significantly affected. 

## Additional Information

Maybe the replacement of the name in the square brackets could be optional. I can imagine that some peoples workflows are maybe not so reliant on the labels.

Also, another consideration could be to instead of having the option in the drop down menu, to create a shortcut for the command. This would maybe make the command a little less accessible to people who are not into shortcuts, but it would prevent that the drop down menu will always be active within the square brackets.

Anyways, for me, this would be a significant time saver.

EDIT: The reason why I use so many links is because I am often creating notes that are similar to the nodes of a mindmap. I don't necessarily fill them with information initially, but they pose a concrete connection point that I can string other notes to.

**Comment by exilexi** [comment] 2020-04-15 10:06
+1

**Comment by nathanlesage** [comment] 2020-04-15 11:18
I am preeeeeeeeeetty sure this is a duplicate of an already existing and open issue

**Comment by exilexi** [comment] 2020-04-15 11:28
Indeed: https://github.com/Zettlr/Zettlr/issues/669

**Comment by PhilHem** [comment] 2020-04-15 13:40
I relied on the automatic display to show me if there was something like that already. If there is, feel free to merge them or delete this one. 

exilexis link goes to this page, lol

**Comment by nathanlesage** [comment] 2020-04-15 15:55
> Indeed: #669

This is not only a duplicate, but the identical issue! ;D

**Comment by Jos512** [comment] 2020-04-16 05:02
The strongly related issue is #178, which talks about the following:

> So you would write [[new id]], then click on the link and find yourself in a new Zettel file, which already contains the generated ID and a Backlink to the former Zettel.

Possibly related is #368, which talks about creating a automatic note from selected text. That may work through the same underlying principle (in terms of coding), except that those new notes don't appear empty.

**Comment by nathanlesage** [comment] 2020-04-16 11:18
Then I'd say let's close this one in favor of a cleaner issue list — please feel free to comment anything not mentioned from your perspective in these issues!

Duplicate of #178

**Closed by nathanlesage** 2020-04-16 11:18 UTC
