### ISSUE TITLE
Zettlr Freezes while Editing - showing empty page

### ISSUE THREAD

**Issue by MaPeras** [Zettlr/Zettlr#3462] opened 2022-05-10 12:22 UTC
### Description

I was editing a file and suddenly there only appeared a blank page without any letters. 

Logs:

[14:17:58]	[Assets Provider] Found outdated filter links.lua; copying ...
[14:17:58]	[Assets Provider] Found outdated filter tags.lua; copying ...
[14:17:59]	[FSAL Directory] Path /home/max/Nextcloud/ZK took 836.1022740000626ms to load.
[14:18:00]	[FSAL] Path /home/max/Nextcloud/ZK took 871ms to load.
[14:18:02]	[R] [Main Window] Uncaught TypeError: Cannot read properties of null (reading '1') (index.js:2)
[14:18:06]	[R] [Main Window] Uncaught TypeError: Cannot read properties of null (reading '1') (index.js:2)
[14:18:06]	[R] [Main Window] Uncaught TypeError: Cannot read properties of null (reading '1') (index.js:2)
....

### Reproducing

Hard to reproduce as I worked as normal.

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.6

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Xubuntu

**Comment by nathanlesage** [comment] 2022-05-17 09:02
How often does this error occur? I'm asking since apparently it started working again at some point …?

**Comment by MaPeras** [comment] 2022-05-17 09:27
Yes, it did. Happened with one file and never since. I suspect that it was triggered by some form of indentation like
 
- [ ] link
   - [ ] another link

**Comment by nathanlesage** [comment] 2022-05-19 18:46
Feel free to poke around and try to reproduce this error. If you can reproduce it, we have found the cause and can fix it.

**Comment by nathanlesage** [comment] 2023-03-21 09:50
Since the corresponding bug has been fixed in #3612, closing!

**Closed by nathanlesage** 2023-03-21 09:50 UTC
Labels: bug
