### ISSUE TITLE
[Bug] Wrong spell check decorations for german verbs and combined words

### ISSUE THREAD

**Issue by johannhuang** [Zettlr/Zettlr#2857] opened 2021-11-25 15:12 UTC
### Description

I am using v2.0.1 of Zettlr

With German and English spell check enabled

![image](https://user-images.githubusercontent.com/26480469/143465081-4d7c657f-066f-49b9-a6ed-f3c99422e53b.png)

When i write many german verbs and combined words, i get wrong spell check decorations. For example, as on the following screenshot.

![image](https://user-images.githubusercontent.com/26480469/143465612-8d5e375e-9a1a-4d86-9222-0a6d0af1b3a8.png)

### Reproducing

As given in the description.

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

macOS Monterey

**Comment by nathanlesage** [comment] 2021-12-02 11:01
The problem is that the hunspell implementation isn't that great, so it doesn't support certain hunspell flags, i.e. for compound words. So I'm not sure we can mitigate this, until nspell has been rewritten which may or may not ever happen.

**Comment by nathanlesage** [comment] 2021-12-14 13:22
I'm going to close this to clean up the issue tracker. To improve spellchecking, we have two options: Either somehow a new npm package appears that does a better job than nspell, or someone needs to improve nspell; I know Titus has not that much time to tend to it himself, so feel free to do so. But there's nothing I can do on this side.

Only fix until then: Manually add all wrong words to the user dictionary.

**Closed by nathanlesage** 2021-12-14 13:22 UTC
Labels: bug, external Issue
