### ISSUE TITLE
Selecting characters in inline code or YAML Frontmatter is not highlighted.

### ISSUE THREAD

**Issue by kicoln** [Zettlr/Zettlr#4561] opened 2023-08-18 09:35 UTC
### Description

When selecting characters in inline code or YAML Frontmatter, the selection range is unknown because the background color does not change.
I checked from Inspect Element in the Develop menu and it seems that the CSS `cm-monospace` class is the problem. However, setting the `background-color` using `::selection` in custom CSS had no effect.

### Reproducing

Select characters entered in inline code or YAML Frontmatter.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta.8

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment] 2023-08-18 13:26
Duplicate of #4559.

**Closed by nathanlesage** 2023-08-18 13:26 UTC
Labels: bug
