### ISSUE TITLE
[1.8.0] Main Preferences dialog cannot be opened via menu (just via shortcut)

### ISSUE THREAD

**Issue by derwok** [Zettlr/Zettlr#1451] opened 2020-11-27 09:28 UTC
## Description
Menu click on `File / Preferences / Preferences` does nothing

## Reproducing
Click `File / Preferences / Preferences`

## Expected behaviour
Preferences dialog should open

## Platform
 - OS and version: Win10
 - Zettlr Version: 1.8.0

## Additional information
Workaround: use shortcut <kbd>CTRL</kbd>+<kbd>,</kbd>

**Comment by robxylyxuk** [comment] 2020-11-27 10:26
I can confirm that I am also encountering this behaviour. It was working fine in beta 4 for me - seems to have occurred since moving it into a sub-menu. Not a show stopper for me though, as I usually access the preferences via the cog icon.

**Comment by jsstanley** [comment] 2020-11-27 12:27
I can also reproduce this bug on Zettlr 1.8.0 and Windows 10.

**Comment by kyaso** [comment] 2020-11-27 14:07
Can confirm this as well on Linux Ubuntu 20.04.

**Comment by rybchuk** [comment] 2020-11-27 18:27
I was able to successfully open the dialog on Ubuntu 16.04.

**Closed** 2020-11-28 11:17 UTC
Labels: bug [non-critical], confirmed, priority:high, scope:Windows
