### ISSUE TITLE
Files aren't moved to correct directory

### ISSUE THREAD

**Issue by avakslo** [Zettlr/Zettlr#3944] opened 2022-11-23 12:19 UTC
### Description

I'm having trouble moving my files from one directory/folder to another. 

I want to move a file, one of my zettels, e.g. from the directory "0. Benken" to "2. Førebelssnotat", however, when I drag and drop it it "disappears" from the lefthand pane in Zettlr. However, when using windows file manager I find the file under the main directory Zettelkasten. So the file is moved, but not to the directory/folder I want. 

![image](https://user-images.githubusercontent.com/118901229/203541944-9fbe52a6-586c-4a1b-8a46-98792352cbb4.png)
![image](https://user-images.githubusercontent.com/118901229/203542014-3505cdc1-aeef-4e53-a137-33e78ed5d4b1.png)

### Reproducing

I created the file structure in Windows file manager. Zettelkasten as main directory, then under that the five different folders/directories. I then imported this to Zettelkasten. 

The individual note/zettel is created in Zettlr in the directory I first want to work in. In the example above, I create a zettel in "0.Benken", then I want to move the zettel to "2. Førebelsnotat". Still in Zettlr, I then drag and drop the file; drag it from the directory I created the zettel in and to the one I want to move it to.   

In Zettlr, when I open the directory I expect to find the zettel in it is not there. In the example, when I open "2.Førebelsnotat" - the zettel is not there. And I cannot find it under the main directory Zettelkasten either. However, using the windows file manager I can locate the zettel under the main directory of Zettelkasten. If I then move it to the directory I want, I find it when I open Zettlr. 

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

### Additional Information

I ran it by the help-channel on discord and hendrik said it sounded like a bug and that I open an issue.

**Comment by nathanlesage** [comment] 2022-11-28 08:40
It could be that the 2.3 branch had an issue where you had to hover the file exactly over the directory name to copy to the correct directory. Could you check if that may be the cause, that this weird moving bug appears when you're just dropping the file anywhere where it seems appropriate?

**Comment by avakslo** [comment] 2022-11-28 20:25
Hi! I've tried it a number of times now, where I hover over the directory
so that in addition to the target directory becoming "lit up" my cursor is
also above it, and I still end up with the same problem unfortunately.

**Comment by nathanlesage** [comment] 2022-12-02 21:13
Alright, I'll keep that in mind, feel free to see if you can spot a pattern that could hint as to where the bug might come from!

**Comment by avakslo** [comment] 2022-12-19 12:12
Hey! A small update from me.

I've found that I DO see the files in Zettlr when viewing, so they don't
disappear as I've described before.

However, the problem is still that when dragging a file from a subdirectory
to another subdirectory they end up (and are shown) in the main
directiry "Zettelkasten".

I AM able to move the files from the main directory to a subdirectory. See
screenshot.

I don't know if this makes it any clearer as to what the problem might be.

[image: image.png]

**Comment by nathanlesage** [comment] 2022-12-19 17:24
The screenshot unfortunately didn't upload as you replied by email ... but in any case, I highly suspect that the issue is only with 2.3 and not with the current develop branch, as I cannot reproduce that problem. I'd suggest you check out the [nightlies](https://nightly.zettlr.com/) and see if the problem persists. If it doesn't, we can close this issue as fixed and hope to move to beta soon!

**Comment by exanrauzer** [comment] 2023-01-10 19:57
I was dealing with same problem. Together with being unable to rename files the folders tree was quite dead and forced me to be a close friend to windows explorer. With 3.0.0 all is perfect fine.

**Comment by nathanlesage** [comment] 2023-01-10 21:20
@exanrauzer Thank you very much for confirming the bug is gone in the 3.0 branch! Closing as fixed.

**Closed by nathanlesage** 2023-01-10 21:20 UTC
Labels: bug

**Comment by avakslo** [comment] 2023-01-11 09:50
Awesome, thanks!
