### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ethanbass** [Zettlr/Zettlr#3175] opened 2022-02-10 16:57 UTC
### Description

I can't save new files unless debug mode is activated in newest version of zettlr. Old files that are already named save fine, but when I go to save new files, the file menu blinks like it's trying to do something, but the save dialogue box doesn't open. Strangely, when I activate the debugging mode, I can save files just fine.

I found this error message in the logs:
<img width="758" alt="Screen Shot 2022-02-10 at 11 50 15 AM" src="https://user-images.githubusercontent.com/15876283/153456263-53e34958-3bcd-4495-811e-d16a2ddafb45.png">
 
(I was also sometimes having this problem in the last version of zettlr, but it would only happen occasionally and I would be able to fix it by restarting the app. However, this no longer seems to be the case).

### Reproducing

- Open new markdown file in zettlr (command N).
- Add some text.
- Try to save. 
(Sorry I'm not really sure what else to add here?)

### Zettlr Version

Stable (most recent version)

### Specify version

2.20

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [x] ARM 64bit

### Operating System Version

12.0.1

**Comment by nathanlesage** [comment] 2022-02-10 20:21
Duplicate of #3172

**Closed by nathanlesage** 2022-02-10 20:21 UTC
Labels: bug
