### ISSUE TITLE
v3.4.0. completely broken - nothing opens or displays

### ISSUE THREAD

**Issue by MenooMeow** [Zettlr/Zettlr#5530] opened 2024-12-24 00:59 UTC
### Description

On launching, the old tabs appear but there is no content anywhere.  The directory browser is also gone.  When I try to open a workspace, nothing happens.  When I try to open a single .md file, nothing happens.  Zettler is now broken with zero ability to use.

![zettler3 4 0](https://github.com/user-attachments/assets/65a4dd51-8992-422e-92b4-349b220848f7)

### Reproducing

Install v3.4.0 via .DEB image or AppImage.
Launch it.
Try to open a file or workspace.

### Zettlr version

3.4.0.

### Installation Method

From the Website or GitHub

### Installation Method (Other)

DEB file and AppImage

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Linux Mint 22 Cinnamon

**Comment by testinnplayin** [comment] 2024-12-24 07:45
Hello,

I am experiencing the same but on MacOS.

**Comment by artptr** [comment] 2024-12-24 07:51
The same on MacOS upgraded using Brew.

**Comment by nathanlesage** [comment] 2024-12-24 08:18
Duplicate of #5526

**Closed by nathanlesage** 2024-12-24 08:18 UTC
Labels: bug
