### ISSUE TITLE
[1.8.0.beta2] Using [[, # or @ no lookuplist is showing

### ISSUE THREAD

**Issue by mattwien** [Zettlr/Zettlr#1419] opened 2020-11-08 18:07 UTC
## Description
When tying the charactres to create a link, a hashtag or the @ symbol usually a lookup list shows up, where you see available entries. In 1.8 Beta this frequently stops working. You type [[, # or @ and no list is shown.
A restart of Zettlr helps.

## Platform
Zettlr Version: 1.8.0-beta.2
System: win32 10.0.19041 (architecture: x64)

**Comment by nathanlesage** [comment] 2020-11-08 23:16
> In 1.8 Beta this frequently stops working.

Is there any way to reproduce this consistently? I did touch the logic for that autocomplete before the last beta, so there might be something off! The more reproducible this is, the quicker and easier I can implement a fix!

**Comment by mattwien** [comment] 2020-11-09 18:57
Hi @nathanlesage , 
Yesterday i haven't yet found out when and why it happens, but today I notice a behavior that can be reproduced:
If I want to add a tag, I get the list and everything works as intended. But if I add a new tag, that is not in the dropdown list, the dropdownlist will no longer pop up when I type a hashtag # - and when one dropdown stopped all others are also gone.

Same happens with @ - I type @ & something that is not in my cite fiel it shows "undefined" and the dropdowns (#,@, [[) aren't showing any more.

**Comment by tobenschmidt** [comment] 2020-11-09 22:56
Almost the same here. Only difference: The autocomplete feature for tags doesn't work at all. Not even before it breaks for internal links and citations.

### Platform

Zettlr Version: 1.8.0-beta.2
System: Linux Mint 20 Mate 5.4.0-52-generic x86_64

**Comment by nathanlesage** [comment] 2020-11-10 22:00
> If I want to add a tag, I get the list and everything works as intended. But if I add a new tag, that is not in the dropdown list, the dropdownlist will no longer pop up when I type a hashtag # - and when one dropdown stopped all others are also gone.

Yes, reason: There's an internal state that is accidentally not correctly reset if you do not choose anything from the list, I am not sure if I already fixed this, or if I need to do this but I know that behaviour.

**Comment by ludos1978** [comment] 2020-11-16 00:45
Not sure wether it's related to this bugreport, but since today (might be several days) when i start a heading (using #) it  suggests my tags (event if i write ##) so currently every heading is converted to the first tag if i dont press escape. My suggestion would be to suggest tags only after "#" and at least one number of letter (without a space inbetween).

**Comment by nathanlesage** [comment] 2020-11-16 07:24
> Not sure wether it's related to this bugreport, but since today (might be several days) when i start a heading (using #) it suggests my tags (event if i write ##) so currently every heading is converted to the first tag if i dont press escape. My suggestion would be to suggest tags only after "#" and at least one number of letter (without a space inbetween).

Nah, that's normal and expectable. However, you don't have to press escape, as soon as you type the first space it'll close again.

P.S.: Closing this as I fixed the issue in one of the latest commits. Coming with next beta.

**Closed by nathanlesage** 2020-11-16 07:24 UTC
Labels: bug [non-critical], confirmed, develop
