### ISSUE TITLE
"File->Open (Workspace)" file selector hangs (but "Open Workspace" toolbar button works fine)

### ISSUE THREAD

**Issue by ghost** [Zettlr/Zettlr#1618] opened 2021-01-10 15:53 UTC
## Description

Clicking either `File->Open` or `File->Open Workspace` opens a file selection window that appears "frozen." Clicking anywhere within the file selection window (e.g. trying to choose a folder or click the "Cancel" or "Open" button) has no effect whatsoever. The file selection window can only be closed by pressing `ESC`.

However, clicking the `Open Workspace` _toolbar icon_ opens a file selector window that works just fine.

## Reproducing

(See description.) I have a hunch that this issue may be platform-specific, but I haven't tried it on another OS. I have not encountered this issue with any other software on the same system.

## Expected behaviour

`File->Open Workspace` should work the same as the `Open Workspace` toolbar icon, and `File->Open` should open a file selection window that works as expected.

## Platform
 - OS and version: Ubuntu MATE 20.04 (amd64 64-bit)
 - Zettlr Version: 1.8.5 (64-bit AppImage for Linux)

## Additional information

Thanks for continuing to improve Zettlr!

**Comment by dw545454** [comment] 2021-01-13 02:36
I have been getting weird "system error"-type messages on this computer lately, so I decided to try to reproduce this issue today on a new, freshly-installed and updated version of Ubuntu MATE 20.04 in Virtualbox. Just to try to see if I had borked something on my specific computer or if it is a Zettlr issue that others might run into too.

...and on this new system everything in Zettlr (1.8.5, 64-bit AppImage) seemed to work just fine, so I kept testing it. Then I **DID** encounter the file-selector freezing issue exactly once with the `File->Open Workspace` command. But then when I tried it again it worked as it should.

Very strange!

**Comment by nathanlesage** [comment] 2021-01-13 12:25
I have just checked the code: Both the toolbar button and the menu button work 100 percent the same, so purely from a technical side this should be no problem. Maybe the window needs to be focused (which happens if you click on the toolbar, but not if you click on the menu item)?

But in general, I figured that the last Electron version (the framework we were using) had had quite a few hiccups with regard to Linux modal dialogs, multiple users have said this

**Comment by nathanlesage** [comment] 2021-01-19 13:28
Could it be that this issue is related to #1645 ? If so I would strongly recommend closing this one and unifying our efforts of getting this to work again.

**Comment by nathanlesage** [comment] 2021-07-09 17:46
Closing as duplicate of #1645.

**Closed by nathanlesage** 2021-07-09 17:46 UTC
Labels: bug, pinned, priority:high, scope:Linux
