### ISSUE TITLE
Switching tab (to open file) scrolls the file up a few lines

### ISSUE THREAD

**Issue by tobiasvandriessel** [Zettlr/Zettlr#1673] opened 2021-01-22 13:03 UTC
## Description

Switching tabs from an open file to another open file scrolls the file up a few lines in one bump after it has been rendered first.

## Reproducing

Open any two files (new or existing) that are scrollable, switch back to any.

## Expected behaviour

Switch to the open file and not scroll up.

## Platform
 - OS and version: 
Operating System: Debian GNU/Linux bullseye/sid
Kernel: Linux 5.9.0-4-amd64
Architecture: x86-64
 - Zettlr Version: 1.8.6

**Comment by nathanlesage** [comment] 2021-02-05 13:19
Duplicate of #1696

**Closed by nathanlesage** 2021-02-05 13:19 UTC
