### ISSUE TITLE
Render Link breaks line

### ISSUE THREAD

**Issue by brunoperdigao** [Zettlr/Zettlr#1519] opened 2020-12-14 15:10 UTC
## Description
When the render link is active, the display breaks the line after the linked word.

## Reproducing
Just create a link in the middle of a paragraph.
When "render links" is disabled:
![image](https://user-images.githubusercontent.com/57102715/102097219-66c65f80-3e04-11eb-8e72-7e8d0170046c.png)

When "render links" is active:
![image](https://user-images.githubusercontent.com/57102715/102097402-9d03df00-3e04-11eb-856b-a7bff2aa4c11.png)

## Expected behaviour
The word should by highlighted but it shouldn't break the line.

## Platform
Windows10 64bit
Zettlr 1.8.2

**Comment by boutil** [comment] 2020-12-14 16:15
This is a duplicate of #1514 and #1517 which is closed in the repository already https://github.com/Zettlr/Zettlr/commit/2e46025263728514ec3b51864edce45e842776d8  (but the fix is not released yet).

**Comment by nathanlesage** [comment] 2020-12-14 18:05
What @boutil says! Fix comes in a few days.

**Closed by nathanlesage** 2020-12-14 18:05 UTC

**Comment by brunoperdigao** [comment] 2020-12-14 20:10
Sorry about that.
