### ISSUE TITLE
No need to add backslash when pasting inside code block

### ISSUE THREAD

**Issue by radifar** [Zettlr/Zettlr#3597] opened 2022-07-11 03:08 UTC
### Description

Hi, I keep getting annoyed every time I copy and pasting code to code block in Zettlr because it always add the backslash to many character which I think it is not necessary as they are enclosed within triple backtick.

### Proposed Changes

Example one
![bash_1](https://user-images.githubusercontent.com/11450417/178181379-2103bbea-3fa4-427f-94cf-218c2402c95a.png)

How it is supposed to be
![bash_2](https://user-images.githubusercontent.com/11450417/178181394-daca4a40-bf9e-4e42-943a-1732777303ca.png)

Example two
![python_1](https://user-images.githubusercontent.com/11450417/178181408-b78502d8-8d1c-48d6-9650-d3b5562b0379.png)

How it is supposed to be
![python_2](https://user-images.githubusercontent.com/11450417/178181412-7a14a34e-4227-4f3f-b59e-13ab85387e8e.png)

### Caveats

no caveat, maybe...

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Fedora 36

**Comment by leo-hstone** [comment] 2022-07-18 08:55
Hi radifar, I am not able to reproduce this behaviour. But I am on the latest nightly on Windows.

Maybe you can try Strg+Shift+V to paste without formatting. I always use this shortcut to paste code since otherwise Zettlr adds some newlines sometimes.

**Comment by nathanlesage** [comment] 2022-07-18 14:43
> Maybe you can try Strg+Shift+V to paste without formatting. I always use this shortcut to paste code since otherwise Zettlr adds some newlines sometimes.

This is the solution. Pasting plain text will not try to convert code into Markdown, therefore not alter the text at all. I will not implement a solution while we're on CodeMirror 5 since I'm sunsetting this at some point, and upgrade to CodeMirror 6. Therefore closing as not implementing; if I forget to implement this in the new CodeMirror 6 editor, please open a new issue later.

**Closed by nathanlesage** 2022-07-18 14:43 UTC
Labels: enhancement

**Comment by radifar** [comment] 2022-07-19 02:49
Thank you @leo-hstone  and @nathanlesage ! I wasn't aware of this feature before.
