### ISSUE TITLE
zettlr crashes on open if you rename workspace path

### ISSUE THREAD

**Issue by LucasZapico** [Zettlr/Zettlr#5283] opened 2024-07-18 21:51 UTC
## Story

I changed the name a parent directory of one of more of the workspaces I open in Zettlr which cause the app to crash. Then when I tried to reopen that app it freezes, crashes on trying to load the workspaces. 

### major concern

There is a secondary level to this bug that is very frustrating and that is the loading screen is just stuck. I have tried to kill the process, `ps -a | grep zettlr`, `kill -9 <pid>` no change. I just uninstall Zettlr and the loading screen is still there. I get that this seems to be an edge case, but a developer pass on some graceful failure seems to be in order.

### Suggested Solutions 

1. app loads and workspaces are indicated as broken
2. init fails and app loads with no workspaces
  - with a message like; "previous session state failed to load, you may have to relink workspaces"
3. Zettlr has a listener on workspace paths and ask the user if they want to update the workspace paths executed. 

 Thank you for all your hard work and I love the app. Cheers

![Screenshot 2024-07-18 at 2 48 42 PM](https://github.com/user-attachments/assets/e1ad5a10-4e06-435c-a984-3406b86142b9)

### Reproducing

1. load in workspace path
2. make minor changes 
3. leave app open 
4. change name of directory in path from file manger or term 
5. reload app

### Zettlr version

3.2.0

### Installation Method

From the Website or GitHub

### Installation Method (Other)

brew install zettlr

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Macos Sonoma 14.5

**Comment by nathanlesage** [comment] 2024-09-29 17:14
I unfortunately can't reproduce this issue locally. Does it still occur with the latest version?

**Comment by LucasZapico** [comment] 2024-09-30 15:24
Thanks for looking into it. I will try and reproduce it today. I won't complain if bugs get solved on their own. Cheers.

**Comment by LucasZapico** [comment] 2024-10-02 17:26
@nathanlesage trying to reproduce. 

## Discovery  

The app still freezes on loading screen `loading workspace_<x>` . This was a "fresh" install of Zettlr from brew.  But when I uninstalled can still see a `Zettlr/`  in `$HOME/Library/ApplicationSupport/`. I remove `$HOME/Library/ApplicationSupport/Zettlr` and reinstalled and renamed the workspace was dropped it in the GUI. So maybe the bug was addressed. 

## Conclusion 

I haven't been using Zettlr since I hit this bug. I'll add it back into my workflow and see if I break stuff again. It's my specialty. Thank you for looking into this. 

Cheers

**Comment by nathanlesage** [comment] 2024-10-05 15:38
The bug is still there, and it's a possibly very easy fix. I'll bump this up because I agree the app shouldn't freeze on start.

**Comment by LucasZapico** [comment] 2024-10-16 18:04
Hey @nathanlesage, I would be very interesting in what is causing this. If it's not too much trouble when you all start working on the PR can you add this issue to it so I can see what's going on.

I'm using Zettlr again  on my new daily driver which is running  Ubuntu 24.04.1 and will let you know if I run into any issues. So far so good. 

Thank you for your time!

**Comment by nathanlesage** [comment] 2024-11-16 14:47
I just double checked the affected code, and indeed it seems that I couldn't reproduce the issue because I'm now properly fetching any problems with no-longer-existing roots. So I'm going to close this issue to clean up the issue tracker a bit.

**Closed by nathanlesage** 2024-11-16 14:47 UTC
Labels: bug
