### ISSUE TITLE
css: how to change

### ISSUE THREAD

**Issue by DoctorSubtilis** [Zettlr/Zettlr#3454] opened 2022-05-08 14:08 UTC
### Description

1) I didn't manage to change the css: how should I do to customize h1, h2, h3 and so on?

2) A md file is not open if is symlinked (I use Linux)

### Reproducing

In custom.css I tried to change the basic css, but nothing to to: you use a proprietary code.

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

KDE Neon

**Comment by DoctorSubtilis** [comment] 2022-05-08 15:55
I managed to find a partial solution to my first question (for headers).

**Comment by DoctorSubtilis** [comment] 2022-05-08 16:31
Where could I find a complete help for css in zettlr?  

And why it is not possible to open symlinked files?
Thank you!

**Comment by nathanlesage** [comment] 2022-05-08 19:36
First, "CSS: How to change" is a question and should therefore go into [the discussions section](https://github.com/Zettlr/Zettlr/discussions) of the repository. Second, we don't use proprietary code in there. All is open source. Third, what you're likely looking for is [this documentation page](https://docs.zettlr.com/en/core/custom-css/); it should give you everything you need. And fourth, symlinked files are not yet supported, but since this issue is focused around CSS which in this case is not a bug, I am going to close this issue. I think there is a symlink issue already open. If not, feel free to put that into its own issue.

**Closed by nathanlesage** 2022-05-08 19:36 UTC
Labels: bug
