### ISSUE TITLE
Table could not be rendered

### ISSUE THREAD

**Issue by wmjordan** [Zettlr/Zettlr#3888] opened 2022-11-11 02:56 UTC
### Description

The following table was generated by Typora (the previously free MarkDown editor) and it looked good in many MarkDown editor except Zettlr.

[Sample.md](https://github.com/Zettlr/Zettlr/files/9986132/WinDbg.SOS.md)

Expected rendition (rendered by MarkText):
<img width="726" alt="image" src="https://user-images.githubusercontent.com/12182730/201252711-88092875-61f3-4a27-a728-470819c41460.png">

What I see in Zettlr:
<img width="547" alt="image" src="https://user-images.githubusercontent.com/12182730/201252858-02e5748a-d85f-4ca0-8f74-7a64a13f8364.png">

### Reproducing

Please download and open the attachment above and test it.

### Zettlr Version

Nightly

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment] 2022-12-04 18:32
Puh, this looks like a super complex table. I think this is not a bug and rather a very complex interaction that is not easy to fix. Your table looks way overcomplex and possibly not even compliant with CommonMark Markdown. I don't know how well or bad Typora aligns with this standard, but I suspect this could be due to malformed syntax.

**Comment by wmjordan** [comment] 2022-12-05 01:42
The sample file rendered correctly in Typora, MarkText, and the recent MarkDown preview in VS.

MarkText is an open-sourced software. Maybe you can take a reference from them: https://github.com/marktext/marktext

**Comment by wmjordan** [comment] 2023-04-23 01:00
I downloaded the latest beta version 3. The table even disappeared at all.

This issue is not fixed, but ignored.

**Comment by nathanlesage** [comment] 2023-04-23 08:46
Ah sorry, I must've closed this in an affect. If you could drop in a few tables that do not work here (using Markdown code blocks), then I can see to have a look once I have time again.

**Comment by wmjordan** [comment] 2023-09-05 01:43
@AkechiShiro 
The [markdown file containing the sample table](https://github.com/Zettlr/Zettlr/files/9986132/WinDbg.SOS.md) is already uploaded in the issue.

**Comment by christophra** [comment] 2023-09-21 10:35
I also have a table that randomly switches between being rendered and not. I figured out one thing that broke it consistently, a cell starting with a greater-than sign, but after fixing these it's unpredictable. 
* Sometimes it gets fixed after copying and pasting it into a new file. 
* Sometimes only part of the table is rendered.
* Sometimes I can delete part of the table and the rest renders.

In the same table there is a line where `ws:2021` (as part of a longer string) gets turned into a link, even if I retype it. Sometimes copy-pasting breaks at that line, sometimes it breaks at the following line.

Once a table renders, I can copy it and it will still render. The other direction, a table that stops rendering, happens while scrolling around a file.

**Comment by sebzeter** [comment] 2023-11-21 19:09
I also have a table (see attachement) that was rendered randomly on Zettlr 2.3 but doesn't even appear on 3.02 (others 3.x versions not tried).
[Editor - Book title - Course XX to YY.md](https://github.com/Zettlr/Zettlr/files/13430119/Editor.-.Book.title.-.Course.XX.to.YY.md)

**Comment by jdnicholas** [comment] 2023-11-22 00:46
> I also have a table (see attachement) that was rendered randomly on Zettlr 2.3 but doesn't even appear on 3.02 (others 3.x versions not tried). [Editor - Book title - Course XX to YY.md](https://github.com/Zettlr/Zettlr/files/13430119/Editor.-.Book.title.-.Course.XX.to.YY.md)

@sebzeter If you add a blank line between the end of the table and the table caption line, I think it should appear with the table editor at least - I encountered this issue before. The rendering still appears to be weird though...

**Comment by sebzeter** [comment] 2023-11-25 22:21
@[jdnicholas](https://github.com/jdnicholas) following your recomandation, the tables appear but the rendering of the textual content is so weird that this is almost useless... I guess I now need to open or complete another bug report. However, thank you for your help!

**Closed** 2024-02-10 18:38 UTC
Labels: bug

**Comment by wmjordan** [comment] 2024-02-11 13:36
Good to see this issue being fixed.
@nathanlesage
Could you please make a binary for us to test?

**Comment by wmjordan** [comment] 2024-02-11 13:43
Good to see this issue being fixed.
@nathanlesage
Could you please make a binary for us to test?

**Comment by nathanlesage** [comment] 2024-02-11 14:16
There are automatic nightlies each Monday: https://nightly.zettlr.com
