### ISSUE TITLE
Frequent "modified remotely" message[Bug] 

### ISSUE THREAD

**Issue by BellLongworth** [Zettlr/Zettlr#2413] opened 2021-09-03 17:21 UTC
### Description

![image](https://user-images.githubusercontent.com/63842998/132043549-e71b4ee0-1c34-40f9-8bfb-c470787eaec8.png)

Started happening recently after every save, but not for every file.

Hints:

1. Possibly related to a recent upgrade to the newest Google Drive from the obsolete Backup and Sync (the Zettlr folder is synced)
2. Happens with biggish files (~>2k words) 100% of the time and does not happen with small files.
3. Whether I choose to load the file or not the result is the same. There is no data loss.

Edit: On 2nd thought, I don't think I was editing large files in the last few weeks, so the Google Drive update is possibly unrelated.

Marking the "always load" checkbox will supposedly solve this, but I'm concerned of side effects.

### Reproducing

Zettlr folder synced with Google Drive.
Change big file, save or wait for autosave.

### Zettlr Version

Beta (if applicable)

### Specify version

beta-3

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by jgsw** [comment] 2021-09-06 12:34
I can confirm this. Also experiencing this bug on Linux (Ubuntu 21.04) with largeish files on 2.0 beta 3. It doesn't happen after every single save of a large file for me, but does happen frequently.

**Comment by camilstaps** [comment] 2021-09-08 10:12
I can also reproduce this (Debian 10, 2.0 beta 3).

Like you I thought it was related to a file syncer (Dropbox in my case), but it also occurs when I pause syncing.

**Comment by BellLongworth** [comment] 2021-09-08 10:14
@camilstaps You are right! I disabled Google Drive and this still happens!

**Comment by camilstaps** [comment] 2021-09-08 11:33
With auto-save disabled, I have now also seen this once when saving with Ctrl-S. (Much less often, but that's probably because auto-saves are much more frequent than manual saves in general.)

**Comment by BellLongworth** [comment] 2021-09-08 17:38
See here a perfect correlation with the jumping text bug:
https://github.com/Zettlr/Zettlr/issues/1621#issuecomment-915437127

**Comment by nathanlesage** [comment] 2021-09-09 07:59
Okay, I just attached a debugger and stepped through the program. (Log messages with time stamp are from Zettlr, without the timestamp are from the debugger.)

```
Will write file to disk: 2021-09-10.md, the BOM is: ""
source/main/modules/fsal/fsal-file.ts:386
2
Will update metadata ...
source/main/modules/fsal/fsal-file.ts:388
source/app/service-providers/log-provider.ts:78
[09:51:41] Saving file 2021-09-10.md...
source/app/service-providers/log-provider.ts:78
[09:51:41] Updated modtime for fileDescriptor 2021-09-10.md to 1631173901103
source/app/service-providers/log-provider.ts:78
[09:51:41] File 2021-09-10.md saved.
source/app/service-providers/log-provider.ts:78
Will write file to disk: 2021-09-10.md, the BOM is: ""
source/main/modules/fsal/fsal-file.ts:386
Will update metadata ...
source/main/modules/fsal/fsal-file.ts:388
[09:51:42] [WATCHDOG] Emitting event: change:2021-09-10.md
source/app/service-providers/log-provider.ts:78
Will write file to disk: 2021-09-10.md, the BOM is: ""
source/main/modules/fsal/fsal-file.ts:386
Will update metadata ...
source/main/modules/fsal/fsal-file.ts:388
[09:51:42] Updated modtime for fileDescriptor 2021-09-10.md to 1631173901103
source/app/service-providers/log-provider.ts:78
```

As you can see the watchdog is firing an event of change. Just speculating, I'm assuming that the problem lies in the fact that recently I've detached the file handling logic of the DocumentManager from the file tree. Ohhhh, yes.

Right, I *think* what is happening here:

1. You save a modified file.
2. The DocumentManager will take care of doing that.
3. The FSAL on the other hand doesn't know about that. So it will detect a `change` event on that file, and, since it still has the old modification time, it will think that the file has been changed.

***

That being said, the necessary changes are:

1. The FSAL should silently ALWAYS update the metadata of the file, since it's not concerned with editing files anymore.
2. The logic of reporting "Hey, a file has been remotely changed – reload?" must be moved to the DocumentManager.

**Comment by noah-arroyo** [comment] 2021-10-04 02:27
@nathanlesage Uncertain if this belongs here, or should be a separate Issue:

After upgrading to beta.5, I'm seeing multiple forked saves of a file when working on it for a long time. 

This is behavior that I previously experienced in beta.4 alongside the jumping text, described in Issue #1621. Now the text no longer jumps, but the forked-save phenomenon remains.

NOTE: I sync my files, but to Box.com rather than Google Drive.

**Comment by nathanlesage** [comment] 2021-10-04 06:51
> This is behavior that I previously experienced in beta.4 alongside the jumping text, described in Issue #1621. Now the text no longer jumps, but the forked-save phenomenon remains.

Uff, that's not great o.O It now seems almost as if Zettlr is way too quick to save stuff so that Box.com gets confused because the local file is always overwritten before it has a chance to catch up

**Comment by noah-arroyo** [comment] 2021-10-04 06:57
Possible/easy to let the user decide how long the delay is on the delayed 
save? Maybe that'd allow people like me to find their sweet spot?

Of course I'm willing to personally shift the way I use Zettlr so that this 
is a non-issue for me. I could sync to some service other than Box, or get 
used to saving manually. But I'm probably not the only person syncing with 
Box, which (I'm pretty sure) predated Dropbox and has many, many corporate 
users.

**Comment by nathanlesage** [comment] 2021-10-04 07:32
Do you think 5 seconds is too short for people...?

Overall, I'm still pretty unhappy with the solution because *something* is going on and I really hate it that this asshole bug is persisting for over a year now, and apparently Zettlr is the only app that has those problems, and I'm beginning to question my sanity...

**Comment by camilstaps** [comment] 2021-10-04 08:15
In my experience turning off Dropbox did not solve the issue. Assuming @noah-arroyo's problem is the same, you should not need a Box.com account to test it.

I have experienced this with autosave enabled on large files after editing for a long time, also saving manually sometimes. Do you have infrastructure to test that automatically? Or perhaps you can lower the autosave period for testing so that you hit the bug sooner?

Was https://github.com/Zettlr/Zettlr/issues/2413#issuecomment-915854670 not also something you still wanted to look at? I'm sorry if I'm writing down things you already know, just in case this got forgotten in a bit because you have so many issues to keep track of.

**Comment by nathanlesage** [comment] 2021-10-04 11:37
@camilstaps Mh no, I think that Noah's problem is different: Now the problem is not that there is the frequently-modified thing, but rather that Box.com is apparently screaming internally as to the many modifications made to the file.

I think our only hope of keeping autosave and keep box.com happy is to perform buffered autosave, where every file is not written to the *actual* file, but rather to a buffer somewhere else on the computer, from where we can then shove everything into the file. But that seems like just relocating the problem.

But I do understand correctly that if you turn off autosave and manually save every, idk, 10 or 20 seconds, the bug does not occur, right?

**Comment by camilstaps** [comment] 2021-10-04 12:22
Then I misunderstood Noah's problem, apologies.

I got this once since turning off autosave (dropbox was disabled at that moment as well): https://github.com/Zettlr/Zettlr/issues/2413#issuecomment-915156448. That was on beta 3. My thought at the time was that this would indicate the problem is not specific to autosave (or external file syncers), but that the problem surfaces much sooner with autosave turned on simply because you are saving much more often. It could be that I saved twice in a row and there was some kind of race condition, so that it doesn't happen in normal use (saving manually every 10 or 20 seconds as you suggest).

All this is of course based on using the app, I have no idea if the above makes sense to someone who knows the code base :)

**Comment by nathanlesage** [comment] 2021-10-04 14:37
> All this is of course based on using the app, I have no idea if the above makes sense to someone who knows the code base :)

Well, you know ... understanding that code base is kind of a relative term; it's just too large to know every moving part by now. And I say that from a position of having written like 99 % of said moving parts 🙈

But this also means that a race condition COULD be the cause of that, which is why I really wanted to try it out myself. But I mean if a similar bug is happening with dropbox, I could test this out as well. Because this seems like one of those bugs where I really need to reproduce this locally to have a chance at fixing it.

**Comment by noah-arroyo** [comment] 2021-10-04 15:52
@nathanlesage I do think that manually saving will sidestep this bug, but I will verify today.

**Comment by noah-arroyo** [comment] 2021-10-04 20:12
**_Curious-er and curious-er._**

I've been able to reliably trigger the bug via manual save, but... I'm not sure why.

I've tested this on two files. 

One of the files is susceptible to the bug; with each save, Box.com forks the file. If I shut down Zettlr and start it again, the bug is still there.

The other file is not susceptible to the bug at all. I can manually save in rapid succession and it still won't fork the file. Yes, this is synced via Box.com as well.

@nathanlesage I've just sent you vids of this behavior, as well as logs. Maybe you can make something of it.

(Sorry, everybody else. Don't feel comfortable sharing the vids with the entire internet. Them's my work stuff.)

**Comment by nathanlesage** [comment] 2021-10-05 07:30
@noah-arroyo I've answered extensively. I have read some FAQ articles on box.com in this regard and they mention that one can "lock" files if someone is editing them. I believe it might be a hiccup in their versioning system. To reiterate what I wrote you: The videos clearly show that you edit the file, then save it, and then you can see how box synchronises them and then it's creating that forked file after a considerable amount of time. In that case it might help to simply reset the state of the box sync to a clean state again.

**Comment by noah-arroyo** [comment] 2021-10-09 18:47
@nathanlesage Good news.

I've "reset" the sync in the manner you suggested and all appears to be well. I guess the bug was with Box.com and my own setup, rather than with Zettlr. Yay!

**Comment by nathanlesage** [comment] 2021-10-09 22:55
Ahhh, that's so nice to hear! Both for you so that you can now work in peace again, and for me because I was going insane :D 

What do the others say? Otherwise, I'm gonna close the issue!

**Comment by dagdrommer** [comment] 2022-01-07 08:35
I, running Zettlr on a Linux machine (Arch btw), can confirm that the bug is still present.

Furthermore the notification also appears on local files that are in non-synced folders.

**Comment by mousetrappling** [comment] 2022-01-08 12:43
I'm also seeing the bug persistently in Ubuntu 20.0.4 – which file I'm editing doesn't seem to matter, it feels almost like it's time I've spent editing a particular file that's the problem.  All my files are local and not synced with any syncing service, and are only extremely rarely edited in any other application and definitely not simultaneously with Zettlr.  Reloading the file changes nothing in the file (it just makes it scroll on the screen).  It happens every time I use Zettlr, multiple times in an editing session.

**Comment by nathanlesage** [comment] 2022-01-08 13:18
Mh. Does the watchdog polling setting maybe help (in the advanced preferences)? We have seen these problems that sometimes the computer is too slow, and by increasing this time the app waits until it checks if a file has definitely changed this has already helped some people.

**Comment by noah-arroyo** [comment] 2022-01-08 17:36
Stepping in for the briefest moment just to say: This bug has not resurfaced for me (Windows 10, Zettlr ver. 2.1.1 at this point). I hope you folks can find a solution for Linux.

**Comment by mousetrappling** [comment] 2022-01-08 18:44
> Mh. Does the watchdog polling setting maybe help (in the advanced preferences)? We have seen these problems that sometimes the computer is too slow, and by increasing this time the app waits until it checks if a file has definitely changed this has already helped some people.

I had forgotten about that setting, and have now switched it on using the default time length.  So far I did an hour of work this afternoon and had no modified remotely messages so this seems promising.  I'll report back in a week or two when I've had the chance to test more thoroughly.

**Comment by nathanlesage** [comment] 2022-01-08 22:40
@mousetrappling Thank you! Let's hope for the best! :)

**Comment by dagdrommer** [comment] 2022-01-10 09:33
> Does the watchdog polling setting maybe help (in the advanced preferences)?

I just switched it on and I'll report back by the end of the week.
However, at least from the hardware side, my PC is the opposite of slow 😄

**Comment by mousetrappling** [comment] 2022-01-23 17:50
OK, I've been using it with that watchdog polling setting for a while, and haven't seen the remote modified message since.  So that fixes it for me.

**Comment by dagdrommer** [comment] 2022-01-23 17:52
> OK, I've been using it with that watchdog polling setting for a while, and haven't seen the remote modified message since. So that fixes it for me.

same for me.

**Comment by nathanlesage** [comment] 2022-01-28 16:52
Okay, perfect! Then I'm closing this issue as fixed.

If someone else stumbles upon this issue or if you want to help others, the corresponding info is also contained [here in the documentation](https://docs.zettlr.com/en/reference/settings/#advanced):

> * **Activate Watchdog polling**: If you work with large files, or your computer is somewhat slower, you can activate this setting. By default, Zettlr listens to your computer to get notified if some file changes remotely. If you activate this setting, Zettlr will wait the defined timespan, before it considers a change to be ready.
> * **Time to wait before writing a file is considered done (in ms)**: Increase this threshold, if Zettlr recognizes too many remote changes.

**Closed by nathanlesage** 2022-01-28 16:52 UTC
Labels: bug
