### ISSUE TITLE
Zettlr doesn't know ')' when link ends with ')'. 

### ISSUE THREAD

**Issue by varvir** [Zettlr/Zettlr#695] opened 2020-04-24 04:02 UTC
## Description
Zettlr doesn't know ')' when link ends with ')'. 

## Reproducing
The source is https://en.wikipedia.org/wiki/Interface_(computing)
The link ends with ')'. Zettlr should make link like this.
[mylink](https://en.wikipedia.org/wiki/Interface_(computing))

But it shows not _mylink_ (italic instead of underline) but _mylink)_.
It doesn't know what really closed parenthesis...

**Screenshots**
![image](https://user-images.githubusercontent.com/35399674/80173654-7b62a700-862b-11ea-927e-93927537404a.png)

## Platform
 - OS and version: Windows 10 1909
 - Zettlr Version: 1.6
 - Screen Resolution: FHD 1980 x 1080

**Comment by PhilHem** [comment] 2020-04-24 07:38
Noticed that too! A fix would be great.

**Comment by nathanlesage** [comment] 2020-04-24 19:25
It's known for a LONG TIME, but due to all the other stuff, I didn't have time to implement a better algorithm for this — so if anyone has time, it's the algorithm in the file `./source/renderer/assets/codemirror/zettlr-plugin-render-links.js` — PRs welcome, otherwise I'll be getting to this once the FSAL is correclty implemented!

**Comment by nathanlesage** [comment] 2020-05-05 09:33
Duplicate of #595

**Closed by nathanlesage** 2020-05-05 09:33 UTC
