### ISSUE TITLE
[BUG] Gutter Margin is too sensitive

### ISSUE THREAD

**Issue by Crowds21** [Zettlr/Zettlr#1199] opened 2020-08-17 08:38 UTC
## Description
1. When I want to click the beginning of a sentence, it will always cause the headline to close, which is very distressing

## Additional Information
This is a great software. Thank you very much

**Comment by nathanlesage** [comment] 2020-08-17 12:52
I noticed this myself, it has been caused by a recent PR which I merged.

**Comment by nathanlesage** [comment] 2020-09-23 13:58
This has already been fixed!

**Closed by nathanlesage** 2020-09-23 13:58 UTC
Labels: bug [non-critical], confirmed, priority:mid, v1.7.x

**Comment by xplosionmind** [comment] 2020-09-28 09:48
> This has already been fixed!

Actually, it doesn't seem like it has, to me. I have Zettlr 1.7.5, which I believe is the latest version, but it happens quite often to me that entire paragraphs are accidentally collapsed, and it’s pretty annoying. May I ask why clicking on the left has been programmed to make the paragraphs collapse? It makes no sense to me at all, and in my experience is more annoying than useful. Nevertheless, can the non-clickable margin be increased even more?

**Comment by nathanlesage** [comment] 2020-09-28 12:32
> Actually, it doesn't seem like it has, to me.

Actually, it has been fixed, but the change is not in the 1.7.5 branch. Issues are closed as soon as a fix has been implemented, independent of whether it's already in a release.

**Comment by dukebarman** [comment] 2020-10-12 16:43
No fix in 1.8.0-alpha.2 yet. Waiting for a fix!

Maybe add an option to Settings for disabling collapse headings?

**Comment by nathanlesage** [comment] 2020-10-13 10:37
Are you sure it's too sensitive? I mean yeah, you can't click like 30px outside of the margin, but I've significantly increased the gutter margin. A setting would be another issue.

**Comment by dukebarman** [comment] 2020-12-16 16:38
@nathanlesage sry for images quality, my screenshot software doesn't grab a mouse cursor. You may see a border for the hiding button.

First example. Whey I try to highlight strings after Header, I often misclick and hide header's section: 

![image](https://user-images.githubusercontent.com/1186777/102377354-9aa4af00-3fd5-11eb-8c71-d66fdf363545.png)

Second example. When I hide two headers, cannot choose needed because they haven't space between each:

![image](https://user-images.githubusercontent.com/1186777/102377517-d50e4c00-3fd5-11eb-824b-a0cc2b3f7013.png)

So the problem that hitbox for hiding header's section is bigger than the button for hiding.

**Comment by dukebarman** [comment] 2020-12-17 15:06
@nathanlesage, should I create another issue?
