### ISSUE TITLE
[Bug] Parameter windows appears too high

### ISSUE THREAD

**Issue by ElCharpi** [Zettlr/Zettlr#3144] opened 2022-02-06 12:38 UTC
### Description

![image](https://user-images.githubusercontent.com/99125217/152680829-4e9dd27b-7a06-4c4b-9080-a9850a75b7c9.png)

As you can see, when I click on "Parameters", the windows appears slightly too high -- the icons are mainly out of the screen. 
I can still click on them, so it is not a critical bug.
I cannot find any way to move the window, maybe because there is none, or because the button is out of reach. 

### Reproducing

Just click on the Parameters button with a config similar to mine.

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

### Additional Information

I'm using an Acer Swift 3.

**Comment by ElCharpi** [comment] 2022-02-08 15:46
It stopped opening too high. I don't understand what happened.
(yes, "opens" would have been better than "appears", pardon my french)

**Comment by nathanlesage** [comment] 2022-02-08 16:14
Yeah, it might've something to do with bumpy state logic for the window sizes. I looked that up several times but I couldn't find any logical error there. Maybe @kyaso if you're short on work at some point feel free to also have a look at that logic, maybe there is something in there which I'm just blind for! But if it's working now that's good to know!

**Comment by nathanlesage** [comment] 2023-02-19 09:30
I'll be closing this as a duplicate of #3037 to concentrate these issues, if they even appear at all.

**Closed by nathanlesage** 2023-02-19 09:30 UTC
Labels: bug
