### ISSUE TITLE
Clicking on outline links takes you to random places

### ISSUE THREAD

**Issue by MenooMeow** [Zettlr/Zettlr#5468] opened 2024-11-07 17:17 UTC
### Description

I have a document with many markdown headings and inserted images.  When I click on an item in the Outline (a heading entry), it does not seek to the proper heading.  In some cases, click on the same link a second time will take you to a different place.  Links do not take you to the right place and to unpredictable places with multiple clicks.

### Reproducing

- Create a standard markdown documents with headings.
- Use the outline feature to select a heading to go to.
- Watch it go to the wrong places.
- 

https://github.com/user-attachments/assets/2235cece-72b9-4852-9774-2d3399483fcf

### Zettlr version

Zettlr 3.2.3.

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Linux Mint 22 Cinammon

**Comment by nathanlesage** [comment] 2024-11-07 18:51
Duplicate of #5389

**Comment by nathanlesage** [comment] 2024-11-07 18:52
Next time please search the issue tracker for existing issues and add your additional info there instead of wildly opening new issues. This unnecessarily binds resources.

**Closed by nathanlesage** 2024-11-07 18:51 UTC
Labels: bug

**Comment by MenooMeow** [comment] 2024-11-08 17:58
> Next time please search the issue tracker for existing issues and add your additional info there instead of wildly opening new issues. This unnecessarily binds resources.

I posted it here because the original was regarding an older version.  There has been a new release and this is relative to the new release.  Plus this includes a video now that I didn't provide before.

**Comment by nathanlesage** [comment] 2024-11-09 13:58
I understand, but my point still stands: please add comments. Knowing if something got even worse with a new version in a comment to the original issue reduces friction by a large margin. If something is deserving of a new issue, rest assured that I will then say so. By default I really appreciate comments instead of new issues.
