### ISSUE TITLE
[Bug] Checkoff highlighting not applied on startup

### ISSUE THREAD

**Issue by chiphogg** [Zettlr/Zettlr#2750] opened 2021-10-31 20:02 UTC
### Description

Thanks for fixing #1583!   I'm trying it out in Zettlr 2.0.1.  I find I can easily customize the CSS.

However, whether I customize it or not, I find the `.task-item-done` styling only "kicks in" after I change the status of one of the checkboxes.

### Reproducing

1. Create a file with a checklist, where some items are checked off (and perhaps some are not).
2. Exit the software and reload (the file should still be open).
3. Observe that no special highlighting (by default, strikethrough) is applied to the checked-off items.
4. Change the status of one item.  Now, every item will be highlighted correctly.

### Zettlr Version

Stable (most recent version)

### Specify version

Zettlr 2.0.1 (85323a54-9adc-4f6f-8c4f-d80bb025ab1f)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux 5.11.0-38-generic (Ubuntu 20.04)

**Comment by efficacy** [comment] 2021-10-31 20:43
See also #2748

**Comment by nathanlesage** [comment] 2021-10-31 22:32
Duplicate of #2748

**Closed by nathanlesage** 2021-10-31 22:32 UTC
Labels: bug
