### ISSUE TITLE
Support URL Scheme to add notes quickly?

### ISSUE THREAD

**Issue by sullevy** [Zettlr/Zettlr#140] opened 2019-04-10 13:09 UTC
Thanks for this work, amazing.

I am using FSnotes and nvALT for quick get my fleeting ideas, they all support url scheme. 

If Zettlr could suport, maybe zettlr://make/new or other similar feature, I could integrate it into many workflow.

Thanks.

**Comment by nathanlesage** [comment] 2019-04-10 20:14
This sounds like a cool thing, although it'll require some thinking at first. But I'll get to it at some point!

**Comment by nathanlesage** [comment] 2020-05-07 22:29
Duplicate of #736

**Closed by nathanlesage** 2020-05-07 22:29 UTC
Labels: Feature
