### ISSUE TITLE
[Bug] Zettlr-1.8.9-amd64.deb depends on libappindicator3-1

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [Zettlr/Zettlr#2464] opened 2021-09-13 19:40 UTC
### Description

Tried to install via `dpkg -i Zettlr-1.8.9-amd64.deb` on Debian 11 (stable / Bullseye).

It depends on `libappindicator3-1` but Debian 11 can offer you `libappindicator3-0.1-cil`. Is this strict version really needed or can we lower that?

### Reproducing

`dpkg -i Zettlr-1.8.9-amd64.deb` on Debian 11 (stable / Bullseye).

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Debian 11 (stable / Bullsey)

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment] 2021-09-13 23:15
That comment of this bot does not add any valuable to this Issue.

**Comment by tscheims1** [comment] 2021-09-17 17:58
I recommend using the appimage. There you don't have any dependency issue by design. 
(Just download; set execute permission and run - Shguld work with almost any linux distribution)

**Comment by nathanlesage** [comment] 2021-09-17 20:14
@Codeberg-AsGithubAlternative-buhtz The bot may not add any value to this issue but does in many cases. Would you please mind downloading and attempting to use the most recent beta version and see if the issue persists? Please report if it does, otherwise we can see the issue as resolved. 2.0 is basically stable now and the only reason we haven't yet released a stable version is because of some rather cosmetic additions we still need to make.

**Comment by zchap26** [comment] 2021-09-23 13:02
Please make Zettlr available as either a snap or a flatpak.

Regards

**Comment by nathanlesage** [comment] 2021-09-25 15:51
@zchap26 Snap packages require a whole lot of setup, so I won't guarantee anything. In the meantime, please refer to the AppImage builds. These work just fine.

**Comment by zchap26** [comment] 2021-09-25 15:54
Unfortunately, the most recent beta still does not install successfully on Debian 11 bullseye:

user@computer:~$ sudo dpkg -i Zettlr-2.0.0-beta.4-amd64.deb 
Selecting previously unselected package zettlr.
(Reading database ... 151241 files and directories currently installed.)
Preparing to unpack Zettlr-2.0.0-beta.4-amd64.deb ...
Unpacking zettlr (2.0.0-beta.4) ...
dpkg: dependency problems prevent configuration of zettlr:
 zettlr depends on libappindicator3-1; however:
  Package libappindicator3-1 is not installed.

dpkg: error processing package zettlr (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.36.0-1) ...
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for mailcap (3.69) ...
Processing triggers for shared-mime-info (2.0-1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 zettlr

**Comment by nathanlesage** [comment] 2021-09-25 16:00
That is good to know. But does the AppImage work …?

**Comment by zchap26** [comment] 2021-09-25 16:15
AppImage does appear to be working just fine.
snap or flatpak would still be very welcome, indeed…

Regards

**Comment by tscheims1** [comment] 2021-09-25 20:42
@zchap26 @nathanlesage 
If I would maintain a cross platform application I would only provide an appimage for linux. Because its easy to maintain, has no external dependencies and works on almost every distribution. (I'm using it with Manjaro (Arch based distribution))

but that are just my two cents

**Comment by tscheims1** [comment] 2021-09-25 20:45
> On Debian 11 bullseye, Zettlr-1.8.9-x86_64.AppImage does appear to be working just fine.
> 
> Zettlr-2.0.0-beta.4-arm64.AppImage, on the other hand, fails to launch with the following error:
> 
> `Sep 25 18:24:30 computer org.gnome.Nautilus[203836]: sh: 1: exec: /home/user/Applications/Zettlr-2.0.0-beta.4-arm64.AppImage: Exec format error`
> 
> Regards

You downloaded the wrong zettlr2 appImage (arm64 instead of x86_64)

**Comment by zchap26** [comment] 2021-09-26 10:27
Ahem…

`Exec format error`

does give it away, doesn't it?

On Debian 11 bullseye, Zettlr-2.0.0-beta.4-x86_64.AppImage is launching just fine.
No further testing done as yet.
If there is supposed to be a Zettlr icon to the left of the file menu (Zettlr-1.8.9-x86_64.AppImage), it's not showing up:

![Screenshot from 2021-09-26 12-15-26](https://user-images.githubusercontent.com/38397493/134803849-1c3df288-f0f0-449c-8051-d8a972dca736.png)

Regards

**Comment by nathanlesage** [comment] 2021-09-26 10:53
> does give it away, doesn't it?

It does, it does ... (many Mac users have the same problem now that Macs come in both Intel and ARM flavors, funny enough)

> If there is supposed to be a Zettlr icon to the left of the file menu (Zettlr-1.8.9-x86_64.AppImage), it's not showing up:

Fixed after the latest beta; so the icon will show up in the next release.

***

I'm going to close this issue, since apparently AppImages are working just fine. I'll think about snap, but since it's effectively the same as AppImage, but with many, many more options to configure, it does not have priority. Plus, AppImages are FOSS while snap is maintained by Canonical.

**Closed by nathanlesage** 2021-09-26 10:53 UTC
Labels: bug
