### ISSUE TITLE
[Bug] Citation with @ does not play nice with snippets

### ISSUE THREAD

**Issue by efficacy** [Zettlr/Zettlr#3273] opened 2022-02-28 14:25 UTC
### Description

When I record notes on an academic paper or other citable resource I like to name the document as the citation key (for example `Anwar2017`) and have the H1 (#) title the same. I also like to include a citation link near the top of the file so that I can easily get to the PDF of the paper by right-clicking and selecting "Open Attachment". This means that in this case the top of the file would look something like:
```
#paper 
# Anwar2017
Towards greener software engineering using software analytics: A systematic mapping 
@Anwar2017
```
To avoid repeating the citation key (which can sometimes be tricky to type) I set up a "snippet" as follows:

```
---
id: $ZKN_ID
title: ${1:Citation Key}
date: $CURRENT_YEAR-$CURRENT_MONTH-$CURRENT_DATE
key: "${1:Citation Key}"
source: "${2:How I Found the Paper}"
---
#paper
# ${1:Citation Key}
${3:Paper Title}
@${1:Citation Key}
```

When I created a new file and invoked the snippet, everything seemed to work OK except for the citation. It produced the following:

```
---
id: 20220228141618
title: Anwar2017
date: 2022-02-28
key: "Anwar2017"
source: "ProQuest"
---
#paper
# Anwar2017
Towards greener software engineering using software analytics: A systematic mapping
@CitationAnwar2017
```

To make it work, I had to delete the rogue text "Citation" and move the cursor away from it, at which point it correctly found the bibliography entry and converted it to a clickable traditional citation.

### Reproducing

1. Create a snippet which includes `@` followed by a placeholder
2. Create a new file and invoke the snippet, providing it with a valid citation key from your bibliography
3. Observe that it has added a rogue word "Citation" and the citation does not convert to a clickable link

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.3

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment] 2022-03-03 11:35
Puah, so basically both the Citation autocomplete as well as the snippets piggyback on the same backend and there is some chance that there are interferences. In any case it seems as if the autocomplete for the citation saves the wrong information as to where to insert the finished citekey. I'll have to run some tests with the debugger to see how they interfere.

Just to be sure: How does this play out if you simply type out everything including the `@` regularly while filling in the snippet?

**Comment by efficacy** [comment] 2022-03-03 11:38
It works fine if I manually add it while still filling the snippet, but it's a fuss, particularly with long citation keys in unfamiliar languages

**Comment by nathanlesage** [comment] 2022-03-03 17:47
Interesting. In fact, I'm surprised that the dropdown even appears, given that you never manually type the `@` sign

**Comment by efficacy** [comment] 2022-03-03 19:35
Ah. Maybe I misunderstood what you were asking. It doesn't give the dropdown list of citations, but does generate a valid citation (which converts to a link when I move away) if I type the `@` then the key while entering a different snippet field.
TBH the appearance of the dropdown is kind of flaky anyway. Often if you accidentally type something which doesn't form part of a valid citation it gets bored and doesn't show the dropdown, even if you delete the offending character. Similarly, the dropdown doesn't appear if you paste in some or all of a citation, only when you type single characters.

**Comment by nathanlesage** [comment] 2022-03-03 20:03
>  it gets bored

🤨

But sounds as if we should be improving the autocomplete even further. I must confess that I never really understood how it works, which is why I'm always happy if it just … works

**Comment by nathanlesage** [comment] 2022-04-02 20:01
Just found the cause: Zettlr already renders the citation even though the text is selected.

You should be able to simply continue typing AS IF there was no rendered element until we get this sorted out.

**Comment by nathanlesage** [comment] 2022-11-04 11:39
Fixed with the new CM6 implementation!

**Closed by nathanlesage** 2022-11-04 11:39 UTC
Labels: bug
