### ISSUE TITLE
[Bug] Version 2.1.3 not started on Windows 7 x64

### ISSUE THREAD

**Issue by JetV** [Zettlr/Zettlr#3150] opened 2022-02-07 00:49 UTC
### Description

After installation, when I try to run it, Zettlr shows a log of changes in dictionaries (pop-up windows at the bottom right), and just a _white window in full screen_ without controls or displaying documents. Empty white window.

### Reproducing

Installation (fierwall are off), run via double-click on icon in Start menu.

### Zettlr Version

Stable (most recent version)

### Specify version

2.1.3

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 7

### Additional Information

I had to roll back to version 2.1.1, it starts correctly.

**Comment by emetselaar** [comment] 2022-02-07 08:13
I have more or less the same issue on Windows 11. Install new version, start - only white screen is shown.
Downgraded to 2.1.0 which does not have this issue. I tried as @JetV also 2.1.1 - also works OK.
Seems the problem starts with 2.1.2.
So you see the message there are new dicts (very briefly) and for the rest the whole screen is white.
It looks like this:

![image](https://user-images.githubusercontent.com/18800/152749580-35891744-3c7f-41a3-87e7-4abce798cbb3.png)

**Comment by nathanlesage** [comment] 2022-02-07 08:16
Duplicate of #3043

**Closed by nathanlesage** 2022-02-07 08:16 UTC
Labels: bug
