### ISSUE TITLE
Scrolling a document broken - jumps all over the place

### ISSUE THREAD

**Issue by MenooMeow** [Zettlr/Zettlr#5467] opened 2024-11-07 16:56 UTC
### Description

I have a document with many images, #headings, and other markdown code.  
- Grabbing the scroll bar position indicator and dragging up and down results in non-correlated scrolling, which is almost random.  The scroll bar position indicator does not remain underneath the mouse cursor as would be expected.
- Scrolling with the mouse wheel also results in almost jumping around scrolling where you can start somewhere, continue scrolling in any direction, and the scroll bar position indicator will jump up and down, backtracking and skipping ahead.  In many cases, you can never scroll past one position because it jumps back all the time.  
- It is impossible to scroll from one end of the document to another.
- 
https://github.com/user-attachments/assets/d68f54cb-78f9-415f-bb82-6727b7d82418

### Reproducing

Create a document using ordinary markdown and structure with headings.

### Zettlr version

Zettlr 3.2.3.

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Linux Mint 22 Cinammon

**Comment by nathanlesage** [comment] 2024-11-07 18:49
Duplicate of #5401

**Closed as completed by nathanlesage** 2024-11-07 18:50 UTC
Labels: bug
