### ISSUE TITLE
[Bug] Significant text input lag due to performance issue

### ISSUE THREAD

**Issue by vtcarlino** [Zettlr/Zettlr#3313] opened 2022-03-09 19:01 UTC
### Description

I noticed some text input lag since the last update. Text takes 1 to 5 seconds (sometimes more) to appear on screen after keyboard input. MacOS Activity Monitor indicates a significant rise of CPU usage of the "Zettlr Helper (Renderer)" process, reaching 80% or 90% of CPU usage, as shown below.

The bug only affects the editor i.e. typing and inserting citations.

## Activity Monitor screenshot

![Capture d’écran 2022-03-09 à 16 18 32](https://user-images.githubusercontent.com/24810357/157510530-b12ad743-add5-4a10-aac2-6a6726d2f76d.png)

## Logs 

Warnings and errors:

```
[15:29:38]	[FSAL Watchdog] The chokidar process falls back to polling. This may lead to a high CPU usage.
[15:29:57]	[R] [Main Window] Could not instantiate table between 659 and 662: Malformed Markdown Table! Found 1 columns on line 3 (should be 3). (index.js:2)
```

### Reproducing

The bug looks like a performance drop. It appears randomly when typing: suddenly, text takes several seconds to appear. 

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.4

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

macOS Catalina 10.15.7

**Comment by nathanlesage** [comment] 2022-03-09 19:05
Could you please check and confirm whether this is a duplicate of #3295 ?

**Comment by vtcarlino** [comment] 2022-03-09 19:12
Yes it is! Indeed, bug appears when immediately typing text after cmd+S and closing the file resolves it.

Sorry for the duplicate, I didn't notice #3295 despite searching recents issues before posting.

**Comment by nathanlesage** [comment] 2022-03-09 22:54
Then let's close this one!

**Closed by nathanlesage** 2022-03-09 22:54 UTC
Labels: bug
