### ISSUE TITLE
Crashes at start

### ISSUE THREAD

**Issue by UFOMelkor** [Zettlr/Zettlr#4099] opened 2023-01-28 14:33 UTC
### Description

Until this morning, Zettlr worked fine. When I start it now, I get the following error and Zettlr quits (without any GUI except the error has appeared).

```
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at M.boot (/opt/Zettlr/resources/app.asar/.webpack/main/index.js:2:1741819)
    at async t.default._informativeBoot (/opt/Zettlr/resources/app.asar/.webpack/main/index.js:2:1501067)
    at async t.default.boot (/opt/Zettlr/resources/app.asar/.webpack/main/index.js:2:1498227)
    at async t.bootApplication (/opt/Zettlr/resources/app.asar/.webpack/main/index.js:2:1502716)
```

When I choose another `data-dir`, Zettlr starts without an error even if I re-add every directory which was open before, so it looks like an error in the configuration.

### Reproducing

Start Zettlr

### Zettlr Version

Nightly

### Specify version

3.0.0-beta.1 (Mon Jan 23rd, 2023 13:37:12)

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04

### Additional Information

I guess this is not worth an in-depth analysis. I'll re-apply my settings and everything is fine. But I reported it because it might be helpful if it appears more often.

**Comment by nathanlesage** [comment] 2023-01-30 10:17
Can't really reproduce it since the code has slightly changed thus far … The column in your error message points to the configuration provider, however, so it does make sense that the config may have become borked. Please observe if this re-occurs, but for now I'm going to close this issue as it is not actionable.

**Closed by nathanlesage** 2023-01-30 10:17 UTC
Labels: bug

**Comment by UFOMelkor** [comment] 2023-01-30 19:35
The bug occurred again, also with the new nightly.
The stack trace remains nearly the same:
```
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at M.boot (/opt/Zettlr/resources/app.asar/.webpack/main/index.js:2:1742003)
    at async t.default._informativeBoot (/opt/Zettlr/resources/app.asar/.webpack/main/index.js:2:1501067)
    at async t.default.boot (/opt/Zettlr/resources/app.asar/.webpack/main/index.js:2:1498227)
    at async t.bootApplication (/opt/Zettlr/resources/app.asar/.webpack/main/index.js:2:1502716)
```

This time I tried a little bit: The problem is the file `window_state.yml`. It looks like sometimes it is emptied and if it is empty, Zettlr crashes with the above error. If I remove the file and start Zettlr again, everything is fine (and the file is filled with correct YAML again).

**Comment by nathanlesage** [comment] 2023-02-04 23:51
> It looks like sometimes it is emptied

While your PR is spot on and will prevent any errors upon boot, please feel free to keep an eye on that. It didn't happen to me in a long time, but I also observed this, but couldn't find the cause yet (as it didn't happen to me for the past 6 months).
