### ISSUE TITLE
[Bug] Once the File Manager Sidebar Has Been Closed Search on Clicking a Zettel Link Fails Until Application Restart

### ISSUE THREAD

**Issue by mousetrappling** [Zettlr/Zettlr#3006] opened 2022-01-06 15:51 UTC
### Description

If I shut the file manager sidebar then clicking on a Zettel link opens the sidebar again but fails to run the search.  From then on the search will not happen when I click a Zettel link.  Searching manually (by copying the ID into the box) still works.  Toggling the option to start a search on link click in the settings off and on again doesn't fix it.  The only way I can get searches to happen again is to restart Zettlr.

Not sure when this started happening, I was experimenting today with switching that sidebar off while I was concentrating and so it may've been happening in earlier versions (I upgraded to 2.1.1 this morning).

There was this error in the log file:
[11:39:18]	[R] [Main Window] TypeError: Cannot read properties of null (reading 'focus') (index.js:2)

### Reproducing

1. Turn on the option to start a search when following Zettel links.
2. Shut the file manager/search sidebar on the left.
3. Follow a Zettel link: the sidebar will open up but no search runs.

### Zettlr Version

Stable (most recent version)

### Specify version

2.1.1

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 20.04

**Comment by nathanlesage** [comment] 2022-01-06 16:43
Found and fixed!

**Comment by kyaso** [comment] 2022-01-16 14:28
I just found this issue is still present in 2.1.2. The reproduction steps from above still apply.

**Comment by mousetrappling** [comment] 2022-01-16 18:11
I find the same, I'm afraid.  However there were no errors in the logs this time, so it looks like you fixed something just not this thing!

**Comment by nathanlesage** [comment] 2022-01-16 20:04
Then let's give it another try!

**Comment by kyaso** [comment] 2022-02-13 19:30
I did some simple debugging, and I noticed that whenever the file manager gets closed, the GlobalSearch component gets _unmounted_. If I understood Vue3 correctly, this is equivalent to destroying a component? Is that a possible reason for this bug?

**Comment by nathanlesage** [comment] 2022-04-23 14:34
Heya, I just tried this thing again, but couldn't reproduce it, and I remember that I did do something to make the global search component much more resilient. Can we close this as fixed ...? @kyaso @mousetrappling

**Comment by mousetrappling** [comment] 2022-04-23 17:35
Worked for me just now, too.

**Comment by mousetrappling** [comment] 2022-04-23 17:40
No, wait, did it a second time and it failed in exactly the same way as the original bug report.

**Comment by nathanlesage** [comment] 2022-04-23 18:35
Alright, thank you for testing, I'm going to reproduce that and then fix that as well!

**Comment by nathanlesage** [comment] 2022-11-04 11:30
Works now!

**Closed by nathanlesage** 2022-11-04 11:30 UTC
Labels: bug
