### ISSUE TITLE
Text alignment/indentation changes in response to the wrong inputs

### ISSUE THREAD

**Issue by noah-arroyo** [Zettlr/Zettlr#4325] opened 2023-05-14 19:45 UTC
### Description

**Expected behavior:** Text's horizontal alignment/position does not change unless in response to user inputs with that intended effect, like indenting via `Tab` or creating an unordered list. 

**Buggy behavior:** Text's horizontal alignment changes in response to user inputs that are not intended to have that effect.

### Reproducing

The buggy alignment seems to be absent in notes where any line containing text (1) _does not_ begin with a space, and (2) is bounded, before and after, with lines containing no text.

Regarding (1): Beginning a line with a space will not move the cursor forward one character (creating the equivalent of a single-space indentation), but instead moves the cursor backward. 

Regarding (2): If two consecutive lines contain text, then all text in the note shifts horizontal alignment to the right by, it appears, a single character.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta.4

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment] 2023-06-28 11:07
This should be fixed in the current nightlies. Would you mind checking?

**Comment by noah-arroyo** [comment] 2023-07-02 19:16
Buggy behavior (1) is gone, but (2) remains.

**Comment by emendir** [comment] 2024-03-13 12:42
Issue (1) persists in Zettlr 3.0.5 and in 3.1.0-beta

**Comment by nathanlesage** [comment] 2024-03-24 15:18
This is likely a duplicate of #4602, I'm trying to clean things up

**Closed by nathanlesage** 2024-03-24 15:18 UTC
Labels: bug
