### ISSUE TITLE
Zettlr fails to scan YAML frontmatter when opening a workspace

### ISSUE THREAD

**Issue by cdelavegamartin** [Zettlr/Zettlr#3887] opened 2022-11-10 17:22 UTC
### Description

When opening a new workspace containing existing notes, formatted for zettlr, Zettlr doesn't seem to read the YAML frontmatter (does not display the title on the sidebar, or recognize tags in the frontmater for example). If I open a note, modify it, and save it then this gets updated. Restarting Zettlr or the computer doesn't fix this. Manually going through all the notes and modifying them is not feasible.

![frontmatter](https://user-images.githubusercontent.com/32675952/201150765-df022683-8087-4817-8bb5-aa25a05a099d.png)
![file list](https://user-images.githubusercontent.com/32675952/201151379-080d12c6-63ba-4ae6-95be-4e0c25aabfcc.png)
![tags](https://user-images.githubusercontent.com/32675952/201151472-00737a94-7569-40ba-8532-351467ba097f.png)

### Reproducing

Copy existing notes to a new location, open a workspace in that new location

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

### Additional Information

I have tested versions 2.2.5 and 2.3.0 in Ubuntu 20.04, and this issue is not present

**Comment by nathanlesage** [comment] 2022-11-13 19:41
Could you please run the following steps and see if they fix the problem?

1. Close the workspace with the corresponding notes.
2. Restart Zettlr.
3. Ensure the workspace is not open.
4. Restart Zettlr again.
5. Open the workspace again.

Then, in order to understand what happened, can you please describe the exact steps you have performed? To me, it sounds like the following, so please correct if I misunderstood:

1. You had some notes existing in a directory that was loaded in Zettlr.
2. You moved these outside the "visibility field" of Zettlr while running.
3. You then proceeded to open the moved files as a new workspace.

**Comment by cdelavegamartin** [comment] 2022-11-14 00:12
Hi,

Thanks a lot for having a look at this. I have tried those steps and the result is the same.
I have done some more simplified testing and I could actually reproduce with a minimal example, with the note created externally, in notepad. I just created the folder structure:
```bash
├── test
│   ├── testfolder
│       ├── 20220520202020.md

```
And load the to top folder as the workspace, doesn't show the info in the frontmatter (title, tags)
![tree and note](https://user-images.githubusercontent.com/32675952/201550771-f7745c2a-956a-44a8-a900-7f2a33e15c25.png)
![tags before modification](https://user-images.githubusercontent.com/32675952/201551162-6e3e3014-5ef6-4ab9-aa28-1465b6689aab.png)
text in the frontmatter is parsed in the search though
![search](https://user-images.githubusercontent.com/32675952/201551332-10e56004-e09f-4ede-a954-345f2082c1a2.png)
If I do any modification (eg add a new line) and save, then it picks up the information in the frontmatter
![tree and note after modification](https://user-images.githubusercontent.com/32675952/201551424-ffa41672-b14f-4981-846e-c17157818d61.png)
![tags after modification](https://user-images.githubusercontent.com/32675952/201551452-a8d24611-9526-4b83-b579-6ada9cc9b4f1.png)

**Comment by cdelavegamartin** [comment] 2022-11-14 00:16
Damn, I just did a clean reinstall, thinking it maybe was my configuration, and now it is is working, even after copying my configuration again. So closing because is no longer reproducible, must have been a fluke of my computer. Sorry for wasting your time.

**Comment by cdelavegamartin** [comment] 2022-11-14 02:38
After further testing, it is still happening. I've created a minimal example that demonstrates the behaviour for two notes in a workspace. Both were written externally (with Notepad on widows), and the configuration in Zettlr is a fresh install of the latest version for Windows x86_64. As before, If I modify the file that is not being scanned correctly (even just adding a space and deleting it, then save) then the frontmatter gets read without an issue.
![Not recognized](https://user-images.githubusercontent.com/32675952/201562792-c87d98c2-fea6-429a-9cdc-634be89d8322.png)
![Ok](https://user-images.githubusercontent.com/32675952/201562736-01e9a10d-457e-4270-82e3-2b5d70af1adc.png)

To reproduce just unpack, and open the foder as a workspace. 
[test.zip](https://github.com/Zettlr/Zettlr/files/9999024/test.zip)

**Comment by cdelavegamartin** [comment] 2022-11-14 02:56
The previous example also fails in my Zettlr 2.2.5 install on Ubuntu. I'm very confused.
![Broken](https://user-images.githubusercontent.com/32675952/201565230-640cfe2f-ab23-4362-928d-83f09399eb99.png)
![Ok](https://user-images.githubusercontent.com/32675952/201565274-e9b11e1c-bed0-4f85-8db1-c7a6a445da71.png)

**Comment by nathanlesage** [comment] 2022-11-20 19:13
> If there is anything more than i can do to test this out (specially if it doesn't reproduce on your machines) I would be very eager to help.

Sure! I mean, the best would be to just keep a look at it. Specifically, as soon as you notice it, make sure to open the logs and look as to whether there's something logged. If so it might be easy to fix.

The best one can hope for to fix a bug is reproducibility, so as soon as you've nailed reproducibility perfectly, I can trace the steps on my own machine to find where the app is breaking.

Also, make sure to switch to the nightly for that, because maybe that bug has already been fixed. It has been quite some time since the last release and a ton of stuff has changed in between! Plus, I think the nightly is by now already fairly stable (at least I'm using it in production and there's no data loss)

**Comment by cdelavegamartin** [comment] 2023-01-27 20:03
Testing this again, as I have now a bit more time, and have been wanting to use Zettlr in Windows as well as Linux.
I have installed the nightly build, default config, and the behaviour seems to be the same.

Here is again the minimal example for reference
[test.zip](https://github.com/Zettlr/Zettlr/files/10522402/test.zip)

Log:

[18:57:20] [Info] こんにちは！ Booting Zettlr at Fri Jan 27 2023 18:57:20 GMT+0000 (Greenwich Mean Time).
[18:57:20] [Info] Registering custom protocol safe-file
[18:57:20] [Warning] [Assets Provider] Found outdated filter links.lua; copying ...
[18:57:20] [Warning] [Assets Provider] Found outdated filter tags.lua; copying ...
[18:57:20] [Info] [Citeproc Provider] Loading CSL locale file at C:\Users\master\AppData\Local\Programs\Zettlr\resources\app.asar\.webpack\main\assets\csl-locales\locales-en-US.xml ...
[18:57:20] [Info] [Update Provider] Checking for application updates ...
[18:57:20] [Info] [Updater] Checking https://zettlr.com/api/releases/latest for updates ...
[18:57:20] [Info] [FSAL] Loaded all files and workspaces in 0.000010499954223632812 seconds
[18:57:21] [Info] [Window Manager] Window Manager started.
[18:57:21] [Info] [Document Manager] Restored 1 open windows.
[18:57:21] [Info] [AppServiceContainer] Boot successful!
[18:57:21] [Info] [Application] Added C:\Users\master\AppData\Local\Programs\Zettlr\resources to PATH.
[18:57:21] [Info] [Application] The bundled pandoc executable is now in PATH. If you do not want to use the bundled pandoc, uncheck the corresponding setting and reboot the app.
[18:57:21] [Info] [Update Provider] No new update available. Current version is v2.3.0.
[18:57:22] [Info] [R] [Main Window (cd77cff8-9a94-4f37-b303-3cef18ef0711)] Loading i18n data ... (index.js:2)
[18:57:22] [Info] [R] [Main Window (cd77cff8-9a94-4f37-b303-3cef18ef0711)] i18n data loaded (index.js:2)
[18:57:40] [Warning] [R] [Main Window (cd77cff8-9a94-4f37-b303-3cef18ef0711)] Skipping linter warning "Missing newline character at end of file": No position (index.js:2)
[18:57:51] [Warning] [R] [Main Window (cd77cff8-9a94-4f37-b303-3cef18ef0711)] Skipping linter warning "Missing newline character at end of file": No position (index.js:2)

![image](https://user-images.githubusercontent.com/32675952/215174853-b9337357-0450-491d-897d-111c02c29614.png)


After adding a newline to `Another Test Note` externally with notepad, the warnings are no longer there, but the behaviour is still not correct:

[19:05:38] [Info] こんにちは！ Booting Zettlr at Fri Jan 27 2023 19:05:38 GMT+0000 (Greenwich Mean Time).
[19:05:38] [Info] Registering custom protocol safe-file
[19:05:38] [Warning] [Assets Provider] Found outdated filter links.lua; copying ...
[19:05:38] [Warning] [Assets Provider] Found outdated filter tags.lua; copying ...
[19:05:38] [Info] [Citeproc Provider] Loading CSL locale file at C:\Users\master\AppData\Local\Programs\Zettlr\resources\app.asar\.webpack\main\assets\csl-locales\locales-en-US.xml ...
[19:05:38] [Info] [Update Provider] Checking for application updates ...
[19:05:38] [Info] [Updater] Checking https://zettlr.com/api/releases/latest for updates ...
[19:05:38] [Info] [FSAL] Loaded all files and workspaces in 0.040460500001907346 seconds
[19:05:38] [Info] [Window Manager] Window Manager started.
[19:05:38] [Info] [Document Manager] Restored 1 open windows.
[19:05:38] [Info] [AppServiceContainer] Boot successful!
[19:05:38] [Info] [Application] Added C:\Users\master\AppData\Local\Programs\Zettlr\resources to PATH.
[19:05:38] [Info] [Application] The bundled pandoc executable is now in PATH. If you do not want to use the bundled pandoc, uncheck the corresponding setting and reboot the app.
[19:05:38] [Info] [Update Provider] No new update available. Current version is v2.3.0.
[19:05:39] [Info] [R] [Main Window (cd77cff8-9a94-4f37-b303-3cef18ef0711)] Loading i18n data ... (index.js:2)
[19:05:39] [Info] [R] [Main Window (cd77cff8-9a94-4f37-b303-3cef18ef0711)] i18n data loaded (index.js:2)

![image](https://user-images.githubusercontent.com/32675952/215174699-6eb288fe-d719-44e5-8896-b09079da6617.png)

If I just save the note in Zettlr, no changes, now the frontmatter is parsed correctly,
[19:11:56] [Info] [DocumentManager] Processing change for C:\Users\master\Downloads\test\testfolder\20220521160158.md
[19:11:56] [Info] [WATCHDOG] Emitting event: change:C:\Users\master\Downloads\test\testfolder\20220521160158.md
[19:11:56] [Info] [DocumentManager] File C:\Users\master\Downloads\test\testfolder\20220521160158.md saved.
[19:12:15] [Info] さようなら！ Shutting down at Fri Jan 27 2023 19:12:15 GMT+0000 (Greenwich Mean Time)

![image](https://user-images.githubusercontent.com/32675952/215176316-fe87acf3-c236-43fe-a597-d5f5697b8d3a.png)

**I noticed using VSCode that the note that fails, `Another Test Note`, uses CRLF whereas the one that gets read correctly `Test note` uses LF. Saving  `Another Test Note` inside Zettlr doesn't change the line ending, despite now working. BUT, changing externally in VSCode the line endings to be LF instead of CRLF, it works correctly from the start. I have now tested this, switching all the notes to LF line endings, and everything is working correctly.**

Not sure if this would be considered a bug anymore, but I think it would be useful if it didn't fail silently. I also left all the explanation of my debugging process in case it helps someone struggling with something similar, but I can edit the comment, or open a new issue explicitly stating that this is a problem due to line endings, if you consider this is actually a bug.

**Comment by BabakFarshchian** [comment] 2023-04-21 06:27
I experience the same when I install the latest 3 beta in Windows 10. My tags in YAML don't show up, only hashtags in the text are visible in the tag cloud.

**Comment by nathanlesage** [comment] 2023-06-28 08:27
This should have been fixed in one of the most recent changes.

**Closed by nathanlesage** 2023-06-28 08:27 UTC
Labels: bug
