### ISSUE TITLE
[Bug] Zettlr v2.1.3.0 doesn't open well - just a white screen (looks like #829 issue)

### ISSUE THREAD

**Issue by 1fomin** [Zettlr/Zettlr#3140] opened 2022-02-05 10:53 UTC
### Description

I have installed Zettlr v2.1.3.0 and it does not open. Only a white windows appears. Tried on Windows 10 and Windous 7 - the same, just white screen. Pop-ups work.

### Reproducing

I installed and choused the option "open the zettlr". Wthite screen appeаred. Restart of PC didn't help. Any keys or mouse pressing doesn't help.
![process](https://user-images.githubusercontent.com/99074462/152639118-d1af4508-a527-40aa-a58d-cc9cfa3c9ace.JPG)
.

### Zettlr Version
![PU](https://user-images.githubusercontent.com/99074462/152639240-61fc7281-c266-43c3-9705-5752a7ef4cd3.JPG)

Stable (most recent version)

### Specify version

v2.1.3.0 from https://www.zettlr.com/

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windwos 10, Windwos 7, last updates

### Additional Information

Nothing but white csreen fron the very begining. No problem with installation. Restart doesn't help. It looks like 829 issue https://github.com/Zettlr/Zettlr/issues/829

**Comment by nathanlesage** [comment] 2022-02-05 12:08
Duplicate of #3043

**Closed by nathanlesage** 2022-02-05 12:08 UTC
Labels: bug

**Comment by 1fomin** [comment] 2022-02-05 16:24
I should wait for monday release of nightly version?

**Comment by nathanlesage** [comment] 2022-02-05 19:48
That should fix it I guess, yes
