### ISSUE TITLE
Option to Pin Tab when "avoid opening new tabs' is active

### ISSUE THREAD

**Issue by DBecker7** [Zettlr/Zettlr#3545] opened 2022-06-16 12:04 UTC
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

The option "avoid opening in new tab when possible" will not close pinned tabs. 

Could be implemented as: a context menu option, an icon next to the close button on a tab, or a double clicking on the tab. The pinned tab could have a "pin" logo next to the close button that can be clicked to un-pin.

### Example Workflow

Journalling: Pin the current tab, then click on previous journals to reference their contents. Since the current day is pinned, clicking on a previous day will open in a new tab (so there are now two tabs open). If you click on another day, the pinned tab stays open but the second tab switches to the new day (still only two tabs open).

Documenting: Pin the README file, while flipping through other files in the directory. The README is one tab, then each new file clicked appears in the second tab so you don't end up with tons of tabs just because you were looking for that one thing.

Organization: I keep a file called Priorities.md which lists the projects I'm working on and their main aspects, but then each project has a more complete description in its own file. I'd like to be able to keep the Priorities tab open while I check what else is on the horizon.

### Caveats

None that I can see. Depending on the implementation, it is hard to pin accidentally and should be obvious that a tab is pinned. This is essentially a more explicit way of forcing a file to open in a new tab, rather than making an edit before clicking a new file.

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

**Comment by nathanlesage** [comment] 2022-06-16 12:37
Duplicate of #3348

**Closed by nathanlesage** 2022-06-16 12:37 UTC
Labels: feature
