### ISSUE TITLE
[3.0.0 beta4] Autodetected file changes not working without new line

### ISSUE THREAD

**Issue by nils-se** [Zettlr/Zettlr#4394] opened 2023-06-03 11:28 UTC
### Description

Zettler doesn't recognize a file as changed, when there is **no** new line in the document. If you only append an existing line, Zettler doesn't autodetect the change and therefore doesn't reload the file, which leads to broken syncs.

sidenote: I love Zettler, thank you for this great app :)

### Reproducing

Open a note in Zettlr. 

Open the same note in another editor. Edit the text.
- if you only append a line and save the file externally, nothing happens in Zettlr.
- if you start a new line and save the file, Zettler recognizes a change and reloads the file.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0 beta4

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Kubuntu 22.04

**Comment by nathanlesage** [comment] 2023-06-03 11:30
This sounds unlikely. A new line character is a character, and as such the file should have its new modification date set. Zettlr doesn't check the file contents to determine changes, it only looks at when the file had last been modified. It is likely that something else might be happening, but to judge that, I would need some more information.

**Comment by nils-se** [comment] 2023-06-04 07:44
You are right, it's not the new line character. If I save the file once, Zettler doesn't show the changes. If I save the second time, Zettler shows the changes.

Zettler 3.0.0 beta4 AppImage on Kubuntu 22.04

- opened .md-File in nano and in Zettler.
- added a "1" to the text of the note in nano and saved (verified via terminal filesize and timestamp changed) -> Zettler doesn't react in any way
- saved again with nano and then Zettler reloads the file and shows the "1"

Will provide more info if needed.

**Comment by nathanlesage** [comment] 2023-06-04 08:56
Thanks, I'll have a look! You could also try another graphical program to edit the file to see if it may be caused by nano in the meantime!

**Comment by nils-se** [comment] 2023-06-05 07:50
@nathanlesage: Strange behavior: 
- The bug occures when note is opened in Zettler, then closed and re-opend.
- The error persists, even if note is closed and opened again, while no other text editor is open. 
- On a fresh start of Zettler, error is not reproducible. Just when note is closed and reopend in Zettler, bug occures again.

Tested with nano and Kate.

**Comment by nathanlesage** [comment] 2023-06-23 12:34
Ah that is some useful information. This indicates that the document may not be properly closed. Oh yes, it could be due to the way I implemented the updating process which has a promise dangling around …

**Comment by nathanlesage** [comment] 2023-06-26 07:31
I did some testing, and it's a relatively diffuse bug, sometimes it occurs, sometimes it doesn't. It appears to originate somewhere in the check for whether the file has actually changed. I'll need to dig deeper, and that could take some time.

**Comment by nathanlesage** [comment] 2024-03-24 17:41
This should be fixed with one of the more recent commits. While implementing the new CodeMirror instance I accidentally had the app overwrite the line endings with newlines regardless of which ones were originally in the file, causing lots of issues.

**Closed by nathanlesage** 2024-03-24 17:41 UTC
Labels: bug
