### ISSUE TITLE
Citations not rendering in Version 1.4.0-beta (1.4.0-beta)

### ISSUE THREAD

**Issue by jrennstich** [Zettlr/Zettlr#261] opened 2019-07-06 14:35 UTC
## Description
Citations not rendering anymore. None of my formerly rendering citations would render anymore. They are not recognized as citations when starting with the leading "@" character. The "View attachments" sidebar shows the message "References: Could not update bibliography!". I updated the database from Zotero, reconnected the file  in the preferences and restarted the computer after updating to the new beta version. No new Java version available.  

## Reproducing
Starting new document. When trying to include new reference starting with "@" no reaction from Zettlr. After completion of correct citation statement (in my case @author-title-year) I get no rendering (either in text or in PDFs).

## Expected behaviour
Proper connection to .json file? I assume, that's the problem. 

**Screenshots**

## Platform
 - OS: MacOS
 - OS Version 10.14.5 (18F132)
 - Zettlr Version 1.4.0-beta)

**Comment by nathanlesage** [comment] 2019-07-06 17:40
Does Zettlr offer you suggestions for titles when you type an `@`? If it does not, would you mind opening up the development console (Activate Develop mode in the advanced preferences, then from the Develop menu) and look out for any errors? Can't reproduce here using the same system configuration unfortunately …

**Comment by jrennstich** [comment] 2019-07-07 07:43
> Does Zettlr offer you suggestions for titles when you type an
No :-(

Hope this helps
[default 09-31-51.065271 +0200 loginwindow -.txt](https://github.com/Zettlr/Zettlr/files/3365378/default.09-31-51.065271.%2B0200.loginwindow.-.txt)

**Comment by jrennstich** [comment] 2019-07-07 07:52
Not quite sure how to track/report errors using the Develop tools in Zettlr. If the file above (which I got from the Terminal filtering "Zettlr" is not helpful, I'd be grateful for some brief pointers how to look for errors using the Develop tools in Zettlr.

**Comment by nathanlesage** [comment] 2019-07-07 08:10
With the debug mode in the preferences on, here you go:

![image](https://user-images.githubusercontent.com/17251683/60765742-5783a400-a09f-11e9-814e-d185dfd19fb5.png)

**Comment by jrennstich** [comment] 2019-07-07 10:10
Ah, thx. V helpful. After I selected "Verbose" under levels I received the following errors:

[Violation] 'setTimeout' handler took 233ms
[Violation] Forced reflow while executing JavaScript took 40ms
[Violation] 'setTimeout' handler took 54ms
[Violation] Forced reflow while executing JavaScript took 47ms
/Applications/Zettlr.app/Contents/Resources/app.asar/node_modules/codemirror/lib/codemirror.js:7992 [Violation] 'mousewheel' handler took 172ms
/Applications/Zettlr.app/Contents/Resources/app.asar/node_modules/codemirror/lib/codemirror.js:148 [Violation] 'setTimeout' handler took 101ms

The Zotero .json file is 6.7 MB 

There was always a noticeable time-lag when starting with `@` but now nothing happens and the existing citations are not rendered.

**Comment by nathanlesage** [comment] 2019-07-07 10:25
> The Zotero .json file is 6.7 MB

6.7 Megabytes? o.O How many entries do you have? I have a file of just 350kb (~600 entries), and it works fine. Would you mind checking with a smaller file? What I could imagine is that probably the citeproc engine just takes a lot to initialise due to the size. Plus it might have a significant memory impact.

**Comment by nathanlesage** [comment] 2019-07-07 10:25
P.S.: These "Violations" are mainly indications that one could optimise the speed of some components, but nothing problematic :)

**Comment by jrennstich** [comment] 2019-07-07 10:42
I feared as much. 13253 entries.

Works fine with test database. So it's the size. One problem remains: When using citations as in-text (that is without the []) then I get the result as pictured. Not sure if that's the regular behavior in Zettlr.  

The references all appear in the sidebar list. 

Thanks for clearing that up. I assume, with a large database that feature is not going to work then?

<img width="743" alt="screenshot_228" src="https://user-images.githubusercontent.com/22581234/60767194-940dca80-a0b4-11e9-8074-e669c299c1b6.png">

**Comment by nathanlesage** [comment] 2019-07-07 14:29
> One problem remains: When using citations as in-text (that is without the []) then I get the result as pictured.

Thanks for reporting, it's fixed now both in Citr and in Zettlr!

**Closed by nathanlesage** 2019-07-07 14:29 UTC

**Comment by nathanlesage** [comment] 2019-07-07 14:31
> I assume, with a large database that feature is not going to work then?

I don't know. I mean, after all what should be inside that database file are only the literature references themselves. But it sounds as if you have put all notes and extracted annotations in it as well, so maybe it helps by telling BetterBibTex to only export the raw references (albeit I don't know from scratch where such an option would be).

**Comment by jrennstich** [comment] 2019-07-07 15:06
Hmm. Im using BetterBibTeX as well and there I excluded the notes and abstracts and all. Is that possible in a simple export as well from Zotero? I wasn’t aware of that.

**Comment by jrennstich** [comment] 2019-07-07 15:07
Ah, so I would export using BBT but the .json format instead of one of the bibtex formats. That makes sense. I give that a try. Thx for the suggestion.

**Comment by jrennstich** [comment] 2019-07-07 15:09
BTW, the option is in the preferences of the BBT-tab under Zotero. First window/tab there.

**Comment by weverthonmachado** [comment] 2019-08-01 14:25
(First time posting here, so kudos for the great work! I've been using a custom SublimeText plugin, loosely based on sublime_zk, with a lot of hacks. Zettlr is the best out-of-the box solution I found for my workflow.)

If I understand correctly, the fix did not address the behavior reported in the original post, only the follow-up. Sorry if it's not the case. 

I'm experiencing similar behavior with version 1.4.0-beta on Windows 10: no suggestions shown when I type "@" and the attachments sidebar shows "References: Could not update bibliography!".  But citations are rendered correctly when exporting to html or pdf. No errors shown in debug mode (as instructed above).

It doesn't seem to be the size: I use a .bib file (generated by Mendeley) of ~700kb and ~900 entries. I guess the problem has to do with special characters in citekeys. I did some tests with versions 1.3 and 1.4 and an example library with a few entries (attached, with extension changed to .txt). 

Zettlr 1.3, [library_original.bib](https://github.com/Zettlr/Zettlr/files/3457170/library_original.txt):
![img1 3_](https://user-images.githubusercontent.com/11988227/62301073-49caff80-b44e-11e9-8ef2-1afdfd043309.jpg)

Zettlr 1.4, library_original.bib:
![img1 4_](https://user-images.githubusercontent.com/11988227/62301084-4df71d00-b44e-11e9-8814-11406716de42.jpg)

Zettlr 1.4, [library_modified.bib](https://github.com/Zettlr/Zettlr/files/3457169/library_modified.txt)(only difference is "o" instead of "ø" in line 47):
![img1 4_libmodified](https://user-images.githubusercontent.com/11988227/62301100-54859480-b44e-11e9-9f6a-fd0391fff510.jpg)

***

**Comment by nathanlesage** [comment] 2019-08-01 15:39
There's a documentation of the citeproc behaviour at https://pandoc.org/demo/example19/Extension-citations.html.

I simply stick to their definition of CiteKeys, which included only "alphanumerics", hence: a-z, A-Z, 0-9 and some special chars. And if the references tell you "References: Could not update bibliography!", this means that Citeproc has reported an error during startup, which may very likely point to an error in its own startup mode.

After testing I can confirm that the [Citr library](https://github.com/Zettlr/Citr) produces the error, as it sticks to the official citeproc-documentation, which seems outdated.

You report, you have no problem exporting a file using such special characters? If so, I'll need to update Citr and report an issue with Pandoc's documentation …

**Comment by weverthonmachado** [comment] 2019-08-01 16:02
Yes, totally fine. I agree that it's better to stick to a strict definition for maximum compatibility. I only bumped into this because Mendeley creates citekeys automatically and includes special chars (they can be manually edited).

**Comment by nathanlesage** [comment] 2019-08-01 16:46
Just double-checked with my Zotero installation — BetterBibTex converts umlauts into their ASCII equivalents, so they're also playing it safe. So unless it becomes a problem for anyone, I think I'll be sticking to the strict version, but I'll also add a notification that some keys are malformed, if there are any!
